### ISSUE TITLE
Catch CurlException to show mirror option hint

### ISSUE THREAD

**Issue by c9s** [phpbrew/phpbrew#1000]
When downloading the php distribution from Taiwan, the mirror site failed to provide the file. However users might not know how to change the mirror site.

**Comment by act28** [comment]
The PHP mirror program has been retired. The `--mirror` option is no longer required and the distribution url should always be `http://www.php.net`, as MyraCloud is a CDN and serves the distribution from your closest node. 

@see https://news-web.php.net/php.mirrors/40932

In the interim, you can use `--mirror https://www.php.net` as a workaround.
