### ISSUE TITLE
ext/mbstring/php_mbregex.c:457:60: error: incomplete definition of type 'struct php_mb_re_pattern_buffer'

### ISSUE THREAD

**Issue by njt1982** [phpbrew/phpbrew#1003]
### Output

```
.phpbrew/build/php-5.5.38/ext/mbstring/php_mbregex.c:457:60: error: incomplete definition of type 'struct php_mb_re_pattern_buffer'
        if (found == FAILURE || (*rc)->options != options || (*rc)->enc != enc || (*rc)->syntax != syntax) {
                                                             ~~~~~^
/usr/local/include/oniguruma.h:673:8: note: forward declaration of 'struct php_mb_re_pattern_buffer'
struct re_pattern_buffer;
       ^
ext/mbstring/php_onig_compat.h:4:37: note: expanded from macro 're_pattern_buffer'
#define re_pattern_buffer           php_mb_re_pattern_buffer
                                    ^
```

I looks like this bug (which is patched/fixed in 5.6+)
https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=226717

### Command

```
phpbrew install -j $(nproc) 5.5 +default +mysql +fpm +gd \
  +bz2="$(brew --prefix bzip2)" \
  +curl="$(brew --prefix curl-openssl)" \
  +zlib="$(brew --prefix zlib)" \
  +iconv="$(brew --prefix libiconv)" \
  -- --with-gd=shared
```

### Platform

OS: OSX 10.14.3

Running PHP:  7.1.x (via Homebrew)

Installing PHP: 5.5.38

**Comment by njt1982** [comment]
I appreciate 5.5 is old and unsupported...

**Comment by abhishekdas29** [comment]
Hello Team,

I'm getting the same issue while installing php 7.0.27 in OSX 10.14.3. Could you please help?

**Comment by morozov** [comment]
According to the details above, it's an upstream issue caused by the incompatibility between the dependencies. Given that it happens on an ancient PHP version, we don't have the needed resources to investigate the issue and possibly backport the patch.

**Comment by yiranzai** [comment]
@morozov  I had the same problem. When installing php7.0

**Comment by unisol-ua** [comment]
> Hello Team,
> 
> I'm getting the same issue while installing php 7.0.27 in OSX 10.14.3. Could you please help?
Here's a 7.0 patch, it does compile (oniguruma 6.9.9) but I have no idea how to test if it works OK (yet), it's a "backported" 5.6.40 patch :
--- php_mbregex.c.orig  2018-12-04 17:22:55.000000000 +0000
+++ php_mbregex.c 2023-10-28 18:57:01.128318869 +0000
@@ -452,7 +452,8 @@
        OnigUChar err_str[ONIG_MAX_ERROR_MESSAGE_LEN];

        rc = zend_hash_str_find_ptr(&MBREX(ht_rc), (char *)pattern, patlen);
-       if (!rc || rc->options != options || rc->enc != enc || rc->syntax != syntax) {
+//     if (!rc || rc->options != options || rc->enc != enc || rc->syntax != syntax) {
+if (!rc || onig_get_options(rc) != options || onig_get_encoding(rc) != enc || onig_get_syntax(rc) != syntax) {
                if ((err_code = onig_new(&retval, (OnigUChar *)pattern, (OnigUChar *)(pattern + patlen), options, enc, syntax, &err_info)) != ONIG_NORMAL) {
                  onig_error_code_to_str(err_str, err_code, &err_info);
                  php_error_docref(NULL, E_WARNING, "mbregex compile err: %s", err_str);
