### ISSUE TITLE
Cannot find OpenSSL's libraries - PHP 5.3.2

### ISSUE THREAD

**Issue by bartbergmans** [phpbrew/phpbrew#1005]
I am trying to install PHP 5.3.2 on Ubuntu 18.04 using PHPBrew. I have no trouble with installing it without OpenSSL but when I want to install OpenSSL I get several errors. 

My first attempt was to just use +openssl but then I got a lot of errors from OpenSSL. Then I installed OpenSSL 0.9.8 and used it as `+openssl=/usr/local/openssl/` and now I get the following error:

```configure: error: Cannot find OpenSSL's libraries```

I have no idea what libraries it can't find. I already fixed the missing `evp.h` file by making a symbolic link in `/usr/local/openssl` to `/usr/local/openssl/include/openssl/evp.h`.

**Comment by Potherca** [comment]
I had the same issue with PHP 5.4. There was [a comment](https://github.com/phpbrew/phpbrew/issues/829#issuecomment-400588001) in https://github.com/phpbrew/phpbrew/issues/829 that worked for me:

> To install php5.6 in ubuntu 18.04, I need to compile openssl 1.0 manually
> https://gist.github.com/marulitua/f8932064ec5bfe6a5be9fadac7c5a141

You could try if compiling OpenSSL yourself (following the steps as described in the linked Gist) works for PHP 5.3 as well...

**Comment by morozov** [comment]
PHP 5.3 doesn't support OpenSSL 1.1 shipped with Ubuntu 18.04, you'll have to compile OpenSSL 1.0 manually.

As of #1041, PHPBrew supports patching PHP 5.6.31 or newer for compatibility with OpenSSL 1.1 but it won't work for PHP 5.3 and won't be fixed.

**Comment by smola** [comment]
For those looking for a solution:
* You can use the following script to build the required OpenSSL version on Linux: https://gist.github.com/smola/a01be46aad2704b3844620a95301b512
* Or the following instructions, which are roughly equivalent: https://gist.github.com/marulitua/f8932064ec5bfe6a5be9fadac7c5a141
