### ISSUE TITLE
MacOS X And Whitespace In Path

### ISSUE THREAD

**Issue by BenediktS1** [phpbrew/phpbrew#1006]
Hello.
When trying to get PHP 7.2.16 with default settings I'm getting this error:

### Output

===> phpbrew will now build 7.2.16
---> Parsing variants from command arguments '+default'
===> Loading and resolving variants...
Checking distribution checksum...
Checksum matched: 2c0ad10053d58694cd14323248ecd6d9ba71d2733d160973c356ad01d09e7f38
===> Distribution file was successfully extracted, skipping...
Source Directory: /Volumes/Macintosh HD/Users/stalker/.phpbrew/build/php-7.2.16
Writing variant info to /Volumes/Macintosh HD/Users/stalker/.phpbrew/php/php-7.2.16/phpbrew.variants
===> Checking patches...
Checking patch for replace apache php module name with custom version name
Enabled variants: [xml, opcache, bcmath, bz2, calendar, cli, ctype, dom, fileinfo, filter, ipc, json, mbregex, mbstring, mhash, mcrypt, pcntl, pcre, pdo, pear, phar, posix, readline, sockets, tokenizer, curl, openssl, zip]
Disabled variants: []
===> Configuring 7.2.16...

Use tail command to see what's going on:
   $ tail -F /Volumes/Macintosh HD/Users/stalker/.phpbrew/build/php-7.2.16/build.log

./configure '--cache-file=/Volumes/Macintosh HD/Users/stalker/.phpbrew/cache/config.cache' '--prefix=/Volumes/Macintosh HD/Users/stalker/.phpbrew/php/php-7.2.16' '--with-config-file-path=/Volumes/Macintosh HD/Users/stalker/.phpbrew/php/php-7.2.16/etc' '--with-config-file-scan-dir=/Volumes/Macintosh HD/Users/stalker/.phpbrew/php/php-7.2.16/var/db' '--disable-all' '--enable-phar' '--enable-session' '--enable-short-tags' '--enable-tokenizer' '--with-pcre-regex' '--with-zlib=/opt/local' '--enable-dom' '--enable-libxml' '--enable-simplexml' '--enable-xml' '--enable-xmlreader' '--enable-xmlwriter' '--with-xsl' '--with-libxml-dir=/opt/local' '--enable-opcache' '--enable-bcmath' '--with-bz2=/opt/local' '--enable-calendar' '--enable-cli' '--enable-ctype' '--enable-dom' '--enable-fileinfo' '--enable-filter' '--enable-shmop' '--enable-sysvsem' '--enable-sysvshm' '--enable-sysvmsg' '--enable-json' '--enable-mbregex' '--enable-mbstring' '--with-mhash=/opt/local' '--with-mcrypt=/opt/local' '--enable-pcntl' '--with-pcre-regex' '--with-pcre-dir=/opt/local' '--enable-pdo' '--with-pear=/Volumes/Macintosh HD/Users/stalker/.phpbrew/php/php-7.2.16/lib/php/pear' '--enable-phar' '--enable-posix' '--with-readline=/opt/local' '--enable-sockets' '--enable-tokenizer' '--with-curl=/opt/local' '--with-openssl=/opt/local' '--enable-zip' >> /Volumes/Macintosh HD/Users/stalker/.phpbrew/build/php-7.2.16/build.log 2>&1
sh: /Volumes/Macintosh: Operation not permitted
Error: Configure failed:

### Expected Result

Installation fo PHP 7.2.16 with your defaults.

### Command

Paste your phpbrew install command here (be sure to install with `--debug` flag, e.g. `phpbrew --debug install`)

phpbrew --debug install -j 4 7.2.16 +default

### Build Log

    gist here

### Platform

OS:

OS X 10.14.3

Running PHP: 
PHP 7.1.23 (cli) (built: Nov  7 2018 18:20:35) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies

Installing PHP:
PHP 7.2.16

To me it seems tail gets confused by /Volumes/Macintosh HD

**Comment by morozov** [comment]
> To me it seems tail gets confused by /Volumes/Macintosh HD

According to the output, it's the `./configure` that gets confused:
```
sh: /Volumes/Macintosh: Operation not permitted
Error: Configure failed:
```
Although, the suggested `tail -F` command should be also updated to display a propper suggestion.

**Comment by morozov** [comment]
Even if we fix handling paths containing whitespaces PHPBrew, it seems that it will require a lot of effort to compile PHP using such paths. Its build scripts seem incapable of handling them as well. For instance [build/php.m4](https://github.com/php/php-src/blob/959091285487878790f2f2fe71301954f3c765a9/build/php.m4#L2165-L2170),
```sh
if test -f $abs_srcdir/include/php/ext/pdo/php_pdo_driver.h; then
  pdo_cv_inc_path=$abs_srcdir/ext
elif test -f $abs_srcdir/ext/pdo/php_pdo_driver.h; then
  pdo_cv_inc_path=$abs_srcdir/ext
elif test -f $phpincludedir/ext/pdo/php_pdo_driver.h; then
  pdo_cv_inc_path=$phpincludedir/ext
fi
```
This is what the build process with the above fragment fixed looks like:
```
testuser@viola:~/.phpbrew/build/php-7.4.0$ echo $HOME
/home/test user
testuser@viola:~/.phpbrew/build/php-7.4.0$ ./configure '--cache-file=/home/test user/.phpbrew/cache/config.cache' '--prefix=/home/test user/.phpbrew/php/php-7.4.0' '--with-config-file-path=/home/test user/.phpbrew/php/php-7.4.0/etc' '--with-config-file-scan-dir=/home/test user/.phpbrew/php/php-7.4.0/var/db' '--with-libdir=lib/x86_64-linux-gnu' '--enable-dom' '--with-libxml' '--enable-simplexml' '--enable-xml' '--enable-xmlreader' '--enable-xmlwriter' '--with-xsl' '--enable-opcache' >> '/home/test user/.phpbrew/build/php-7.4.0/build.log'
./configure: line 3327: /home/test user/.phpbrew/cache/config.cache: No such file or directory
/bin/sed: can't read /home/test: No such file or directory
/bin/sed: can't read user/.phpbrew/build/php-7.4.0/sapi/cli/Makefile.frag: No such file or directory
/bin/sed: can't read /home/test: No such file or directory
/bin/sed: can't read user/.phpbrew/build/php-7.4.0/sapi/phpdbg/Makefile.frag: No such file or directory
/bin/sed: can't read /home/test: No such file or directory
/bin/sed: can't read user/.phpbrew/build/php-7.4.0/sapi/cgi/Makefile.frag: No such file or directory
/bin/sed: -e expression #1, char 25: unterminated `s' command
/bin/sed: -e expression #1, char 25: unterminated `s' command
/bin/sed: -e expression #1, char 25: unterminated `s' command
/bin/sed: -e expression #1, char 25: unterminated `s' command
/bin/sed: -e expression #1, char 25: unterminated `s' command
/bin/sed: can't read /home/test: No such file or directory
/bin/sed: can't read user/.phpbrew/build/php-7.4.0/ext/fileinfo/Makefile.frag: No such file or directory
/bin/sed: -e expression #1, char 25: unterminated `s' command
/bin/sed: -e expression #1, char 25: unterminated `s' command
/bin/sed: -e expression #1, char 25: unterminated `s' command
/bin/sed: -e expression #1, char 25: unterminated `s' command
/bin/sed: can't read /home/test: No such file or directory
/bin/sed: can't read user/.phpbrew/build/php-7.4.0/ext/json/Makefile.frag: No such file or directory
/bin/sed: -e expression #1, char 25: unterminated `s' command
/bin/sed: can't read /home/test: No such file or directory
/bin/sed: can't read user/.phpbrew/build/php-7.4.0/ext/pdo/Makefile.frag: No such file or directory
/bin/sed: -e expression #1, char 25: unterminated `s' command
/bin/sed: -e expression #1, char 25: unterminated `s' command
/bin/sed: can't read /home/test: No such file or directory
/bin/sed: can't read user/.phpbrew/build/php-7.4.0/ext/phar/Makefile.frag: No such file or directory
/bin/sed: -e expression #1, char 25: unterminated `s' command
/bin/sed: -e expression #1, char 25: unterminated `s' command
/bin/sed: -e expression #1, char 25: unterminated `s' command
/bin/sed: -e expression #1, char 25: unterminated `s' command
/bin/sed: -e expression #1, char 25: unterminated `s' command
/bin/sed: can't read /home/test: No such file or directory
/bin/sed: can't read user/.phpbrew/build/php-7.4.0/ext/standard/Makefile.frag: No such file or directory
/bin/sed: can't read /home/test: No such file or directory
/bin/sed: can't read user/.phpbrew/build/php-7.4.0/ext/tokenizer/Makefile.frag: No such file or directory
/bin/sed: -e expression #1, char 25: unterminated `s' command
mkdir: cannot create directory '/home/test': Permission denied
/bin/sed: can't read /home/test: No such file or directory
/bin/sed: can't read user/.phpbrew/build/php-7.4.0/scripts/Makefile.frag: No such file or directory
/bin/sed: can't read /home/test: No such file or directory
/bin/sed: can't read user/.phpbrew/build/php-7.4.0/Zend/Makefile.frag: No such file or directory
cat: /home/test: No such file or directory
cat: user/.phpbrew/build/php-7.4.0/build/Makefile.global: No such file or directory
./build/genif.sh: 35: cd: can't cd to /home/test
./build/genif.sh: 46: cd: can't cd to /home/test
./build/genif.sh: 35: cd: can't cd to /home/test
./build/genif.sh: 46: cd: can't cd to /home/test

testuser@viola:~/.phpbrew/build/php-7.4.0$ make
make: Circular ext/opcache/ZendAccelerator.lo <- /home/test dependency dropped.
make: *** No rule to make target 'user/.phpbrew/build/php-7.4.0/ext/opcache/ZendAccelerator.c', needed by 'ext/opcache/ZendAccelerator.lo'.  Stop.
```
