### ISSUE TITLE
About some question to switch php version in MacOS

### ISSUE THREAD

**Issue by 0clickjacking0** [phpbrew/phpbrew#1016]
My system OS is `MacOS10.13`. The default PHP version is `7.1.16`.

I use `phpbrew` to manage the PHP version. And I installed the `php5.6`.When I use command `phpbrew switch php5.6`. Then I use the command `php -v`

Then it outputs:
```
PHP 5.6.30 (cli) (built: May 14 2019 18:30:16)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
```

Then I use the command `php-fpm -v`

output:
```
PHP 7.1.16 (fpm-fcgi) (built: Mar 31 2018 03:00:16)
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
```

![php-fpm_problem](https://user-images.githubusercontent.com/40328559/58426450-16c36300-80cf-11e9-84f5-1203abf9440e.png)

My system OS is MacOS10.13. The default PHP version is 7.1.16.

I use phpbrew to manage the PHP version. And I installed the php5.6.When I use command phpbrew switch php5.6. Then I use the commandphp -v

Then it outputs:

PHP 5.6.30 (cli) (built: May 14 2019 18:30:16)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
Then I use the commandphp-fpm -v

output:

PHP 7.1.16 (fpm-fcgi) (built: Mar 31 2018 03:00:16)
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
The php version in terminal is php5.6, and in the web, the version is php7.1

The php-fpm default path is in `/usr/sbin`.

When I try to replace the php-fpm, the web page is 404. The nginx `error.log` is in here.

```
2019/05/15 18:35:48 [error] 3125#0: *51 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "127.0.0.1:82"
2019/05/15 18:35:48 [error] 3125#0: *51 open() "/usr/local/Cellar/nginx/1.15.12/html/50x.html" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "127.0.0.1:82"
2019/05/15 18:35:48 [error] 3125#0: *51 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "127.0.0.1:82"
2019/05/15 18:35:48 [error] 3125#0: *51 open() "/usr/local/Cellar/nginx/1.15.12/html/50x.html" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "127.0.0.1:82"
ailed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "127.0.0.1:82"
2019/05/15 18:48:03 [error] 3125#0: *64 kevent() reported that connect() failed (61: Connection refused) while connecting to upstream, client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "127.0.0.1:82"
2019/05/15 18:48:03 [error] 3125#0: *64 open() "/usr/local/Cellar/nginx/1.15.12/html/50x.html" failed (2: No such file or directory), client: 127.0.0.1, server: localhost, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "127.0.0.1:82"
```

And I try to modify nginx.conf,the result is hear
```
#user  nobody;
worker_processes  1;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    #log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
    #                  '$status $body_bytes_sent "$http_referer" '
    #                  '"$http_user_agent" "$http_x_forwarded_for"';

    #access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on;

    server {
        listen       82;
        server_name  localhost;
        #charset koi8-r;

        #access_log  logs/host.access.log  main;

        location / {
            root   /Users/xianyu123/WWW/;
            index  index.html index.htm index.php;
        }

        #error_page  404              /404.html;

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

        # proxy the PHP scripts to Apache listening on 127.0.0.1:80
        #
        #location ~ \.php$ {
        #    proxy_pass   http://127.0.0.1;
        #}

        # pass the PHP scripts to FastCGI server listening on 127.0.0.1:9000
        #
        location ~ \.php$ {
            root           /Users/xianyu123/WWW/;
            fastcgi_pass   unix:/Users/xianyu123/.phpbrew/php/php-5.6.30/var/run/php-fpm.sock;
            fastcgi_index  index.php;
            fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
            include        fastcgi_params;
        }

        # deny access to .htaccess files, if Apache's document root
        # concurs with nginx's one
        #
        #location ~ /\.ht {
        #    deny  all;
        #}
    }


    # another virtual host using mix of IP-, name-, and port-based configuration
    #
    #server {
    #    listen       8000;
    #    listen       somename:8080;
    #    server_name  somename  alias  another.alias;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}


    # HTTPS server
    #
    #server {
    #    listen       443 ssl;
    #    server_name  localhost;

    #    ssl_certificate      cert.pem;
    #    ssl_certificate_key  cert.key;

    #    ssl_session_cache    shared:SSL:1m;
    #    ssl_session_timeout  5m;

    #    ssl_ciphers  HIGH:!aNULL:!MD5;
    #    ssl_prefer_server_ciphers  on;

    #    location / {
    #        root   html;
    #        index  index.html index.htm;
    #    }
    #}
    include servers/*;
}
```

And when I access `127.0.0.1:82/index.php`,the result is hear
![50A3017A-4F7A-4C30-957B-8DA2400E2356](https://user-images.githubusercontent.com/40328559/58426408-f398b380-80ce-11e9-804c-608e2fd39063.png)

And access `127.0.0.1:82/1.html` is ok
![B9401287-50A9-4CB2-A134-6D7EF7818FAC](https://user-images.githubusercontent.com/40328559/58426501-45413e00-80cf-11e9-808b-de72c6e1845c.png)

when I use command ` ps -ef | grep php-fpm`,the result is hear
![A8FBD25C-2151-43A9-9CEB-3FD2723824E0](https://user-images.githubusercontent.com/40328559/58426614-9bae7c80-80cf-11e9-9f54-cd2531ecea4b.png)

I know the php-fpm5.6 is error,but I don't konw how to fix it

**Comment by 0clickjacking0** [comment]
I already fix this problem,I write it in my blog,the address is hear
https://xianyu123.me/2019/05/28/mac%E4%B8%8B%E5%AE%89%E8%A3%85%E5%A4%9A%E7%89%88%E6%9C%ACphp%E5%92%8C%E9%85%8D%E7%BD%AEphp-fpm%E7%9A%84%E4%B8%80%E4%BA%9B%E5%9D%91/

**Comment by 0clickjacking0** [comment]
The above link cannot be opened because my old domain name has expired, so I can access this。https://0clickjacking0.github.io/2019/05/28/mac%E4%B8%8B%E5%AE%89%E8%A3%85%E5%A4%9A%E7%89%88%E6%9C%ACphp%E5%92%8C%E9%85%8D%E7%BD%AEphp-fpm%E7%9A%84%E4%B8%80%E4%BA%9B%E5%9D%91/

**Comment by peter279k** [comment]
According to the above reference, the current solutions are as follows:

- Running the `rm -f /usr/sbin/php-fpm` command.
- Running the `ln -s /Users/kb/.phpbrew/php/php-5.6.30/sbin/php-fpm /usr/sbin/php-fpm` to create a soft link. 
- Running the `cat ~/.phpbrew/php/php-5.6.30/etc/php-fpm.conf | grep "listen = /"` command to get the absolute path.
- Modifing the `/usr/local/etc/nginx/nginx.conf` file and replace the `THE_UNIX_PATH` with above path.

```
......
location ~ \.php$ {
    root                  html;
    fastcgi_pass      unix:THE_UNIX_PATH;
    fastcgi_index    index.php;
    fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
    include            fastcgi_params;
}
......
```

When encountering the `Permission denied while connecting to upstream` problem, adding the following lines after the line of `listen` keyword in the `/Users/kb/.phpbrew/php/php-5.6.30/etc/php-fpm.conf` file:

```
listen.owner = nobody
listen.group = nobody
```

- Finding the `user` keyword in the `/usr/local/etc/nginx/nginx.conf` file and uncomment  that line.
- Restarting the Nginx and PHP-FPM services, and the issue will be resolved.
