### ISSUE TITLE
PhpBrew cannot detect the directory with libraries on Ubuntu 19.04

### ISSUE THREAD

**Issue by morozov** [phpbrew/phpbrew#1035]
```
$ phpbrew --debug install 7.3.7 +neutral +openssl
===> phpbrew will now build 7.3.7
---> Parsing variants from command arguments '+neutral +openssl'
===> Loading and resolving variants...
Checking distribution checksum...
Checksum matched: c3608fa7114642725854119ccffe722f42fc7c31e5e4c00d5cb4cb1a0d16bf18
===> Distribution file was successfully extracted, skipping...
Source Directory: /home/morozov/.phpbrew/build/php-7.3.7
Found existing Makefile, running make clean to ensure everything will be rebuilt.
You can append --no-clean option after the install command if you don't want to rebuild.
===> Running make clean: /usr/bin/make -C '/home/morozov/.phpbrew/build/php-7.3.7' --quiet 'clean'
Running Command:/usr/bin/make -C '/home/morozov/.phpbrew/build/php-7.3.7' --quiet 'clean'
Writing variant info to /home/morozov/.phpbrew/php/php-7.3.7/phpbrew.variants
===> Checking patches...
Checking patch for replace apache php module name with custom version name
Enabled variants: [openssl, xml, opcache]
Disabled variants: []
===> Configuring 7.3.7...


Use tail command to see what's going on:
   $ tail -F /home/morozov/.phpbrew/build/php-7.3.7/build.log


./configure '--cache-file=/home/morozov/.phpbrew/cache/config.cache' '--prefix=/home/morozov/.phpbrew/php/php-7.3.7' '--with-config-file-path=/home/morozov/.phpbrew/php/php-7.3.7/etc' '--with-config-file-scan-dir=/home/morozov/.phpbrew/php/php-7.3.7/var/db' '--with-openssl=/usr' '--enable-dom' '--enable-libxml' '--with-libxml-dir=/usr' '--enable-simplexml' '--enable-xml' '--enable-xmlreader' '--enable-xmlwriter' '--with-xsl' '--enable-opcache' >> /home/morozov/.phpbrew/build/php-7.3.7/build.log 2>&1
Error: Configure failed:
The last 5 lines in the log file:
/usr/include/openssl/evp.h

/usr/lib/libssl.a /usr/lib/libssl.so



configure: error: Cannot 11 find OpenSSL's libraries

Please checkout the build log file for more details:
	 tail /home/morozov/.phpbrew/build/php-7.3.7/build.log
```
As you can see, there's no `--with-libdir=lib/x86_64-linux-gnu` switch in the call to `./configure` which leads to not being able to find the OpenSSL library:
```
$ locate -b libssl.so
/usr/lib/i386-linux-gnu/libssl.so.1.1
/usr/lib/x86_64-linux-gnu/libssl.so
/usr/lib/x86_64-linux-gnu/libssl.so.1.0.0
/usr/lib/x86_64-linux-gnu/libssl.so.1.1

$ dpkg -S /usr/lib/x86_64-linux-gnu/libssl.so
libssl-dev:amd64: /usr/lib/x86_64-linux-gnu/libssl.so
```
This issue looks similar and may be related to #418.

**Comment by morozov** [comment]
Further investigation shows that there's a `/usr/lib64` directory on my relatively fresh Ubuntu 19.04 instance which contains a single symlink:
```
$ ls -l /usr/lib64/ld-linux-x86-64.so.2 
lrwxrwxrwx 1 root root 32 Jul 24 15:44 /usr/lib64/ld-linux-x86-64.so.2 -> /lib/x86_64-linux-gnu/ld-2.29.so
```
The symlink itself doesn't seem to belong to any specific package but it could be just created during a package installation. This `/usr/lib64` directory tricks PhpBrew into searching for the `x86_64-linux-gnu` directory in `/usr/lib64` instead of `/usr/lib` where it does exist and this causes the failure.

**Comment by morozov** [comment]
Also, a similar issue: #794.

**Comment by morozov** [comment]
Even given that we went through that 3 years ago, the existing logic of detecting the prefix doesn't seem right. The fact that `/usr/lib64` was created as a workaround for some package shouldn't break the installation. The existing logic looks too complicated and brittle:
https://github.com/phpbrew/phpbrew/blob/bceaee1faf158cf2b073be715877e8ba0d71797d/src/PhpBrew/VariantBuilder.php#L1108-L1112

@c9s, @jhdxr could we replace it with something like the following?
```php
if (file_exists('/usr/lib/x86_64-linux-gnu')) {
    $this->addOptions('--with-libdir=lib/x86_64-linux-gnu');
} elseif (file_exists('/usr/lib/i386-linux-gnu')) {
    $this->addOptions('--with-libdir=lib/i386-linux-gnu');
}
```

**Comment by Naoray** [comment]
Could this please be merged in :)!!!

**Comment by morozov** [comment]
@jhdxr could you review #1036, please? It should be straightforward.

**Comment by jhdxr** [comment]
I agree that on Debian/Ubuntu `/lib64` is not used any more .[1][2]
however, I think the code [here](https://github.com/phpbrew/phpbrew/blob/01de61670dc172e3d1311675c75b295da57a72cf/src/PhpBrew/Utils.php#L124) is aimed for Fedora. I never use Fedora so I'm not sure if this is true. 

IMO the issue here is `detectArch` only return the first folder existed from the list, without looking if the full path exists or not (this is done in `findLibPrefix`).

My suggestion is we should change `detectArch` to return all existing folders, instead of only the first one. and let caller to pick the correct one.

1. https://wiki.ubuntu.com/MultiarchSpec
2. https://unix.stackexchange.com/questions/43190/where-did-usr-lib64-go-and-what-is-usr-lib-x86-64-linux-gnu

**Comment by morozov** [comment]
> […] however, I think the code [here](https://github.com/phpbrew/phpbrew/blob/01de61670dc172e3d1311675c75b295da57a72cf/src/PhpBrew/Utils.php#L124) is aimed for Fedora. I never use Fedora so I'm not sure if this is true. 

FWIW, `/lib64` in the latest Fedora is also a symlink to `/usr/lib64`, as well as in Ubuntu:
```
$ docker run --rm fedora:latest ls -l /
total 52
lrwxrwxrwx   1 root root    7 Feb 11  2019 bin -> usr/bin
dr-xr-xr-x   2 root root 4096 Feb 11  2019 boot
drwxr-xr-x   5 root root  340 Oct 24 01:05 dev
drwxr-xr-x   1 root root 4096 Oct 24 01:05 etc
drwxr-xr-x   2 root root 4096 Feb 11  2019 home
lrwxrwxrwx   1 root root    7 Feb 11  2019 lib -> usr/lib
lrwxrwxrwx   1 root root    9 Feb 11  2019 lib64 -> usr/lib64
drwx------   2 root root 4096 Sep 26 07:49 lost+found
drwxr-xr-x   2 root root 4096 Feb 11  2019 media
drwxr-xr-x   2 root root 4096 Feb 11  2019 mnt
drwxr-xr-x   2 root root 4096 Feb 11  2019 opt
dr-xr-xr-x 355 root root    0 Oct 24 01:05 proc
dr-xr-x---   2 root root 4096 Sep 26 07:50 root
drwxr-xr-x  13 root root 4096 Sep 26 07:50 run
lrwxrwxrwx   1 root root    8 Feb 11  2019 sbin -> usr/sbin
drwxr-xr-x   2 root root 4096 Feb 11  2019 srv
dr-xr-xr-x  13 root root    0 Oct 24 01:05 sys
drwxrwxrwt   2 root root 4096 Sep 26 07:50 tmp
drwxr-xr-x  12 root root 4096 Sep 26 07:49 usr
drwxr-xr-x  18 root root 4096 Sep 26 07:49 var
```

> My suggestion is we should change `detectArch` to return all existing folders, instead of only the first one. and let caller to pick the correct one.

@jhdxr please check the updated PR. Is that what you suggested?

**Comment by jhdxr** [comment]
@morozov exactly! I have approved the PR and it's good to merge. thanks.
