### ISSUE TITLE
execution speed issues with compiled php

### ISSUE THREAD

**Issue by ioweb-gr** [phpbrew/phpbrew#1047]
### Description
I'm creating a custom php version and I'm testing it's performance with a production php version. 
The enabled modules in production php are the ones included in the brewed php and a few more. 

However when I run a simple benchmark script to test the performance on both 
https://raw.githubusercontent.com/vanilla-php/benchmark-php/master/benchmark.php

The results are astonishingly different. 
For example 

Brew PHP = 9sec
Production PHP = 0.7s 

Output of php -m

```
| production     | phpbrew      |
|----------------|--------------|
| bcmath         | bcmath       |
| bz2            | bz2          |
| calendar       | calendar     |
| Core           | Core         |
| ctype          | ctype        |
| curl           | curl         |
| date           | date         |
| dba            | dba          |
| dom            | dom          |
| enchant        | exif         |
| exif           | fileinfo     |
| fileinfo       | filter       |
| filter         | ftp          |
| ftp            | gettext      |
| gd             | gmp          |
| gettext        | hash         |
| gmp            | iconv        |
| hash           | intl         |
| iconv          | json         |
| imagick        | ldap         |
| imap           | libxml       |
| intl           | mbstring     |
| ionCube Loader | mysqli       |
| json           | mysqlnd      |
| ldap           | openssl      |
| libxml         | pcntl        |
| mbstring       | pcre         |
| mysqli         | PDO          |
| mysqlnd        | pdo\_mysql   |
| odbc           | pdo\_pgsql   |
| openssl        | pdo\_sqlite  |
| pcntl          | pgsql        |
| pcre           | Phar         |
| PDO            | posix        |
| pdo\_mysql     | pspell       |
| PDO\_ODBC      | readline     |
| pdo\_pgsql     | Reflection   |
| pdo\_sqlite    | session      |
| pgsql          | SimpleXML    |
| Phar           | soap         |
| posix          | sockets      |
| pspell         | SPL          |
| readline       | sqlite3      |
| redis          | standard     |
| Reflection     | sysvmsg      |
| session        | sysvsem      |
| SimpleXML      | sysvshm      |
| soap           | tidy         |
| sockets        | tokenizer    |
| sodium         | xml          |
| SPL            | xmlreader    |
| sqlite3        | xmlrpc       |
| standard       | xmlwriter    |
| sysvmsg        | xsl          |
| sysvsem        | Zend OPcache |
| sysvshm        | zip          |
| tidy           | zlib         |
| tokenizer      |
| xml            |
| xmlreader      |
| xmlrpc         |
| xmlwriter      |
| xsl            |
| Zend OPcache   |
| zip            |
| zlib           |

```

### Expected Result
Execution speed shouldn't be so drastically different. I can understand even taking twice as long in execution speed but here it's like 15 times slower. 

### Command

`phpbrew --debug install 7.2.23 +default +small +mb +dbs +fpm +everything -wddx +gd=shared -- --with-pspell --disable-shmop --disable-debug --disable-rpath --without-gdbm --without-readline as phpbrew7_2_23_dev`
`phpbrew ext install opcache`

### Platform

OS: Ubuntu 18.04

Running PHP: 
7.2.23

Installing PHP:
7.2.23

I would like to understand why it's growing so slow and how to troubleshoot so I can compile efficient phps with phpbrew. Whenever I followed the howtoforge guides to compile a php manually with all those extensions the speed was similar to the production values.If it's not a bug It appears there's something really different in the way phpbrew is compiling in this case that I can't understand or see due to inexperience. Could someone point me in the right direction to create a more efficient php version?

**Comment by morozov** [comment]
I'm closing this as invalid due to the lack of actionable details. PHPBrew is a build and configuration tool that doesn't focus on PHP performance.

**Comment by cayolblake** [comment]
I'm experiencing the same.

Still investigating, yet, `phpbrew` builds are outrageously slow!

**Comment by peter279k** [comment]
PHPBrew need to compile the PHP to manage the different PHP versions and it is up to your hardware requirements.

If you experienced the slow speed, it should consider switching the hardware requirements.

**Comment by ioweb-gr** [comment]
Hi we're not talking about phpbrew speed. 

We're talking about the final php executable being very slow

**Comment by peter279k** [comment]
The final executable PHP is out of scope for the PHPBrew. And PHPBrew is the configuration building tool.

**Comment by ioweb-gr** [comment]
Indeed but when the compiled result is slower than what we normally get by compiling php without phpbrew it seems that the building tool is doing something that's affecting it

**Comment by theofidry** [comment]
Indeed that looks weird, but I think given the scope and overwhelming amount of (GitHub) issues for the project nothing will be investigated by the maintainers, much less without a clear actionable.
