### ISSUE TITLE
How to use this package with valet?

### ISSUE THREAD

**Issue by saippuakauppias** [phpbrew/phpbrew#1049]
Valet is MacOS development environment.

1. I removed `php` installed from `brew`
2. Install php7.3.11 from phpbrew
3. Run `phpbrew use 7.3.11`
4. Run `valet install` (no errors)

But in browser I see "502 Bad Gateway" (I think, it is because valet not found php interpreter).

In valet issues writes about this tool use only php from `brew` (not phpbrew). Maybe someone solve this? I want to use php with compiled `lmdb` support (maybe I can recompile `brew` php for this?)

**Comment by saippuakauppias** [comment]
My method for compile PHP in homebrew with custom configuration args (phpbrew not need!): https://gist.github.com/saippuakauppias/fac2a33dfe420adb4a6cf19c257eef46

**Comment by morozov** [comment]
@saippuakauppias you'll need to look at the logs of the application that produces the 502 response and figure out what it's missing. It's pretty much possible that the path of the PHP binary provided by `brew` is different from the one provided by PHPBrew.

**Comment by saippuakauppias** [comment]
Sorry, I can't reproduce this now, because this break my dev env

**Comment by morozov** [comment]
Then I have to close it since there's nothing we can help with.
