### ISSUE TITLE
Syntax error in PHP53Patch.php

### ISSUE THREAD

**Issue by airdrummingfool** [phpbrew/phpbrew#1053]
I'm running the new 1.24.0 release.

It looks like there's a [trailing comma](https://github.com/phpbrew/phpbrew/blob/ffd381ea213cc5c9c1d36ad453b00778e764afaf/src/PhpBrew/Patches/PHP53Patch.php#L32) in `PHP53Patch.php`, which is causing a syntax error when I try to install PHP 7.3.

### Output
```
[snip]
===> Checking patches...
PHP Parse error:  syntax error, unexpected ')' in phar:///usr/local/bin/phpbrew/src/PhpBrew/Patches/PHP53Patch.php on line 33
```

### Expected Result
PHP 7.3 installs correctly

### Command

```
phpbrew install 7.3 +default +iconv="$(brew --prefix libiconv)" +intl +pgsql +bz2="$(brew --prefix bzip2)" +gd -- --with-gd=shared --with-jpeg-dir=/usr --with-png-dir=/usr --with-zlib-dir="$(brew --prefix zlib)"
```

### Platform

OS: macOS 10.15.1

Running PHP: PHP 5.6.36

Installing PHP: 7.3

**Comment by morozov** [comment]
Indeed. Having a [trailing comma in function calls](https://wiki.php.net/rfc/trailing-comma-function-calls) is valid as of PHP 7.3 and I didn't test this patch on an older PHP version.

**Comment by airdrummingfool** [comment]
Thanks for the quick fix!
