### ISSUE TITLE
Can't install gd with jpeg support

### ISSUE THREAD

**Issue by drgomesp** [phpbrew/phpbrew#106]
I'm trying to install the `gd` extension to support `jpeg`, but I can't do it.

I've installed `libjpeg` with homebrew and set the `--with-jpeg-dir` flag to point to the directory where homebrew installed it.

But I still can't make it work.

The `gd_info()` shows me:

```
array (size=11)
  'GD Version' => string 'bundled (2.1.0 compatible)' (length=26)
  'FreeType Support' => boolean false
  'T1Lib Support' => boolean false
  'GIF Read Support' => boolean true
  'GIF Create Support' => boolean true
  'JPEG Support' => boolean false
  'PNG Support' => boolean true
  'WBMP Support' => boolean true
  'XPM Support' => boolean false
  'XBM Support' => boolean true
  'JIS-mapped Japanese Font Support' => boolean false
```

Any tips?

**Comment by inetfuture** [comment]
> phpbrew 1.11 let you do the things automatically:
> 
>  phpbrew lookup-prefix homebrew
>  phpbrew install 5.4.4 +gd
> This will expand the options to:
> 
> --with-gd=/usr/local/Cellar \
>     --with-png-dir=/usr/local/Cellar \
>     --with-jpeg-dir=/usr/local/Cellar \
>     --with-freetype-dir=/usr/local/Cellar  \
>     --enable-gd-native-ttf

For my case, this works for png and jpeg, but not freetype, I have to use more specific path `--with-freetype-dir=/usr/local/Cellar/freetype/2.6_1/lib`, @c9s any idea why is this happening?

**Comment by inetfuture** [comment]
@c9s 

And, it did not automatically expand, it always use `--with-xx-dir=/usr/local`

I'm on OS X 10.10.5, phpbrew version is 1.20.1

**Comment by sheanhoxie** [comment]
Holy schmoly, I was having so much trouble with this, this was what finally worked for me as suggested by @c9s 

`phpbrew ext install gd -- --with-jpeg-dir=/usr/local/Cellar/`

GD was already installed, but without jpeg support

**my setup**
Mac OS X El Cap 10.11.1
homebrew 0.9.5
phpbrew 1.20.1
php 5.3.29

**Comment by rslhdyt** [comment]
Thanks @c9s your suggestion its works

**Comment by tsusanka** [comment]
If you already had gd installed don't forget to clean the directory before rebuilding.
```
cd ~/.phpbrew/build/$PHPBREW_PHP/ext/gd && make clean && cd -;
phpbrew ext install gd -- --with-jpeg-dir;
```

**Comment by alexswww** [comment]
Please help


`
root@vm2150:~# phpbrew ext install gd
`

`
[ ] gd extension is already disabled.
===> Installing gd extension...
Log stored at: /root/.phpbrew/build/php-5.6.22/ext/gd/build.log
``
Changing directory to /root/.phpbrew/build/php-5.6.22/ext/gd
``
PHP Warning:  shell_exec() has been disabled for security reasons in phar:///usr/local/bin/phpbrew/src/PhpBrew/Tasks/MakeTask.php on line 48
``
===> Running make clean: /usr/bin/make -C '/root/.phpbrew/build/php-5.6.22/ext/gd' 'clean'
PHP Notice:  Undefined variable: returnValue in phar:///usr/local/bin/phpbrew/src/PhpBrew/Utils.php on line 253
`
`
PHP Warning:  system() has been disabled for security reasons in phar:///usr/local/bin/phpbrew/src/PhpBrew/Utils.php on line 253
`
`
PHP Notice:  Undefined variable: returnValue in phar:///usr/local/bin/phpbrew/src/PhpBrew/Utils.php on line 254
`
`
PHP Catchable fatal error:  Argument 2 passed to PhpBrew\Exception\SystemCommandException::__construct() must be an instance of PhpBrew\Build, instance of PhpBrew\Extension\M4Extension given, called in phar:///usr/local/bin/phpbrew/src/PhpBrew/Utils.php on line 255 and defined in phar:///usr/local/bin/phpbrew/src/PhpBrew/Exception/SystemCommandException.php on line 14
root@vm2150:~#
`




`
root@vm2150:~# phpbrew ext clean --purge gd
`

`
Cleaning gd...
PHP Notice:  Undefined variable: returnValue in phar:///usr/local/bin/phpbrew/src/PhpBrew/Utils.php on line 253
PHP Warning:  system() has been disabled for security reasons in phar:///usr/local/bin/phpbrew/src/PhpBrew/Utils.php on line 253
PHP Notice:  Undefined variable: returnValue in phar:///usr/local/bin/phpbrew/src/PhpBrew/Utils.php on line 254
Error: Command failed: rm -rvf /root/.phpbrew/build/php-5.6.22/ext/gd returns:
PHP Notice:  Undefined variable: configureOptions in phar:///usr/local/bin/phpbrew/src/PhpBrew/Console.php on line 131
PHP Warning:  implode(): Invalid arguments passed in phar:///usr/local/bin/phpbrew/src/PhpBrew/Console.php on line 131
Configure options:
`

`
root@vm2150:~# phpbrew ext install gd stable
`

`
[ ] gd extension is already disabled.
===> Installing gd extension...
Log stored at: /root/.phpbrew/build/php-5.6.22/ext/gd/build.log
Changing directory to /root/.phpbrew/build/php-5.6.22/ext/gd
PHP Warning:  shell_exec() has been disabled for security reasons in phar:///usr/local/bin/phpbrew/src/PhpBrew/Tasks/MakeTask.php on line 48
===> Running make clean: /usr/bin/make -C '/root/.phpbrew/build/php-5.6.22/ext/gd' 'clean'
PHP Notice:  Undefined variable: returnValue in phar:///usr/local/bin/phpbrew/src/PhpBrew/Utils.php on line 253
PHP Warning:  system() has been disabled for security reasons in phar:///usr/local/bin/phpbrew/src/PhpBrew/Utils.php on line 253
PHP Notice:  Undefined variable: returnValue in phar:///usr/local/bin/phpbrew/src/PhpBrew/Utils.php on line 254
PHP Catchable fatal error:  Argument 2 passed to PhpBrew\Exception\SystemCommandException::__construct() must be an instance of PhpBrew\Build, instance of PhpBrew\Extension\M4Extension given, called in phar:///usr/local/bin/phpbrew/src/PhpBrew/Utils.php on line 255 and defined in phar:///usr/local/bin/phpbrew/src/PhpBrew/Exception/SystemCommandException.php on line 14
root@vm2150:~#
`



`
root@vm2150:~# tail /root/.phpbrew/build/php-5.6.22/ext/gd/build.log
`

`
Build complete.
Don't forget to run 'make test'.
`
`
make: Leaving directory `/root/.phpbrew/build/php-5.6.22/ext/gd'
make: Entering directory `/root/.phpbrew/build/php-5.6.22/ext/gd'
Installing shared extensions:     /root/.phpbrew/php/php-5.6.22/lib/php/extensions/no-debug-zts-20131226/
Installing header files:           /root/.phpbrew/php/php-5.6.22/include/php/
make: Leaving directory `/root/.phpbrew/build/php-5.6.22/ext/gd'
`

**Comment by ivanchenkoandriy** [comment]
### php 5.6.16
```
phpbrew use 5.6.16
phpbrew ext install gd
--- fail
phpbrew ext disable gd
cd ~/.phpbrew/build/php-5.6.16/ext/gd
make clean
./configure --with-gd=shared --with-vpx-dir=/usr  --with-jpeg-dir=/usr --with-xpm-dir=/usr --with-png-dir=/usr --enable-gd-native-ttf --with-freetype-dir=/usr/include/freetype2/freetype
make
make test
make install
phpbrew ext enable gd
```

this help for me

**Comment by c9s** [comment]
Can you run self-update?

ivanchenkoandriy <notifications@github.com> 於 2016年6月14日 星期二寫道：

**Comment by ivanchenkoandriy** [comment]
![selection_341](https://cloud.githubusercontent.com/assets/10464352/16042115/d12c6528-3241-11e6-85ec-c870e93ee19a.png)
>Can you run self-update?
yes

**Comment by c9s** [comment]
Try reinstall gd extension?

ivanchenkoandriy <notifications@github.com> 於 2016年6月14日 星期二寫道：

**Comment by ivanchenkoandriy** [comment]
sorry, wrong translated
code above helped me
gd - ok
after
```
phpbrew ext disable gd
cd ~/.phpbrew/build/php-5.6.16/ext/gd
make clean
./configure --with-gd=shared --with-vpx-dir=/usr  --with-jpeg-dir=/usr --with-xpm-dir=/usr --with-png-dir=/usr --enable-gd-native-ttf --with-freetype-dir=/usr/include/freetype2/freetype
make
make test
make install
phpbrew ext enable gd
```

**Comment by c9s** [comment]
Looks like your php disabled the shell_exec?

Did you install php with suhosin patch?

ivanchenkoandriy <notifications@github.com> 於 2016年6月14日 星期二寫道：

**Comment by ivanchenkoandriy** [comment]
[phpbrew.info.txt](https://github.com/phpbrew/phpbrew/files/315497/phpbrew.info.txt)

**Comment by ivanchenkoandriy** [comment]
> Try reinstall gd extension?

http://pastebin.com/fNjHmL1P

**Comment by bordeo** [comment]
thanks @sheanhoxie it works for me

**Comment by schnetzi** [comment]
For me the solution was to use the new configuration (see https://github.com/docker-library/php/issues/912)

```sh
phpbrew ext install gd -- --with-freetype --with-jpeg
```
