### ISSUE TITLE
Uninstalling phpbrew and reverting php version

### ISSUE THREAD

**Issue by Lc5** [phpbrew/phpbrew#110]
Is there a possibility to do a clean uninstall of phpbrew, deleting php versions installed with it and reverting to the system php version, that was used originally?

**Comment by colceagdaniel** [comment]
after uninstalling (physically removing .phpbrew folders, both from root and current user) and removing lines from .bashrc files, apache2 somehow still uses the php version previously used by phpbrew. How can i tell apache to use the system php version ? 

Thank you, 
Daniel

**Comment by colceagdaniel** [comment]
you have to change the php5.load file by sudo vi /etc/apache2/mods-enabled/php5.load. there is the current module loaded for php. Remove /usr/lib/apache2/modules/libphp5.x.x.so file. Restart apache2 service and reload. 

Done.

**Comment by eduard-sukharev** [comment]
omg, thank you @colceagdaniel for this - when i understood that managing separate versions and configs of phpbrew is too much for me, the removing of phpbrew didn't work :( I still had weird state and not working setup.
Fixing the php5.load did the trick!
