### ISSUE TITLE
GD with Freetype support [PHP 5.3, DEBIAN]

### ISSUE THREAD

**Issue by chupzzz** [phpbrew/phpbrew#112]
In my Debian 7 Wheezy I have freetype lib installed:
libfreetype6

But when I installing GD extension I have no freetype support (and any type at all).

`phpbrew ext install gd -- --enable-gd-native-ttf --with-freetype-dir=/usr/lib/x86_64-linux-gnu`

Running command without extra parameters have same result.
May be I'm using wrong path for Freetype?

Please, help me to enable it.
Thank you.

**Comment by inetfuture** [comment]
@drgomesp 

I fixed the issue by using more specific path like `--with-freetype-dir=/usr/local/Cellar/freetype/2.6_1/lib`
