### ISSUE TITLE
Error installing PHP 5.6

### ISSUE THREAD

**Issue by neverlose-lv** [phpbrew/phpbrew#1141]
### Output

```
Error: openssl: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases/openssl:1: syntax error, unexpected ..
../Formula/openssl@1.1.rb
^~
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases/openssl:1: unknown regexp options - pl
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases/openssl:1: `@1' is not allowed as an instance variable name
Homebrew formula "openssl" not found.

```

...

```
Error: Configure failed:
The last 5 lines in the log file:
checking for DSA_get_default_method in -lssl... no

checking for X509_free in -lcrypto... no

checking for RAND_egd... no

checking for pkg-config... no

configure: error: Cannot find OpenSSL's <evp.h>

Please checkout the build log file for more details:
	 tail /Users/volk/.phpbrew/build/php-5.6.40/build.log
```

### Expected Result

Successfull installation of PHP 5.6

### Command

```
phpbrew install 5.6
```

### Build Log

    https://gist.github.com/neverlose-lv/556ed963b1ff2e60ef6948bb4a3f1912

### Platform

OS:

OS X 10.15.2 (Catalina)

Running PHP: 

Installed system PHP
PHP 7.4.1 (cli) (built: Dec 18 2019 14:46:18) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.1, Copyright (c), by Zend Technologies

Installing PHP:

5.6

**Comment by morozov** [comment]
The error output seems to belong to Homebrew which PHPBrew just displays. Could you run `brew --prefix openssl` and see if it comes from there?

**Comment by neverlose-lv** [comment]
```
volk ~/sites/cargotenders.com/web (make_refactoring) $ brew --prefix openssl
Error: openssl: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases/openssl:1: syntax error, unexpected ..
../Formula/openssl@1.1.rb
^~
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases/openssl:1: unknown regexp options - pl
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Aliases/openssl:1: `@1' is not allowed as an instance variable name
```

As I'm on MAC (Catalina), I read that they cut of the openssl and replaced it with libressl, so I'm wondering, how to install php 5.6 on mac with openssl

**Comment by morozov** [comment]
This is the right way: Homebrew should provide the OpenSSL dependency for PHP. You probably should solve the Homebrew issue somewhere where Homebrew is supported.
