### ISSUE TITLE
PHP Fatal error:  Uncaught PharException: bz2 extension is required for bzip2 compressed .phar file "/usr/local/bin/phpbrew" in /usr/local/bin/phpbrew:10

### ISSUE THREAD

**Issue by unrelaxs** [phpbrew/phpbrew#1149]
run the command:
apt install php-bz2

**Comment by morozov** [comment]
Thank you. I've updated the requirements and Ubuntu/Debian installation instructions on [wiki](https://github.com/phpbrew/phpbrew/wiki/Requirement).

**Comment by jaltek** [comment]
Maybe I did something wrong but I have the following problem:

I built php-7.0.32 with phpbrew which went fine so far. Then I tried to install an other extension:

```
[jan@foo ~]$ phpbrew list
* (system)
  php-7.0.32     
[jan@foo ~]$ phpbrew use php-7.0.32
[jan@foo ~]$ phpbrew ext install gettext

PHP Fatal error:  Uncaught PharException: bz2 extension is required for bzip2 compressed .phar file "/usr/bin/phpbrew" in /usr/bin/phpbrew:10
Stack trace:
#0 /usr/bin/phpbrew(10): Phar::mapPhar('box-auto-genera...')
#1 {main}
  thrown in /usr/bin/phpbrew on line 10

Fatal error: Uncaught PharException: bz2 extension is required for bzip2 compressed .phar file "/usr/bin/phpbrew" in /usr/bin/phpbrew:10
Stack trace:
#0 /usr/bin/phpbrew(10): Phar::mapPhar('box-auto-genera...')
#1 {main}
  thrown in /usr/bin/phpbrew on line 10

```
IMHO phpbrew should build the bz2 extension by default when installing/building a php version?

**Comment by jaltek** [comment]
Forget it. Found the issue. I somehow excluded bz2 from the default. Sorry.

**Comment by grayguest** [comment]
Environment
```
OS: Linux Mint 19.3
```
-------------------------------------------------------
Problem
i also meet the same problem, and `sudo apt install php-bz2` didn't work for me.
```
# xiaopo in ~/php [10:47:09] C:255
$ sudo apt install php-bz2   
Reading package lists... Done
Building dependency tree       
Reading state information... Done
php-bz2 is already the newest version (1:7.2+60ubuntu1).
0 upgraded, 0 newly installed, 0 to remove and 9 not upgraded.

# xiaopo in ~/php [10:48:20] 
$ phpbrew init            
PHP Fatal error:  Uncaught PharException: bz2 extension is required for bzip2 compressed .phar file "/usr/local/bin/phpbrew" in /usr/local/bin/phpbrew:10
Stack trace:
#0 /usr/local/bin/phpbrew(10): Phar::mapPhar('box-auto-genera...')
#1 {main}
  thrown in /usr/local/bin/phpbrew on line 10
```

**Comment by morozov** [comment]
@grayguest it looks like you're installing `php-bz2` into the PHP managed by your OS and then are trying to use the one built by PHPBrew which still doesn't have the extension.

You could try backup and remove the `~/.phpbrew/init` file and then start a new shell. It will make PHPBrew use the system PHP which will have the extension. After that, you may want to use the PHP managed by your OS as the [system interpreter](https://github.com/phpbrew/phpbrew/wiki/System-Interpreter).

**Comment by MasterBroki** [comment]
add the location of bz2 during the installation helped fix the problem for me
+bz2=/usr/local/Cellar/bzip2/1.0.6_1

**Comment by Sylk** [comment]
I just started getting this error, after triggering a rebuild with `phpbrew install 7.4 +fpm`. I can still start `php-fpm` and my version of PHP prints out nicely for `php -v`. Any commands involving `phpbrew` produce the following error though.

```
PHP Fatal error:  Uncaught PharException: bz2 extension is required for bzip2 compressed .phar file "/usr/local/bin/phpbrew" in /usr/local/bin/phpbrew:10
Stack trace:
#0 /usr/local/bin/phpbrew(10): Phar::mapPhar('box-auto-genera...')
#1 {main}
  thrown in /usr/local/bin/phpbrew on line 10

Fatal error: Uncaught PharException: bz2 extension is required for bzip2 compressed .phar file "/usr/local/bin/phpbrew" in /usr/local/bin/phpbrew:10
Stack trace:
#0 /usr/local/bin/phpbrew(10): Phar::mapPhar('box-auto-genera...')
#1 {main}
  thrown in /usr/local/bin/phpbrew on line 10
```

The strange thing is bzip2, is installed. It's located at `/usr/local/Cellar/bzip2`. Not sure what to do about this.

My Environment:
OSX Catalina: 10.15.6

**Comment by morozov** [comment]
> The strange thing is bzip2, is installed. It's located at `/usr/local/Cellar/bzip2`. Not sure what to do about this.

In your case, bzip2 is available as a library but it doesn't mean that your PHP has the corresponding extension loaded. What's your current PHP (`which php`)? Please see if it has `bzip2 loaded` (`php -m`).

**Comment by Sylk** [comment]
Here is the output of the following commands you've asked for @morozov

`php -v`

```
PHP 7.4.10 (cli) (built: Sep 26 2020 14:06:04) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
```

`which php`

```
/Users/xxx/.phpbrew/php/php-7.4.10/bin/php
```

`php -m`

```
[PHP Modules]
Core
date
dom
hash
libxml
pcre
Phar
Reflection
session
SimpleXML
SPL
standard
tokenizer
xml
xmlreader
xmlwriter
xsl

[Zend Modules]

```

**Comment by morozov** [comment]
Please try the approach in https://github.com/phpbrew/phpbrew/issues/1149#issuecomment-637949090. When you build PHP 7.4.10 using PHPBrew, you need to build it with bz2 and make sure it's displayed by `php -m` before switching to it.

Instead of deleting the init file, you can also try switching off PHPBrew to fall back to the system one.
