### ISSUE TITLE
not find phpbrew app command

### ISSUE THREAD

**Issue by unrelaxs** [phpbrew/phpbrew#1150]
### Output

phpbrew app get compose
...
root@iZwz94p8ja5oybqrmp8ek7Z:~/.phpbrew/php/php-7.2.25/etc/php-fpm.d# phpbrew app get composer
Warning! The usage of PHP older than 7.2.0 as the interpreter is deprecated.
Please set the system interpreter using 'phpbrew system <version>'.
See https://github.com/phpbrew/phpbrew/wiki/System-Interpreter for details.
Did you mean 'fpm'? [Y/n] Y
Did you mean 'setup'? [Y/n] Y
*WARNING* php-fpm --pid option requires php >= 5.6. You need to update your php-fpm.conf for the pid file location.
Exception: /root/.phpbrew/php/composer/sbin/php-fpm doesn't exist.
Trace:

    0) PhpBrew\Command\FpmCommand\SetupCommand->execute('composer')
    1) call_user_func_array([PhpBrew\Command\FpmCommand\SetupCommand, 'execute'], ['composer'])
    2) CLIFramework\CommandBase->executeWrapper(['composer'])
    3) CLIFramework\Application->run(['/usr/local/bin/phpbrew', 'app', 'get', 'composer'])
    4) PhpBrew\Console->runWithTry(['/usr/local/bin/phpbrew', 'app', 'get', 'composer'])
    5) require('phar:///usr/local/bin/phpbrew/bin/phpbrew')

...
phpbrew help
...
rew your latest php!

SYNOPSIS
	phpbrew [options] <command>

OPTIONS
	-v, --verbose
		Print verbose message.

	-d, --debug
		Print debug message.

	-q, --quiet
		Be quiet.

	-h, --help
		Show help.

	--version
		Show version.

	-p, --profile
		Display timing and memory usage information.

	--log-path=[<value>]
		The path of a log file.

	--no-interact
		Do not ask any interactive question.

	--no-progress
		Do not display progress bar.

COMMANDS
                help    Show help message of a command
                init    Initialize phpbrew config file.
               known    List known PHP versions
             install    Install php
                list    List installed PHPs
                 use    Use php, switch version temporarily
              switch    Switch default php version.
                each    Iterate and run a given shell command over all php versions managed by PHPBrew.
              config    Edit your current php.ini in your favorite $EDITOR
                info    Show current PHP information
                 env    Export environment variables
           extension    List extensions or execute extension subcommands
            variants    List php variants
                path    Show paths of the current PHP.
                  cd    Change to directories
            download    Download php
               clean    Clean up the source directory of a PHP distribution
              update    Update PHP release source file
               ctags    Run ctags at current php source dir for extension development.
                 fpm    fpm commands
            list-ini    List loaded ini config files.
         self-update    Self-update, default to master version
              remove    Remove installed php build.
               purge    Remove installed php version and config files.
                 off    Temporarily go back to the system php
          switch-off    Definitely go back to the system php
              system    Get or set the internally used PHP binary
          system-off    Use the currently effective PHP binary internally

HELP
	'phpbrew help' lists available subcommands and some topics. See
	'phpbrew help <command>' or 'phpbrew help <topic>' to read about a
	specific subcommand or phpbrew.

phpbrew 1.25.3		powered by https://github.com/c9s/CLIFramework

### Expected Result

```
...
```

### Command

phpbrew app get compose

### Build Log

    gist here

### Platform

OS:

    ubunut 16.04

Running PHP: 

Installing PHP:

**Comment by unrelaxs** [comment]
#phpbrew help app
Warning! The usage of PHP older than 7.2.0 as the interpreter is deprecated.
Please set the system interpreter using 'phpbrew system <version>'.
See https://github.com/phpbrew/phpbrew/wiki/System-Interpreter for details.
PHP Notice:  Undefined index: app in phar:///usr/local/bin/phpbrew/vendor/corneltek/cliframework/src/Command/HelpCommand.php on line 102
TOPIC
PHP Fatal error:  Uncaught Error: Call to a member function getTitle() on null in phar:///usr/local/bin/phpbrew/vendor/corneltek/cliframework/src/Command/HelpCommand.php:38
Stack trace:
#0 phar:///usr/local/bin/phpbrew/vendor/corneltek/cliframework/src/Command/HelpCommand.php(102): CLIFramework\Command\HelpCommand->displayTopic(NULL)
#1 [internal function]: CLIFramework\Command\HelpCommand->execute('app')
#2 phar:///usr/local/bin/phpbrew/src/PhpBrew/Command/HelpCommand.php(28): call_user_func_array(Array, Array)
#3 [internal function]: PhpBrew\Command\HelpCommand->execute('app')
#4 phar:///usr/local/bin/phpbrew/vendor/corneltek/cliframework/src/CommandBase.php(846): call_user_func_array(Array, Array)
#5 phar:///usr/local/bin/phpbrew/vendor/corneltek/cliframework/src/Application.php(398): CLIFramework\CommandBase->executeWrapper(Array)
#6 phar:///usr/local/bin/phpbrew/src/PhpBrew/Console.php(105): CLIFramework\Application->run(Array)
#7 phar:///usr/local/bin/phpbrew/bin/phpbrew(26): PhpBrew\Console->runWithTry(Array)
#8 /usr/lo in phar:///usr/local/bin/phpbrew/vendor/corneltek/cliframework/src/Command/HelpCommand.php on line 38

**Comment by morozov** [comment]
> ```
> root@iZwz94p8ja5oybqrmp8ek7Z:~/.phpbrew/php/php-7.2.25/etc/php-fpm.d# phpbrew app get composer
> Warning! The usage of PHP older than 7.2.0 as the interpreter is deprecated.
> Please set the system interpreter using 'phpbrew system <version>'.
> See https://github.com/phpbrew/phpbrew/wiki/System-Interpreter for details.
> Did you mean 'fpm'? [Y/n] Y
> Did you mean 'setup'? [Y/n] Y
> ```
The `app` command was deprecated in https://github.com/phpbrew/phpbrew/pull/1088, removed in https://github.com/phpbrew/phpbrew/pull/1126 and accidentally merged into `1.25.1` (71749ae0a6a50254743f266e8ab31727c3413671). There's nothing can be done about that.

The "Fatal error: Uncaught Error: Call to a member function getTitle() on null", as the stack trace shows, comes from the `corneltek/cliframework` which we don't have control over (#1137). It yields the same error for any non-existing command (try `phpbrew help xyz`).

I'm (slowly) trying to replace the currently used CLI framework with Symfony Console (https://github.com/phpbrew/phpbrew/pull/1138).
