### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Phar' not found in /usr/local/bin/phpbrew:10

### ISSUE THREAD

**Issue by UDK** [phpbrew/phpbrew#1152]
### Output

phpbrew init
PHP Fatal error:  Uncaught Error: Class 'Phar' not found in /usr/local/bin/phpbrew:10
Stack trace:
#0 {main}
  thrown in /usr/local/bin/phpbrew on line 10

Fatal error: Uncaught Error: Class 'Phar' not found in /usr/local/bin/phpbrew:10
Stack trace:
#0 {main}
  thrown in /usr/local/bin/phpbrew on line 10

my history commands:
  100  curl -L -O https://github.com/phpbrew/phpbrew/raw/master/phpbrew
  101  chmod +x phpbrewls
  102  ls
  103  chmod +x phpbrew
  104  mv phpbrew /usr/local/bin/phpbrew
  105  ll
  106  phpbrew init --root=/opt/phpbrew
  107  mkdir /opt/phpbrew
  108  phpbrew init --root=/opt/phpbrew
  109  yum install php-cli
  110  phpbrew init --root=/opt/phpbrew
  111  yum install php-common
  112  phpbrew init --root=/opt/phpbre
  113  yum install bizon re2c
  114  phpbrew init --root=/opt/phpbre
  115  phpbrew init
  116  ls /opt/phpbrew/
  117  gist here
  118  history

### Expected Result

I want to install php 5.3.3

### Platform

OS:

Centos 7

Running PHP: 

Installing PHP: before installing v7.1.33

**Comment by morozov** [comment]
@UDK what PHP are you running? According to the [documentation](https://www.php.net/manual/en/phar.installation.php):

> The Phar extension is bundled with PHP as of PHP version 5.3.0, and enabled by default.

Please see what the following commands produce for you:
```
$ which php
/usr/bin/php

$ php -m | grep -i phar
Phar
```
Depending on how PHP is packaged in Centos 7, you may need to install the PHAR extension additionally.

**Comment by UDK** [comment]
Thanks for the answer
it works for me php: php 7.2.26
output commands:
`
[root@ivsupport ~]# which php
/usr/bin/php

[root@ivsupport ~]# php -m | grep -i phar
Phar
`

**Comment by peter279k** [comment]
The Phar extension should be existed before using the PHPBrew.

Please use the latest PHPBrew version and try again.
