### ISSUE TITLE
Broken signature

### ISSUE THREAD

**Issue by akoSalman** [phpbrew/phpbrew#1155]
### Output

```
PHP Fatal error:  Uncaught PharException: phar "/usr/local/bin/phpbrew" has a broken signature in /usr/local/bin/phpbrew:3
Stack trace:
#0 /usr/local/bin/phpbrew(3): Phar::mapPhar('phpbrew.phar')
#1 {main}
  thrown in /usr/local/bin/phpbrew on line 3

```

### Command
```
phpbrew
```

### Platform

OS:
    Debian 8

When running `phpbrew` I get that error.
What causes that?

**Comment by peter279k** [comment]
Please follow the [Quick Start](https://github.com/phpbrew/phpbrew/wiki/Quick-Start) and try again.

I think this issue is temporary and please use the latest stable PHPBrew version. Thanks.
