### ISSUE TITLE
source phpbrew.fish fails on fish 3

### ISSUE THREAD

**Issue by mitsuru793** [phpbrew/phpbrew#1160]
### Output

I got a error when fish shell starts.

```
~/.phpbrew/phpbrew.fish (line 519): Expected a string, but instead found a '&'
            set curr_fs (stat -f %d "$curr_dir" >/dev/null ^&1)  # BSD version
```

What does it means?

I think because of fish version 3. When fish version 2, it was fixed by the issue.
[Fish fails :\( · Issue \#577 · phpbrew/phpbrew](https://github.com/phpbrew/phpbrew/issues/577)

### Expected Result

The error will be resolved.

### Command

Nothing

### Build Log

Nothing

### Platform

```
> sw_vers
ProductName:    Mac OS X
ProductVersion: 10.15.3
BuildVersion:   19D76

> fish --version
fish, version 3.1.0

> phpbrew --version
phpbrew - 1.25.3
cliframework core: 2.5.4
```

**Comment by morozov** [comment]
This is caused by https://github.com/fish-shell/fish-shell/issues/4394.

**Comment by fjorgemota** [comment]
@morozov Could you release a new PHPBrew release with this fix, please? Using `phpbrew self-update` here doesn't seem to fix this issue as expected because there's no release with this fix included..:)

**Comment by morozov** [comment]
@fjorgemota thank you for the reminder. I’ll release 1.26 as soon as I find the time.

**Comment by fjorgemota** [comment]
@morozov Oh, no problem. Thank you for the awesome project and keep the good work! :)

**Comment by morozov** [comment]
Done. Please see [Release 1.26.0](https://github.com/phpbrew/phpbrew/releases/tag/1.26.0).

**Comment by fjorgemota** [comment]
Nice, thanks!
