### ISSUE TITLE
zshrc style broken

### ISSUE THREAD

**Issue by phoenixg** [phpbrew/phpbrew#1168]
After I add `[[ -e ~/.phpbrew/bashrc ]] && source ~/.phpbrew/bashrc` to `~/.zshrc` , my shell style is ugly displaying like this:

```shell
\w > \u@\h [php:7.4.3 -phpbrew]\n$
```

**Comment by Swanty** [comment]
@phoenixg did you manage to resolve it?

**Comment by peter279k** [comment]
I don't present the issue when running the Zsh with `[[ -e ~/.phpbrew/bashrc ]] && source ~/.phpbrew/bashrc` to `~/.zshrc` file in the Ubuntu 22.04.

And my Zsh version is `5.8`.
