### ISSUE TITLE
argon2 password hashing undefined constants, unable to hash passwords.

### ISSUE THREAD

**Issue by Elycin** [phpbrew/phpbrew#1170]
Hi there, 
I'm hoping this is pretty trivial and there's some kind of build flag I am missing, but I need Argon2 for password hashing for this particular project I am working on.

I've tried googling, but can't seem to find anything so I figured a github issue would be the best place to ask.

### Output

```
# php testargon2id.php 
PHP Warning:  Use of undefined constant PASSWORD_ARGON2ID - assumed 'PASSWORD_ARGON2ID' (this will throw an Error in a future version of PHP) in /var/www/html/releases/20200319180102/testargon2id.php on line 3

Warning: Use of undefined constant PASSWORD_ARGON2ID - assumed 'PASSWORD_ARGON2ID' (this will throw an Error in a future version of PHP) in /var/www/html/releases/20200319180102/testargon2id.php on line 3
PHP Warning:  password_hash(): Unknown password hashing algorithm: PASSWORD_ARGON2ID in /var/www/html/releases/20200319180102/testargon2id.php on line 3

Warning: password_hash(): Unknown password hashing algorithm: PASSWORD_ARGON2ID in /var/www/html/releases/20200319180102/testargon2id.php on line 3
```

### Expected Result
A password hash of some sort.  
eg: `$argon2id$v=19$m=1024,t=1,p=1$c29tZXNhbHQ$wRWJvQjyINIOOGrjeE9zXONu5VJuZbGFUTkhcst0LuU`

### Command
`phpbrew install php-7.4.4 +zts +phar +fpm +mysql +pdo -- --with-bz2=/us`

### Build Log
Not sure if needed due to there being no kinds of compile errors, but [here you go](https://gist.github.com/Elycin/3cab5b3cad93248b9c19035a2b622313)

### Platform
```
# uname -a
Linux 3.10.0-1062.18.1.el7.x86_64 #1 SMP Tue Mar 17 23:49:17 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
```

Running PHP: 
7.4.4 (system)

Installing PHP:
7.4.4 (phpbrew)

**Comment by Fahl-Design** [comment]
Hi, 

to make PASSWORD_ARGON2ID you have to compile php with an additional flag: ` --with-password-argon2`

try to install it with:
```bash
phpbrew install php-7.4.4 +zts +phar +fpm +mysql +pdo -- --with-bz2=/us  --with-password-argon2
```

:v:

**Comment by Elycin** [comment]
Hi @Fahl-Design this worked for the most part, however I seem to be encountering issues with libsodium as it seems that the compiler cannot find the libraries/headers.

Do you have any idea about the arguments that would be required, or if there's a way I can point the compiler somewhere to where `libsodium`, `libsodium-headers` and `libsodium-devel` is?

Best Regards,
Ely

**Comment by peter279k** [comment]
For Ubuntu, it should run the `sudo apt-get install libsodium-dev libargon2-dev` command.

Then run the `php-7.4.4 +default -- --with-password-argon2` command.

After compiling and building the `PHP 7.4.4` is done, using the following command to verify the Argon2 password is supported:

```sh
$ phpbrew switch php-7.4.4
php -r "echo password_hash('test', PASSWORD_ARGON2ID);"
$argon2id$v=19$m=65536,t=4,p=1$ZnA0NHJZV3VPNTJadzRJUw$AaoRF97fymGm7dgI3lEpW9zpQmkEXI7h/cyLC8aWmXo
```
