### ISSUE TITLE
phpbrew outputting question marks after installing php 5.3

### ISSUE THREAD

**Issue by awright424** [phpbrew/phpbrew#1173]
### Output
oot@server-28:~# phpbrew use php-5.3.29
-bash: warning: command substitution: ignored null byte in input
????: command not found
root@server-28:~# php -v
PHP 5.3.29 (cli) (built: Apr  7 2020 18:07:15) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2014 Zend Technologies
root@server-28:~# phpbrew ext list
????root@server-28:~# phpbrew ext install mcrypt
????root@server-28:~# 
root@server-28:~# phpbrew ext install mcrypt
????root@server-28:~# 
root@server-28:~# phpbrew
root@server-28:~# source ~/.phpbrew/bashrc
root@server-28:~# phpbrew
????root@server-28phpbrew init
????root@server-28php -version

```
...
```

### Expected Result

I was able to get php5.3 to build once it completed phpbrew starting outputting ??? php -v shows the correct version as well. I am also running this on ubuntu 18.04
```
...
```

### Command

Paste your phpbrew install command here (be sure to install with `--debug` flag, e.g. `phpbrew --debug install`)

    phpbrew  

### Build Log

    gist here

### Platform

OS:
ubuntu 18.04

Running PHP: 7.2
 
Installing PHP: 5.3.29

**Comment by peter279k** [comment]
I don't get the issue in the `Ubuntu 18.04` with `PHPBrew 1.27.0` version.

Please feel free to open the issue if the issue still happens.
