### ISSUE TITLE
.phpbrewrc is not loaded initially

### ISSUE THREAD

**Issue by halilim** [phpbrew/phpbrew#1175]
### Steps to Reproduce

1. Create a RC file in a project
    ```
    # project/.phpbrewrc
    phpbrew use 7.2.29
    ```
2. Open a new terminal window or tab in project folder

### Output

```
$ php -v
PHP 7.3.11 ...
```

### Expected

```
$ php -v
PHP 7.2.29 ...
```

## Description

`~/.phpbrew/bashrc` doesn't call `_phpbrewrc_load` initially, only when changing the current directory.

### Workaround

```
# ~/.zshrc
export PHPBREW_RC_ENABLE=1
source ~/.phpbrew/bashrc
_phpbrewrc_load # <---
```

### Platform

What | Version
-- | --
OS | macOS 10.15.4 (19E287)
terminal | iTerm2 3.3.10beta3
shell | zsh 5.8
phpbrew | 1.26.0
system PHP | 7.3.11

```
# ~/.zshrc
export PHPBREW_RC_ENABLE=1
source ~/.phpbrew/bashrc
```

**Comment by heywhy** [comment]
Thank you for the fix. I hope the library author can address this sooner

**Comment by peter279k** [comment]
I install the `zsh 5.8` and use the `PHPBrew 1.27.0` version.

I don't get the issue and it seems to be fixed.
