### ISSUE TITLE
imap variant doesn't work

### ISSUE THREAD

**Issue by jpickwell** [phpbrew/phpbrew#1176]
### Platform

OS: macOS Catalina 10.15.4

Running PHP: 7.3.11 (system PHP)

Installing PHP: 5.6.40 and 7.4.4

The "imap" variant specifies only the `--with-imap-ssl` flag, but this is incomplete and PHP is not compiled with IMAP support. The variant should be specifying both `--with-imap[=DIR]` and `--with-imap-ssl[=DIR]`. `--with-imap-ssl` does not imply `--with-imap`. [PHP's IMAP documentation](https://www.php.net/manual/en/imap.installation.php) confirms this:

> To get these functions to work, you have to compile PHP with `--with-imap[=DIR]`, where DIR is the c-client install prefix.
> ...
> **Note:** Depending on how the c-client was configured, you might also need to add `--with-imap-ssl=/path/to/openssl/` and/or `--with-kerberos=/path/to/kerberos` to the PHP configure line.

**Comment by peter279k** [comment]
I prepare the fresh and clean Ubuntu 18.04 to try to reproduce the issue.

Here are commands I run:

- Install the required package for compiling the PHP with default extensions via the `phpbrew`.
- Installing the latest stable PHPBrew version.
- Running the `sudo apt-get install libc-client-dev libkrb5-dev` to compile the IMAP extension.
- Running  the ` ln -s /usr/lib/libc-client.a /usr/lib/x86_64-linux-gnu/libc-client.a` to let PHP configuring know where the IMAP library is.
- Running the `phpbrew install 7.0 +default +imap` command to install/build the latest `PHP 7.0` version.
- After compiling the `PHP 7.0` version, running the `phpbrew switch php-7.0.33` command to switch current installed version.
- Running the `php -i` to look at the related `Configure Command` message. And the message is as follows:

```sh
'./configure'  '--cache-file=/root/.phpbrew/cache/config.cache' '--prefix=/root/.phpbrew/php/php-7.0.33' '--with-config-file-path=/root/.phpbrew/php/php-7.0.33/etc' '--with-config-file-scan-dir=/root/.phpbrew/php/php-7.0.33/var/db' '--disable-all' '--enable-phar' '--enable-session' '--enable-short-tags' '--enable-tokenizer' '--with-pcre-regex' '--with-zlib=/usr' '--with-libdir=lib/x86_64-linux-gnu' '--enable-cgi' '--with-imap' '--with-kerberos' '--with-imap-ssl=/usr' '--enable-dom' '--enable-libxml' '--with-libxml-dir=/usr' '--enable-simplexml' '--enable-xml' '--enable-xmlreader' '--enable-xmlwriter' '--with-xsl' '--enable-opcache'
```

As we can see the above outputs, the `'--with-imap-ssl=/usr'` is added correctly.

I think the issue can be closed.
