### ISSUE TITLE
PHP 7.4.5 installed correctly, but apache is still using 7.4.3 (from ubuntu repositories)

### ISSUE THREAD

**Issue by ToX82** [phpbrew/phpbrew#1178]
### Output
PHP Version | 7.4.3

### Expected Result
PHP Version | 7.4.5

### Command
phpbrew --debug install 7.4 +default +mysql +pdo +gd +intl +zip +curl +imap +xml +mbstring +apxs2=$(which apxs2)

### Build Log

https://gist.github.com/ToX82/ff16ecea3635ac019db41b189b1e18f8

### Platform

OS: Ubuntu 20.04 (fresh, clean install)

Running PHP: Ubuntu repositories have php 7.4.3
Installing PHP: I am trying to install php 7.4.5 through phpbrew. I will also install php 7.2 and 5.6, as soon as I can fix this

### Installation procedure
This is everything I've done in order to use phpbrew. This procedure is the result of several trials and errors, I hope everything is correct.

```
# Installing apache2 and some dev or needed tools
sudo apt install apache2 mariadb-server mariadb-client php-codesniffer ruby ruby-dev filezilla git subversion meld wkhtmltopdf
sudo apt install apache2-dev libapache2-mod-php php php-common php-cli php-fpm php-pear php-bz2 build-essential autoconf automake autotools-dev re2c libxml2 libxml2-dev libssl-dev openssl gettext libicu-dev libmcrypt-dev libmcrypt4 libmhash-dev libonig-dev libxslt1-dev libmhash2 libfreetype6 libfreetype6-dev libgd-dev libgd3 libpng-dev libpng16-16 libjpeg-dev libxpm4 libltdl7 libltdl-dev libreadline-dev libbz2-dev libcurl4-gnutls-dev libzip-dev bison re2c

# Make curl visibile to phpbrew
sudo ln -s /usr/include/x86_64-linux-gnu/curl /usr/local/include/curl

# Make folders accessible by phpbrew (without sudo)
sudo chmod -R oga+rw /usr/lib/apache2/modules
sudo chmod -R oga+rw /etc/apache2
sudo chmod -R oga+rw /etc/php

# Download and install phpbrew
curl -L -O https://github.com/phpbrew/phpbrew/raw/master/phpbrew
chmod +x phpbrew
sudo mv phpbrew /usr/local/bin/phpbrew
phpbrew init
phpbrew update
phpbrew --debug install 7.4 +default +mysql +pdo +gd +intl +zip +curl +imap +xml +mbstring +apxs2=$(which apxs2)
```

**Comment by tc4rv** [comment]
Hello, @ToX82 !

Have you tried to run the `use` or `switch` phpbrew's commands?
you can try the following:

`phpbrew list` # this lists your phpbrew's installed versions of PHP
`phpbrew switch [version choosen in the output of the phpbrew list command]`
or
`phpbrew use [version choosen in the output of the phpbrew list command]`

The `switch` and `use` commands will tell the phpbrew to choose and apply system-wide one of the versions downloaded by itself.
The difference is `use` is temporarily and `switch` isn't, [as said here](https://github.com/phpbrew/phpbrew#use-and-switch).

If you haven't tried any of these yet, give it a shot!

Hope it helps!

**Comment by peter279k** [comment]
Please look at this [solution ](https://github.com/phpbrew/phpbrew/issues/1221#issuecomment-1140433451)to let your `PHP-7.4.5` Apache2 module be enabled in Apache2. I think these issues are same.
