### ISSUE TITLE
Install does not use zlib homebrew prefix when available

### ISSUE THREAD

**Issue by arthurflachs** [phpbrew/phpbrew#1179]
When zlib was installed using homebrew, we should use `brew --prefix zlib` as the default zlib argument.
Running `phpbrew install php-7.x.x +default +zlib=$(brew --prefix zlib)` fixes the issue.

This is very similar to this : https://github.com/phpbrew/phpbrew/pull/1118. I am happy to open a PR if the same fix is the right way to go.

Thanks!

### Output

```
checking for EXSLT support... not found

checking for zip archive read/writesupport... yes

checking pcre install prefix... /usr/local

checking libzip... no

checking for the location of zlib... configure: error: zip support requires ZLIB. Use --with-zlib-dir=<DIR> to specify prefix where ZLIB include and library are located
```

### Command

`phpbrew install php-7.x.x +default`

### Platform

OS: OS X 10.15
Using homebrew

**Comment by peter279k** [comment]
The issue is outdated and will be closed.
