### ISSUE TITLE
using phpbrew on Solaris

### ISSUE THREAD

**Issue by jphustman** [phpbrew/phpbrew#1183]
### Output

```
$ phpbrew -v install 7.4.5 +default
===> phpbrew will now build 7.4.5
===> Loading and resolving variants...
Checking distribution checksum...
Checksum matched: 39daa533d5b63c3394da711dc12867dd76c2ec31c940bbba16f14e577df13d6f
===> Extracting /export/home/dotissd/.phpbrew/distfiles/php-7.4.5.tar.bz2 to /export/home/dotissd/.phpbrew/build/tmp.1589222561/php-7.4.5
tar: C: unknown function modifier
Usage: tar {c|r|t|u|x}[BDeEFhilmnopPTvw@/[0-7]][bf][X...] [j|z|Z] [blocksize] [tarfile] [size] [exclude-file...] {file | -I include-file | -C directory file}...
Error: Extract failed:
```

### Expected Result
On Solaris, the default 'tar' is Solaris's own version. In order to use the gnu-tools, need to be able to alias 'tar' as 'gtar' 

Maybe create a flag like "phpbrew --use-gtar or something to that effect.  I primarily use Solaris at work, and getting this to work on Solaris would be awesome.  I would be happy to help contribute.
```

```

**Comment by peter279k** [comment]
It's about the operating system environment setting. And it simply run the `alias tar="gtar"` command to resolve the issue.
