### ISSUE TITLE
mbstring not installed correctly on PHP 7.4.7

### ISSUE THREAD

**Issue by dingo-d** [phpbrew/phpbrew#1188]
I installed mbstring and it was installed, but a project I'm trying to run failed, saying I'm missing `mbstring` extension. So when I tried to do `php -v` I got an error

### Output

```
PHP Warning:  Module 'mbstring' already loaded in Unknown on line 0

Warning: Module 'mbstring' already loaded in Unknown on line 0
PHP 7.4.7 (cli) (built: Jul 20 2020 20:45:52) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
```

### Expected Result

```
PHP 7.4.7 (cli) (built: Jul 20 2020 20:45:52) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
```

The weird thing is that I can see the `mbstring.so` in the extensions folder and when I do `php -m`. The project installation still fails, saying I don't have it installed.

### Command

Paste your phpbrew install command here (be sure to install with `--debug` flag, e.g. `phpbrew --debug install`)

```
$ phpbrew ext install mbstring --debug

PHP Warning:  Module 'mbstring' already loaded in Unknown on line 0

Warning: Module 'mbstring' already loaded in Unknown on line 0
[ ] mbstring extension is disabled.
===> Installing mbstring extension...
Log stored at: /Users/denis.zoljom/.phpbrew/build/php-7.4.7/ext/mbstring/build.log
Changing directory to /Users/denis.zoljom/.phpbrew/build/php-7.4.7/ext/mbstring
===> Running make clean: /usr/bin/make -C '/Users/denis.zoljom/.phpbrew/build/php-7.4.7/ext/mbstring' --quiet 'clean'
===> Phpize...
===> Configuring...
===> Building...
===> Running make all: /usr/bin/make -C '/Users/denis.zoljom/.phpbrew/build/php-7.4.7/ext/mbstring' 'all'  >> '/Users/denis.zoljom/.phpbrew/build/php-7.4.7/ext/mbstring/build.log' 2>&1
===> Installing...
===> Running make install: /usr/bin/make -C '/Users/denis.zoljom/.phpbrew/build/php-7.4.7/ext/mbstring' 'install'  >> '/Users/denis.zoljom/.phpbrew/build/php-7.4.7/ext/mbstring/build.log' 2>&1
===> Extension is installed.
===> Creating config file /Users/denis.zoljom/.phpbrew/php/php-7.4.7/var/db/mbstring.ini.disabled
===> Enabling extension mbstring
[*] mbstring extension is enabled.
Done.
```

### Build Log

https://gist.github.com/dingo-d/0a7e4d3339f7194983f048b6ec4a5a22

### Platform

**OS**: OSX Catalina 10.15.6

**Running PHP**: 7.4.7

**Comment by smola** [comment]
@dingo-d Your PHP build probably has mbstring already built-in (statically linked), so it cannot load it again as a shared library.

Can you post the output of `php -r 'phpinfo();' | grep -C 5 mbstring`?

**Comment by dingo-d** [comment]
Unfortunately, I had to clean my mac completely so I no longer have phpbrew installed. So I'll close the issue.
