### ISSUE TITLE
centos 7.8 fail to install requirements

### ISSUE THREAD

**Issue by zqfan** [phpbrew/phpbrew#1198]
following doc: https://github.com/phpbrew/phpbrew/wiki/Requirement#centos-requirement

```
# cat /etc/redhat-release 
CentOS Linux release 7.8.2003 (Core)

# rpm -Uvh https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
Retrieving https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
warning: /var/tmp/rpm-tmp.8GXhJ2: Header V4 RSA/SHA1 Signature, key ID 62e74ca5: NOKEY
error: Failed dependencies:
        epel-release >= 7 is needed by webtatic-release-7-3.noarch
```
after yum install epel-release, it fixed

```
# wget http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.2-2.el5.rf.x86_64.rpm
--2020-10-03 19:54:25--  http://pkgs.repoforge.org/rpmforge-release/rpmforge-release-0.5.2-2.el5.rf.x86_64.rpm
Resolving pkgs.repoforge.org (pkgs.repoforge.org)... 78.46.17.228
Connecting to pkgs.repoforge.org (pkgs.repoforge.org)|78.46.17.228|:80...
```

pkgs.repoforge.org cannot be opened by my browser neither

**Comment by jhdxr** [comment]
It's a sad news that webtatic is not updated actually. Personally I suggest to change to remi repo instead. Here is a quick guide: https://blog.remirepo.net/post/2018/12/10/Install-PHP-7.3-on-CentOS-RHEL-or-Fedora

**Comment by peter279k** [comment]
I've updated for the CentOS 7 and CentOS 8 streams. And I also test them in these Linux distributions.

Please feel free to refer the [CentOS/Fedora requirements](https://github.com/phpbrew/phpbrew/wiki/Requirement#fedoracentos-requirements) to setup and install required packages.

Thanks.
