### ISSUE TITLE
Catalina - PHP build failing -  implicit declaration of function 'getpid' is invalid in C99

### ISSUE THREAD

**Issue by Snowmanko** [phpbrew/phpbrew#1199]
Hi,

I am trying to install PHP 7.1 with phpbrew on newest Catalina and build keeps failing at this error. 
What have I missing?

```
Error: Make failed:
The last 5 lines in the log file:
/Users/XXX/.phpbrew/build/php-7.1.33/ext/zip/lib/mkstemp.c:75:8: error: implicit declaration of function 'getpid' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
    pid = getpid();
       ^
1 error generated.
make: *** [ext/zip/lib/mkstemp.lo] Error 1
Please checkout the build log file for more details:
```

**Comment by laupiFrpar** [comment]
Because the file `~/.phpbrew/build/php-<version>/ext/zip/lib/mkstemp.c` has no the following include `#include <unistd.h>`.

I added this include instruction, it works but I have a new error

```

```

**Comment by laupiFrpar** [comment]
Because the file `~/.phpbrew/build/php-<version>/ext/zip/lib/mkstemp.c` has no the following include `#include <unistd.h>`.

I added this include instruction, it works but I have a new error

```
/Users/pl.launay/.phpbrew/build/php-7.1.33/main/reentrancy.c:139:23: error: too few arguments to function call, expected 3, have 2
        readdir_r(dirp, entry);
        ~~~~~~~~~            ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/dirent.h:110:1: note: 'readdir_r' declared here
int readdir_r(DIR *, struct dirent *, struct dirent **) __DARWIN_INODE64(readdir_r);
^
1 error generated.
make: *** [main/reentrancy.lo] Error 1
```

But it is a dirty solution.

**Comment by laupiFrpar** [comment]
@Snowmanko 

I solved my problem by downgrading Xcode.

I’ve updated Xcode to version 12, and these issues appeared. Since I downgraded Xcode from 12 to 11.7, these issues disappeared.

You can download older versions of Xcode here: https://developer.apple.com/download/more/?=xcode

**Comment by Snowmanko** [comment]
Thanks! Will try!
