### ISSUE TITLE
Unable to install PHP: Warning during rename, followed by Unable to move error

### ISSUE THREAD

**Issue by James34Shaw100** [phpbrew/phpbrew#1205]
Followed the quickstart guide up to choosing the first php installation to install, then unable to continue.
Tried setting ~/.phpbrew to chmod 777, same error.

### Output

```
===> phpbrew will now build 7.2.34
---> Parsing variants from command arguments '+default'
===> Loading and resolving variants...
Checking distribution checksum...
Checksum matched: 0e5816d668a2bb14aca68cef8c430430bd86c3c5233f6c427d1a54aac127abcf
===> Extracting /home/drake/.phpbrew/distfiles/php-7.2.34.tar.bz2 to /home/drake/.phpbrew/build/tmp.1605791086/php-7.2.34
===> Moving /home/drake/.phpbrew/build/tmp.1605791086/php-7.2.34 to /home/drake/.phpbrew/build/php-7.2.34
PHP Warning:  rename(/home/drake/.phpbrew/build/tmp.1605791086/php-7.2.34,/home/drake/.phpbrew/build/php-7.2.34): Permission denied in phar:///usr/local/bin/phpbrew/src/PhpBrew/Tasks/ExtractTask.php on line 91
Error: Unable to move /home/drake/.phpbrew/build/tmp.1605791086/php-7.2.34 to /home/drake/.phpbrew/build/php-7.2.34
```

### Command

    phpbrew --debug install 7.2 +default

### Build Log

    N/A - No log file generated

### Platform

OS:

    Ubuntu 20.04.1 LTS
Running under WSL2 on Windows, Kernel:

    4.4.0-18362-Microsoft

Running PHP: 
    PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56) ( NTS )
Installing PHP:
    7.2.34

**Comment by peter279k** [comment]
I run the `phpbrew --debug install 7.2 +default` to compile/install the PHP-7.2 from source inside the Ubuntu 20.04 on WSL and I don't have the permission.

Here the environment I use:

### OS

```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal
```

Running the kernel:

```
4.4.0-19041-Microsoft
```

### Running PHP

```
PHP 7.4.29 (cli) (built: Jun  6 2022 18:04:11) ( NTS )
```

### Installing PHP

```
php-7.2.34
```
