### ISSUE TITLE
Question: can I distribute built PHP binary?

### ISSUE THREAD

**Issue by alfredsgenkins** [phpbrew/phpbrew#1207]
### Question

I have many projects which all require similar PHP configuration, the same extensions, etc. I have prepared the requierement list for each platform. The only issue is, each installation people are forced to wait for compilation of PHP (if it not cached).

Can I bypass it and distribute the build PHP binary?

I am asking here, becuase you seem very compitent in PHP compilation. Does build PHP has some runtime dependencies? I sent a ZIP of built PHP (on my computer) and it worked, while I am unsure, if it will work at all 100%, the CLI does at least.

Is my idea possible? And if it is, may you reccomend the best way to approach it?

**Comment by morozov** [comment]
AFAIK, PHP cannot be compiled as a single binary. What you're looking for is probably Docker.
