### ISSUE TITLE
Phpbrew and Apache setup?

### ISSUE THREAD

**Issue by sakiss** [phpbrew/phpbrew#1221]
I am trying to use the build php with Apache, in Ubuntu 18.04

1. Build php 8.0.2 with apx
`sudo phpbrew install 8.0 +default +pdo +mysql +zip +apxs2=/usr/bin/apxs2 +gd +iconv +json +mcrypt +soap`

2. Disabled the existing apache's php module
`a2dismod php7.2`

Though i cannot locate any php 8 module in my apache's mods-available, neither a _libphp8.0.so_ in the folder: _/usr/lib/apache2/modules/_

Instead i found a libphp.so in phpbrew's folder: _/home/me/.phpbrew/build/php-8.0.2/libs/libphp.so_

Any guidance/info on how this works is really welcome!

**Comment by ttodua** [comment]
Have you ever found a solution?

**Comment by peter279k** [comment]
Compiling the PHP with Apache2 SAPI support tutorial is available [here](https://github.com/phpbrew/phpbrew/wiki/Cookbook#apache2-support).

Here are detailed steps to compile the PHP with Apache2 SAPI support:

- Preparing for the Ubuntu 22.04 VM to complete above tutorial.
- Install the `apache2` and `apache2-dev` packages.
- I also install the `PHP 8.1` module with the `sudo apt-get install libapache2-mod-php8.1` command.
   - ```sudo apt-get install -y apache2 apache2-dev```
- Using the `sudo chmod -R oga+rw /usr/lib/apache2/modules` command to make PHPBrew writable for Apache2 modules directory. (This command is not safe for public system. Be careful for using that.)
- Using the `sudo chmod -R oga+rw /etc/apache2` command to make PHPBrew writable for Apache2 settings directory.(This command is not safe for public system. Be careful for using that.)
- Running the `phpbrew install 8.0 +default +apxs2=/usr/bin/apxs2` command to compile the `PHP-8.0` with required extensions and Apache2 SAPI module.
- After compiling the `PHP-8.0` is successful, it should have the `php.load` in `/etc/apache2/mods-available/` directory.

```sh
lee@lee-VirtualBox:~$ ls /etc/apache2/mods-available/ | grep php
php8.1.conf
php8.1.load
php.load
```

- And I also find the `libphp.so` in the `/usr/lib/apache2/modules/` directory:

```sh
lee@lee-VirtualBox:~$ ls /usr/lib/apache2/modules/ | grep php
libphp8.1.so
libphp.so
lee@lee-VirtualBox:~$
```

- According to above step, we can see that the `libphp.so` is the `PHP-8.0` that generated by PHPBrew.
- Then running the `sudo a2enmod php8.1` to ensure the PHP-8.1 module for Apache2 is enabled.
- Running the `sudo a2enmod php` to enable our `PHP-8.1.19` module Apache2.
- Then running the `sudo systemctl restart apache2` to restart the Apache2 service.

And it will be done to use our compiled `PHP-8.0.19` version for Apache2 support. I know above steps about enabling `PHP-8.0.19` doesn't make sense and weird. But I find the only way to resolve this issue at this moment.

BTW, if we want to use the `PHP-8.1.2` again, we can run the `sudo a2dismod php` and `sudo systemctl restart apache2` commands.

**Comment by peter279k** [comment]
To make `php.load` and `libphp.so` identified for the `PHP-8.0.19`, I think it can rename them to be `php8.0.19.load` and `libphp8.0.19.so`. Here are the steps to do that:

- Running the `mv /usr/lib/apache2/modules/libphp.so /usr/lib/apache2/modules/libphp8.0.19.so` command to rename the `libphp.so` file.
- Running the `mv /etc/apache2/mods-available/php.load /etc/apache2/mods-available/php8.0.19.load` command to rename the `php.load` file.
- Running the `vim /etc/apache2/mods-available/php8.0.19.load` to edit the file and modified contents are as follows:

```
LoadModule php_module         /usr/lib/apache2/modules/libphp8.0.19.so
```

- After completing above steps, using the following commands to enable the `PHP-8.0.19` module again:

```sh
lee@lee-VirtualBox:~$ sudo a2enmod php8.0.19
[sudo] password for lee:
Enabling module php8.0.19.
To activate the new configuration, you need to run:
  systemctl restart apache2
lee@lee-VirtualBox:~$ sudo a2enmod php8.1
Considering dependency mpm_prefork for php8.1:
Considering conflict mpm_event for mpm_prefork:
Considering conflict mpm_worker for mpm_prefork:
Module mpm_prefork already enabled
Considering conflict php5 for php8.1:
Module php8.1 already enabled
lee@lee-VirtualBox:~$
```

**Comment by ttodua** [comment]
@peter279k is it possible, that all those things was available in phpbrew, with some arguments, like `phpbrew set_apache` or whatever you imagine, so that cumbersome steps were automatized for apache users? thanks

**Comment by peter279k** [comment]
Since the [PR](https://github.com/phpbrew/phpbrew/pull/1265) is merged, the original issue is fixed.

That is, it can refer the [tutorial](https://github.com/phpbrew/phpbrew/wiki/Cookbook#apache2-support) to setup the PHP 8.x module for Apache happily.

**Comment by ttodua** [comment]
@peter279k your above comments were also useful, it had more details, which are missing from the tutorial you linked. might be good if those parts were added from those comments into that tutorial.
thanks anyway, really helped.
