### ISSUE TITLE
PHP build failing readdir_r

### ISSUE THREAD

**Issue by rayu666** [phpbrew/phpbrew#1222]
```
too few arguments to function call, expected 3, have 2 readdir_r(dirp, entry);
```
Some people have reloaded Xcode.
But you only need to execute this command before installation:

### Command

   export CFLAGS="-Wno-implicit-function-declaration"

https://bugs.php.net/bug.php?id=80171

**Comment by wibicms** [comment]
Thank you for the solution.

**Comment by peter279k** [comment]
Could you edit the [Troubleshooting](https://github.com/phpbrew/phpbrew/wiki/Troubleshooting) page to add this problem?

I think this is not the issue, and it's a troubleshoot :).

**Comment by peter279k** [comment]
The solution is available in the [troubleshooting section](https://github.com/phpbrew/phpbrew/wiki/Troubleshooting#php-build-failing-readdir_r-in-the-macos-11x) now :).

**Comment by FrancisQX** [comment]
May I ask what is the exact package for the export command in freebsd 13.4 I just experience this issue below
<img width="1434" alt="image" src="https://github.com/user-attachments/assets/b5d029dd-7ace-44fa-9342-b5dce0da4db3" />


/tmp/php-7.3.33/main/reentrancy.c:125:23: error: too few arguments to function call, expected 3, have 2
  125 |         readdir_r(dirp, entry);
      |         ~~~~~~~~~            ^
/usr/include/dirent.h:121:6: note: 'readdir_r' declared here
  121 | int      readdir_r(DIR *, struct dirent *, struct dirent **);
      |          ^         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
*** Error code 1

Stop.
make: stopped in /tmp/php-7.3.33
root@freebsd:/tmp/php-7.3.33 # make install
/bin/sh /tmp/php-7.3.33/libtool --silent --preserve-dup-deps --mode=compile cc -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -Imain/ -I/tmp/php-7.3.33/main/ -DPHP_ATOM_INC -I/tmp/php-7.3.33/include -I/tmp/php-7.3.33/main -I/tmp/php-7.3.33 -I/tmp/php-7.3.33/ext/date/lib -I/usr/local/include/libxml2 -I/tmp/php-7.3.33/ext/sqlite3/libsqlite -I/tmp/php-7.3.33/TSRM -I/tmp/php-7.3.33/Zend    -I/usr/include -g -O2 -fvisibility=hidden -DZEND_SIGNALS   -c /tmp/php-7.3.33/main/reentrancy.c -o main/reentrancy.lo
/tmp/php-7.3.33/main/reentrancy.c:125:23: error: too few arguments to function call, expected 3, have 2
  125 |         readdir_r(dirp, entry);
      |         ~~~~~~~~~            ^
/usr/include/dirent.h:121:6: note: 'readdir_r' declared here
  121 | int      readdir_r(DIR *, struct dirent *, struct dirent **);
      |          ^         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
*** Error code 1

**Comment by peter279k** [comment]
Do you refer this [troubleshooting section](https://github.com/phpbrew/phpbrew/wiki/Troubleshooting#php-build-failing-readdir_r-in-the-macos-11x) to try to resolve the issue?

**Comment by drook** [comment]
@FrancisQX just add 3rd argument to the readdir_r() call on the line 125, which would be result.
