### ISSUE TITLE
phpbrew and wsl2

### ISSUE THREAD

**Issue by sstavridis** [phpbrew/phpbrew#1223]
Hello everyone,

I was wondering if phpbrew can be installed on WSL2?

**Comment by sergiz** [comment]
Yes,

**Comment by peter279k** [comment]
I've setup the Ubuntu 20.04 on WSL2 and compile the PHP-7.4 from source successfully.

You can refer the [Wiki](https://github.com/phpbrew/phpbrew/wiki) and find about Ubuntu 20.04.
