### ISSUE TITLE
'lookup-prefix' does not exist

### ISSUE THREAD

**Issue by selfagency** [phpbrew/phpbrew#1229]
### Command

    12:42:47 ➜ phpbrew lookup-prefix homebrew

### Output

```
Did you mean 'self-update'? [Y/n] n
Command lookup-prefix not found. available commands are: help, zsh, bash, meta, compile, archive, github:build-topics, init, known, install, list, use, switch, each, config, info, env, extension, variants, path, cd, download, clean, update, ctags, fpm, list-ini, self-update, remove, purge, off, switch-off, system, system-off

Please try the command below to see the details:

	/usr/local/bin/phpbrew help
```

### Expected Result

For the command to exist

**Comment by owsygavin** [comment]
also having this problem. I tried downgrading to older version 1.24.1 and the same thing. I previously had phpbrew working just fine but a `brew upgrade` hosed my copy of PHP which was compiled referencing Homebrew's former version of `libicuio` so now I'm in a right pickle!

**Comment by peter279k** [comment]
I use the `PHPBrew 1.27.0` version and the `lookup-prefix` command is available.

Here are some commands I run:

```
$ phpbrew --version
phpbrew - 1.27.0
cliframework core: 2.5.4

$ phpbrew lookup-prefix
/usr/local
```

The issue is going to be closed because the solution is resolved.
