### ISSUE TITLE
Documentation for per dir/project version switch

### ISSUE THREAD

**Issue by vpArth** [phpbrew/phpbrew#1233]
Just missing the documentation for executable phpbrew file for per directory/project php version autoswitching.
Is that feature still alive? Where I can find documentation for it?

**Comment by vpArth** [comment]
I have `PHPBREW_RC_ENABLE=1` in my .bashrc now, but totally forget what file should I create in my project =)
There is not PHPBREW_RC_ENABLE entry on https://phpbrew.github.io/phpbrew/ page.

**Comment by morozov** [comment]
There's an [article](https://github.com/phpbrew/phpbrew/wiki/Using-.phpbrewrc-files) on Wiki.

**Comment by vpArth** [comment]
Thank you
