### ISSUE TITLE
zsh theme looks broken after phpbrew install

### ISSUE THREAD

**Issue by joepagan** [phpbrew/phpbrew#1234]
Hey, just tried phpbrew first time today. 

Can't see any reference to how to resolve this or open/closed issues but looks like phpbrew has obscured my zsh theme.

I'm using zsh, ohmyzsh & [spaceship-prompt](https://github.com/spaceship-prompt/spaceship-prompt)

Have you any suggestions on how to resolve?

### Output

<img width="267" alt="image" src="https://user-images.githubusercontent.com/2337910/120808624-276e0580-c541-11eb-86ef-c7a95c3e70ff.png">

### Expected Result
<img width="361" alt="image" src="https://user-images.githubusercontent.com/2337910/120808593-2046f780-c541-11eb-9166-a8fe6f73dd0a.png">

### Platform

OS:

  macos bigsur 11.3.1

Running PHP: 

7.4.16

Let me know if you need anything else from me.

**Comment by peter279k** [comment]
I only use the zsh on the `macOS 11.6 Bigsur` and it doesn't have the issue:

```
cloudxmac@cloudxmacs-Mac ~ % phpbrew switch php-7.0.33
cloudxmac@cloudxmacs-Mac ~ % php -v
PHP 7.0.33 (cli) (built: Dec  5 2022 16:02:01) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
cloudxmac@cloudxmacs-Mac ~ % sw_vers
ProductName:    macOS
ProductVersion: 11.6
BuildVersion:   20G165
```

**Comment by skinofstars** [comment]
I've resolved this by explicitly disabling the phpbrew prompt

In `~/.zshrc`

```bash
export PHPBREW_SET_PROMPT=0
[[ -e ~/.phpbrew/bashrc ]] && source ~/.phpbrew/bashrc
```

**Comment by peter279k** [comment]
It seems that the [spaceship-prompt](https://github.com/spaceship-prompt/spaceship-prompt) has the issue about Zsh theme.

And the resolved issue is available in the previous reply.
