### ISSUE TITLE
When system interpreter is set, `phpbrew path ext` always returns the system interpreters extension_dir

### ISSUE THREAD

**Issue by TRowbotham** [phpbrew/phpbrew#1235]
When the system interpreter is set, `phpbrew path ext` and `phpbrew path extension-dir` always returns the system interpreter's extension_dir rather than the current php's extension dir.

**Comment by TRowbotham** [comment]
This is on Ubuntu 20.04/WSL2

```bash
$ phpbrew system /usr/bin/php
$ phpbrew switch 7.4.20
$ phpbrew path ext
```
Prints `/usr/lib/php/20190902`, but I expect it to print the extension_dir of the currently active php `~/.phpbrew/php/php-7.4.20/lib/php/extensions/no-debug-non-zts-20190902`

**Comment by peter279k** [comment]
It seems that the `phpbrew path ext` is affected by the `phpbrew system` command.

If the extension directory can change into the `~/.phpbrew/php/php-7.4.20/lib/php/extensions/no-debug-non-zts-20190902`, it can set the `phpbrew system ~/.phpbrew/php/php-7.4.20/bin/php`.

**Comment by peter279k** [comment]
Here are some commands to verify above reply:

```
$ phpbrew system /usr/bin/php
$ phpbrew switch 7.3.33
$ phpbrew path ext
/usr/lib/php/20190902

$ phpbrew system $HOME/.phpbrew/php/php-7.3.33/bin/php
$ phpbrew path ext
$HOME/.phpbrew/php/php-7.3.33/lib/php/extensions/no-debug-non-zts-20180731
```

I'm going to close the issue because the solution is available.
