### ISSUE TITLE
Update for Ubuntu 20.04

### ISSUE THREAD

**Issue by ttodua** [phpbrew/phpbrew#1238]
On [Requirements page](https://github.com/phpbrew/phpbrew/wiki/Requirement#ubuntu-requirements), there is not given an instruction for Ubuntu 20.04 . Would be nice to have.  so, any instructions for successful installation (php8) on ubuntu 20.04?  (atm, I  tried same settings as for 18.04 (without "7.2" version mentioning)

**Comment by ttodua** [comment]
2) Ah, my bad, I have missed that phpbrew instructions about .fish  is not required for regular users.

**Comment by jhdxr** [comment]
I'm sorry but I'm not using Ubuntu so there is little I can help.

**Comment by peter279k** [comment]
I update the [Requirement page](https://github.com/phpbrew/phpbrew/wiki/Requirement) and feel free to use these commands to install required packages in Ubuntu 20.04 :).

**Comment by ttodua** [comment]
> I update the [Requirement page](https://github.com/phpbrew/phpbrew/wiki/Requirement) and feel free to use these commands to install required packages in Ubuntu 20.04 :).

thnx!

**Comment by ttodua** [comment]
Does same apply now ubuntu 22.04 ? (as we are already migrating from 20.04)

**Comment by peter279k** [comment]
Just notify that I also update the [Requirement page](https://github.com/phpbrew/phpbrew/wiki/Requirement#ubuntu-2204) to add the requirements for Ubuntu 22.04. Please feel free to use and enjoy it :).
