### ISSUE TITLE
Error on: phpbrew ext install gd

### ISSUE THREAD

**Issue by Bbarbosa7** [phpbrew/phpbrew#1240]
Hi guy's,
I'm trying to install an extension using phpbrew but i only received this message error. Someone can help me?

### Output

```
Error: Command failed: ./configure '--with-php-config=/home/brayann/.phpbrew/php/php-5.6.40/bin/php-config' >> '/home/brayann/.phpbrew/build/php-5.6.40/ext/gd/build.log' 2>&1 returns:

```

### Command

Paste your phpbrew install command here (be sure to install with `--debug` flag, e.g. `phpbrew --debug install`)

    phpbrew ext install gd  

### Build Log

Configuring for:
PHP Api Version:         20131106
Zend Module Api No:      20131226
Zend Extension Api No:   220131226
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /home/brayann/.phpbrew/php/php-5.6.40
checking for PHP includes... -I/home/brayann/.phpbrew/php/php-5.6.40/include/php -I/home/brayann/.phpbrew/php/php-5.6.40/include/php/main -I/home/brayann/.phpbrew/php/php-5.6.40/include/php/TSRM -I/home/brayann/.phpbrew/php/php-5.6.40/include/php/Zend -I/home/brayann/.phpbrew/php/php-5.6.40/include/php/ext -I/home/brayann/.phpbrew/php/php-5.6.40/include/php/ext/date/lib
checking for PHP extension directory... /home/brayann/.phpbrew/php/php-5.6.40/lib/php/extensions/no-debug-non-zts-20131226
checking for PHP installed headers prefix... /home/brayann/.phpbrew/php/php-5.6.40/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... gawk
checking for GD support... yes, shared
checking for the location of libvpx... no
checking for the location of libjpeg... no
checking for the location of libpng... no
checking for the location of libz... no
checking for the location of libXpm... no
checking for FreeType 2... no
checking for T1lib support... no
checking whether to enable truetype string function in GD... no
checking whether to enable JIS-mapped Japanese font support in GD... no
If configure fails try --with-vpx-dir=<DIR>
If configure fails try --with-jpeg-dir=<DIR>
configure: error: png.h not found.

### Platform

OS: Zorin OS 15.01

    Ubuntu based 18.04

Running PHP: 
5.6.40
Installing PHP:
7.2

**Comment by fozbek** [comment]
On fedora installing libpng-devel package might help

**Comment by peter279k** [comment]
If we want to compile the PHP with GD support, it needs to install some packages in Ubuntu 18.04:

```sh
sudo apt-get install libpng-dev
```

- I use the `PHP-7.4.29` to compile the GD support, but I think the steps are same as the `PHP-7.2` version.
- After installing above package, running the ` phpbrew ext install gd` command again.
- And  it will compile GD support for target PHP version now. Some building logs are as follows:

```sh
lee@lee-VirtualBox:~$ phpbrew ext install gd
===> Installing gd extension...
Log stored at: /home/lee/.phpbrew/build/php-7.4.29/ext/gd/build.log
Changing directory to /home/lee/.phpbrew/build/php-7.4.29/ext/gd
===> Phpize...
===> Configuring...
===> Building...
===> Running make all: /usr/bin/make -C '/home/lee/.phpbrew/build/php-7.4.29/ext/gd' 'all'  >> '/home/lee/.phpbrew/build/php-7.4.29/ext/gd/build.log' 2>&1
===> Installing...
===> Running make install: /usr/bin/make -C '/home/lee/.phpbrew/build/php-7.4.29/ext/gd' 'install'  >> '/home/lee/.phpbrew/build/php-7.4.29/ext/gd/build.log' 2>&1
===> Extension is installed.
===> Creating config file /home/lee/.phpbrew/php/php-7.4.29/var/db/gd.ini.disabled
===> Enabling extension gd
[*] gd extension is enabled.
Done.
```
