### ISSUE TITLE
How to execute under CLI from Apache?

### ISSUE THREAD

**Issue by ttodua** [phpbrew/phpbrew#1241]
I use latest phpbrew (on Ubuntu 20.04,  used php-cli 7.4.3 as a requirement to install phpbrew), finished setup (PHP 8) everything per instructions, using `switch` etc.. etc..
From CLI/Terminal, when I run `php -v` it shows `PHP 8` (shortly, works everything).

However, when I created a `example.php` script under `/var/www/html` with content:
`var_dump(  system('php -v') ); exit;`

When visited from browser, it shows:
`PHP 7.4.3 (cli) ... etc`

Then inside code changed from `php` location to `/root/.phpbrew/php/php-8.0.7/bin/php` but it returns empty response. Is there any recommended/example way of doing that?

**Comment by ttodua** [comment]
related: https://github.com/phpbrew/phpbrew/issues/1221 but neither there is solution posted.

**Comment by peter279k** [comment]
The Apache2 has no correct permission to run the `/root/.phpbrew/php/php-7.4.29/bin/php` command.

It uses the `www-data` to run the programs and the `/root/.phpbrew/php/php-7.4.29/bin/php` is for `root` user.

You can look at the `Apache2` log to know more above details:

```sh
lee@lee-VirtualBox:~$ tail -F /var/log/apache2/error.log
[Sun May 29 13:11:19.624334 2022] [mpm_event:notice] [pid 111695:tid 140640629684096] AH00492: caught SIGWINCH, shutting down gracefully
[Sun May 29 13:11:19.701168 2022] [mpm_prefork:notice] [pid 113116] AH00163: Apache/2.4.52 (Ubuntu) configured -- resuming normal operations
[Sun May 29 13:11:19.701325 2022] [core:notice] [pid 113116] AH00094: Command line: '/usr/sbin/apache2'
[Sun May 29 13:11:19.935620 2022] [mpm_prefork:notice] [pid 113116] AH00170: caught SIGWINCH, shutting down gracefully
[Sun May 29 13:11:20.049800 2022] [mpm_prefork:notice] [pid 113157] AH00163: Apache/2.4.52 (Ubuntu) configured -- resuming normal operations
[Sun May 29 13:11:20.049891 2022] [core:notice] [pid 113157] AH00094: Command line: '/usr/sbin/apache2'
sh: 1: /root/.phpbrew/php/php-7.4.29/bin/php: Permission denied
```

I don't recommend using the PHP CLI running inside Apache2, it should use

**Comment by ttodua** [comment]
@peter279k thanks for response! _(btw, maybe you missed something in last sentence...)_
