### ISSUE TITLE
fish init file uses unsupported and syntax

### ISSUE THREAD

**Issue by seyfahni** [phpbrew/phpbrew#1244]
### Output

Opening a new terminal:
```
~/.phpbrew/phpbrew.fish (line 413): Unsupported use of '&&'. In fish, please use 'COMMAND; and COMMAND'.
    __phpbrew_update_config $argv && __phpbrew_set_path
                                   ^
from sourcing file ~/.phpbrew/phpbrew.fish
	called on line 17 of file ~/.config/fish/config.fish

from sourcing file ~/.config/fish/config.fish
	called during startup

source: Error while reading file “~/.phpbrew/phpbrew.fish”
```

Sourcing the file by hand (`source ~/.phpbrew/phpbrew.fish`):
```
~/.phpbrew/phpbrew.fish (line 413): Unsupported use of '&&'. In fish, please use 'COMMAND; and COMMAND'.
    __phpbrew_update_config $argv && __phpbrew_set_path
                                   ^
from sourcing file ~/.phpbrew/phpbrew.fish
	called on standard input

source: Error while reading file “~/.phpbrew/phpbrew.fish”
```

### Expected Result

- no output when opening a new shell
- no errors when sourcing the `phpbrew.fish` file from within fish

### Command

`source ~/.phpbrew/phpbrew.fish --debug`

### Platform

OS: `Ubuntu 18.04.5 LTS`

Running PHP:
```
PHP 7.2.24-0ubuntu0.18.04.8 (cli) (built: Jul  5 2021 17:41:32) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.24-0ubuntu0.18.04.8, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.9.4, Copyright (c) 2002-2020, by Derick Rethans
```

phpbrew:
```
phpbrew - 1.27.0
cliframework core: 2.5.4
```

fish: `version 2.7.1`

**Comment by alex-vlasov** [comment]
I guess this issue can be closed as outdated.
`fish` supports `&&` starting from version 3 - https://github.com/fish-shell/fish-shell/issues/4620

**Comment by seyfahni** [comment]
Whoa, completely forgot about this issue (I've been using so much docker that I don't use phpbrew anymore). And now I'm wondering why I didn't just opened a PR...

**Comment by peter279k** [comment]
I'm going to close the issue because it's outdated and it's fixed in the Fish 3 version.
