### ISSUE TITLE
current php version:8.1.2，cannot switch to php-7.2.24

### ISSUE THREAD

**Issue by miaotiao** [phpbrew/phpbrew#1259]
### Output

```
Deprecated: strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in phar:///usr/local/bin/phpbrew/vendor/corneltek/getoptionkit/src/Option.php on line 128
```

### Expected Result

```
no error
```

### Command

phpbrew use php-7.2.24

### Build Log

    gist here

### Platform

OS:  Ubuntu 20.10

Running PHP:  8.1.2

**Comment by peter279k** [comment]
I think this issue is resolved since the related dependency is [released](https://github.com/c9s/GetOptionKit/releases/tag/2.6.1) now. Please upgrade the PHPBrew dependencies then switching the PHP version again.
