### ISSUE TITLE
Running PHPs in parrallel on single web server?

### ISSUE THREAD

**Issue by eimajenthat** [phpbrew/phpbrew#127]
Hi, just came across this project.  Love it!  Could have really used this about 3 years ago, when I was supporting an app installed on hundreds of different PHP environments.  These days I don't do that as much, but it's still a great thin to be able to manage multiple versions of PHP.

Let me ask you this, though.  I see that the primary use case for phpbrew is to switch to the preferred PHP environment as needed.  I assume when you run that command, it repoints the php command in the path as a sym link to the correct version (that's how rvm and nvm seem to be doing it).

I see also that all the installations live in their own directory, so if you had a CLI php script that needed a particular version, you could probably specify the path to the needed php version in your shebang syntax, or else explicitly call the php version, like:
`/path/to/specific/version/php myscript.php`.

And I even see that I can compile Apache modules for different php versions, and modify my apache config to use the one I want.

Okay, none of that was actually a question, but here goes.  What if I have specific vhosts that need specific versions of PHP?  Is there a way to configure that?  I'm open to using Apache or Nginx (presumably with FPM?).  What I'd like to have is something like this:

`/var/www/vhosts/supercoolapp.dev` runs PHP 5.5.1
`/var/www/vhosts/somewhatlesscoolapp.dev` runs PHP 5.3.15
`/var/www/vhosts/realoldcrustyapp.dev` run PHP 5.1.12 (the horror!!)

all at the same time, without modifying web server config and restarting it.  I'm betting Apache would only want to deal with a single PHP module, right?  But if we're using nginx, could we have different hosts point to different instances of FPM, presumably running on different ports, running different PHP versions?  I have not worked with nginx and FPM that much, so I really have no clue how to do that, or if one could.

I guess this isn't really within the scope of your project, but you all seem to be a heck of a lot closer to achieving this than anyone else I've encountered.  So I'd love to hear your thoughts.

**Comment by osopolar** [comment]
Did anybody get this work for php 5.2.17 or before?
