### ISSUE TITLE
Document phpbrew fpm setup command

### ISSUE THREAD

**Issue by MagicLegend** [phpbrew/phpbrew#1271]
Hey!

Looks like the `phpbrew fpm setup` command is not documented. This lead me to having to find it in the code, which is not how it should be. The command (with an example or two) should be documented in the FPM section of the docs.

In my case, I was searching how to auto-start FPM since I always forget to do so manually. Turns out that this was a single command away. I ended up finding the functionality via #201 .

### Command

Example setup command:

    sudo PHPBREW_PHP=php-7.4.27 phpbrew fpm setup --launchctl

### Platform

OS:
MacOS 12.5

**Comment by peter279k** [comment]
I think the document can be added in the [wiki](https://github.com/phpbrew/phpbrew/wiki/) and the related setting can be same as the [Apache2](https://github.com/phpbrew/phpbrew/wiki/Cookbook#apache2-support) or [Lighttpd](https://github.com/phpbrew/phpbrew/wiki/Cookbook#how-to-use-with-lighttpd-ubuntu).

**Comment by peter279k** [comment]
And adding the auto-start command I think it's the great idea.

**Comment by MagicLegend** [comment]
Imo it should be added to `README.md` as well, since that's the place where I figure most people would end up (via https://phpbrew.github.io/phpbrew/). This link the first result in Google and DuckDuckGo when searching for `phpbrew docs`. The site could also really do with some section links at the top, but that's a seperate issue I guess. There already is a [FPM section](https://github.com/phpbrew/phpbrew#php-fpm), it should be enough to just mention the command.

**Comment by peter279k** [comment]
You're right. Let's focus on the FPM command in [FPM section](https://github.com/phpbrew/phpbrew#php-fpm):).
