### ISSUE TITLE
Wiki is editable for any user

### ISSUE THREAD

**Issue by djbrown** [phpbrew/phpbrew#1273]
I found out that anyone with a GitHub account is able to create/edit/delete wiki pages:

see: https://github.com/phpbrew/phpbrew/wiki/_permission-test

is this intended? if not you should restrict editing permissions to contributors only

**Comment by c9s** [comment]
yes, this is intended, anyone can update them if they found anything needs to be updated

**Comment by peter279k** [comment]
Our documentation editing style is very similar with the [pyodbc doc](https://github.com/mkleehammer/pyodbc/wiki).
