### ISSUE TITLE
fatal error: 'capstone/capstone.h' file not found

### ISSUE THREAD

**Issue by MagicLegend** [phpbrew/phpbrew#1275]
### Output

```
/bin/sh /Users/<user>/.phpbrew/build/php-8.1.8/libtool --silent --preserve-dup-deps --tag CC --mode=compile cc -Iext/opcache/ -I/Users/<user>/.phpbrew/build/php-8.1.8/ext/opcache/ -I/Users/<user>/.phpbrew/build/php-8.1.8/include -I/Users/<user>/.phpbrew/build/php-8.1.8/main -I/Users/<user>/.phpbrew/build/php-8.1.8 -I/Users/<user>/.phpbrew/build/php-8.1.8/ext/date/lib -I/opt/homebrew/Cellar/openssl@1.1/1.1.1q/include -I/opt/homebrew/Cellar/zlib/1.2.13/include -I/opt/homebrew/opt/bzip2/include -I/opt/homebrew/Cellar/curl/7.85.0/include -I/opt/homebrew/Cellar/libpng/1.6.38/include/libpng16 -I/opt/homebrew/Cellar/jpeg-turbo/2.1.4/include -I/opt/homebrew/opt/freetype/include/freetype2 -I/opt/homebrew/opt/libiconv/include -I/opt/homebrew/Cellar/icu4c/71.1/include -I/opt/homebrew/Cellar/oniguruma/6.9.8/include -I/Users/<user>/.phpbrew/build/php-8.1.8/ext/mbstring/libmbfl -I/Users/<user>/.phpbrew/build/php-8.1.8/ext/mbstring/libmbfl/mbfl -I/opt/homebrew/Cellar/capstone/4.0.2/include/capstone -I/opt/homebrew/opt/readline/include -I/opt/homebrew/Cellar/libsodium/1.0.18_1/include -I/opt/homebrew/Cellar/libzip/1.9.2/include -I/Users/<user>/.phpbrew/build/php-8.1.8/TSRM -I/Users/<user>/.phpbrew/build/php-8.1.8/Zend    -fno-common -Wstrict-prototypes -Wall -Wextra -Wno-strict-aliasing -Wno-unused-parameter -Wno-sign-compare -g -O2 -fvisibility=hidden -DZEND_SIGNALS    -Wno-implicit-fallthrough -DZEND_ENABLE_STATIC_TSRMLS_CACHE=1 -DZEND_COMPILE_DL_EXT=1 -c /Users/<user>/.phpbrew/build/php-8.1.8/ext/opcache/jit/zend_jit.c -o ext/opcache/jit/zend_jit.lo  -MMD -MF ext/opcache/jit/zend_jit.dep -MT ext/opcache/jit/zend_jit.lo
In file included from /Users/<user>/.phpbrew/build/php-8.1.8/ext/opcache/jit/zend_jit.c:713:
ext/opcache/jit/zend_jit_disasm.c:24:11: fatal error: 'capstone/capstone.h' file not found
# include <capstone/capstone.h>
          ^~~~~~~~~~~~~~~~~~~~~
1 error generated.
make: *** [ext/opcache/jit/zend_jit.lo] Error 1
```

### Expected Result

```
Compiled PHP (doi)
```

### Command

Paste your phpbrew install command here (be sure to install with `--debug` flag, e.g. `phpbrew --debug install`)

Initially:

    phpbrew -d install latest +default +soap +iconv="$(brew --prefix libiconv)" +fileinfo +mysql +openssl=$(brew --prefix openssl@1.1) +fpm +sodium +intl +gd +bz2="$(brew --prefix bzip2)" +zlib="$(brew --prefix zlib)" -- --without-pcre-jit

In an attempt to point opcache to capstone's location:

    /opt/homebrew/opt/php@7.4/bin/php /usr/local/bin/phpbrew -d install latest +default +soap +iconv="$(brew --prefix libiconv)" +fileinfo +mysql +openssl=$(brew --prefix openssl@1.1) +fpm +sodium +intl +gd +bz2="$(brew --prefix bzip2)" +zlib="$(brew --prefix zlib)" +opcache="($brew --prefix capstone)" -- --without-pcre-jit

### Build Log

    https://gist.github.com/MagicLegend/b8dfcbad7d418237fa09ebf9bbf88f9f

### Platform

OS:

    MacOS 12.6, M1

Running PHP: 

`7.4.27`

Installing PHP:

`latest` (`8.1.8`)

---

Installing PHP 7.4.27 went fine with this command. How do I disable these other JIT parts, since they appear to be broken on ARM? Note that `capstone` is installed via brew at `/opt/homebrew/opt/capstone`, and the header file it's searching for is available at `/opt/homebrew/opt/capstone/include/capstone/capstone.h`.

Thank you!

**Comment by MagicLegend** [comment]
And of course right as you give up and post the question, you figure out the answer. The solution is to also add `--disable-opcache-jit` to the end of the argument list, as I kind of suspected already. However, disabling JIT in general is not a great solution - is there a better more permanent fix?

**Comment by YmBIgo** [comment]
It helps me, when installed PHP8.1.10 using phpenv.
Thank you !

**Comment by peter279k** [comment]
I prepare fresh and clean Ubuntu 18.04 and try to reproduce the issue.

Some related commands I run are as follows:

- Preparing fresh and clean Ubuntu 18.04.
- Installing required packages with `sudo apt-get install` command for PHP versions.
- Installing the latest stable PHPBrew version.
- Running the `phpbrew install 8.1 +default` command to install/building the latest `PHP 8.1` version.
- After compiling/building latest `PHP 8.1` version, running the `` command to switch current `PHP 8.1` version.
- It's worked successfully. Some command outputs are as follows:

```
......
Congratulations! Now you have PHP with 8.1.13 as php-8.1.13

* To configure your installed PHP further, you can edit the config file at
    /root/.phpbrew/php/php-8.1.13/etc/php.ini

To use the newly built PHP, try the line(s) below:

    $ phpbrew use php-8.1.13

Or you can use switch command to switch your default php to php-8.1.13:

    $ phpbrew switch php-8.1.13

Enjoy!
```

I think the issue only happens in the macOS and possible solution is available in the previous reply.

I think the issue can be closed now.

**Comment by MagicLegend** [comment]
Correct, this appears to be a MacOS only bug. However, as the current workaround disables JIT we're leaving performance on the table. Is there no permanent fix for this? I can do more testing if that helps.

**Comment by theofidry** [comment]
I can confirm I always had to disable JIT on OSX as well. I couldn't figure if it was a PHP issue or a PHPBrew one (it looks like it was PHP to me)

**Comment by peter279k** [comment]
I notice that `fatal error: 'capstone/capstone.h' file not found` message presented in many other C/C++ projects compiling.

Especially it happens on the `MacOS 12.6, M1`. Maybe we should check the `capstone.h` file path firstly?

And ensure the running the `$brew --prefix capstone` command can get the current `capstone.h` fie path.

**Comment by peter279k** [comment]
@MagicLegend, sorry. I don't have the MacBook M1 and please try to use the following steps at your available time and ensure that:

- Running the `PHPBrew` to build/install latest PHP 8.1 without adding any `+opcache` variant.
- After running above command is successful, running the `phpbrew switch ` to switch above PHP version.
- Running the `phpbrew ext install opcache` command to try whether the `opcache` extension with JIT can be compiled dynamically for the PHP.

**Comment by peter279k** [comment]
Finally, I've one `MACOS 11.6` and try to use the following steps to reproduce the issue:

```bash
cloudxmac@cloudxmacs-Mac ~ % sw_vers
ProductName:    macOS
ProductVersion: 11.6
BuildVersion:   20G165
cloudxmac@cloudxmacs-Mac ~ % brew install bzip2
cloudxmac@cloudxmacs-Mac ~ % ls /usr/local/opt/bzip2
CHANGES                 LICENSE                 bin                     lib
INSTALL_RECEIPT.json    README                  include                 share
cloudxmac@cloudxmacs-Mac ~ % brew install zlib
cloudxmac@cloudxmacs-Mac ~ % brew install openssl@1.1
cloudxmac@cloudxmacs-Mac ~ % brew install oniguruma
cloudxmac@cloudxmacs-Mac ~ % brew install readline
cloudxmac@cloudxmacs-Mac ~ % brew install libzip
cloudxmac@cloudxmacs-Mac ~ % phpbrew install -j 4 8.1.13 +default +bz2="$(brew --prefix bzip2)" +zlib="$(brew --prefix zlib)" +openssl="$(brew --prefix openssl@1.1)"
===> phpbrew will now build 8.1.13
===> Loading and resolving variants...
Homebrew prefix "/usr/local/opt/libxml2" does not exist.
Homebrew prefix "/usr/local/opt/mhash" does not exist.
Homebrew prefix "/usr/local/opt/curl" does not exist.
Checking distribution checksum...
Checksum matched: 93fcfdfaaa3d094a0fdb18ce08d20f20d526ee3f07a146a8a8ec82ce00b237ca
===> Distribution file was successfully extracted, skipping...
===> Checking patches...
Checking patch for replace apache php module name with custom version name
Checking patch for replace freetype-config with pkg-config on php older than 7.4
Found existing build.log, renaming it to /Users/cloudxmac/.phpbrew/build/php-8.1.13/build.log.1670211355
===> Configuring 8.1.13...
......
Congratulations! Now you have PHP with 8.1.13 as php-8.1.13

* To configure your installed PHP further, you can edit the config file at
    /Users/cloudxmac/.phpbrew/php/php-8.1.13/etc/php.ini

* WARNING:
  You haven't setup your .bashrc file to load phpbrew shell script yet!
  Please run 'phpbrew init' to see the steps!

To use the newly built PHP, try the line(s) below:

    $ phpbrew use php-8.1.13

Or you can use switch command to switch your default php to php-8.1.13:

    $ phpbrew switch php-8.1.13

Enjoy!
cloudxmac@cloudxmacs-Mac ~ % phpbrew use 8.1.13
cloudxmac@cloudxmacs-Mac ~ % phpbrew ext install opcache
......
===> Creating config file /Users/cloudxmac/.phpbrew/php/php-8.1.13/var/db/opcache.ini.disabled
===> Enabling extension opcache
[*] opcache extension is enabled.
Done.
cloudxmac@cloudxmacs-Mac ~ % php -v
PHP 8.1.13 (cli) (built: Dec  5 2022 11:41:36) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.13, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.13, Copyright (c), by Zend Technologies
```

**Comment by Baachi** [comment]
I just encountered this problem, too. The PHP compiler uses capstone, if this module is available. This is the [related commit](https://github.com/php/php-src/commit/617276d8074e849dcbf879231aef611ca1e52506) in the php-src repository.

So in my case, i just removed capstone since i doesn't need it anyways. In my case  it was a dependency for qemu.
So @peter279k you may check this, with capstone installed. 

```
$ brew install capstone
```

Hope this helps anybody.

**Comment by peter279k** [comment]
Just notice that the PHPBrew can be worked successfully after running the `brew install capstone` command in the `MACOS 12.6`.

**Comment by peter279k** [comment]
The issue is available in the [troubleshooting page](https://github.com/phpbrew/phpbrew/wiki/Troubleshooting#fatal-error-capstonecapstoneh-file-not-found-in-the-macos-11x).
