### ISSUE TITLE
PHP Installation fails on Ubuntu 22.04 WSL2

### ISSUE THREAD

**Issue by 7ahery** [phpbrew/phpbrew#1280]
### Error 🔴 
Running phpbrew on Ubuntu 22.04 WSL2, when I try to install any PHP version lower than `8.0` I get various errors related to OpenSSL. My take is that this is most likely related to OpenSSL 3 being the default in Ubuntu 22.04 but lower PHP versions need OpenSSL 1.1.1 to build.

Here are the errors:

```
Error: Configure failed:
The last 5 lines in the log file:
checking for Kerberos support... no

checking whether to use system default cipher list instead of hardcoded value... no

checking for RAND_egd... no

checking for pkg-config... /usr/bin/pkg-config

configure: error: Cannot find OpenSSL's libraries
```
```
Error: Make failed:
/usr/include/openssl/rsa.h:289:29: note: expected ‘RSA *’ {aka ‘struct rsa_st *’} but argument is of type ‘const struct rsa_st *’

  289 |                        RSA *rsa, int padding);

      |                        ~~~~~^~~

make: *** [Makefile:631: ext/openssl/openssl.lo] Error 1
```

### Solution (Partial - Please read [this comment](https://github.com/phpbrew/phpbrew/issues/1280#issuecomment-1345533391)) 
**Use At Your Own Risk**

This was the only way I was able to fix these errors.

1. Remove current (version 3) OpenSSL: `sudo apt remove openssl`
2. [Download OpenSSL 1.1.1 source](https://www.openssl.org/source/), extract the .tar.gz file and build/install OpenSSL:
    1. `cd` to OpenSSL source folder.
    2. make `config` file executable: `chmod +x config`
    3. run config: `./config`
    4. build the source: `make`
    5. run tests to make sure the built source is OK: `make test`
    6. install the built OpenSSL: `sudo make install`
8. Now install your PHP version with the following command: `phpbrew install 7.0 +default +openssl=shared -- --with-openssl-dir=/usr/include/openssl` which essentially tells the installed PHP version to use the OpenSSL path you provide.

**! Important Note !** You can not have two versions of OpenSSL activated simultaneously. With this approach you are eliminating OpenSSL 3 lib from Ubuntu 22.04 so please make sure you know what you are doing.

To uninstall OpenSSL 1.1.1, `cd` to OpenSSL source folder and run `sudo make uninstall`.
To install back OpenSSL 3, first remove OpenSSL 1.1.1 and then run: `sudo apt install openssl`.

Note: When installing PHP 5.6 you may face a curl error `easy.h should be in <curl-dir>/include/curl/`. In that case please check out [this answer](https://github.com/phpbrew/phpbrew/issues/861#issuecomment-310196141).

**Comment by theofidry** [comment]
@7ahery on OSX with homebrew (and I think you could have the same with Ubuntu), you can also build with `+openssl=<path-to-openssl1.1>`

**Comment by 7ahery** [comment]
@theofidry The issue is that when I build with `+openssl=/usr/include/openssl` I get:

```
configure: error: Cannot find OpenSSL's <evp.h>
```

But `evp.h` is available at `/usr/include/openssl`, don't know why this happens.

**Comment by 7ahery** [comment]
@theofidry I think the same can not be said for Ubuntu as OpenSSL `bin`, `include,` `lib` etc. are in different folders in `/usr/local`. I think this is a phpbrew incompatibility with Linux.

Even when I build and install OpenSSL 1.1.1 manually in a single folder, with  `bin`, `include,` `lib` etc. available in one folder, I get `configure: error: Cannot find OpenSSL's libraries` error and if I point it to `lib` folder it will throw error `configure: error: Cannot find OpenSSL's <evp.h>`

**Comment by 7ahery** [comment]
I just found out that although you are able to install PHP<8.0 with the solution I provided above, Only PHP 7.4 will correctly recognize OpenSSL and work, anything lower will throw an error indicating OpenSSL Extension is not installed. This error will be obvious when for example you run a `composer install` command.

So this is **not** completely and reliably solved on Ubuntu 22.04. We need a way to retain Ubuntu 22.04 default OpenSSL but be able to install PHP versions lower than 8.0.

**Comment by 7ahery** [comment]
I can confirm that phpbrew can install any PHP version>=5.6 without any issue on Ubuntu 20.04. So this is definitely an issue related to Ubuntu 22.04.

**Comment by peter279k** [comment]
The solutions are available for the following references:

- https://github.com/phpbrew/phpbrew/issues/1263#issuecomment-1140375871
- https://github.com/phpbrew/phpbrew/wiki/Troubleshooting/#compiling-php74-with-the-openssl-extension-error-in-ubuntu-2204
