### ISSUE TITLE
Artifact filename change in Release 1.28.0 doesn't match install documentation 

### ISSUE THREAD

**Issue by markbeazley** [phpbrew/phpbrew#1287]
Not sure if its intentional, but the generated php binary/package has changed to be just phpbrew dropping the .phar from the file name, the install instructions still use the [url ](https://github.com/phpbrew/phpbrew/releases/latest/download/phpbrew.phar) with the .phar included.

**Comment by peter279k** [comment]
The [new released version](https://github.com/phpbrew/phpbrew/releases) is going back to the `.phar` extension. Thanks for your reporting :).
