### ISSUE TITLE
Make GitHub Actions build required

### ISSUE THREAD

**Issue by theofidry** [phpbrew/phpbrew#1296]
Follow up of the discussion in https://github.com/phpbrew/phpbrew/pull/1293/files#r1049612212.

I highly recommend to enable a branch rule with the desired builds as required:

- Go to "Settings" -> Branches -> Add a rule or edit the rule for the master branch and:
- tick "Require status checks to pass before merging"
- look for status checks to check

This prevents to accidentally merge a pull request that did not pass the pipeline and as well allow to add more builds that are allowed to fail (e.g. non-supported yet future versions).

**Comment by c9s** [comment]
Agree

**Comment by peter279k** [comment]
I think the setting is done.
