### ISSUE TITLE
Binary file 'Not found'

### ISSUE THREAD

**Issue by pbrilius** [phpbrew/phpbrew#1302]
### Output

Not Found%    

### Expected Result
```shell
#!/usr/bin/env php
/../
```

### Command

Paste your phpbrew install command here (be sure to install with `--debug` flag, e.g. `phpbrew --debug install`)

```shell
    curl -L -O https://github.com/phpbrew/phpbrew/releases/latest/download/phpbrew.phar
```
### Build Log

    gist here

### Platform

OS:
```shell
   DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.1 LTS"
```

Running PHP: 

Installing PHP:

**Comment by peter279k** [comment]
Sorry. I release the wrong file name. Now it's fixed.
