### ISSUE TITLE
cannot install gd with php 8.1.12  on ubuntu 18.04

### ISSUE THREAD

**Issue by ioweb-gr** [phpbrew/phpbrew#1310]
### Output

```

root@d5server:~# # test gd / freetype
root@d5server:~# php -r 'var_dump( function_exists("imagettftext"));';
Command line code:1:
bool(false)
root@d5server:~# php -r 'var_dump( function_exists("imagettfbbox"));';
Command line code:1:
bool(false)
root@d5server:~# php -r 'var_dump( function_exists("imagecreatefromjpeg"));';
Command line code:1:
bool(false)
root@d5server:~# php -r 'var_dump( function_exists("imageftbbox"));';
Command line code:1:
bool(false)
root@d5server:~#
```

### Expected Result
GD is installed 

### Command

Paste your phpbrew install command here (be sure to install with `--debug` flag, e.g. `phpbrew --debug install`)

    phpbrew --debug ext install gd -- --with-freetype="/usr/lib" --with-jpeg=/usr; # or replace with the library path | works for 7.4 and up

### Build Log

https://gist.github.com/ioweb-gr/2a45613dac1bd18db243fba14c7d02ae

### Platform

OS:

root@d5server:~# cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.6 LTS"

Running PHP: 

PHP 7.2 to install php and then using PHP 8.1.12 to install the extension

Installing PHP:

PHP 8.1.12

**Comment by peter279k** [comment]
For PHP 8.x, here are my solutions about installing GD extension for the `PHP 8.1` version in the Ubuntu 18.04:

- Running the `apt-get install libjpeg-dev libpng-dev libfreetype6-dev` to install packages for GD JPEG and PNG libraries.
- Using the system-wide `PHP 7.2` to run the `phpbrew install 8.1 +default +gd` to install the PHP 8.1 version.
- Running the `phpbrew switch php-8.1.13` to switch the current PHP version.
- Running the `phpbrew ext install gd` to enable the GD extension.

After completing above steps, running the following commands to verify the freetype is supported inside the GD extension in PHP 8.1 version correctly:

```sh
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic

$ php -v
PHP 8.1.13 (cli) (built: Jan  3 2023 09:50:33) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.13, Copyright (c) Zend Technologies

$ php -i | grep freetype
Configure Command =>  './configure'  '--cache-file=/root/.phpbrew/cache/config.cache' '--prefix=/root/.phpbrew/php/php-8.1.13' '--disable-all' '--enable-phar' '--enable-session' '--enable-short-tags' '--enable-tokenizer' '--with-zlib=/usr' '--with-libdir=lib/x86_64-linux-gnu' '--enable-gd=shared' '--with-jpeg=/usr' '--with-freetype=/usr' '--enable-dom' '--with-libxml' '--enable-simplexml' '--enable-xml' '--enable-xmlreader' '--enable-xmlwriter' '--with-xsl' '--enable-opcache' '--enable-bcmath' '--with-bz2=/usr' '--enable-calendar' '--enable-cli' '--enable-ctype' '--enable-fileinfo' '--enable-filter' '--enable-shmop' '--enable-sysvsem' '--enable-sysvshm' '--enable-sysvmsg' '--enable-json' '--enable-mbregex' '--enable-mbstring' '--with-mhash' '--enable-pcntl' '--enable-pdo' '--with-pear=/root/.phpbrew/php/php-8.1.13/lib/php/pear' '--enable-posix' '--with-readline=/usr' '--enable-sockets' '--with-curl' '--with-openssl' '--with-zip' '--with-config-file-path=/root/.phpbrew/php/php-8.1.13/etc/cli' '--with-config-file-scan-dir=/root/.phpbrew/php/php-8.1.13/var/db/cli' 'PKG_CONFIG_PATH=/usr/lib/pkgconfig'
FreeType Linkage => with freetype

$ php -r 'var_dump( function_exists("imagettftext"));';
bool(true)

$ php -r 'var_dump( function_exists("imagettfbbox"));';
bool(true)

$  php -r 'var_dump( function_exists("imagecreatefromjpeg"));';
bool(true)

$  php -r 'var_dump( function_exists("imageftbbox"));';
bool(true)
```

**Comment by ioweb-gr** [comment]
Thank you I was missing the +gd parameter in the php compilation 

As soon as I added it, it worked great. 

```
phpbrew --debug install "$PHPBREW_VERSION" as "$PHPBREW_VERSION_ALIAS" +default +small +mb +dbs +fpm +gd -wddx +openssl=/usr -- --disable-shmop
```

Much appreciated
