### ISSUE TITLE
phpbrew install php 7.4.33 fail

### ISSUE THREAD

**Issue by Nicksxs** [phpbrew/phpbrew#1328]
### Output

```
tar: Error opening archive: Unrecognized archive format
Error: Extract failed:
```

### Expected Result

```
...
```

### Command

Paste your phpbrew install command here (be sure to install with `--debug` flag, e.g. `phpbrew --debug install`)

    phpbrew install 7.4.33

### Build Log

===> phpbrew will now build 7.4.33
You haven't enabled any variants. The default variant will be enabled:
[bcmath, bz2, calendar, cli, ctype, dom, fileinfo, filter, ipc, json, mbregex, mbstring, mhash, pcntl, pcre, pdo, pear, phar, posix, readline, sockets, tokenizer, xml, curl, openssl, zip]
Please run 'phpbrew variants' for more information.

===> Loading and resolving variants...
Homebrew prefix "/opt/homebrew/opt/libxml2" does not exist.
Homebrew prefix "/opt/homebrew/opt/bzip2" does not exist.
Homebrew prefix "/opt/homebrew/opt/mhash" does not exist.
Checking distribution checksum...
Checksum mismatch: ef71213d9b5753d77534059d77b7861281b89635554299802528183c4ffd010d != 4e8117458fe5a475bf203128726b71bcbba61c42ad463dffadee5667a198a98a
Re-Downloading...
Downloading https://www.php.net/distributions/php-7.4.33.tar.bz2 via curl extension
[==================================================================] 12.42/12.42MB 100%
https://www.php.net/distributions/php-7.4.33.tar.bz2 => /Users/shixuesen/.phpbrew/distfiles/php-7.4.33.tar.bz2
===> Extracting /Users/shixuesen/.phpbrew/distfiles/php-7.4.33.tar.bz2 to /Users/shixuesen/.phpbrew/build/tmp.1677812950/php-7.4.33
tar: Error opening archive: Unrecognized archive format
Error: Extract failed:

### Platform

OS:

    e.g. OS X 12.6

Running PHP: 
8.1.12
Installing PHP:
7.4.33

**Comment by peter279k** [comment]
The error message is as follows:
```
tar: Error opening archive: Unrecognized archive format
Error: Extract failed:
```

It seems that the archived file is not downloaded correctly. Do you try this again?
I think it's the temporary error.
