### ISSUE TITLE
Failing on every install

### ISSUE THREAD

**Issue by Sylk** [phpbrew/phpbrew#1330]
### Output

```
===> phpbrew will now build 7.2.34
---> Parsing variants from command arguments '+default'
===> Loading and resolving variants...
Checking distribution checksum...
Checksum matched: 0e5816d668a2bb14aca68cef8c430430bd86c3c5233f6c427d1a54aac127abcf
===> Distribution file was successfully extracted, skipping...
Source Directory: /home/starburst/.phpbrew/build/php-7.2.34
Found existing Makefile, running make clean to ensure everything will be rebuilt.
You can append --no-clean option after the install command if you don't want to rebuild.
===> Running make clean: /usr/bin/make -C '/home/starburst/.phpbrew/build/php-7.2.34' --quiet 'clean'
Running Command:/usr/bin/make -C '/home/starburst/.phpbrew/build/php-7.2.34' --quiet 'clean'
Writing variant info to /home/starburst/.phpbrew/php/php-7.2.34/phpbrew.variants
Running make clean to ensure everything will be rebuilt.
===> Running make clean: /usr/bin/make -C '/home/starburst/.phpbrew/build/php-7.2.34' --quiet 'clean'
Running Command:/usr/bin/make -C '/home/starburst/.phpbrew/build/php-7.2.34' --quiet 'clean'
===> Checking patches...
Checking patch for replace apache php module name with custom version name
Checking patch for replace freetype-config with pkg-config on php older than 7.4
Checking patch for fix readline detection on PHP 5.3 to PHP 7.1
---> Applying patch...
patching file ext/readline/config.m4
Reversed (or previously applied) patch detected!  Skipping patch.
2 out of 2 hunks ignored -- saving rejects to file ext/readline/config.m4.rej

Patch failed
0 changes patched.
Enabled variants: [xml, opcache, bcmath, bz2, calendar, cli, ctype, dom, fileinfo, filter, ipc, json, mbregex, mbstring, mhash, pcntl, pcre, pdo, pear, phar, posix, readline, sockets, tokenizer, curl, openssl, zip]
Disabled variants: []
Found existing build.log, renaming it to /home/starburst/.phpbrew/build/php-7.2.34/build.log.1678831813
===> Configuring 7.2.34...


Use tail command to see what's going on:
   $ tail -F '/home/starburst/.phpbrew/build/php-7.2.34/build.log'


./configure '--cache-file=/home/starburst/.phpbrew/cache/config.cache' '--prefix=/home/starburst/.phpbrew/php/php-7.2.34' '--disable-all' '--enable-phar' '--enable-session' '--enable-short-tags' '--enable-tokenizer' '--with-pcre-regex' '--with-zlib=/usr' '--with-libdir=lib/x86_64-linux-gnu' '--enable-dom' '--enable-libxml' '--with-libxml-dir=/usr' '--enable-simplexml' '--enable-xml' '--enable-xmlreader' '--enable-xmlwriter' '--with-xsl' '--enable-opcache' '--enable-bcmath' '--with-bz2=/usr' '--enable-calendar' '--enable-cli' '--enable-ctype' '--enable-fileinfo' '--enable-filter' '--enable-shmop' '--enable-sysvsem' '--enable-sysvshm' '--enable-sysvmsg' '--enable-json' '--enable-mbregex' '--enable-mbstring' '--with-mhash' '--enable-pcntl' '--with-pcre-dir=/usr' '--enable-pdo' '--with-pear=/home/starburst/.phpbrew/php/php-7.2.34/lib/php/pear' '--enable-posix' '--with-readline=/usr' '--enable-sockets' '--with-curl=/usr' '--with-openssl=/usr' '--enable-zip' '--with-config-file-path=/home/starburst/.phpbrew/php/php-7.2.34/etc/cli' '--with-config-file-scan-dir=/home/starburst/.phpbrew/php/php-7.2.34/var/db/cli' >> '/home/starburst/.phpbrew/build/php-7.2.34/build.log' 2>&1
===> Checking patches...
Checking patch for php5.3.x on 64bit machine when intl is enabled.
Checking patch for openssl dso linking patch
Checking patch for php5.6 with openssl 1.1.x patch.
===> Building...
make >> '/home/starburst/.phpbrew/build/php-7.2.34/build.log' 2>&1
Error: Make failed:
The last 5 lines in the log file:
In file included from /home/starburst/.phpbrew/build/php-7.2.34/ext/openssl/openssl.c:47:

/usr/include/openssl/rsa.h:289:29: note: expected ‘RSA *’ {aka ‘struct rsa_st *’} but argument is of type ‘const struct rsa_st *’

  289 |                        RSA *rsa, int padding);

      |                        ~~~~~^~~

make: *** [Makefile:629: ext/openssl/openssl.lo] Error 1

...
```

### Expected Result

Clean build. Nothing more.

### Command

    phpbrew --debug install 7.2 +default

### Build Log

https://gist.github.com/Sylk/79613a4a7035f41536225d115419fa08

### Platform

OS: Ubuntu 22.04.2: Kubuntu

Running PHP:  Default Install Script PHP 8.1

Installing PHP: 7.2

## Additional Info
I installed the required scripts as defined by the setup phase. However I still had errors where I needed to install autoconf, so I `sudo apt install autoconf` and that resolved that, now I've been sitting at this for over 2 hours. No matter which version I install PHP 7+ it throws this error. Other concerns, are the patches failing a negative thing as well? Some of the versions have had that attached inside of them.

**Comment by theofidry** [comment]
I am not certain but this is likely the OpenSSL version used. PHP 8+ uses OpenSSL@3 whereas 7.x uses 1.1.

For example the command I used to install my PHP 7.2 (on OSX) was:

```
phpbrew install 7.2 +small +openssl="$(brew --prefix openssl@1.1)" +hash -intl
```

The relevant bit for you I think is the `+openssl="$(brew --prefix openssl@1.1)"` where you need to have an OpenSSL@1.1 version installed somewhere and pass the right path to phpbrew.

**Comment by electrical** [comment]
I'm hitting the same error with installing php-8.0.28
php 8.1.x and 8.2.x are fine

**Comment by peter279k** [comment]
The solution is available [here](https://github.com/phpbrew/phpbrew/issues/1280#issuecomment-1345828965). Please look at that.

**Comment by peter279k** [comment]
As far as I know, the PHP 7.2 requires `OpenSSL 1.x`. But it's the `OpenSSL 3.x` version in the Ubuntu 22.04.

The `PHP-8.0` requires `OpenSSL 1.x` version, too.

To resolve the issue, it should compile `OpenSSL 1.x` version and cURL with linking `OpenSSL 1.x` manually.

And it's nice to use the latest PHPBrew `2.1.0` version to do above works.

Some useful solutions are as follows:

- https://github.com/phpbrew/phpbrew/issues/1267#issuecomment-1503251101

**Comment by Sylk** [comment]
> The solution is available [here](https://github.com/phpbrew/phpbrew/issues/1280#issuecomment-1345828965). Please look at that.

This didn't fix my issue, but alright.

**Comment by peter279k** [comment]
> > The solution is available [here](https://github.com/phpbrew/phpbrew/issues/1280#issuecomment-1345828965). Please look at that.
> 
> This didn't fix my issue, but alright.

If possible, you can provide the completed building log and. And I can see the OpenSSL configuring situation.

You don't fix the issue with above solutions I mention because it's very likely to have the incorrect OpenSSL library path setup.
