### ISSUE TITLE
php deprecated creation of dynamic property warning

### ISSUE THREAD

**Issue by KTruesdell** [phpbrew/phpbrew#1331]
### Output

```
─➤  phpbrew list
PHP Deprecated:  Creation of dynamic property PhpBrew\Console::$loader is deprecated in phar:///usr/local/Cellar/phpbrew/2.0.0/bin/phpbrew/vendor/corneltek/cliframework/src/Application.php on line 117

Deprecated: Creation of dynamic property PhpBrew\Console::$loader is deprecated in phar:///usr/local/Cellar/phpbrew/2.0.0/bin/phpbrew/vendor/corneltek/cliframework/src/Application.php on line 117
PHP Deprecated:  Creation of dynamic property CLIFramework\ArgInfo::$desc is deprecated in phar:///usr/local/Cellar/phpbrew/2.0.0/bin/phpbrew/vendor/corneltek/cliframework/src/ArgInfo.php on line 38

Deprecated: Creation of dynamic property CLIFramework\ArgInfo::$desc is deprecated in phar:///usr/local/Cellar/phpbrew/2.0.0/bin/phpbrew/vendor/corneltek/cliframework/src/ArgInfo.php on line 38
PHP Deprecated:  Creation of dynamic property CLIFramework\ArgInfo::$desc is deprecated in phar:///usr/local/Cellar/phpbrew/2.0.0/bin/phpbrew/vendor/corneltek/cliframework/src/ArgInfo.php on line 38

Deprecated: Creation of dynamic property CLIFramework\ArgInfo::$desc is deprecated in phar:///usr/local/Cellar/phpbrew/2.0.0/bin/phpbrew/vendor/corneltek/cliframework/src/ArgInfo.php on line 38
* php-8.1.17
```

### Expected Result

```
actual list
```

### Command

Paste your phpbrew install command here (be sure to install with `--debug` flag, e.g. `phpbrew --debug install`)

    phpbrew list

### Build Log

    trying to run any phpbrew command i get the above code.  When doing any install there is also the same php deprecated messages.  I can't do a `brew install phpbrew@1.28` or anything other than the latest.

### Platform

OS:

    ─➤  sw_vers
    ProductName:            macOS
    ProductVersion:         13.2.1
    BuildVersion:           22D68

Running PHP: 
    ─➤  php -v
    PHP 8.2.4 (cli) (built: Mar 16 2023 16:46:52) (NTS)
    Copyright (c) The PHP Group
    Zend Engine v4.2.4, Copyright (c) Zend Technologies
        with Zend OPcache v8.2.4, Copyright (c), by Zend Technologies

Installing PHP:
    installing any version

**Comment by Allen307** [comment]
How should this problem be solved？

**Comment by km1230** [comment]
try falling back to PHP8.0 instead of PHP8.2

**Comment by peter279k** [comment]
Which PHPBrew version do you use?

Could you help me to use the `2.1.0` version and run `phpbrew list` command again with `PHP-8.0` or `PHP-8.1` version?

**Comment by KTruesdell** [comment]
i just manually downloaded phpbrew 2.1.0 and I did the `phpbrew init` and I got the following message...

```
Box Requirements Checker
========================

> Using PHP 8.2.5
> PHP is using the following php.ini file:
  /usr/local/etc/php/8.2/php.ini

> Checking Box requirements:
  E.


 [ERROR] Your system is not ready to run the application.


Fix the following mandatory requirements:
=========================================

 * The application requires the version "^7.2.5 || <8.2.0" or greater.
```

Not sure what this really means, when its saying essentially "less than php version 8.2 or greater".  
I guess I might need to downgrade my version of PHP?  Or wait until phpbrew catches up with the version of PHP 8.2.5?

**Comment by peter279k** [comment]
At this moment, the PHPBrew is not supported for the `PHP-8.2` version.

You should use the `PHP-8.0` or `PHP-8.1` version now. And here are my commands about running `phpbrew list` command with `PHP-8.1` version in Ubuntu 18.04:

```Bash
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.6 LTS
Release:        18.04
Codename:       bionic
$ php -v
PHP 8.1.17 (cli) (built: Mar 16 2023 14:37:57) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.1.17, Copyright (c) Zend Technologies
    with Zend OPcache v8.1.17, Copyright (c), by Zend Technologies
$ phpbrew --version
phpbrew - 2.1.0
cliframework core: 2.5.4
$ phpbrew list
* (system)
  php-8.1.14
  php-8.1.13
  php-7.4.33
  phpbrew7_2_34_fdev
$ phpbrew use php-7.4.33
$ php -v
PHP 7.4.33 (cli) (built: Dec 15 2022 12:20:56) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies

```

**Comment by peter279k** [comment]
It's related to issue #1300.

**Comment by KTruesdell** [comment]
I manually downgraded the system PHP to 8.1, and then downloaded the most current version of phpbrew and all that seems to have done the trick for now.  Thank you.

**Comment by a4992214** [comment]
Why is this not fixed yet - php8.3 is out now

**Comment by theofidry** [comment]
@a4992214 did you do a PR to fix this? Maybe that's why...
