### ISSUE TITLE
Php 8.2 not supported?

### ISSUE THREAD

**Issue by cdbessig** [phpbrew/phpbrew#1345]
### Output

```
[root@dev ~]# phpbrew install php-8.2.6 +default +dbs +intl +gd +iconv +imap +openssl=/usr -- --with-libdir=lib64 --with-imap=/usr/lib64/ --with-kerberos
[root@dev ~]# phpbrew switch php-8.2.6

[root@dev ~]# phpbrew

Box Requirements Checker
========================

> Using PHP 8.2.6
> PHP is using the following php.ini file:
  /usr/local/src/php_versions/phpbrew/php/php-8.2.6/etc/cli/php.ini

> Checking Box requirements:
  E.


 [ERROR] Your system is not ready to run the application.


Fix the following mandatory requirements:
=========================================

 * The application requires the version "^7.2.5 || <8.2.0" or greater.

[root@dev ~]#
```

### Expected Result

```
The normal phpbrew help page would come up and the above error would not be present.
```

### Command

Paste your phpbrew install command here (be sure to install with `--debug` flag, e.g. `phpbrew --debug install`)

    phpbrew --debug install php-5.x.x +openssl -- --....

### Platform

OS: Rocky Linux release 8.7 (Green Obsidian)

Running PHP:  8.2.6

Installing PHP: 8.2.6

**Comment by bahag-schlachterk** [comment]
Is there a way to at least install extensions for 8.2.x after building it? I don't mind phpbrew currently not running with 8.2. Building a 8.2.x version works fine, but afterwards I would need to install some extensions like imagick or xdebug which fails as phpbrew then tells me about not being compatible with 8.2.x when trying:
`~$ phpbrew use php-8.2.8
~$ php -v
PHP 8.2.8 (cli) (built: Jul 19 2023 08:20:44) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.8, Copyright (c) Zend Technologies
:~$ php ext install xdebug
Could not open input file: ext
:~$ phpbrew ext install xdebug

Box Requirements Checker
========================

> Using PHP 8.2.8
> PHP is using the following php.ini file:
  /home/xxxx/.phpbrew/php/php-8.2.8/etc/cli/php.ini

> Checking Box requirements:
  E.
                                                                                                                                                                                                                                           
 [ERROR] Your system is not ready to run the application.                                                                                                                                                                                   

Fix the following mandatory requirements:
=========================================

 * The application requires the version "^7.2.5 || <8.2.0" or greater.
`

**Comment by ioweb-gr** [comment]
> To skip the Box Requirement checker, you can run the following command to do at your own risk:
> 
> ```shell
> BOX_REQUIREMENT_CHECKER=0 phpbrew use php8.2.8
> ```

This doesn't quite work for me 

```
~$ BOX_REQUIREMENT_CHECKER=0 phpbrew use "$PHPBREW_VERSION_ALIAS"
PHP Warning:  Module 'blackfire' already loaded in Unknown on line 0
Thu Oct 26 07:23:37[root@d1.iohosting.eu]
~$ phpbrew --debug ext install gd -- --with-freetype="/usr/lib" --with-jpeg=/usr; # or replace with the library path | works for 7.4 and up

Box Requirements Checker
========================

> Using PHP 8.2.11
> PHP is using the following php.ini file:
  /opt/phpbrew/php/phpbrew8_2_11_fdev/etc/cli/php.ini

> Checking Box requirements:
  E.


 [ERROR] Your system is not ready to run the application.


Fix the following mandatory requirements:
=========================================

 * The application requires the version "^7.2.5 || <8.2.0" or greater.
```

Any ideas why?

**Comment by peter279k** [comment]
Please run the `BOX_REQUIREMENT_CHECKER=0 phpbrew --debug ext install gd -- --with-freetype="/usr/lib" --with-jpeg=/usr;` in your second line.

If you want to use multiple commands with `PHP 8.2` version, it should run the following command before running these `phpbrew` commands:

```bash
export BOX_REQUIREMENT_CHECKER=0
```

**Comment by ioweb-gr** [comment]
ah ok thanks ;)

**Comment by theofidry** [comment]
@peter279k shouldn't a proper release that supports PHP 8.2 be done though? Or is there any blocker?

**Comment by AuroraYolo** [comment]
希望尽快支持8.2 8.3

**Comment by farhan4648gul** [comment]
> Please run the `BOX_REQUIREMENT_CHECKER=0 phpbrew --debug ext install gd -- --with-freetype="/usr/lib" --with-jpeg=/usr;` in your second line.
> 
> If you want to use multiple commands with `PHP 8.2` version, it should run the following command before running these `phpbrew` commands:
> 
> export BOX_REQUIREMENT_CHECKER=0

Just a quick note... need to add this _**export**_ on every cli start... 
[for those who are looking for a similar solution on PHP 8.4 and beyond...]

**Comment by theofidry** [comment]
export just persist the call indeed.

FYI you can also install a PHP 8.2 version and make phpbrew use that version:

```shell
phpbrew system 8.2.20 # for a PHPBrew installed php version
phpbrew system $(brew --prefix php@8.2)/bin/php # an example with a homebrew installed PHP version
```
