### ISSUE TITLE
Was 2.2.0 retagged?

### ISSUE THREAD

**Issue by SMillerDev** [phpbrew/phpbrew#1362]
Homebrew updated to phpbrew 2.2.0 on Tue Nov 28 10:10:41 2023 -0800, but the release on the repo says it's from the 12th of December. The [git manual](https://git-scm.com/docs/git-tag#_on_re_tagging) says re-tagging is "the insane thing" to do, so I just wanted to check if this was intentional or if something malicious happened to the repo.

**Comment by peter279k** [comment]
After checking the latest released log, it's not malicious and it's re-tagging because the old tag is incorrect.
