### ISSUE TITLE
Set correct exit code when "phpbrew install" fails

### ISSUE THREAD

**Issue by pkordylewski** [phpbrew/phpbrew#159]
Hi,

could you please set an exit code != 0 when "phpbrew install" fails? Currently the exit code is 0, which indicates there is no error.

Example output:

```
# phpbrew install php-5.3.28 +default
...
configure: error: Please reinstall readline - I cannot find readline.h
Error
# echo $?
0
```

That would really help to use phpbrew for example in puppet.

Cheers,
Patryk

**Comment by c9s** [comment]
@marcioAlmada I remember that this was already done in some commits, right?

**Comment by marcioAlmada** [comment]
Yes, and 99% of the times it works 100% of the times. Let's close it.
