### ISSUE TITLE
Provide HHVM installer

### ISSUE THREAD

**Issue by c9s** [phpbrew/phpbrew#192]
Reference: 
- https://github.com/facebook/hhvm/wiki/Building-and-installing-HHVM-on-OSX-10.8
- https://github.com/facebook/hhvm/wiki

**Comment by keradus** [comment]
:+1:
any news on that ?

**Comment by c9s** [comment]
I found that the HHVM build system currently is pretty unstable to build.

for now, to install on Mac OS X, you can check out:  http://github.com/c9s/hhvm-macports

**Comment by hashar** [comment]
HHVM provides a bunch of precompiled version for a wide range of Linux distributions:
https://github.com/facebook/hhvm/wiki/Prebuilt%20Packages%20for%20HHVM

The Debian project as an intent to package it https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=727085 and the packaging work is hosted on http://anonscm.debian.org/cgit/pkg-hhvm/hhvm.git/ . Look at files under /debian for some clues:

http://anonscm.debian.org/cgit/pkg-hhvm/hhvm.git/tree/debian/control (list dependencies)
http://anonscm.debian.org/cgit/pkg-hhvm/hhvm.git/tree/debian/rules (build commands)

**Comment by morozov** [comment]
Given that it's been more than 2 years since the last comment, and HHVM doesn't seem that demanded by the PHP community [1][2], closing this as unlikely to be ever implemented.

[1] https://symfony.com/blog/symfony-4-end-of-hhvm-support
[2] https://github.com/doctrine/annotations/pull/134

**Comment by hashar** [comment]
Since my March 2015 comment, HHVM entered Debian in July 2015 though it did not make it to the stable versions.  It is maintained by Debian Developers from the Wikimedia Foundation (Faidon Liambotis and Moritz Muehlenhoff).
