### ISSUE TITLE
Add plist file for fpm under OSX

### ISSUE THREAD

**Issue by chadrien** [phpbrew/phpbrew#201]
Do you think it may be useful to plist file(s) so OSX users can easilly start FPM at startup and such?

**Comment by johanderuijter** [comment]
If anyone is still looking for a working plist to load with `launchctl` i made one yesterday. I based it on the one that comes with https://github.com/Homebrew/homebrew-php. Not sure if everything is required, but it works:

replace {USERNAME} with your username and {PHPBREW DIST DIR} with the path to you phpbrew install. Use `$ phpbrew cd dist` if you're not sure where that is.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
  <dict>
    <key>KeepAlive</key>
    <true/>
    <key>Label</key>
    <string>phpbrew.fpm</string>
    <key>ProgramArguments</key>
    <array>
        <string>{PHPBREW DIST DIR}/sbin/php-fpm</string>
        <string>--php-ini</string>
        <string>{PHPBREW DIST DIR}/etc/php.ini</string>
        <string>--fpm-config</string>
        <string>{PHPBREW DIST DIR}/etc/php-fpm.conf</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>LaunchOnlyOnce</key>
    <true/>
    <key>UserName</key>
      <string>{USERNAME}</string>
    <key>WorkingDirectory</key>
    <string>/usr/local</string>
    <key>StandardErrorPath</key>
      <string>{PHPBREW DIST DIR}/var/log/php-fpm.log</string>
  </dict>
</plist>
```

**Comment by c9s** [comment]
Integrated in 1.22 release.

**Comment by allocenx** [comment]
The new setup command is not working properly at all! I am on a MAC, Catalina and i always this: **/Library/LaunchDaemons/org.phpbrew.fpm.plist is not writable.**
