### ISSUE TITLE
Installation failed with icu-config error on Mac OS X 10.8

### ISSUE THREAD

**Issue by jaceju** [phpbrew/phpbrew#21]
在 Mac OS X 10.8 執行以下指令時：

```
phpbrew install php-5.4.x +default
```

出現以下錯誤：

```
configure: error: Unable to detect ICU prefix or no failed. Please verify ICU install prefix and make sure icu-config works.
```

解決方法：

```
brew install icu4c
brew link icu4c
```

**Comment by zx1986** [comment]
Warning: icu4c is keg-only and must be linked with --force
Note that doing so can interfere with building software.

**Comment by lano-vargas** [comment]
That's awesome.
It's exactly what I was looking for It worked as a treat after battling a whole day thank dude.

**Comment by mtamzid270-wq** [comment]
https://github.com/phpbrew/phpbrew/issues/21#issue-5935309

**Comment by theofidry** [comment]
Maybe worth adding a doc entry for it?
