### ISSUE TITLE
php installation with apxs2

### ISSUE THREAD

**Issue by wyhmichael** [phpbrew/phpbrew#221]
Hey there,

I met the following problem when trying phpbrew - 1.13.1 cliframework core: 1.5.12 on Centos 6.4 with php5.3.3

- if I install php with apxs2, after installation ```phpbrew list``` won't show the newly installed php and ```phpbrew switch``` won't work on newly installed php

checking build-dir, there's no new php downloaded

- if I install php without apxs2, everything seems like working except the php used by apache is the system one instead of newly installed php after ```phpbrew switch``` 

and also, on CentOS, if system php is installed by system package manager(yum), then in conf.d folder of apache configuration directory, there's probably a separate file for php configuration where there already is a LoadModule php5_module  modules/libphp5.so line. 

so when installing php by phpbrew with apxs2, and restarting httpd, an error message says "you are trying to load an already loaded module" is going to be shown, and newly installed php won't be configured properly to be used by apache.

Please help, thx in advance~!

**Comment by c9s** [comment]
apache module switch is not supported.
