### ISSUE TITLE
Add support to .phpbrewrc

### ISSUE THREAD

**Issue by hlegius** [phpbrew/phpbrew#223]
Hi folks,

Would be nice if phpbrew has a `.phpbrewrc` (rvm `.rvmrc` clone) or something to allow us configure what PHP's version should be loaded when entering in some project directory.

**Comment by brunobatista** [comment]
:+1:

**Comment by marcioAlmada** [comment]
@brunobatista say thanks to @morozov https://github.com/phpbrew/phpbrew/pull/391;)
