### ISSUE TITLE
phpbrew switch doesn't change php on apache

### ISSUE THREAD

**Issue by gmbelart** [phpbrew/phpbrew#226]
hello

when I run this

phpbrew switch 5.4.27

then execute

php -v 

it give me php version 5.4.27,

but when I execute script <?php echo phpinfo(); ?> on browser, 
it give me php version 5.3.28

I try to reload apache with 

sudo service apache2 reload

nothing change,  
<?php echo phpinfo(); ?> still give me 5.3.28

but if I change file on /etc/apache2/mods-enabled/php5.load

from
LoadModule php5_module /usr/lib/apache2/modules/libphp5.3.28.so

to
LoadModule php5_module /usr/lib/apache2/modules/libphp5.4.27.so

then I reload apache,

finally
<?php echo phpinfo(); ?> give me 5.4.27

it's bug of phpbrew switch? or not?

my laptop 
OS: elementary os luna (based on ubuntu 12.04)
Apache: 2.2.22

sorry for my bad english .. :smiley: 

thanks.

**Comment by Anahkiasen** [comment]
Where do the `.so` files even go when installing with phpbrew, I can't find them anywhere on Mac?

**Comment by shinnya** [comment]
@Anahkiasen You can know where apache library directory is by `apxs -q LIBDIR` and find `.so` files under `modules/` subdirectory(for example, `/usr/lib/httpd/modules/libphp5.3.20.so` in my environment).

**Comment by Anahkiasen** [comment]
Yes no don't mind me, they weren't getting installed because I wasn't installing with `+apxs2`. Thought that was encompassed by `+default`

**Comment by alexserver** [comment]
shit, I'm having problems installing apsx2 in ubuntu. in ubuntu this is called apache2 and not apxs2.

**Comment by convenient** [comment]
I scripted this on my Ubuntu 15.10 instance. Created a little shell script `phpbrewswitch` which will only switch php version when the `.so` file is found.


### Usage

Attempting to switch to a php version that wasn't built for apache

    [21:02:55] luker [~]$ phpbrewswitch 5.4.45
    5.4.45 is not configured for apache
      php-5.6.16     
      php-5.6.10     
    * php-5.5.30     
      php-5.4.45     

Successfully changing to a php version that has an existing `.so` file.

    [21:03:55] luker [~]$ phpbrewswitch 5.6.16
    * php-5.6.16     
      php-5.6.10     
      php-5.5.30     
      php-5.4.45     
    Updated /etc/apache2/mods-available/php5.load

### /home/luker/bin/phpbrewswitch

    #!/usr/bin/env bash
    VERSION=$1
    
    SOFILE=/usr/lib/apache2/modules/libphp$VERSION.so
    CONFFILE=/etc/apache2/mods-available/php5.load
    
    source ~/.phpbrew/bashrc
    
    if [ -f $SOFILE ]; then
        phpbrew switch $VERSION
        phpbrew list
    
        FILECONTENTS="LoadModule php5_module $SOFILE"
        echo $FILECONTENTS > $CONFFILE
    
        echo "Updated $CONFFILE"
        sudo service apache2 restart
    
    else
        echo $VERSION "is not configured for apache"
        phpbrew list
    fi

**Comment by hell-n** [comment]
Hello!

I ran into the same problem, but can't get it to work, like gmbelart.
`php -v` returns my desired version, after using `phpbrew switch php-5.4.45`, but i'm too incompetent to get the right .so-file loaded by Apache. :D

Since I'm currently using Apache/2.4.18 (Ubuntu), which runs PHP 7.0 out of box, there isn't even a php5.load file in /etc/apache2/mods-enabled. And if i add the line to the php7.0.load apache won't reload. Error: apache2: Syntax error on line 140 of /etc/apache2/apache2.conf: Syntax error on line

I even tried to create the php5.load file, but this failed as well.

Please, help me guys!
Nik

**Comment by Pupp3tm4st3r** [comment]
@hell-n 
Me helped this one:
https://github.com/phpbrew/phpbrew/issues/738

**Comment by ve3** [comment]
Hello 

Does anyone know how to switch version on  Apache using PHP fast cgi?

**Comment by Pupp3tm4st3r** [comment]
Die you build php with +apxs2?

**Comment by ve3** [comment]
@Pupp3tm4st3r  Yes, I did. @schneidermayer  comment works fine for me as Apache module.

**Comment by drupalranger** [comment]
On Ubuntu 17.04 I'm using following bash script 

```
#!/bin/bash
phpswitch() {
 echo "Starging phpbrew switch to $1"; 
 eval string="$1";
 eval version=${string:0:3};
 phpbrew switch php-"$1"; 

 echo "Disabling all versions apache php module";
 sudo a2dismod php*;

 sudo a2enmod php"$version";
 sudo service apache2 restart; 
 echo "apache2 has been restarted" 
}
```
it needs version number as an argument, so while I have following version installed: 
```
$ phpbrew list
  php-7.1.4      
* php-7.0.18     
  php-7.0.13     
  php-5.6.30    
``` 
All I need to do is to type one command with version number, e.g.: 
`phpswitch 5.6.30`

**Comment by site-me** [comment]
great article, helped a lot

http://www.sivaschenko.com/multiple-php-versions-simultaneously-apache/

**Comment by oscarromero** [comment]
Maybe too late, but for colleagues with apache2 + debian need to install the libapache2-mod-php7.3 and disable the default/system php that you have. after that, restart the apache2 service.

**Comment by ttodua** [comment]
This is also helpful to tell apache2 to use phpbrew's `.so` files: https://stackoverflow.com/a/41904646/2377343
