### ISSUE TITLE
Can't execute phpbrew ubuntu server 13.04 x64

### ISSUE THREAD

**Issue by kkoci** [phpbrew/phpbrew#228]
Hi, i did

curl -O https://raw.github.com/c9s/phpbrew/master/phpbrew
chmod +x phpbrew
sudo cp phpbrew /usr/bin/phpbrew

Everything seemed fine, but when i execute

phpbrew init, comes this exception:

"Fatal error: Uncaught exception 'PharException' with message 'zlib extension is required for gz compressed .phar file "/usr/bin/phpbrew"' in /usr/bin/phpbrew:3
Stack trace:
#0 /usr/bin/phpbrew(3): Phar::mapPhar('phpbrew.phar')
#1 {main}

  thrown in /usr/bin/phpbrew on line 3
"

Anybody knows something about it?

Thanks in advance!

**Comment by barttom** [comment]
Hi!
I have same problem.
In phpinfo() i Have this:

ZLib Support	enabled
Stream Wrapper	compress.zlib://
Stream Filter	zlib.inflate, zlib.deflate
Compiled Version	1.2.3.4
Linked Version	1.2.3.4

Directive	Local Value	Master Value
zlib.output_compression	On	On
zlib.output_compression_level	1	1
zlib.output_handler	no value	no value

And the resoult of ?php var_dump(function_exists('gzopen')); 
bool(true)

Thanks for advance!
