### ISSUE TITLE
Invalid library 'curl.so'

### ISSUE THREAD

**Issue by mbayou** [phpbrew/phpbrew#256]
Hi,

I try to run my project with my new php installation from phpbrew, but I have a curious message 

```
Notice: Use of undefined constant CURLOPT_HEADER
```

Yet I installed curl extension with this command : 

```
phpbrew ext install curl
```

And it finished with success, then I retry to switch the version of php and I saw this : 

```
PHP Warning:  PHP Startup: Invalid library (maybe not a PHP library) 'curl.so' in Unknown on line 0
bash: /home/mbayou/.phpbrew/init: ligne 3: Erreur de syntaxe près du symbole inattendu « ( »
bash: /home/mbayou/.phpbrew/init: ligne 3: `Warning: PHP Startup: Invalid library (maybe not a PHP library) 'curl.so' in Unknown on line 0'
```

I don't understand why ... Do you have an idea ?

I am on Ubuntu 14.04 x64 with all requirements for phpbrew

**Comment by embluk** [comment]
I'm still getting the same issue but with mbstring and zip. Is there a solution?

**Comment by c9s** [comment]
@embluk please provide your platform, the php version and the build variants. would be great to have the build log as well.
