### ISSUE TITLE
Setup arginfo for completion

### ISSUE THREAD

**Issue by c9s** [phpbrew/phpbrew#266]
- Version list => suggestions
- Variants => valid values
- Extension list => suggestions

Example from CLIFramework: https://github.com/c9s/php-CLIFramework/blob/master/example/demo

**Comment by c9s** [comment]
is this already implemented?

**Comment by marcioAlmada** [comment]
Yes. Did you spot something missing?

**Comment by c9s** [comment]
Yes, for example the DownloadCommand.

**Comment by c9s** [comment]
That one was supplemented in 56ad0d6.
