### ISSUE TITLE
Support Variant Attributes

### ISSUE THREAD

**Issue by c9s** [phpbrew/phpbrew#270]
Some attributes:

- available after version
- supported platform
- libraries (may check by pkg-config)
- description

These attributes can also be converted into completion descriptions.

**Comment by c9s** [comment]
Why do we close this?

**Comment by marcioAlmada** [comment]
Bad heuristics.

**Comment by c9s** [comment]
maybe we delayed this item for too long XD

**Comment by c9s** [comment]
I will open a new issue to track the variant DSL, it's implemented in 2.0 branch but it's not done yet.
