### ISSUE TITLE
GD w. PHP 5.3.28 on Ubuntu 14.04 won't install

### ISSUE THREAD

**Issue by pbowyer** [phpbrew/phpbrew#279]
I have an... interesting issue. I am on Ubuntu 14.04, trying to compile PHP 5.3.28. I used the requirement steps at https://github.com/phpbrew/phpbrew/wiki/Requirement#install-medium-requirement-gd-openssl-gettext-mhash-mcrypt-icu to set up my environment and it completes without any serious errors.

I look at the list of included modules using `php -m`. gd.so isn't there so I locate it and add a line to my php.ini file.

Now, every time I execute php I get the following errors:

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/local/phpbrew/php/php-5.3.28/lib/php/extensions/no-debug-non-zts-20090626/gd.so' - /usr/local/phpbrew/php/php-5.3.28/lib/php/extensions/no-debug-non-zts-20090626/gd.so: undefined symbol: gdGetC in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/usr/local/phpbrew/php/php-5.3.28/lib/php/extensions/no-debug-non-zts-20090626/gd.so' - /usr/local/phpbrew/php/php-5.3.28/lib/php/extensions/no-debug-non-zts-20090626/gd.so: undefined symbol: gdGetC in Unknown on line 0
```

GD built seemingly without error, libgd3 is installed.

I have tried both `+gd` and `+gd=shared,/usr` -- neither of which give different results (`shared,/usr` seems to be the default).

My build command is:

```
phpbrew --debug install --patch fpm.patch 5.3 +default +sqlite +mysql +pdo +gd=shared,/usr +intl +fpm +openssl +soap +pcre
```

This generates:

```
./configure '--prefix=/usr/local/phpbrew/php/php-5.3.28' '--with-config-file-path=/usr/local/phpbrew/php/php-5.3.28/etc' '--with-config-file-scan-dir=/usr/local/phpbrew/php/php-5.3.28/var/db' '--with-pear=/usr/local/phpbrew/php/php-5.3.28/lib/php' '--disable-all' '--enable-phar' '--enable-session' '--enable-short-tags' '--enable-tokenizer' '--with-pcre-regex' '--with-zlib=/usr' '--with-libdir=lib/x86_64-linux-gnu' '--with-sqlite3' '--with-pdo-sqlite' '--with-mysql=mysqlnd' '--with-mysqli=mysqlnd' '--with-pdo-mysql=mysqlnd' '--enable-pdo' '--with-gd=shared,/usr' '--enable-gd-native-ttf' '--with-jpeg-dir=/usr' '--with-png-dir=/usr' '--with-freetype-dir=/usr' '--enable-intl' '--enable-fpm' '--with-openssl=/usr' '--enable-soap' '--with-pcre-regex=/usr' '--with-pcre-dir=/usr' '--enable-dom' '--enable-libxml' '--enable-simplexml' '--enable-xml' '--enable-xmlreader' '--enable-xmlwriter' '--with-xsl' '--with-libxml-dir=/usr' '--enable-bcmath' '--with-bz2=/usr' '--enable-calendar' '--enable-cli' '--enable-ctype' '--enable-dom' '--enable-fileinfo' '--enable-filter' '--enable-shmop' '--enable-sysvsem' '--enable-sysvshm' '--enable-sysvmsg' '--enable-json' '--enable-mbregex' '--enable-mbstring' '--with-mhash=/usr' '--with-mcrypt=/usr' '--enable-pcntl' '--enable-phar' '--enable-posix' '--with-readline=/usr' '--with-libedit=/usr' '--enable-sockets' '--enable-tokenizer' '--with-curl=/usr' '--enable-zip' 2>&1 > /usr/local/phpbrew/build/php-5.3.28/build.log
```

And here is the contents of my build.log: https://gist.github.com/pbowyer/abc0a60e4aa8cd793746

Does this make any sense to you? I have searched here and Google and not found similar issues. Thanks.

**Comment by wellingtonlorindo** [comment]
I had the same error, but with php-5.4.38 :
~/.phpbrew/build/php-5.4.38/ext/gd/libgd/gdft.c:64:22: fatal error: ft2build.h: No such file or directory
 #include <ft2build.h>

And after a lot of trouble I used this:
phpbrew -d ext install gd -- --with-libdir=lib/x86_64-linux-gnu --with-gd=shared --enable-gd-native-ttf --with-jpeg-dir=/usr --with-png-dir=/usr --with-freetype-dir=/usr/include/freetype2/ft2build.h --with-xpm-dir=/usr

Hope it helps

**Comment by renatomoya** [comment]
Thanks @wellingtonlorindo, that worked for me.

```bash
phpbrew -d ext install gd -- --with-libdir=lib/x86_64-linux-gnu --with-gd=shared --enable-gd-native-ttf --with-jpeg-dir=/usr --with-png-dir=/usr --with-freetype-dir=/usr/include/freetype2/ft2build.h --with-xpm-dir=/usr
```

**Comment by StagnantIce** [comment]
Thanks @wellingtonlorindo, work for me too!

**Comment by kifion** [comment]
Work for me too!

**Comment by emfluenceindia** [comment]
@c9s : `phpbrew -d ext install gd` is the lifesaver! Thanks a lot :)
