### ISSUE TITLE
/usr/lib/i386-linux-gnu/libstdc++.so.6: error adding symbols: DSO missing from command line

### ISSUE THREAD

**Issue by bupy7** [phpbrew/phpbrew#292]
Hi! I can't compile php-5.3.28. I have Ubuntu 14.04 LTS x86. Before this I successfully compiled php-5.4.31. 

What's the problem?

Log of error:

```
/usr/bin/ld: ext/intl/msgformat/.libs/msgformat_helpers.o: undefined reference to symbol '__gxx_personality_v0@@CXXABI_1.3'
/usr/lib/i386-linux-gnu/libstdc++.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [sapi/cli/php] Error 1
Error
```

Command:

```
phpbrew install 5.3.28 +default +dbs +apxs2 +icu +intl
```

**Comment by GerardBrouwer** [comment]
Same problem here... installing without +intl parameter didn't work for me..

**Comment by GerardBrouwer** [comment]
Specifically setting -intl parameter fixed it for me:
sudo phpbrew install 5.3.29 +aspxs2 -intl

**Comment by sofuckingnice** [comment]
-intl works for me too, thx

**Comment by Bogdaan** [comment]
Same problem, 
-intl works

**Comment by sgpandey05** [comment]
Your linker need X11 library,You need to specify -lX11 to linker

Try 
/usr/local/cuda/bin/nvcc -arch=compute_30 -code=sm_30,compute_30 -o Main.o Display.o FileUtil.o Timer.o NeuralNetwork.o -L/usr/lib -L/usr/local/lib -L/usr/lib/x86_64-linux-gnu -L/usr/local/cuda/lib64 -lGLEW -lglfw3 -lGL -lGLU -lcuda -lcudart -lX11
