### ISSUE TITLE
Getting 'Multiple SAPI' error

### ISSUE THREAD

**Issue by sikhlana** [phpbrew/phpbrew#309]
Hello,
I am trying to compile 5.3.29 with the following command:

```
$ phpbrew -d install 5.3.29 +default +mysql +pdo +mbstring +bcmath +fpm +bz2 +ctype +dba +dom +embed +exif +fileinfo +filter +ftp +gcov +gd +gettext +hash +iconv +imap +intl +json +kerberos +mhash +openssl +pcntl +pcre +phar +posix +readline +session +sockets +tidy +xml_all +xmlrpc +zip +zlib -apxs2
```

And the error I am getting is:

```
+--------------------------------------------------------------------+
|                        *** ATTENTION ***                           |
|                                                                    |
| You've configured multiple SAPIs to be build. You can build only   |
| one SAPI module and CLI binary at the same time.                   |
+--------------------------------------------------------------------+
```

I have no idea what I am doing to be frank.

P.S. I am building it on Ubuntu 14.04

**Comment by cabp-ec** [comment]
I'm getting the same issue when installing 8.2.0 (no cgi, no fpm), everything is installed OK but get that error when using `+apxs2`.
`phpbrew install 8.2.0 +dba +ipv6 +dom +calendar +inifile +inline +cli +filter +json +hash +exif +mbstring +mbregex +pdo +embed +sockets +phpdbg +zip +bcmath +fileinfo +ctype +soap +pcntl +phar +session +tokenizer +opcache +imap +dtrace +pcre +mhash +mcrypt +zlib +curl +readline +editline +gd +intl +sodium +openssl +mysql +sqlite +pgsql +xml +gettext +iconv +bz2 +ipc +gmp +pear +apxs2`
