### ISSUE TITLE
Mysql Extension Won't Install

### ISSUE THREAD

**Issue by mattcdavis1** [phpbrew/phpbrew#322]
On Mac OS X 10.9.5 when trying to install the mysql extension i get the error below.  I'm using homebrew for mysql.  On the PHPBrew troubleshooting page it says to "adjust your variant to match the options." when there are missing header files but I'm not sure what that means in this context.  The results of "locate mysqlnd.h" are below also.  Any ideas on how to resolve this?

-------- Install Output-------

===> Using xml extension meta
===> Installing mysql extension...
===> Phpizing...
===> Configuring...
===> Building...
In file included from /Users/matthewdavis/.phpbrew/build/php-5.6.1/ext/mysql/php_mysql.c:69:
./php_mysql_structs.h:39:10: fatal error: 'ext/mysqlnd/mysqlnd.h' file not found
# include "ext/mysqlnd/mysqlnd.h"

```
     ^
```

1 error generated.
make: **\* [php_mysql.lo] Error 1

--------Locate mysqlnd.h output--------
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/php/ext/mysqli/mysqli_mysqlnd.h
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/php/ext/mysqlnd/mysqlnd.h
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk/usr/include/php/ext/mysqlnd/php_mysqlnd.h
/usr/include/php/ext/mysqli/mysqli_mysqlnd.h
/usr/include/php/ext/mysqlnd/mysqlnd.h
/usr/include/php/ext/mysqlnd/php_mysqlnd.h
/usr/local/Cellar/php53/5.3.28/include/php/ext/mysqlnd/mysqlnd.h
/usr/local/Cellar/php53/5.3.28/include/php/ext/mysqlnd/php_mysqlnd.h
/usr/local/Cellar/php54/5.4.31/include/php/ext/mysqli/mysqli_mysqlnd.h
/usr/local/Cellar/php54/5.4.31/include/php/ext/mysqlnd/mysqlnd.h
/usr/local/Cellar/php54/5.4.31/include/php/ext/mysqlnd/php_mysqlnd.h
/usr/local/Cellar/php55/5.5.15/include/php/ext/mysqli/mysqli_mysqlnd.h
/usr/local/Cellar/php55/5.5.15/include/php/ext/mysqlnd/mysqlnd.h
/usr/local/Cellar/php55/5.5.15/include/php/ext/mysqlnd/php_mysqlnd.h

**Comment by egorsmkv** [comment]
This helped me:

```
export PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig

phpbrew ext install mysqlnd
```
