### ISSUE TITLE
cant access phpmyadmin

### ISSUE THREAD

**Issue by xfoxawy** [phpbrew/phpbrew#344]
after install php-5.4.31 i cant access phpmyadmin with the same username and password
tried sudo dpkg-reconfigure phpmyadmin
even tried to change it using skip-grant 
where is the right directory i can access my phpmyadmin or change user and pass?

**Comment by ahmedofali** [comment]
I have the same problem @xfoxawy  I see you closed the Issue did you found a solution?

**Comment by ahmedofali** [comment]
More Info: Installed phpbrew only the cli got updated Apache did not changed and phpmyadmin can not connect to the socket for php.

**Comment by jhdxr** [comment]
@ahmedofali  you may need `+apxs2` to integrate with Apache.
