### ISSUE TITLE
1.15.3 Invalid version (Yosemite on homebrew)

### ISSUE THREAD

**Issue by jlem** [phpbrew/phpbrew#364]
I've installed php5.6 and most of the extensions I try to install all come back with "Invalid version:"

I can't install apxs2, fpm, and many others. 

What's the invalid version? My OS? The version of PHP? The version of phpbrew? The version of the extension?

**Comment by marcioAlmada** [comment]
It's impossible to satisfy this through the ext installer, so... closing.
