### ISSUE TITLE
Using Ubuntu 14.04 x86 keeps showing system php after switching a phpbrew php installation

### ISSUE THREAD

**Issue by czmole** [phpbrew/phpbrew#366]
Hi,

I am using Ubuntu 14.04. I have lamp installed with php 5.5.9. I installed phpbrew an for starting php 5.3.29. After I use phpbrew switch php-5.3.29 (and even "use") the system is still showing me that it uses 5.5.9  as user but 5.3.29 as root.

What should I do? I am using the normal user...

If I use phpbrew switch php-5.3.29 from normal user, I get: You should not see this, please check if bashrc is sourced in your shell.

Thank you.

**Comment by jeremywight** [comment]
I am getting something odd as well.

If I check php -v as the root user, I get my phpbrew version that I have switched to of PHP 5.4.34, but if I check in my user account I get the default PHP 5.5.9.

Any ideas?

**Comment by akomm** [comment]
I'v noticed you can install a php version not providing the minor version part. It seem to install the newest version. Example: phpbrew install 5.3 would install 5.3.29.

But you can not switch to 5.3. You must switch explicitly to 5.3.29 (asume you'v set no alias). You don't get any error/feedback, if you'v tried to switch to a non existing version.

This would explain the first problem.

Now the "weirdness" getting another version as root user, using php -v:

Check if you have a .phpbrew directory in /root. It might be you have a separate phpbrew initialized for the root user.

**Comment by jeremywight** [comment]
Thanks Andriy. I will check into those. - Jeremy

**Comment by akomm** [comment]
On ubuntu 14.04 I use the following script to switch the used php5_module on apache:

```
#!/usr/bin/env bash

VERSION=`php -r "echo phpversion();"`
SO_PATH=/usr/lib/apache2/modules/libphp${VERSION}.so

echo "LoadModule php5_module ${SO_PATH}" | sudo tee /etc/apache2/mods-available/php5.load
sudo service apache2 restart

exit 0
```

### Constraints:  
- you must have installed your php using +apxs2 option
- switch to the php version with before invoking it
- naming convention for location and *.so file naming (works on the fly with phpbrew)

```
phpbrew switch 5.3.29 && [script-file-above]
```
