### ISSUE TITLE
Can't install Imagick extension

### ISSUE THREAD

**Issue by makbeth** [phpbrew/phpbrew#372]
on php-5.3.28
phpbrew ext install imagick
===> Installing imagick extension...
Log stored at: /home/vagrant/.phpbrew/build//ext/imagick/build.log
Changing directory to /home/vagrant/.phpbrew/build//ext/imagick
===> Phpize...
===> Configuring...
Command failed: ./configure  >> /home/vagrant/.phpbrew/build//ext/imagick/build.log 2>&1 returns 
in log file (4 last lines):
checking for gawk... gawk
checking whether to enable the imagick extension... yes, shared
checking whether to enable the imagick GraphicsMagick backend... no
checking ImageMagick MagickWand API configuration program... configure: error: not found. Please provide a path to MagickWand-config or Wand-config program.

If i try to install MagickWand or ImageMagick using phpbrew ext install I get this error:
phpbrew ext install imagemagick
Invalid package version: imagemagick @ 

Maybe I'm doing something wrong? Need help, guys.

**Comment by EliasZ** [comment]
I am still having this exact issue:

    checking ImageMagick MagickWand API configuration program... configure: error: not found. Please provide a path to MagickWand-config or Wand-config program.

`PHP 5.5.26`
`Debian 8.1`
`ImageMagick 6.8.9-9`

Have installed `libmagickwand-dev` and `libmagickcore-dev`

Any pointers?

**Comment by marcioAlmada** [comment]
Can you post use your debug output on a gist? `phpbrew --debug ext install <extension-name>`

**Comment by EliasZ** [comment]
Yes, I have read the cookbook. Managed to install multiple extensions and the installation has been running without any problems. The only recurring issue is the warning in the CLI regarding `PHP Startup: Invalid library (maybe not a PHP library) 'hash.so'` but I don't think that has anything to do with this issue. 

https://gist.github.com/EliasZ/8c005eb6530f90d951ba

**Comment by davidfuhr** [comment]
On Debian Jessie it might be necessary to create two symlinks. I've updated the cookbook accordingly.

**Comment by EliasZ** [comment]
@davidfuhr Thank you for your effort, latest instructions work for me on Jessie.

**Comment by ezekg** [comment]
Thanks, @marcioAlmada. Installing `libmagickwand-dev` and `libmagickcore-dev` worked for me.
