### ISSUE TITLE
Safe unserialize for PHP releases

### ISSUE THREAD

**Issue by marcioAlmada** [phpbrew/phpbrew#376]
Just found this userland safe unserialize implementation that we can use to retrieve PHP releases and stop maintaining the `releases.json` file:

https://github.com/piwik/piwik/blob/master/libs/upgradephp/upgrade.php#L373-L602

I would never bother to implement unserialization on userland, but since people from **piwiki** project already made the effort, why not use it? :)

PS: It seems we won't need it on PHP7 https://wiki.php.net/rfc/secure_unserialize

**Comment by ramsey** [comment]
This is now available on php.net: http://php.net/releases/index.php?json

**Comment by marcioAlmada** [comment]
Fixed 442e7021450a69cc912a6f95119dc2320ab79cc4

We cant drop the releases json file for now because some people haven't updated phpbrew yet, but from next minor minor version and ahead it will be useless.
