### ISSUE TITLE
Something strange with bashrc

### ISSUE THREAD

**Issue by adisos** [phpbrew/phpbrew#383]
Now it's my console:
`\w > \u@\h [php:5.5.10-phpbrew]\n$ vi ~/.zshrc`

When I uncomment this:
```
if [[ -n "$PHPBREW_SET_PROMPT" && "$PHPBREW_SET_PROMPT" == "1" ]]; then
    #export PS1="\w > \u@\h [$(phpbrew_current_php_version)]\n\\$ "
fi
```
It's working fine, what's the problem?

P.S. I'm using zsh

**Comment by marcioAlmada** [comment]
closing because too localized
