### ISSUE TITLE
Phar App Installer

### ISSUE THREAD

**Issue by c9s** [phpbrew/phpbrew#385]
For now I could only think about:

- composer
- pyrus
- phpunit

@marcioAlmada I guess you might want to come up with some awesome apps?

**Comment by marcioAlmada** [comment]
I'd prefer to let this be handled with composer. Please, reopen if necessary.

**Comment by c9s** [comment]
Done in b5223eb074f24b130e9e19b43cd5cbe0c214ec7a, users can get them without opening a browser to search or modifying a config file.
