### ISSUE TITLE
Problem loading Xdebug

### ISSUE THREAD

**Issue by jcyamo** [phpbrew/phpbrew#39]
Not sure if this is an issue with phpbrew or not. If not, here is at least some info for someone who might run into the same problem I did.

**Problem:**
Xdebug not properly loading after install.

**Versions:**

``` shell
$ phpbrew --version
phpbrew - 1.6.3
cliframework core: 1.5.1

$ php -v
PHP 5.3.20 (cli) (built: Jan 15 2013 15:11:49) 
Copyright (c) 1997-2012 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2012 Zend Technologies
```

**Install procedure:**

``` shell
$ phpbrew install php-5.3.20 +default +dbs
$ pecl install xdebug
$ phpbrew enable xdebug
```

This created the following file:

``` shell
# ~/.phpbrew/php/php-5.3.20/var/db/xdebug.ini
extension=xdebug.so
```

Which resulted in the following warning:
`PHP Warning:  Xdebug MUST be loaded as a Zend extension in Unknown on line 0`

**First fix attempt:**

``` shell
# ~/.phpbrew/php/php-5.3.20/var/db/xdebug.ini
zend_extension=xdebug.so
```

Which resulted in the following error:
`Failed loading xdebug.so:  xdebug.so: cannot open shared object file: No such file or directory`

**Issue resolved:**

``` shell
# ~/.phpbrew/php/php-5.3.20/var/db/xdebug.ini
zend_extension="/home/jonyamo/.phpbrew/php/php-5.3.20/lib/php/extensions/no-debug-non-zts-20090626/xdebug.so"
```

``` shell
$ php -v
PHP 5.3.20 (cli) (built: Jan 15 2013 15:11:49) 
Copyright (c) 1997-2012 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2012 Zend Technologies
    with Xdebug v2.2.1, Copyright (c) 2002-2012, by Derick Rethans
```

**Comment by podarok** [comment]
```phpbrew ext install xdebug```
doesn/t work for php-5.3 and ubuntu 14.04

**Comment by marcioAlmada** [comment]
@podarok please refer to https://github.com/phpbrew/phpbrew/issues/538#issuecomment-123786963
