### ISSUE TITLE
When only +cgi is built (on web server), phpbrew ext install fails.

### ISSUE THREAD

**Issue by chris001** [phpbrew/phpbrew#394]
"please install at least one php with your preferred version"

Config.php  method getInstalledPhpVersions() fails because it's looking for the directory "php" , but it should match the directory "php-cgi"

**Comment by marcioAlmada** [comment]
ping

**Comment by c9s** [comment]
@marcioAlmada  I think we just add +cli as the default, this could prevent most of confusion.

**Comment by peter279k** [comment]
When using the `phpbrew install 7.0 +cgi` command to install and build the `PHP 7.0` version, running the `phpbrew ext install uuid` command then related outputs are as follows:

```sh
$ phpbrew install 7.0 +cgi
$ phpbrew switch php-7.0.33
$ sudo apt-get install uuid-dev # For installing uuid extension via following command
$ phpbrew ext install uuid
......
===> Running make install: /usr/bin/make -C '/root/.phpbrew/build/php-7.0.33/ext/uuid' 'install'  >> '/root/.phpbrew/build/php-7.0.33/ext/uuid/build.log' 2>&1
===> Extension is installed.
===> Creating config file /root/.phpbrew/php/php-7.0.33/var/db/uuid.ini.disabled
===> Enabling extension uuid
[*] uuid extension is enabled.
Done.
```

I think the issue is outdated, resolved and can be closed now.
