### ISSUE TITLE
add phalcon 

### ISSUE THREAD

**Issue by scoutman57** [phpbrew/phpbrew#396]
Could you add an option to install the phalcon framework with this.

**Comment by TrogWarZ** [comment]
Not working. What's happening? How can install it with phpbrew?

`# phpbrew ext install phalcon
Downloading https://pecl.php.net/rest/r/phalcon/stable.txt via curl extension
CurlKit\CurlException: (22) The requested URL returned error: 404 Not Found at [https://pecl.php.net/rest/r/phalcon/stable.txt:The requested URL returned error: 404 Not Found]`

`# phpbrew ext install https://github.com/phalcon/cphalcon
Downloading https://github.com/phalcon/cphalcon/archive/master.tar.gz via curl extension
Redirecting to https://codeload.github.com/phalcon/cphalcon/tar.gz/master
===> Extracting to /root/.phpbrew/build/php-5.6.25/ext...
===> Rename source directory to /root/.phpbrew/build/php-5.6.25/ext/phalcon...
===> Installing phalcon extension...
Log stored at: /root/.phpbrew/build/php-5.6.25/ext/phalcon/build/_resource/config/build.log
Changing directory to /root/.phpbrew/build/php-5.6.25/ext/phalcon/build/_resource/config
===> Phpize...
===> Configuring...
===> Building...
===> Running make all: /usr/bin/make -C '/root/.phpbrew/build/php-5.6.25/ext/phalcon/build/_resource/config' 'all'  >> '/root/.phpbrew/build/php-5.6.25/ext/phalcon/build/_resource/config/build.log' 2>&1
Error: Command failed: /usr/bin/make -C '/root/.phpbrew/build/php-5.6.25/ext/phalcon/build/_resource/config' 'all'  >> '/root/.phpbrew/build/php-5.6.25/ext/phalcon/build/_resource/config/build.log' 2>&1 returns:
The last 5 lines in the log file:
configure: creating ./config.status

config.status: creating config.h

make: Entering directory `/root/.phpbrew/build/php-5.6.25/ext/phalcon/build/_resource/config'

make: *** No rule to make target `/root/.phpbrew/build/php-5.6.25/ext/phalcon/build/_resource/config/phalcon.zep.c', needed by `phalcon.lo'.  Stop.

make: Leaving directory `/root/.phpbrew/build/php-5.6.25/ext/phalcon/build/_resource/config'

Please checkout the build log file for more details:
       	 tail /root/.phpbrew/build/php-5.6.25/ext/phalcon/build/_resource/config/build.log`

`# cat /root/.phpbrew/build/php-5.6.25/ext/phalcon/build/_resource/config/build.log
Configuring for:
PHP Api Version:         20131106
Zend Module Api No:      20131226
Zend Extension Api No:   220131226
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /root/.phpbrew/php/php-5.6.25
checking for PHP includes... -I/root/.phpbrew/php/php-5.6.25/include/php -I/root/.phpbrew/php/php-5.6.25/include/php/main -I/root/.phpbrew/php/php-5.6.25/include/php/TSRM -I/root/.phpbrew/php/php-5.6.25/include/php/Zend -I/root/.phpbrew/php/php-5.6.25/include/php/ext -I/root/.phpbrew/php/php-5.6.25/include/php/ext/date/lib
checking for PHP extension directory... /root/.phpbrew/php/php-5.6.25/lib/php/extensions/no-debug-non-zts-20131226
checking for PHP installed headers prefix... /root/.phpbrew/php/php-5.6.25/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... re2c
checking for re2c version... 0.13.5 (ok)
checking for gawk... gawk
checking whether to enable phalcon... yes, shared
checking whether HAVE_BUNDLED_PCRE is declared... yes
checking for ext/pcre/php_pcre.h... yes
checking whether HAVE_JSON is declared... yes
checking for ext/json/php_json.h... yes
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for /usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking the maximum length of command line arguments... 1572864
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC
checking if cc PIC flag -fPIC works... yes
checking if cc static flag -static works... yes
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
configure: creating ./config.status
config.status: creating config.h
make: Entering directory `/root/.phpbrew/build/php-5.6.25/ext/phalcon/build/_resource/config'
make: *** No rule to make target `/root/.phpbrew/build/php-5.6.25/ext/phalcon/build/_resource/config/phalcon.zep.c', needed by `phalcon.lo'.  Stop.
make: Leaving directory `/root/.phpbrew/build/php-5.6.25/ext/phalcon/build/_resource/config'`

**Comment by TrogWarZ** [comment]
Not working. What's happening? How can install it with phpbrew?

```
# phpbrew ext install phalcon
Downloading https://pecl.php.net/rest/r/phalcon/stable.txt via curl extension
CurlKit\CurlException: (22) The requested URL returned error: 404 Not Found at [https://pecl.php.net/rest/r/phalcon/stable.txt:The requested URL returned error: 404 Not Found]
```

```
# phpbrew ext install https://github.com/phalcon/cphalcon
Downloading https://github.com/phalcon/cphalcon/archive/master.tar.gz via curl extension
Redirecting to https://codeload.github.com/phalcon/cphalcon/tar.gz/master
===> Extracting to /root/.phpbrew/build/php-5.6.25/ext...
===> Rename source directory to /root/.phpbrew/build/php-5.6.25/ext/phalcon...
===> Installing phalcon extension...
Log stored at: /root/.phpbrew/build/php-5.6.25/ext/phalcon/build/_resource/config/build.log
Changing directory to /root/.phpbrew/build/php-5.6.25/ext/phalcon/build/_resource/config
===> Phpize...
===> Configuring...
===> Building...
===> Running make all: /usr/bin/make -C '/root/.phpbrew/build/php-5.6.25/ext/phalcon/build/_resource/config' 'all'  >> '/root/.phpbrew/build/php-5.6.25/ext/phalcon/build/_resource/config/build.log' 2>&1
Error: Command failed: /usr/bin/make -C '/root/.phpbrew/build/php-5.6.25/ext/phalcon/build/_resource/config' 'all'  >> '/root/.phpbrew/build/php-5.6.25/ext/phalcon/build/_resource/config/build.log' 2>&1 returns:
The last 5 lines in the log file:
configure: creating ./config.status

config.status: creating config.h

make: Entering directory `/root/.phpbrew/build/php-5.6.25/ext/phalcon/build/_resource/config'

make: *** No rule to make target `/root/.phpbrew/build/php-5.6.25/ext/phalcon/build/_resource/config/phalcon.zep.c', needed by `phalcon.lo'.  Stop.

make: Leaving directory `/root/.phpbrew/build/php-5.6.25/ext/phalcon/build/_resource/config'

Please checkout the build log file for more details:
         tail /root/.phpbrew/build/php-5.6.25/ext/phalcon/build/_resource/config/build.log
```

```
# cat /root/.phpbrew/build/php-5.6.25/ext/phalcon/build/_resource/config/build.log
Configuring for:
PHP Api Version:         20131106
Zend Module Api No:      20131226
Zend Extension Api No:   220131226
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /root/.phpbrew/php/php-5.6.25
checking for PHP includes... -I/root/.phpbrew/php/php-5.6.25/include/php -I/root/.phpbrew/php/php-5.6.25/include/php/main -I/root/.phpbrew/php/php-5.6.25/include/php/TSRM -I/root/.phpbrew/php/php-5.6.25/include/php/Zend -I/root/.phpbrew/php/php-5.6.25/include/php/ext -I/root/.phpbrew/php/php-5.6.25/include/php/ext/date/lib
checking for PHP extension directory... /root/.phpbrew/php/php-5.6.25/lib/php/extensions/no-debug-non-zts-20131226
checking for PHP installed headers prefix... /root/.phpbrew/php/php-5.6.25/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... re2c
checking for re2c version... 0.13.5 (ok)
checking for gawk... gawk
checking whether to enable phalcon... yes, shared
checking whether HAVE_BUNDLED_PCRE is declared... yes
checking for ext/pcre/php_pcre.h... yes
checking whether HAVE_JSON is declared... yes
checking for ext/json/php_json.h... yes
checking for ld used by cc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking for /usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm -B
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking the maximum length of command line arguments... 1572864
checking command to parse /usr/bin/nm -B output from cc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking if cc supports -fno-rtti -fno-exceptions... no
checking for cc option to produce PIC... -fPIC
checking if cc PIC flag -fPIC works... yes
checking if cc static flag -static works... yes
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
configure: creating ./config.status
config.status: creating config.h
make: Entering directory `/root/.phpbrew/build/php-5.6.25/ext/phalcon/build/_resource/config'
make: *** No rule to make target `/root/.phpbrew/build/php-5.6.25/ext/phalcon/build/_resource/config/phalcon.zep.c', needed by `phalcon.lo'.  Stop.
make: Leaving directory `/root/.phpbrew/build/php-5.6.25/ext/phalcon/build/_resource/config'
```

**Comment by marcioAlmada** [comment]
Hi! Here is an explanation:

> phpbrew ext install phalcon

This will attempt to install phalcon from pecl and AFAIK phalcon is not hosted there.

> phpbrew ext install https://github.com/phalcon/cphalcon

This will attempt to install phalcon from `master` but it's possible master is no longer compatible with php `5.6.25` *or* perhaps the branch is not even stable enough right now to compile. Installing from version tags works for me:

```
# on php 5.6.25
phpbrew ext install github:phalcon/cphalcon@phalcon-v1.3.4 # works
phpbrew ext install github:phalcon/cphalcon@phalcon-v2.0.13 # works
phpbrew ext install github:phalcon/cphalcon@phalcon-v3.0.0 # works
```

**Comment by TrogWarZ** [comment]
@marcioAlmada , i didn't find info on wiki about branch syntax, thank you.

Tried this:
```
# php -v
PHP 5.6.25 (cli) (built: Aug 23 2016 19:59:17)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Xdebug v2.4.1, Copyright (c) 2002-2016, by Derick Rethans
# phpbrew ext install github:phalcon/cphalcon@phalcon-v1.3.6
# phpbrew ext install github:phalcon/cphalcon@phalcon-v3.0.x
```

But it gives same error:
```
# cat /root/.phpbrew/build/php-5.6.25/ext/phalcon/build/_resource/config/build.log
Configuring for:
PHP Api Version:         20131106
Zend Module Api No:      20131226
Zend Extension Api No:   220131226
[... trimmed log ...]
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
configure: creating ./config.status
config.status: creating config.h
make: Entering directory `/root/.phpbrew/build/php-5.6.25/ext/phalcon/build/_resource/config'
make: *** No rule to make target `/root/.phpbrew/build/php-5.6.25/ext/phalcon/build/_resource/config/phalcon.zep.c', needed by `phalcon.lo'.  Stop.
make: Leaving directory `/root/.phpbrew/build/php-5.6.25/ext/phalcon/build/_resource/config'
```

**Is this issue with phpbrew or phalcon?**

Tried to compile it manually:
```
# git clone git://github.com/phalcon/cphalcon.git /tmp/cphalcon
# cd /tmp/cphalcon/build
# git checkout 1.3.6
# ./install
# cp /etc/php5/mods-available/phalcon.ini /root/.phpbrew/php/php-5.6.25/var/db/phalcon.ini
# cp /root/.phpbrew/php/php-5.6.25/lib/php/extensions/no-debug-non-zts-20131226/phalcon.so /root/.phpbrew/php/php-5.6.25/lib/php/extensions/no-debug-non-zts-20131226/phalcon.so
# phpbrew ext enable phalcon
# php -m | grep phalcon
```
And it works.
