### ISSUE TITLE
Cannot find OpenSSL's libraries

### ISSUE THREAD

**Issue by xreeckz** [phpbrew/phpbrew#418]
I've tried my luck with google and nothing came up. 

Whenever I run "phpbrew install 5.5.19 +default +mysql +fpm"
I get the following error: configure: error: Cannot find OpenSSL's libraries

I'm running CentOS 6.6 with cPanel. I'm trying to use phpbrew in combination with nDeploy. 
OpenSSL should be installed in /usr/bin/openssl
The version is: openssl-1.0.1e-30.el6_6.4.x86_64

Any help would be greatly appreciated!

**Comment by shinnya** [comment]
@c9s @marcioAlmada @xreeckz @mfham
```phpbrew install 5.5.19 +default +mysql +fpm +openssl=/usr -- --with-libdir=lib64``` solves the issue. The point is that we must specify `--with-libdir=lib64` with `+openssl=/usr`. The reason why it needs `--with-libdir=lib64` is described at https://gist.github.com/shinnya/beb7c5f0e64c19dcb940.

**Comment by shinnya** [comment]
The same solution is mentioned at http://php.net/manual/en/image.installation.php#105155.

**Comment by yireo** [comment]
The solution of @shinnya works for me also. Installing PHP on a 64-bits Fedora install works with the following command: `phpbrew install 5.428 +default +mysql +fpm +openssl=/usr -- --with-libdir=lib64`

**Comment by marcioAlmada** [comment]
This simply works for me on fedora too: `phpbrew install 5.428 +default +mysql +fpm +openssl`

**Comment by jbondc** [comment]
On FreeBSD, need to use:
```
phpbrew install 5.5.32 +default +openssl=/usr/local     
```

**Comment by 1stone** [comment]
To compile a PHP 5.5.38 on i386 (with phpbrew 1.22.5) I still had to create a link to prevent this error:

    cd /usr/lib
    ln -s i386-linux-gnu/libssl.so

This is on Debian "Jessie".

**Comment by ashnazg** [comment]
For googlers:  to get past this openssl error on Ubuntu 16.10, trying to install 5.6.5 with just `+default` required ` -- --with-openssl`.  No dir prefix required, no `+openssl` required.

**Comment by koflerdavid** [comment]
I'll put the Fedora solution into  the Cookbook.

**Comment by ncloudsbconnelly** [comment]
`+default  -- --with-openssl` works on Ubuntu for `5.3.4` also.

**Comment by findSaif** [comment]
It got past the openssl error but produced a new one

`Makefile:510: recipe for target 'ext/openssl/openssl.lo' failed`

`phpbrew install -j $(nproc) --old 5.4 +default -- --with-openssl`

**Comment by egorsmkv** [comment]
For MacOS also this works:

```
export OPENSSL_CFLAGS=-I/usr/local/opt/openssl/include
export OPENSSL_LIBS=-L/usr/local/opt/openssl/lib

phpbrew ext install openssl
```
