### ISSUE TITLE
could not find driver after execute composer

### ISSUE THREAD

**Issue by puterakahfi** [phpbrew/phpbrew#452]
Hi all, I have installed phpbrew in my elementary os, but I got problem when execute composer update for my symfony app

i got this issue :

  [Doctrine\DBAL\Exception\DriverException]              
  An exception occured in driver: could not find driver  
                                       
  [Doctrine\DBAL\Driver\PDOException]  
  could not find driver 

I tried to reinstalling phpbrew phpvers +default +pdo

but it's doesn't work

I'm using php-5.4.35

Thank you.
Kahfi

**Comment by c9s** [comment]
you shiuld at least use `+pdo +mysql`

**Comment by marcioAlmada** [comment]
or go with `+dbs` if you intend to use different db drivers for multiple projects.

**Comment by puterakahfi** [comment]
oh i see,
thanks it's worked

thanks all for your help.
