### ISSUE TITLE
Unable to install with apxs2

### ISSUE THREAD

**Issue by Anahkiasen** [phpbrew/phpbrew#453]
I'm trying to install 5.6 with the apache extension, without it everything works fine:

```
$ phpbrew install 5.6 +default+dbs+mb+debug
```

However if I add `apxs2` it fails:

```
$ phpbrew install 5.6 +default+dbs+mb+debug+apxs2
```

```
Undefined symbols for architecture x86_64:
  "_lo_lseek64", referenced from:
      _zif_pg_lo_seek in pgsql.o
  "_lo_tell64", referenced from:
      _zif_pg_lo_tell in pgsql.o
  "_lo_truncate64", referenced from:
      _zif_pg_lo_truncate in pgsql.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libs/libphp5.6.4.bundle] Error 1
```

I checked the required libraries from Homebrew and they're all properly installed. If I install 5.6 with *just* apxs2 it works but the combination above crashes everytime, any idea why?

**Comment by shinnya** [comment]
@Anahkiasen Hi. The issue seems to be not in Apache but PostgreSQL, from what I can see. I think it might be the same issue as described in #298. Could you check itout, please?

**Comment by Anahkiasen** [comment]
Oh, had forgotten about that one. What dependency is required through brew to get pgsql? I tried installing postgresql92 but that didn't install pgsql.

**Comment by shinnya** [comment]
@Anahkiasen Well, are you using Mac OSX and homebrew, aren't you? According to http://braumeister.org/formula/postgresql, `postgresql` needs only `libxml2`, `openssl` and `readline`.
I found the thread https://github.com/Homebrew/homebrew-php/issues/1291 and the problem is similar to yours.

**Comment by Anahkiasen** [comment]
Yes I have those, but that still doesn't give me the pgsql binary:

```
Macedoine ➜  remindme git:(feature/bugsnag) brew install libxml2 openssl readline postgresql
Warning: libxml2-2.9.2 already installed
Warning: openssl-1.0.1k already installed
Warning: readline-6.3.8 already installed
Warning: postgresql-9.4.0 already installed

Macedoine ➜  remindme git:(feature/bugsnag) brew unlink postgresql && brew link postgresql
Unlinking /usr/local/Cellar/postgresql/9.4.0... 426 symlinks removed
Linking /usr/local/Cellar/postgresql/9.4.0... 426 symlinks created

Macedoine ➜  remindme git:(feature/bugsnag) which pgsql
pgsql not found
```

In the issue mentioned above is also mentioned `brew install php55 --with-pgsql` but... if I have to install PHP through Homebrew anyway, that kind of defeats the purpose, no?

**Comment by shinnya** [comment]
I've installed PostgreSQL on my system, but there is no `pgsql`command. Do you mean `postgres` command?

**Comment by Anahkiasen** [comment]
I don't know, I don't personally use PostgreSQL, it's just included by default in `+dbs`, just trying to track back what was said in the [previous issue](https://github.com/phpbrew/phpbrew/issues/298#issuecomment-54008037)

**Comment by shinnya** [comment]
Uhm, I think you've misunderstood the meaning of `pgsql`. `pgsql` means not an executable command but the base directory of your postgresql. And in the previous issue, he meant that when you added `+dbs` on Mac OSX, you had to specify the base directory of `postgresql` because the default value is `/usr/local/pgsql`.
So the entire command should be like `phpbrew install 5.6 +default+dbs+mb+debug+apxs2=/usr/sbin/apxs -- --with-pdo-pgsql=/usr/loca/Cellar/postgresql/9.4.0/`.

> In the issue mentioned above is also mentioned brew install php55 --with-pgsql but... if I have to install PHP through Homebrew anyway, that kind of defeats the purpose, no?
I didn't mean you should install PHP with homebrew. I meant you might need to create links for postgresql explicitly after installing it by homebrew.

**Comment by c9s** [comment]
Here is the note of `--with-pgsql` option:

```
PHP_ARG_WITH(pgsql,for PostgreSQL support,
[  --with-pgsql[=DIR]        Include PostgreSQL support.  DIR is the PostgreSQL
                          base install directory or the path to pg_config])
```

You need to run `pg_config` to the correct path, however the `[=DIR]` is optional, if you don't specify one, PHP build system will detect the path for you.

**Comment by c9s** [comment]
When you run install command with `+pgsql`, it's actually `--with-pgsql`, for example, my install command is like:

```
phpbrew install 5.4.22 +pdo +mysql +pgsql=/opt/local/lib/postgresql92/bin  +fpm +sqlite +pcntl \
              +posix +gettext +intl +openssl +default +curl +readline +session +xml_all \
              +phpdbg +soap +bcmath +exif +fileinfo +ipc +imap +mbregex +mbstring +mhash \
              +opcache +xml +zts +icu -- --with-icu-dir=/opt/local \
              --with-icu-dir=/opt/local
```

**Comment by Anahkiasen** [comment]
Just used `+mysql+sqlite` since I don't need PostgreSQL, should be good for now. I'm getting another error transitioning from Homebrew when I try to use the `+gettext` variant but I'm guessing that's the same thing, some dependency I'm missing.

```
configure: error: Cannot locate header file libintl.h
```

I think the wiki would benefit from having the dependencies for each variant listed, cause currently the basic requirements are listed but not the ones for all the facultative variants.

**Comment by c9s** [comment]
I think you're missing `libintl` for `gettext`.

Dependency is a good idea, it was noted in #270 and #194. It would be great if there is a PR for this. :)

**Comment by Anahkiasen** [comment]
@c9s That's what I found too but I do seem to have it:

```
Macedoine ➜  Sites  brew install icu4c
Warning: icu4c-54.1 already installed
```

**Comment by Anahkiasen** [comment]
Any idea? gettext/intl is the last extension I'm missing that prevents me from moving from homebrew, and I have both those dependencies:

```
Macedoine ➜ brew install intltool icu4c
Warning: intltool-0.50.2 already installed
Warning: icu4c-54.1 already installed

Macedoine ➜ phpbrew extension install intl
===> Installing intl extension...
Log stored at: /Users/anahkiasen/.phpbrew/build/php-5.6.4/ext/intl/build.log
Changing directory to /Users/anahkiasen/.phpbrew/build/php-5.6.4/ext/intl
Makefile not found
===> Phpize...
===> Configuring...
Command failed: ./configure --with-php-config=/Users/anahkiasen/.phpbrew/php/php-5.6.4/bin/php-config >> /Users/anahkiasen/.phpbrew/build/php-5.6.4/ext/intl/build.log 2>&1 returns

Macedoine ➜ cat /Users/anahkiasen/.phpbrew/build/php-5.6.4/ext/intl/build.log
Configuring for:
PHP Api Version:         20131106
Zend Module Api No:      20131226
Zend Extension Api No:   220131226
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-apple-darwin14.0.0
checking host system type... x86_64-apple-darwin14.0.0
checking target system type... x86_64-apple-darwin14.0.0
checking for PHP prefix... /Users/anahkiasen/.phpbrew/php/php-5.6.4
checking for PHP includes... -I/Users/anahkiasen/.phpbrew/php/php-5.6.4/include/php -I/Users/anahkiasen/.phpbrew/php/php-5.6.4/include/php/main -I/Users/anahkiasen/.phpbrew/php/php-5.6.4/include/php/TSRM -I/Users/anahkiasen/.phpbrew/php/php-5.6.4/include/php/Zend -I/Users/anahkiasen/.phpbrew/php/php-5.6.4/include/php/ext -I/Users/anahkiasen/.phpbrew/php/php-5.6.4/include/php/ext/date/lib
checking for PHP extension directory... /Users/anahkiasen/.phpbrew/php/php-5.6.4/lib/php/extensions/debug-non-zts-20131226
checking for PHP installed headers prefix... /Users/anahkiasen/.phpbrew/php/php-5.6.4/include/php
checking if debug is enabled... yes
checking if zts is enabled... yes
checking for re2c... re2c
checking for re2c version... 0.13.7.5 (ok)
checking for gawk... no
checking for nawk... no
checking for awk... awk
checking if awk is broken... no
checking whether to enable internationalization support... yes, shared
checking for icu-config... no
checking for location of ICU headers and libraries... not found
configure: error: Unable to detect ICU prefix or no failed. Please verify ICU install prefix and make sure icu-config works.
```

Any other dependency I might be missing?

**Comment by Anahkiasen** [comment]
So what was needed was `brew link icu4c gettext --force`, having them installed isn't enough

**Comment by c9s** [comment]
Hi @Anahkiasen , Thanks, I just commented your solution in the trouble shooting page.

**Comment by Ma-Xiaolei** [comment]
When I I had this error.
