### ISSUE TITLE
Cannot exec a2enmod on phpbrew install

### ISSUE THREAD

**Issue by Benjen** [phpbrew/phpbrew#455]
I am trying to install php using phpbrew on Debian Wheezy using the following command.  

phpbrew install php-5.4.36 +default +mysql +gettext +mcrypt +intl +iconv +ftp +exif +dba +openssl +soap +apxs2=/usr/bin/apxs2 -- --with-libdir=lib/x86_64-linux-gnu --with-gd=shared --enable-gd-native-ttf --with-jpeg-dir=/usr --with-png-dir=/usr --enable-wddx --with-mysql-sock=/var/run/mysqld/mysqld.sock

However the install fails with the following from the log:

Build complete.
Don't forget to run 'make test'.
Installing PHP SAPI module:       apache2handler
Use of uninitialized value $includedir in concatenation (.) or string at (eval 9) line 1.
/usr/share/apache2/build/instdso.sh SH_LIBTOOL='/usr/share/apr-1.0/build/libtool' libphp5.4.36.la /usr/lib/apache2/modules
/usr/share/apr-1.0/build/libtool --mode=install cp libphp5.4.36.la /usr/lib/apache2/modules/
libtool: install: cp .libs/libphp5.4.36.so /usr/lib/apache2/modules/libphp5.4.36.so
libtool: install: cp .libs/libphp5.4.36.lai /usr/lib/apache2/modules/libphp5.4.36.la
libtool: install: warning: remember to run `libtool --finish /home/ben/.phpbrew/build/php-5.4.36/libs'
chmod 644 /usr/lib/apache2/modules/libphp5.4.36.so
[preparing module`php5' in /etc/apache2/mods-available/php5.load]
Can't exec "a2enmod": No such file or directory at /usr/bin/apxs2 line 558.
'a2enmod php5' failed
make: **\* [install-sapi] Error 2

**Comment by c9s** [comment]
```
Use of uninitialized value $includedir in concatenation (.) or string at (eval 9) line 1.
```
looks like some perl script is using uninitialized value.

**Comment by Benjen** [comment]
Not sure if this issue is outside of the scope of phpbrew or not, but do you by chance have any idea on how I might be able to resolve this issue?

**Comment by c9s** [comment]
I think this is related to Debian, can you run `which a2enmod` and see if you can execute it?

It should be existing on every Debian linux system.

**Comment by Benjen** [comment]
I ran `which a2enmod`, but it couldn't find anything (i.e. nothing was returned).

**Comment by c9s** [comment]
If your system does not provide `a2enmod` you're probably missing some packages or you need to configure (load the module) by yourself.

**Comment by carltondickson** [comment]
I get a similar error

```
/usr/share/apache2/build/instdso.sh SH_LIBTOOL='/usr/share/apr-1.0/build/libtool' libphp5.4.45.la /usr/lib/apache2/modules
/usr/share/apr-1.0/build/libtool --mode=install cp libphp5.4.45.la /usr/lib/apache2/modules/
libtool: install: cp .libs/libphp5.4.45.so /usr/lib/apache2/modules/libphp5.4.45.so
libtool: install: cp .libs/libphp5.4.45.lai /usr/lib/apache2/modules/libphp5.4.45.la
libtool: install: warning: remember to run `libtool --finish /home/carlton/.phpbrew/build/php-5.4.45/libs'
chmod 644 /usr/lib/apache2/modules/libphp5.4.45.so
[preparing module `php5' in /etc/apache2/mods-available/php5.load]
Can't exec "a2enmod": No such file or directory at /usr/bin/apxs2 line 555.
'a2enmod php5' failed
```

Version
```
me@debian:/home/me$  lsb_release -da
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 6.0.10 (squeeze)
Release:	6.0.10
Codename:	squeeze
```

I can see the location of a2enmod when running `sudo which a2enmod` but not as my normal user.

Is there an additional step that needs to be done so that `a2enmod` can be found & executed?

**Comment by peter279k** [comment]
The issue is outdated and closed now.
