### ISSUE TITLE
Can't install spl_types

### ISSUE THREAD

**Issue by c9s** [phpbrew/phpbrew#456]
$ phpbrew ext install spl_types

Failure:

```
phpbrew ext install spl_types
===> Downloading from http://pecl.php.net/get/SPL_Types-0.4.0.tgz
[==================================================================] 8.19/8.19KB 100%
===> /Users/c9s/.phpbrew/distfiles/SPL_Types-0.4.0.tgz downloaded.
===> Extracting to /Users/c9s/.phpbrew/build/php-5.5.17/ext...
===> Rename source directory to /Users/c9s/.phpbrew/build/php-5.5.17/ext/SPL_Types...
mv: rename /Users/c9s/.phpbrew/build/php-5.5.17/ext/spl_types to /Users/c9s/.phpbrew/build/php-5.5.17/ext/SPL_Types: No such file or directory
Command failed: mv /Users/c9s/.phpbrew/build/php-5.5.17/ext/spl_types /Users/c9s/.phpbrew/build/php-5.5.17/ext/SPL_Types returns
```

**Comment by marcioAlmada** [comment]
It looks like like `package.xml` is giving the wrong `.so` file to PeclExtension:

```xml
<providesextension>SPL_Types</providesextension>
```
It should be `spl_types`. In the old implementation of the extension installer we had a `strtolower` call when getting the extension `.so` name. Do you think it could become a problem if we repeat the old solution here? Not sure if there is any extension that has a weird mixed case name.

**Comment by marcioAlmada** [comment]
Ok, it's fixed. The patch seems to do not break any other tested extension (even APCu, which has a weird name).

One possible flaw is that if somebody installed APCu before and try to install it again (after the patch) ones might end up with two `.ini` files `APCu.ini` and `apcu.ini` loading `apcu.so` twice and erroring... but I guess this has to be fixed at some point on phpbrew side.

**Comment by c9s** [comment]
@marcioAlmada++! Thanks!

**Comment by esilvajr** [comment]
===> /home/esilva/.phpbrew/distfiles/SPL_Types-0.4.0.tgz downloaded.
===> Extracting to /home/esilva/.phpbrew/build/php-7.0.3/ext...
===> Installing spl_types extension...
Log stored at: /home/esilva/.phpbrew/build/php-7.0.3/ext/spl_types/build.log
Changing directory to /home/esilva/.phpbrew/build/php-7.0.3/ext/spl_types
===> Phpize...
===> Configuring...
===> Building...
===> Running make all: make -C /home/esilva/.phpbrew/build/php-7.0.3/ext/spl_types  all  >> /home/esilva/.phpbrew/build/php-7.0.3/ext/spl_types/build.log 2>&1
Exception: Command failed: make -C /home/esilva/.phpbrew/build/php-7.0.3/ext/spl_types  all  >> /home/esilva/.phpbrew/build/php-7.0.3/ext/spl_types/build.log 2>&1 returns 


Anyone can help?
