### ISSUE TITLE
Install using +all -variant

### ISSUE THREAD

**Issue by kherge** [phpbrew/phpbrew#457]
The command `phpbrew install 5.6 +all -imap` does not appear to work.

If using variants in this manner does not work, it would be something very nice to have. It's a pain to write out all the variants needed as opposed to just subtracting from a predefined list.

**Comment by marcioAlmada** [comment]
@kherge maybe `+all` was a bad name. Currently it stands for `--enable-all` option, it's not a virtual variant you can subtract from like [`+default`](https://github.com/phpbrew/phpbrew/blob/develop/src/PhpBrew/VariantBuilder.php#L64-L92).

We can't change meaning of `+all` (huge BC break) but we can create another virtual variant that contains all other variants and allows subtraction, we just need a good name for it.

**Comment by kherge** [comment]
Here are a few I can think of:

- combined
- everything
- pool

**Comment by marcioAlmada** [comment]
Since `+everything` can't really have all the things because conflicts, I'll take a look at what `--enable-all` does, exactly, and reproduce it with `+everything`.

In the meantime, `+everything` contains only [+dbs+mb+default](https://github.com/phpbrew/phpbrew/blob/develop/src/PhpBrew/VariantBuilder.php#L48-L90).

**Comment by kherge** [comment]
I was hoping that `+everything` would simply include all of the available variants, and any `-variable` would remove it from the final list that would be used.

**Comment by marcioAlmada** [comment]
Me too, but I noticed a lot of failures due to conflicts so I'll check which variants cannot be on `+everything`, most of them can but some are causing troubles on different PHP versions.

**Comment by kherge** [comment]
Actually, this is the reason I wanted to be able to specify the variants I want removed from a complete list of varaints. The `+everything` variant is just for convenience, and I completely do not expect it to work without specifically excluding some variants.

**Comment by marcioAlmada** [comment]
Oh, that would make it useless for most part of the user base which expects variants to work without too much intervention, just requirements. I'll keep wiping which variants are too troublesome (specially the ones that might require sudo) and in the end we can get a good `+everything` without making it too error prone, don't worry.

**Comment by marcioAlmada** [comment]
The only variants that offered too much trouble were `apxs2` and `all`, so they will not be part of `+everything`. All other variants are in :)

**Comment by marcioAlmada** [comment]
Off topic: are you the maintainer of box2 project? would it be hard to migrate phpbrew phar build to box2? I tried before but got some trouble with autoloading inside phar.

**Comment by kherge** [comment]
Yep, that would be me.

Look at the `phpbrew/scripts/compile` script, it looks like it would be very simple. Something like this might work:

**box.json**

```json
{
    "blacklist": [
        "Tests",
        "CHANGELOG",
        "README",
        "phpunit.xml"
    ],
    "bootstrap": "scripts/phpbrew-emb.php",
    "directories": [
        "src",
        "vendor/corneltek/cliframework/src",
        "vendor/corneltek/pearx/src",
        "vendor/corneltek/getoptionkit/src",
        "vendor/corneltek/curlkit/src",
        "vendor/corneltek/universal/src",
        "vendor/symfony/process",
        "vendor/symfony/yaml",
        "shell"
    ],
    "output": "phpbrew.phar",
    "stub": true
}
```

**Comment by marcioAlmada** [comment]
Will be on master soon. Thanks for the suggestion.
