### ISSUE TITLE
 bin directory not in the path

### ISSUE THREAD

**Issue by iamhappycoder** [phpbrew/phpbrew#458]
I installed composer (phpbrew install-composer) and was expecting to just be able to type 'composer' on the command line but it didn't worked.

Upon checking, composer is present in ~/.phpbrew/bin but it is not in the PATH.

Of course, I can just modify PATH to include ~/.phpbrew/bin but it would be nice if I won't have to do this everyime I install phpbrew.

**Comment by c9s** [comment]
It was fixed.
