### ISSUE TITLE
Issues with php-fpm

### ISSUE THREAD

**Issue by bddenhartog** [phpbrew/phpbrew#459]
Hey there.

I've used my google-fu and looked through the issues here but have had no luck in resolving this issue.

I'm attempting to set up nginx using php-fpm (installed/managed by phpbrew). I have nginx installed on my server. I've also used phpbrew to install php-5.6.4 along with the variants I want (+default, +fpm) and have ensured that the aforementioned packages are my "current environment".

Here's what I did after setting up the environment:

**1. Configure php-fpm**
Because of how nginx and php-fpm work, the nginx user needs to be in control of the `php5-fpm.sock` file. To emulate environments that I currently have on live servers, I ran `phpbrew fpm config` and modified the configuration file as such:

```
Line 149: user = www-data
Line 150: group = www-data
....
Line 175: listen.owner = www-data
Line 176: listen.owner = www-data
```

**2. Save and test**
I then wrote to the file and closed it. Running `phpbrew fpm test` returns:
`$ NOTICE: configuration /home/usr/.phpbrew/php/php-5.6.4/etc/php-fpm.conf test is successful`

So far, so good!

**3. Start it!**
Then came the issue. I ran `phpbrew fpm start`, and this was the following output:

```
[25-Jan-2015 20:59:16] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
[25-Jan-2015 20:59:16] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
[25-Jan-2015 20:59:16] ERROR: failed to chown() the socket '/home/user/.phpbrew/php/php-5.6.4/var/run/php5-fpm.sock': Operation not permitted (1)
[25-Jan-2015 20:59:16] ERROR: FPM initialization failed
php-fpm start failed.
```

The socket is created in `var/run`, but the user/group owner is `user:user`. This isn't a surprise, as normal users are not able to `chown` (or "give away") files, and the `phpbrew fpm start` command is not using root privileges.

Any way to get around this and continue using phpbrew? I'd appreciate any help you can offer.

**Comment by bddenhartog** [comment]
To note, running the script manually (e.g. `/home/user/.phpbrew/php/php-5.6.4/sbin/php-fpm -allow-to-run-as-root` does not fix this issue.

**Comment by webavant** [comment]
I wanted to avoid running as root altogether, so I added the web server's primary group (e.g. www-data) to my user.

* **linux:** sudo usermod --G www-data my_user_name
* **mac:** sudo dseditgroup -o edit -a my_user_name -t user www-data 

**In the php-fpm pool conf files:**
1. Remove the 'group', 'user' and 'listen.owner' directives
2. Set the 'listen.group' directive to 'www-data'
3. Set 'listen.mode' directive to 0660

Now php-fpm starts without running it as root.

**Comment by wellingtonlorindo** [comment]
I have already edited the php-fpm.conf, but I when try to start the php-fpm it shows the error:

phpbrew fpm test
[23-Mar-2015 13:33:25] ERROR: failed to open error_log (/home/vagrant/.phpbrew/php/php-5.4.38/var/log/php-fpm.log): Permission denied (13)
[23-Mar-2015 13:33:25] ERROR: failed to post process the configuration
[23-Mar-2015 13:33:25] ERROR: FPM initialization failed

**Comment by wellingtonlorindo** [comment]
It has solved my problem
$ chown -R my_user:my_user ~/.phpbrew/php/

And in the nginx configuration file I have used
fastcgi_pass 127.0.0.1:9000;

Instead of 
fastcgi_pass unix:/var/run/php5-fpm.sock;

**Comment by bddenhartog** [comment]
Tony,

Is your user in your web server's group? Check by running the `groups`
command in your shell.

On Monday, March 23, 2015, Wellington Lorindo <notifications@github.com>
wrote:

> It has solved my problem
> $ chown -R my_user:my_user ~/.phpbrew/php/
>
> And in the nginx configuration file I have used
> fastcgi_pass 127.0.0.1:9000;
>
> Instead of
> fastcgi_pass unix:/var/run/php5-fpm.sock;
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phpbrew/phpbrew/issues/459#issuecomment-85088049>.
>


-- 
Benjamin Denhartog
bddenhartog@gmail.com
http://github.com/bddenhartog
http://twitter.com/bddenhartog

**Comment by webavant** [comment]
@bddenhartog That's what I was suggesting, but I would up changing it, since it's not ideal for security to put users in groups intended for daemons. I wound up reconfiguring it on my dev environment to run Apache and php-fpm as my user and did chown -R on all my conf and www directories. I'd never need to do any of this on a production server, so I guess it's kind-of a moot point. I can delete my previous comment if you think it's confusing.

**Comment by bddenhartog** [comment]
Whoops! My last comment should have been directed at @wellingtonlorindo, not you. 

In regards to your _solution_... isn't that even less secure? I mean, from an abstraction standpoint, now all I need to do is gain control of your user and your entire system (well, webserver at least) is at my disposal, no sudo needed.

**Comment by webavant** [comment]
Right, I considered both solutions and I resolved to myself that I will never do this is production, heh heh. Sorry to confound this issue further. I suppose it's still open until someone proposes something ideal.

**Comment by andyexeter** [comment]
@bddenhartog Did you ever get anywhere with this? I'm using `sudo ~/.phpbrew/php/php-5.6.4/sbin/php-fpm -R` manually every time I start up at the moment and it's a real pain.

I thought about adding the command in to the `/etc/rc.local` file but then the PHP version being used would be hard coded, unless the version can be retrieved by sourcing the phpbrew bashrc file perhaps...

**Comment by bddenhartog** [comment]
@andyexeter No, I decided instead to simply dockerize the existing applications I had that I had previously used phpbrew with. If you're in a development environment and not concerned about security, @webavant's solution should work nicely for you (adding your user to the necessary groups).

**Comment by bddenhartog** [comment]
@morozov Why was this closed?

**Comment by morozov** [comment]
There was no development on this issue during a year, so it's unlikely to be ever resolved.

As far as I understand the original issue, you wanted a regular user to be able to run PHP FPM on behalf of www-data which is not possible and not something PHPBrew is designed to take care of.

Personally, I run PHP FPM on behalf of my own user during development.

If this is still important to be fixed, please feel free to provide a pull request.

**Comment by bddenhartog** [comment]
@morozov said:

> As far as I understand the original issue, you wanted a regular user to be able to run PHP FPM on behalf of www-data which is not possible and not something PHPBrew is designed to take care of.

It is entirely possible to run a process as another user, but I suppose that is beside the point as it would require sudo anyway, and the user could simply do that themselves.

I just wanted clarification, so that the reason for closure was documented. Thanks!
