### ISSUE TITLE
Allow install of next major php 7

### ISSUE THREAD

**Issue by henrikbjorn** [phpbrew/phpbrew#462]
The title says it all :)

The php7 release is coming up and fast. Would be cool if we could build and install it through phpbrew

**Comment by marcioAlmada** [comment]
What a coincidence, I'm working on that :)

:+1:

**Comment by c9s** [comment]
@marcioAlmada are you working on the git installer for php 7?

**Comment by marcioAlmada** [comment]
Yup, but I'm also working to pass this RFC https://wiki.php.net/rfc/batch_use_declarations, so if you think you can do it like **really** quick go for it.

**Comment by marcioAlmada** [comment]
FYI, there was problems due to some extensions that were not ported to PHP7 yet so a few variants won't work.

**Comment by c9s** [comment]
Cool, I will start working on the Git installer on the end of Feb, but you can go for it if you have time :+1:

**Comment by ovr** [comment]
Any news?

**Comment by fdewinne** [comment]
Zend is now proposing nightly builds of php7. Maybe it could be possible to reuse them ? https://php7.zend.com

**Comment by henrikbjorn** [comment]
@fdewinne would only work for debian based system.

**Comment by fdewinne** [comment]
@henrikbjorn debian/RHEL... but yes, it does not cover all system :(

**Comment by sagikazarmark** [comment]
Any news?

**Comment by helmuthva** [comment]
+1 for this

**Comment by guiwoda** [comment]
+1 for this!

**Comment by shinnya** [comment]
I will work on the git installer if no one is working on now.

**Comment by sagikazarmark** [comment]
Looking forward to it.

**Comment by marcioAlmada** [comment]
@shinnya see 8e21f68

```
phpbrew install next
phpbrew install next:<branch-name>
```

Most extensions and variants are working.

I'm not so sure about the `next` pseudo version, but we have `latest` already. Anyway, request for feedback here... cc @c9s

**Comment by c9s** [comment]
Can we have it named with `github:php/php-src` ? so people can install the repository from any forks, not just the php-src repository:

```
phpbrew install github:php/php-src
phpbrew install github:c9s/php-src
phpbrew install github:anyuser/php-src
```

And the branch name syntax could be:

```
phpbrew install github:php/php-src@master
```

**Comment by marcioAlmada** [comment]
Yea, I like that. We can follow the same patterns as the ext install DSL. But I'll keep the `next` pseudo version though, aliasing it to the official php-src/master branch, because it's appealing :stuck_out_tongue:

**Comment by c9s** [comment]
@marcioAlmada  sound great :) Expecting!

**Comment by henrikbjorn** [comment]
Dont think the binary in master have been updated, which makes it hard to test it out :smile:

**Comment by shinnya** [comment]
I like `next` pseudo version name and think it useful.

**Comment by marcioAlmada** [comment]
@henrikbjorn `phpbrew self-update develop`

**Comment by marcioAlmada** [comment]
Released:

```bash

phpbrew self-update

# basic support

phpbrew install next as php-7.0.0
phpbrew use php-7.0.0

# full syntax so forks can be installed too

phpbrew install github:<owner>/php-src:<branch>
phpbrew install git@github.com:<owner>/php-src:<branch>
phpbrew install https://github.com/<owner>/php-src:<branch>
```

Thanks.

**Comment by pierredup** [comment]
:clap: This is an excellent addition, thanks for the awesome work!

**Comment by Soullivaneuh** [comment]
Thanks for this @marcioAlmada.

How can I update PHP7 once installed? Any doc about it?

**Comment by marcioAlmada** [comment]
@Soullivaneuh just run the same command again. Ex:
```bash
phpbrew install next as php-7.0.0
# master gets new commits
phpbrew install next as php-7.0.0 # will redownload, compile and overwrite the old one
```
PS: there was a bug regarding `wget` fallback https://github.com/phpbrew/phpbrew/issues/554, so you might want to run `phpbrew self-update` if you fall into this edge case.

**Comment by Soullivaneuh** [comment]
Not get any problem with `wget`. Thanks for the tip! :+1:

**Comment by Niehztog** [comment]
Getting the following error:

    phpbrew use php-7.0.0
    php version: php-7.0.0 not exists.

`PHP -v` tells me that the above command had no effect. Right before I did `phpbrew self-update` to verify I am using the latest version. I am testing on Debian 8 Jessie.

**Comment by Soullivaneuh** [comment]
@Niehztog Can you provide result of `phpbrew list` command?

**Comment by Niehztog** [comment]
phpbrew list
    * (system)
    php-5.3.22

I also tried with sudo:

    sudo phpbrew use php-7.0.0
    Invalid argument php-7.0.0

Compilation seems to have worked however:

    sudo ls -al /root/.phpbrew/php/
    drwxr-xr-x 3 root root 4096 Aug 24 13:54 .
    drwxr-xr-x 8 root root 4096 Aug 24 13:54 ..
    drwxr-xr-x 8 root root 4096 Aug 24 13:59 php-7.0.0

    sudo /root/.phpbrew/php/php-7.0.0/bin/php -v
    PHP 7.0.0-dev (cli) (built: Aug 24 2015 14:04:53) 
    Copyright (c) 1997-2015 The PHP Group
    Zend Engine v3.0.0-dev, Copyright (c) 1998-2015 Zend Technologies

**Comment by Niehztog** [comment]
nevermind, I acidentaly installed php 7 using sudo: `sudo phpbrew install next as php-7.0.0`
Without sudo it worked fine

**Comment by Pupp3tm4st3r** [comment]
Hi,

sorry for pulling this old thread out of the mud but I´ve tried to compile PHP-7.1.0 via

phpbrew install github:php/php-src:PHP-7.1.0 as PHP-7.1.0

but it always uses the master branch. What am I doing wrong?

Thanks in advance.
Simon
