### ISSUE TITLE
"name lookup timed out" error

### ISSUE THREAD

**Issue by vasiliy-pdk** [phpbrew/phpbrew#464]
Hi! I get "name lookup timed out" message when I try to fetch known versions or to install some php.

Here is the output: 

```
vasiliy@vasiliy-Inspiron-7720:~$ phpbrew -v -d known
===> Fetching release list...
name lookup timed out
vasiliy@vasiliy-Inspiron-7720:~$ phpbrew -v -d install 5.6.5 +default
name lookup timed out
vasiliy@vasiliy-Inspiron-7720:~$ phpbrew --version
phpbrew - 1.18.4
cliframework core: 1.10.0
```

You can see my php.ini here https://www.dropbox.com/s/0xlv6y2cts46u08/php.ini?dl=0
You can see output of the phpinfo here: https://www.dropbox.com/s/x56kcnp9c0w6s7s/phpinfodump?dl=0

The problem appears on my Ubuntu 12.04. I have tried to disable Suhosin plugin by 

```
[suhosin]
suhosin.simulation = On
```

**Comment by c9s** [comment]
looks like your network is blocked? try using proxy options?

**Comment by vasiliy-pdk** [comment]
I am going to try proxy. Where can I find a URL requested by phpbrew's commands `<known>` or `<install>`?

**Comment by vasiliy-pdk** [comment]
Network is not blocked. I've found the URL "https://raw.githubusercontent.com/phpbrew/phpbrew/$branch/assets/php-releases.json" here https://github.com/phpbrew/phpbrew/blob/develop/src/PhpBrew/ReleaseList.php#L103 .

I've copied it to the browser's address bar and replaced `$branch` with "master". I've seen correct packages json structure. So, I don't think that the problem appears because of network.

**Comment by vasiliy-pdk** [comment]
I've found the problem. The reason for the error is the small value of CURLOPT_CONNECTTIMEOUT. It is set to 10 seconds now. When I set it to 30 seconds, all works fine.  

There is no way to customize it by any option of PHPBrew now. 

Here is set the option: https://github.com/c9s/CurlKit/blob/1.0.5/src/CurlKit/CurlDownloader.php#L72
`CurlDownloader` allows us to set an another value. But we don't do this in the `ReleaseList::fetchRemoteReleaseList` method: https://github.com/phpbrew/phpbrew/blob/develop/src/PhpBrew/ReleaseList.php#L106

So, I suggest to add `curl-connection-timeout` option to the PHPBrew's Config file. 

I am going to do this if nobody has other suggestions.

**Comment by c9s** [comment]
Thanks, if you have any pr for this, i would like to merge. :)

**Comment by c9s** [comment]
by the way, can we also add an env var for override this setting?

**Comment by vasiliy-pdk** [comment]
`CONNECT_TIMEOUT` environment variable or `--connect-timeout` command's option can be set since #466 pull request was merged. So, if someone gets `name lookup timed out` error message try to set a bigger timeout. 

```
$ export CONNECT_TIMEOUT=30
$ phpbrew known
```

or 

```
$ phpbrew known --connect-timeout=30
```

It works for me.

**Comment by c9s** [comment]
Hi @vasiliy-pdk, :+1:  I think it would be helpful to others if you could update this usage on our wiki. I guess the proper page might be the "Trouble Shooting". :)
