### ISSUE TITLE
Getting memory issue with phpbrew but not Homebrew

### ISSUE THREAD

**Issue by Anahkiasen** [phpbrew/phpbrew#468]
I have PHP 5.6.5 installed, both on Homebrew and on phpbrew. Exact same configuration to the letter, exact same set of extensions, exact same configuration for said extensions.

When I run a script with Homebrew's PHP all runs fine, when I run it with phpbrew's it runs out of memory. Any idea where it might come from? Something that may different in the way PHP is built or something? Error is:

> Allowed memory size of 536870912 bytes exhausted at /Users/anahkiasen/.phpbrew/build/php-5.6.5/Zend/zend_API.c:1155 (tried to allocate 40 bytes)

**Comment by Anahkiasen** [comment]
Note that I do the comparaison with Homebrew's PHP cause that's what I have in local but the script I'm trying to run is a test suite and when Travis runs it, it [doesn't encounter any issue](https://travis-ci.org/rocketeers/rocketeer/builds/50761075) either with any version of PHP.

I also get that error most of the times when running `composer update`.

**Comment by c9s** [comment]
I don't know. I suspect the homebrew one has some patches for your installation.

**Comment by c9s** [comment]
Might relate to some specific options (copied from homebrew)

764420b0d30fa2fbf70edca45fc83775788ed948
