### ISSUE TITLE
Failing to install apxs

### ISSUE THREAD

**Issue by KrzysztofMadejski** [phpbrew/phpbrew#469]
I got error: `apxs binary is not executable`

`sudo apt-get install apache2-dev` helped there

**Comment by roman-1983** [comment]
Thanks, this helped me.

**Comment by Gamesh** [comment]
on linux debian 7.11 wheezy you need to install `apache2-threaded-dev` which provides `apache2-dev`

**Comment by nelson6e65** [comment]
Thanks. In Fedora is:

```bash
sudo dnf install httpd-devel
```
