### ISSUE TITLE
TCPDF with PHP-FPM

### ISSUE THREAD

**Issue by brianjking** [phpbrew/phpbrew#470]
Hello,

I'm using nDeploy (https://github.com/AnoopAlias/nDeploy) which utilizes the PHPBrew libraries for adding in NGINX & PHP-FPM on my CentOS server running cPanel & WHM. 

One of the functions that I'm having issues with is when PHP-FPM is utilized having it successfully utilize the TCPDF scripts for creating PDF files dynamically. No errors seem to be logged anywhere and I'm at a loss -- any help?

TCPDF - http://www.tcpdf.org/

Thanks!

PS - If I use NGINX as a reverse proxy to apache I can still create the PDFs just fine.

**Comment by brianjking** [comment]
Bump... Please help!

**Comment by marcioAlmada** [comment]
Not related to phpbrew. Try `phpbrew config` to edit your php.ini file and log errors to somewhere you can see.
