### ISSUE TITLE
parallel compilation support - automatically detecting number of CPU cores for make -j {jobs}

### ISSUE THREAD

**Issue by olaulau** [phpbrew/phpbrew#477]
it would be great to add support for parallel compilation (make -j 2) :
- with a config switch
- automatically by detecting number of CPÜ cores

**Comment by marcioAlmada** [comment]
PR welcome. I usually just pass `-j8` manually or `-j4` when I'm compiling more than on PHP at same time.

**Comment by morozov** [comment]
@marcioAlmada do you mean it's possible to pass `-j4` to `phpbrew install`? I don't see the `MakeTask` support any arguments.

**Comment by c9s** [comment]
It's defined in src/PhpBrew/Tasks/BuildTask.php:

src/PhpBrew/Tasks/BuildTask.php:        if ($makeJobs = $this->options->{'jobs'}) {
src/PhpBrew/Tasks/BuildTask.php-            $cmd->addArg("-j{$makeJobs}");
src/PhpBrew/Tasks/BuildTask.php-        }

**Comment by morozov** [comment]
@c9s, thanks.

**Comment by larsnystrom** [comment]
For reference, here's how to use the `jobs` argument:

    phpbrew install --jobs=4 5.5 +default

On a somewhat modern linux version you can get the number of processing units running `nproc`.

**Comment by marcioAlmada** [comment]
I find it a bit invasive to automatically use all resources. Thoughts?

**Comment by olaulau** [comment]
when you play a game, it tries to use all cpu. same when you encode a movie.
a long time ago, when we had only 1 core, it used it 100%.
if you want to use your computer while compiling, just play with process priorities.

**Comment by marcioAlmada** [comment]
Sorry, your "game" logic is just unnecessary lawyering. No sane build tool will try to use all your resources **by default**, that's why we have `--jobs`|`-j` option almost everywhere.

A PR with some optional config switch through a `$PHPBREW_JOBS` env variable is welcome though.

**Comment by marcioAlmada** [comment]
The following should be good enough and is on README:

```bash
phpbrew install -j $(nproc) 5.4.0 +default
```
