### ISSUE TITLE
Standardise auto-swapping of PHP versions

### ISSUE THREAD

**Issue by jacobbednarz** [phpbrew/phpbrew#481]
Hey,
I see there are a couple of PHP version managers out there and before this becomes an issue I would like to propose we look at standardising how auto-switching can work across the different solutions.

The idea would be that despite which PHP version manager a developer was using a single `.php-version` file would account for all of them and be able to be committed to a project. Here are some of the specifications I think would be a good start.
#### .php-version file

The file itself should contain a single string such as `5.6.22`. Acceptable values would include: 
- `5.6` (which would use the latest version for the 5.6 release that you have locally)
- `5.6-RC4` (which would use the RC4 of the 5.6 release)
#### Project specific

If a user puts a `.php-version` inside of a project, upon changing into that directory the PHP version is updated to use the requested version.
#### Global

Should a user want to change the global PHP version used, they can add a `.php-version` file to `$HOME` and it would be applied when a local `.php-version` could not be found.

What are your thoughts?

**Comment by marcioAlmada** [comment]
What are the other php version managers?

**Comment by jacobbednarz** [comment]
Here are some of the ones I've come across:

- https://github.com/wilmoore/php-version
- https://github.com/CHH/phpenv
- https://github.com/phpenv/phpenv

Not sure how many of these allow a central configuration but it would be good to start somewhere!

**Comment by kevindperezm** [comment]
I support this. It'll be a great feature for developers that need to make sure they write code that is going to run in their production environments. Also, can we check for required php version inside `composer.json` file'? I know that `composer` is not being used everywhere, but it'll be nice if we can detect the php version declared in that file and autoswap to it.

**Comment by roman-1983** [comment]
+1 this is a very useful feature for a bunch of developers and web-development agencies! ;-)

Auto-Swapping to a related php-version from the `composer.json` is not so good, because `composer.json` just requires the lowest-needed version of php. A better way would be to use a `.php-version`-file as jacob mentioned.

**Comment by DavidBruchmann** [comment]
@kevindperezm as far as I see it's only for phpbrew the script.
The intention I understood different.
