### ISSUE TITLE
`pear: command not found`

### ISSUE THREAD

**Issue by tejasmanohar** [phpbrew/phpbrew#482]
my `pear` command isn't found. i am on mac os x 10.10 on a fairly new macbook and i use homebrew + phpbrew btw. i have 5.6.6 + defaults installed via phpbrew. what should i do? $PATH issue?

**Comment by marcioAlmada** [comment]
Hi, whats the output of `echo $PATH`?

BTW, I totally recommend you to abandon PEAR as it has too many issues. Suggestion: http://www.phptherightway.com/#handling-pear-dependencies-with-composer

**Comment by tejasmanohar** [comment]
It's all fixed.
