### ISSUE TITLE
Older PHP minor versions are on different links now

### ISSUE THREAD

**Issue by jasdeepkhalsa** [phpbrew/phpbrew#483]
I cannot seem to download a specific PHP version `5.4.7`. I used:

`phpbrew install 5.4.7 +default+dbs +openssl +soap +iconv +curl +apxs2=/usr/bin/apxs2`

And got:
```
===> phpbrew will now build 5.4.7
===> Loading and resolving variants...
Checking distribution checksum...
Checksum mismatch: d41d8cd98f00b204e9800998ecf8427e != 9cd421f1cc8fa8e7f215e44a1b06199f
Re-Downloading...
===> Downloading from http://www.php.net/get/php-5.4.7.tar.bz2/from/this/mirror
--2015-04-14 13:41:25--  http://www.php.net/get/php-5.4.7.tar.bz2/from/this/mirror
Resolving www.php.net (www.php.net)... 72.52.91.14, 2a02:cb41::7
Connecting to www.php.net (www.php.net)|72.52.91.14|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: http://php.net/get/php-5.4.7.tar.bz2/from/this/mirror [following]
--2015-04-14 13:41:25--  http://php.net/get/php-5.4.7.tar.bz2/from/this/mirror
Resolving php.net (php.net)... 72.52.91.14, 2a02:cb41::7
Reusing existing connection to www.php.net:80.
HTTP request sent, awaiting response... 404 Not Found
2015-04-14 13:41:26 ERROR 404: Not Found.

Command failed: wget --no-check-certificate -c  -O/home/{user}/.phpbrew/distfiles/php-5.4.7.tar.bz2 http://www.php.net/get/php-5.4.7.tar.bz2/from/this/mirror returns
```

Going to `http://www.php.net/get/php-5.4.7.tar.bz2/from/this/mirror` I find that it's asking me to pick a mirror, but whichever mirror I select, none of them host the file.

In the end I manually went to http://php.net/releases/, found my release and saved it to `/home/{user}/.phpbrew/distfiles/`. This was the `.tar.bz2` version.

There should therefore be:

1. A mirror selected automatically (if that's not already the case?)
2. A better failover mechanism if no mirror hosts the file e.g. going direct to the releases like I did
3. If all else fails, some instructions to help install it manually like I did

**Comment by marcioAlmada** [comment]
could not reproduce here :(

**Comment by jasdeepkhalsa** [comment]
Okay I'll test it from a different network location in case the issue was with a local network - but what happens when you go to: http://www.php.net/get/php-5.4.7.tar.bz2/from/this/mirror ? For me it goes to the page "Download not found" with a list of alternative mirrors

**Comment by marcioAlmada** [comment]
ok, it looks like that older v5.4 minor versions are now with a different link :scream:

The good news is that the latest versions are still on the same place. So, for now, you can go with:

    phpbrew install 5.4 +default+dbs +openssl +soap +iconv +curl +apxs2=/usr/bin/apxs2

**Comment by jasdeepkhalsa** [comment]
The problem is that I needed the exact version 5.4.7 because that's the one on the server that I'm writing code for.

So best approach for others is to manually go to http://php.net/releases/, and save the release to /home/{user}/.phpbrew/distfiles/ :(

**Comment by shinnya** [comment]
@c9s @marcioAlmada 
I've fixed the reported issue of missing download urls in https://github.com/phpbrew/phpbrew/commit/02c22270d19a3cfdbf10d020764304fce8e774cf (feature/distribution_url).
How do you think this change? If it looks good to you, I want to merge the branch to develop branch.

**Comment by marcioAlmada** [comment]
works for me @shinnya

**Comment by marcioAlmada** [comment]
moved to develop

**Comment by c9s** [comment]
I like the changes :+1:

**Comment by shinnya** [comment]
Thank you for your reply! I'll merge this change!

**Comment by jasdeepkhalsa** [comment]
Looks good :) Will make the codebase a bit more flexible in case of future changes
