### ISSUE TITLE
phpbrew doesn't know 5.5.24, 5.5.23 and 5.5.21

### ISSUE THREAD

**Issue by larsnystrom** [phpbrew/phpbrew#486]
After running `phpbrew update` I still can't install PHP 5.5.24 and some other versions.

I've run `phpbrew self-update` and my current phpbrew version is 1.18.4.

**Comment by marcioAlmada** [comment]
Try: `phpbrew update --official`

**Comment by marcioAlmada** [comment]
Note to myself: migrate `--official` to the new json endpoint
