### ISSUE TITLE
can't install php versions

### ISSUE THREAD

**Issue by cgfix** [phpbrew/phpbrew#490]
this seems broken. When I try to install a version of php, I get this 404 errors

**Comment by c9s** [comment]
which version you were trying to install?

**Comment by floscom** [comment]
===> phpbrew will now build 5.2.12
===> Loading and resolving variants...
===> Downloading from http://www.php.net/get/php-5.2.12.tar.bz2/from/this/mirror
[==================================================================] 184.00/184.                                  00B 100%
Redirecting to http://php.net/get/php-5.2.12.tar.bz2/from/this/mirror
The requested URL returned error: 404

**Comment by floscom** [comment]
done - phpbrew install http://museum.php.net/php5/php-5.2.17.tar.bz2 sorry

**Comment by cgfix** [comment]
So you have to include the actual URL in the command now?
Because phpbrew install [version#] does not work for any version.

also, lookup-prefix is not recognized either?

Jon Clawson
mail@jonclawson.com
317-572-8491

Florian Narr wrote:

**Comment by cgfix** [comment]
after I run this command, it fails to configure.

Jon Clawson
mail@jonclawson.com
317-572-8491

Florian Narr wrote:

**Comment by floscom** [comment]
i am using a debian linux and have installed the newest openssl version and
this is a problem for old php versions. have a look at the log file of
phpbrew - i have had to change the openssl c file and forced the openssl3
usage.

cgfix <notifications@github.com> schrieb am Mi., 22. Apr. 2015 um 19:05 Uhr:
