### ISSUE TITLE
Difficulties installing PHP 5.2.17

### ISSUE THREAD

**Issue by dooug** [phpbrew/phpbrew#492]
Not seeing the old known versions:
```
vagrant@cosmo:~$ phpbrew --version
phpbrew - 1.18.5
cliframework core: 1.10.0
vagrant@cosmo:~$ phpbrew known
5.6: 5.6.8, 5.6.7, 5.6.6, 5.6.5, 5.6.4, 5.6.3, 5.6.2, 5.6.1 ...
5.5: 5.5.24, 5.5.23, 5.5.22, 5.5.21, 5.5.20, 5.5.19, 5.5.18, 5.5.17 ...
5.4: 5.4.40, 5.4.39, 5.4.38, 5.4.37, 5.4.36, 5.4.35, 5.4.34, 5.4.33 ...
5.3: 5.3.29, 5.3.28, 5.3.27, 5.3.26, 5.3.25, 5.3.24, 5.3.23, 5.3.22 ...
You can run `phpbrew update` to get a newer release list.
vagrant@cosmo:~$ phpbrew known --old
5.6: 5.6.8, 5.6.7, 5.6.6, 5.6.5, 5.6.4, 5.6.3, 5.6.2, 5.6.1 ...
5.5: 5.5.24, 5.5.23, 5.5.22, 5.5.21, 5.5.20, 5.5.19, 5.5.18, 5.5.17 ...
5.4: 5.4.40, 5.4.39, 5.4.38, 5.4.37, 5.4.36, 5.4.35, 5.4.34, 5.4.33 ...
5.3: 5.3.29, 5.3.28, 5.3.27, 5.3.26, 5.3.25, 5.3.24, 5.3.23, 5.3.22 ...
You can run `phpbrew update` to get a newer release list.
```

Trying to install 5.2.17 fails:
```
vagrant@cosmo:~$ phpbrew install http://museum.php.net/php5/php-5.2.17.tar.bz2 +default
===> phpbrew will now build 5.2.17
===> Loading and resolving variants...
Checking distribution checksum...
Checksum matched:
===> Distribution file was successfully extracted, skipping...
Found existing build.log, renaming it to /home/vagrant/.phpbrew/build/php-5.2.17/build.log.1429831251
===> Configuring 5.2.17...

Use tail command to see what's going on:
   $ tail -F /home/vagrant/.phpbrew/build/php-5.2.17/build.log

Configure failed. 1
```

**Comment by shinnya** [comment]
We need more information to understand and resolve your problem. Can you describe your error in more detail?

**Comment by shinnya** [comment]
I tried your command and the following is my result:

```bash
% phpbrew install http://museum.php.net/php5/php-5.2.17.tar.bz2 +default
===> phpbrew will now build 5.2.17
===> Loading and resolving variants...
===> Downloading from http://museum.php.net/php5/php-5.2.17.tar.bz2
[==================================================================] 8.67/8.67MB 100%
===> /home/shinnya/.phpbrew/distfiles/php-5.2.17.tar.bz2 downloaded.
===> Extracting /home/shinnya/.phpbrew/distfiles/php-5.2.17.tar.bz2 to /home/shinnya/.phpbrew/tmp/php-5.2.17
===> Moving /home/shinnya/.phpbrew/tmp/php-5.2.17 to /home/shinnya/.phpbrew/build/php-5.2.17
===> Configuring 5.2.17...


Use tail command to see what's going on:
   $ tail -F /home/shinnya/.phpbrew/build/php-5.2.17/build.log



PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Configure failed. 1' in /home/shinnya/repos/mine/phpbrew.git/src/PhpBrew/Tasks/ConfigureTask.php:124
Stack trace:
#0 /home/shinnya/repos/mine/phpbrew.git/src/PhpBrew/Command/InstallCommand.php(355): PhpBrew\Tasks\ConfigureTask->configure(Object(PhpBrew\Build), Object(GetOptionKit\OptionResult))
#1 [internal function]: PhpBrew\Command\InstallCommand->execute('http://museum.p...', '+default')
#2 /home/shinnya/repos/mine/phpbrew.git/vendor/corneltek/cliframework/src/CLIFramework/CommandBase.php(658): call_user_func_array(Array, Array)
#3 /home/shinnya/repos/mine/phpbrew.git/vendor/corneltek/cliframework/src/CLIFramework/Application.php(282): CLIFramework\CommandBase->executeWrapper(Array)
#4 /home/shinnya/repos/mine/phpbrew.git/bin/phpbrew(21): CLIFramework\Application->run(Array)
#5 {main}
  thrown in /home/shinnya/repos/mine/phpbrew.git/src/PhpBrew/Tasks/ConfigureTask.php on line 124
```

I found the following error message in build.log:

```
configure: error: Please reinstall libmhash - I cannot find mhash.h
```

After installing `libmhash`, I came across the following error:

```bash
$ phpbrew install -j $(nproc ) http://museum.php.net/php5/php-5.2.17.tar.bz2 +default

/home/shinnya/.phpbrew/build/php-5.2.17/ext/dom/node.c: In function ‘dom_canonicalization’:
/home/shinnya/.phpbrew/build/php-5.2.17/ext/dom/node.c:1953:21: error: dereferencing pointer to incomplete type
    ret = buf->buffer->use;
                     ^
In file included from /home/shinnya/.phpbrew/build/php-5.2.17/main/php.h:38:0,
                 from /home/shinnya/.phpbrew/build/php-5.2.17/ext/dom/node.c:26:
/home/shinnya/.phpbrew/build/php-5.2.17/ext/dom/node.c:1955:40: error: dereferencing pointer to incomplete type
     RETVAL_STRINGL((char *) buf->buffer->content, ret, 1);
                                        ^
/home/shinnya/.phpbrew/build/php-5.2.17/Zend/zend_API.h:472:14: note: in definition of macro ‘ZVAL_STRINGL’
   char *__s=(s); int __l=l;  \
              ^
/home/shinnya/.phpbrew/build/php-5.2.17/ext/dom/node.c:1955:5: note: in expansion of macro ‘RETVAL_STRINGL’
     RETVAL_STRINGL((char *) buf->buffer->content, ret, 1);
     ^
Makefile:565: recipe for target 'ext/dom/node.lo' failed
make: *** [ext/dom/node.lo] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by shinnya** [comment]
The last error is the well-known `libxml2` compatibility issue and we can fix it by applying a patch.
You can download a patch from https://code.google.com/p/php52-backports/issues/detail?id=16.
Then applys it:

```bash
$ cd ~/.phpbrew/build/php-5.2.17/
$ patch -p0 < ~/Downloads/libxml29_compat.patch 
patching file ext/dom/node.c
Hunk #1 succeeded at 1950 (offset 55 lines).
patching file ext/dom/documenttype.c
Hunk #1 succeeded at 215 (offset 10 lines).
patching file ext/simplexml/simplexml.c
Hunk #1 succeeded at 1343 (offset -74 lines).
```
After that, you might build PHP 5.2 successfully.

**Comment by marcioAlmada** [comment]
I'm closing this since php 5.2 should be dead already. If you still want/need to install php 5.2 (sorry for you) it won't be easy because most distro's build toolchains will offer trouble.

People still can try to build it, but we should end the php 5.2 helpline and close php 5.2 issues instantly. Thoughts?

**Comment by c9s** [comment]
Agree, I documented in the wiki page: https://github.com/phpbrew/phpbrew/wiki/Troubleshooting

**Comment by sebastientaggart** [comment]
Sorry to comment on a closed ticket, but does anyone know how to continue the 5.2.17 install after applying the patch?

```phpbrew install http://museum.php.net/php5/php-5.2.17.tar.bz2 +default``` of course overwrites the patched 5.2.17 directory in .phpbrew/build.  ```phpbrew list``` and ```phpbrew known``` don't show 5.2.17, and running ```phpbrew install 5.2.17``` or ```phpbrew install php-5.2.17``` both error out with "Exception: Version 5.2.17 not found".

So I guess put more simply: how do I do a phpbrew install from a version of PHP already in ~/.phpbrew/build?

(btw I agree that 5.2 should die in a fire, but unfortunately I'm stuck trying to debug an old application, so no choice).

**Comment by XedinUnknown** [comment]
Of course PHP 5.2.17 needs to be supported! WP runs on it! And yes, it should absolutely die in a fire, but what to do? This is supposed to be a tool for easy testing with different PHP versions! I think it's particularly this kind of edge-cases that would make this an absolutely indispensable tool Please, add support for it. Me and millions of developers who have to deal with WP will be so grateful!

**Comment by marcioAlmada** [comment]
Supporting php 5.2 is out of scope. You can build PHP 5.2 if you really hate yourself, but you will need to downgrade a lot of OS dependencies. Most distros won't let you install legacy packages that php depends on to build, you will get a ton of version conflicts and, in addition, you will be running a PHP version that is already full of non patched vulnerabilities.

So, no. Answering issues is already time consuming enough. We won't give support to build extremely outdated software through github issues.

**Comment by XedinUnknown** [comment]
I didn't mean "through PHP issues". I meant, maybe build into the software the ability do apply the necessary patches, etc. But if no, then... I'll have to use Ansible to provision all that ridiculous mess of installing 5.2 :(

**Comment by uglide** [comment]
This patch helps to compile php 5.2.17 https://mail.gnome.org/archives/xml/2012-August/txtbgxGXAvz4N.txt

**Comment by baronvertigovongrahamthefirstofsealand** [comment]
I have to agree, you must support older version if you want this tool to be relevant. Limiting it to versions of PHP that arent particularly different to each other defeats the point.
