### ISSUE TITLE
Undefined imagecreatefromjpeg function

### ISSUE THREAD

**Issue by Anahkiasen** [phpbrew/phpbrew#494]
I installed PHP 5.6 with the `+gd` variant, when I prompt `phpinfo()` the GD variant is there and enabled, however trying to call `imagecreatefromjpeg` says the function is undefined. I'm on OSX Yosemite with the Homebrew lookups and gd installed in Homebrew, is there any particular command I need to run?

**Comment by shinnya** [comment]
@Anahkiasen 
Hi. Could you please paste the result by the following command:

```bash
$ php -r 'var_dump(gd_info());'
```

According to http://php.net/manual/en/function.imagecreatefromjpeg.php#70832, if jpeg isn't supported on your PHP, you can't call `imagecreatefromjpeg`.

**Comment by Anahkiasen** [comment]
```
array(11) {
  'GD Version' =>  string(26) "bundled (2.1.0 compatible)"
  'FreeType Support' =>  bool(false)
  'T1Lib Support' =>  bool(false)
  'GIF Read Support' =>  bool(true)
  'GIF Create Support' =>  bool(true)
  'JPEG Support' =>  bool(false)
  'PNG Support' =>  bool(true)
  'WBMP Support' =>  bool(true)
  'XPM Support' =>  bool(false)
  'XBM Support' =>  bool(true)
  'JIS-mapped Japanese Font Support' =>  bool(false)
}
```

**Comment by shinnya** [comment]
@Anahkiasen 
Thank you! Since JPEG Support seems to be off, you should enable it. Mac OS X has a known issue on building PHP with GD extension, so try to install PHP with the following options (specify jpeg dir):

```bash
$ phpbrew install php-5.6.4 +default \ -- --with-libdir=lib/x86_64-linux-gnu \ --with-gd=shared \ --enable-gd-natf \ --with-jpeg-dir=/usr \ --with-png-dir=/usr
```

**Comment by Anahkiasen** [comment]
Running the following command I get this error during Configuring extensions:

```
configure: error: Cannot find OpenSSL's libraries
```

```
Configuring extensions
checking size of long... (cached) 8
checking size of int... (cached) 4
checking for int32_t... yes
checking for uint32_t... yes
checking for sys/types.h... (cached) yes
checking for inttypes.h... (cached) yes
checking for stdint.h... (cached) yes
checking for string.h... (cached) yes
checking for stdlib.h... (cached) yes
checking for strtoll... yes
checking for atoll... yes
checking for strftime... (cached) yes
checking which regex library to use... php
checking whether to enable LIBXML support... yes
checking libxml2 install dir... /usr
checking for xml2-config path... /usr/bin/xml2-config
checking whether libxml build works... yes
checking for OpenSSL support... yes
checking for Kerberos support... no
checking whether to use system default cipher list instead of hardcoded value... no
checking for DSA_get_default_method in -lssl... no
checking for X509_free in -lcrypto... yes
checking for pkg-config... /usr/local/bin/pkg-config
configure: error: Cannot find OpenSSL's libraries
```

**Comment by shinnya** [comment]
Hi @Anahkiasen. I think you should specify openssl option explicitly. Add `+openssl=/usr` to the previous options and run `phpbrew install` again.

**Comment by Anahkiasen** [comment]
Hm same result it seems

**Comment by shinnya** [comment]
Uhm... I don't use phpbrew on Mac OS X and I have no idea. Since openssl problem isn't a matter of concern, let's ignore it for now.
I suggested the above options to show how to give `--with-jpeg-dir` option, so you can use your current options which succeeded in running `phpbrew install`. The combination of your current options and `--with-jpeg-dir` option will fix this issue.

**Comment by c9s** [comment]
I think you can install gd extension separately by running the command below?

    $ phpbrew install gd2 -- --with-libdir=lib/x86_64-linux-gnu --with-gd=shared  --enable-gd-natf --with-jpeg-dir=/usr \ --with-png-dir=/usr

**Comment by c9s** [comment]
Hi @Anahkiasen you don't have to recompile php, please take a look at this entry: https://github.com/phpbrew/phpbrew/wiki/Cookbook#setting-up-prefered-lookup-prefix

**Comment by c9s** [comment]
Also this one: https://github.com/phpbrew/phpbrew/wiki/Troubleshooting#i-cant-install-extension-why

**Comment by c9s** [comment]
Homebrew prefix lookup should already be improved, please try self-update and install that again.
