### ISSUE TITLE
Hyphened directory names treated as variants

### ISSUE THREAD

**Issue by etki** [phpbrew/phpbrew#495]
Hi.
I've stumbled upon error with missing `gmp.h` (as described in #123): the headers file was located in `/usr/include/x86_64-linux-gnu/` rather than just `/usr/include/`. First thing i've tried was to add `+gmp=/usr/include/x86_64-linux-gnu` variant, but phpbrew halted because it treated `-linux` part as another variant.

**Comment by c9s** [comment]
Hi @etki 

Can you provide the complete command for us to add failing tests? Thanks

**Comment by marcioAlmada** [comment]
confirmed, I'm about to push a fix

**Comment by etki** [comment]
@c9s Hi, i'm afraid that docker container is already wiped away, but it was something like

    phpbrew install --name 5.3 5.3.29 +gmp=/usr/include/x86_64-linux-gnu

**Comment by c9s** [comment]
Thanks @marcioAlmada++

**Comment by shinnya** [comment]
@marcioAlmada++

**Comment by marcioAlmada** [comment]
Fixed `phpbrew self-update`

**Comment by etki** [comment]
@marcioAlmada thank you
