### ISSUE TITLE
Removing an installation + autocomplete

### ISSUE THREAD

**Issue by sagikazarmark** [phpbrew/phpbrew#496]
Executing the following command does not work:

`$ phpbrew remove 5.6.6`

It requires a specific directory, not just the version:

`$ phpbrew remove php-5.6.6`

**Comment by c9s** [comment]
Since users may have different build with the same version, the removing operation should specify the full qualified name to avoid confusion. :)

**Comment by sagikazarmark** [comment]
I see. But shouldn't the autocomplete complete the dir name instead of the
version?

**Comment by c9s** [comment]
well, it should. the completion works for me.

if it does not complete dir names for you, you might need to re-generate the zsh completion script and reload it.

https://github.com/phpbrew/phpbrew/blob/develop/src/PhpBrew/Command/RemoveCommand.php#L20
https://github.com/phpbrew/phpbrew/blob/develop/src/PhpBrew/Config.php#L190

**Comment by sagikazarmark** [comment]
I am using the bash autocompletion script. I've just updated it and it got even worse. Not it does not even complete the installed versions, but lists the files/folders in the current directory. See screenshot.
I am using the latest version from master branch (both the executable and the completion script).

![mark mark-nb -tmp-test_006](https://cloud.githubusercontent.com/assets/1226384/7444542/5cf21c44-f187-11e4-8bdf-b2e4f664f484.png)

**Comment by c9s** [comment]
looks like the completion is not hooked to your command, how do you generate the script and load it? can you show me the commands?

[Sent from iPhone]

**Comment by sagikazarmark** [comment]
I don't generate it. I download it from the repo and put it into `/etc/bash_completion.d/`

**Comment by c9s** [comment]
OK, I think that version is hand-written completion script, we have an auto-generated one:

https://github.com/phpbrew/phpbrew/blob/develop/completion/bash/_phpbrew

Please download it and retry again :)

**Comment by sagikazarmark** [comment]
You mean the one from the master branch? At least you updated that one.  I tried the one from both the master and the develop branch. No luck.

**Comment by marcioAlmada** [comment]
Hi, I authored the hand written completion file in the past but it got behind after many releases. So now I'm just generating it through the *cli framework* support https://github.com/phpbrew/phpbrew/blob/develop/Makefile#L42. The version name completion needs to be implemented again, hence why this is still on develop branch only.

**Comment by marcioAlmada** [comment]
@c9s help needed. Completion for `phpbrew install|switch|remove` are back in place, but completion for `phpbrew ext intall|enable|disable|show...` is not working. Am I missing something?

**Comment by marcioAlmada** [comment]
BTW, this cli completion generator is a killer feature!

**Comment by c9s** [comment]
@marcioAlmada only for bash completion? or both zsh and badh?

**Comment by marcioAlmada** [comment]
@c9s only bash AFAIK

**Comment by c9s** [comment]
I just tried, and found out command name, option name completion works, but the argument completion seems not working.

here is the meta command of the completion result generator:

    php bin/phpbrew meta --bash extension.install arg 0 suggestions

**Comment by c9s** [comment]
@marcioAlmada  OK, i think it might be a bug of completing command arguments.

currently we only support `valid-values`, not `suggestions`:
https://github.com/phpbrew/phpbrew/blob/develop/completion/bash/_phpbrew#L2238

and here:
https://github.com/phpbrew/phpbrew/blob/develop/completion/bash/_phpbrew#L2258

it should call `..._complete_extension_install`, however `..._complete_extension_install` was not generated.

**Comment by c9s** [comment]
bash completion debug tips:

```
echo $var > bash.debug
```

And `tail -f bash.debug` in another shell to see the debug messages.

**Comment by c9s** [comment]
I have a project deadline before Friday, so I have to back to work. XD good luck

**Comment by c9s** [comment]
I think it should work now, I will roll out a patch release of cliframework today.

**Comment by c9s** [comment]
`phpbrew remove ...` completion now works too.

**Comment by c9s** [comment]
@marcioAlmada we need to run `phprelease` to run the steps defined in `phprelease.ini`, does it still work? since you moved the commands into Makefile, could you also add a MakeStep into `phprelease`when you find some time? Thanks ;)

**Comment by marcioAlmada** [comment]
Thanks!

**Comment by marcioAlmada** [comment]
> since you moved the commands into Makefile, could you also add a MakeStep into phpreleasewhen you find some time?

Yes sure ^^

**Comment by marcioAlmada** [comment]
Ok more debug info. The trace for `php bin/phpbrew meta --bash extension.install arg 0 suggestions` is resulting in:

```
#groups
declare -A groups
declare -A labels
groups[5.6]="5.6.8 5.6.7 5.6.6 5.6.5 5.6.4 5.6.3 5.6.2 5.6.1 5.6.0"
groups[5.5]="5.5.24 5.5.23 5.5.22 5.5.21 5.5.20 5.5.19 5.5.18 5.5.17 5.5.16 5.5.15 5.5.14 5.5.13 5.5.12 5.5.11 5.5.10 5.5.9 5.5.8 5.5.7 5.5.6 5.5.5 5.5.4 5.5.3 5.5.2 5.5.1 5.5.0"
groups[5.4]="5.4.40 5.4.39 5.4.38 5.4.37 5.4.36 5.4.35 5.4.34 5.4.33 5.4.32 5.4.31 5.4.30 5.4.29 5.4.28 5.4.27 5.4.26 5.4.25 5.4.24 5.4.23 5.4.22 5.4.21 5.4.20 5.4.19 5.4.18 5.4.17 5.4.16 5.4.15 5.4.14 5.4.13 5.4.12 5.4.11 5.4.10 5.4.9 5.4.8 5.4.7 5.4.6 5.4.5 5.4.4 5.4.3 5.4.2 5.4.1 5.4.0"
groups[5.3]="5.3.29 5.3.28 5.3.27 5.3.26 5.3.25 5.3.24 5.3.23 5.3.22 5.3.21 5.3.20 5.3.19 5.3.18 5.3.17 5.3.16 5.3.15 5.3.14 5.3.13 5.3.12 5.3.11 5.3.10 5.3.9 5.3.8 5.3.7 5.3.6 5.3.5"
labels[5.6]="PHP 5.6"
labels[5.5]="PHP 5.5"
labels[5.4]="PHP 5.4"
labels[5.3]="PHP 5.3"
```

The nested `ext install` command is being arg completed with the outermost `install` command.

**Comment by c9s** [comment]
@marcioAlmada seems like it's expected? no? bash completion doesn't support sections.

**Comment by marcioAlmada** [comment]
You don't have a formal section support in bash, but the manual completion script handled this ambiguity with: https://github.com/phpbrew/phpbrew/blob/8de802454666d913d61ca8030e703f6b1cbca4d7/completion/bash/_phpbrew#L30-L37

**Comment by marcioAlmada** [comment]
```bash
    case "${prev}" in
        install)
            case "${prev_prev}" in
                ext)
                # list available extensions
                opts="$(cd $PHPBREW_HOME/build/$PHPBREW_PHP/ext/ && ls -d */ | cut -d '/' -f 1)"
                COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
                return 0
                ;;
            esac
```

I'm not sure how hard it is to generate a completion file to handle this situation ^ though.

**Comment by c9s** [comment]
Got it, almost forgot the extension install command should be completed with extension name.

**Comment by c9s** [comment]
I think the bug is inside the meta command:

```
php bin/phpbrew meta --bash app.extension.install arg 0 suggestions
```

the above command should call the suggestion callback defined in ExtensionInstallCommand class.

**Comment by marcioAlmada** [comment]
I still get the same output as https://github.com/phpbrew/phpbrew/issues/496#issuecomment-101930270

**Comment by c9s** [comment]
I submitted another fix for the meta command. please give it a retry.

**Comment by c9s** [comment]
Fixed

**Comment by marcioAlmada** [comment]
Awesome! Works here \o/

I'm using `corneltek/cliframework:dev-master` as a composer dependency temporarily, please ping me when you release next minor.

**Comment by c9s** [comment]
CLIFramework 2.5.2 was released, and this one seems fixed?

**Comment by marcioAlmada** [comment]
Fixed `phpbrew self-update`
