### ISSUE TITLE
Adding --with-libedit to configure option affects the behaviour of readline() function.

### ISSUE THREAD

**Issue by shinnya** [phpbrew/phpbrew#497]
`readline` function implemented with libedit can't stop echoing user input. The code below should not display user input.

```php
<?php    
`/bin/stty -echo`;    
$line = readline('> ');    
var_dump($line);    
`/bin/stty echo`;
```
This code works with libreadline, but doesn't work with libedit. As far as I searched, `--with-libedit` causes this issue.

Accordint to PHP doc, we can choose either `--with-readline` or `--with-libedit` for enabling readline, but the two options are given in phpbrew at the same time when `+readline` variant is enabled and phpbrew can find the headers of `readline` and `libedit`.
See https://github.com/phpbrew/phpbrew/blob/3b8e0cd7bf50f2d717ae9bddd2c97a2eebe1d445/src/PhpBrew/VariantBuilder.php#L229.

Is this code a bug? I think we should give either of them.

**Comment by shinnya** [comment]
You can check which library you use by the following command:

```bash
$ php -i | grep EditLine
```

If you get no output, you're using libreadline.

**Comment by c9s** [comment]
CLIFramework 2.5.2 was released, which shall contain your commits. :)

**Comment by c9s** [comment]
Fixed to prefer readline over editline
