### ISSUE TITLE
5.4.40 does not exist in /root/.phpbrew/php directory

### ISSUE THREAD

**Issue by RudyJessop** [phpbrew/phpbrew#499]
Just like the title of this issue states. I am running `phpbrew use 5.4.40` and i am getting that error. When i navigate to the mentioned directory i see `php-5.4.40` I am stuck here and need help on this issue.

Thanks in advance

**Comment by shinnya** [comment]
@RudyJessop Hi. You can fetch a new release list of PHP by `phpbrew update` command, so could you try this?

**Comment by RudyJessop** [comment]
No luck. still getting the same issue

**Comment by shinnya** [comment]
Oh, that looks strange. Normally, `$PHPBREW_ROOT` is the home directory of an user. I guess that you might manually set `$PHPBREW_ROOT` in your `.bashrc` or `.zshrc`. What is it like?

**Comment by c9s** [comment]
Can you print your ~/.phpbrew/init file?

also, we need to kown tge user id you install or switch php.

**Comment by c9s** [comment]
If you installed php as root and you want to use the installed php as a normal user, you need to configure your PHPBREW_ROOT and PHPBREW_HOME path, the `PHPBREW_ROOT` should be something pointing to `/root/.phpbrew....`

**Comment by c9s** [comment]
I will close this. if you still have the problem, please bump this issue up, I will reopen this for support.

**Comment by RudyJessop** [comment]
Sorry @c9s i just saw your response on twitter and github. I'm using a vagrant box so i installed it on the normal user "vagrant". Are you suggesting to install it on the root user?

**Comment by c9s** [comment]
Hi @RudyJessop , never mind. :) we just need to clean up some issues that are not updated or we will feel stressful =p

it depends, if you want to share the installed php cross different users, you can install some php by root user and then users can separate the settings of PHPBREW_ROOT and PHPBREW_HOME to use the shared PHP(s).

if you just want to have some php to run on personal machine, you can just install the php by normal user.

**Comment by RudyJessop** [comment]
I have already set `$PHPBREW_ROOT` in `vagrant` user `.bashrc` file and its giving me the source from the `/home/vagrant`. I am guessing if i point `$PHPBREW_ROOT` to `/root/.phpbrew/bashrc` and `$PHPBREW_HOME` to `/home/vagrant` would that solve my issue.

**Comment by c9s** [comment]
Hi,

The `$PHPBREW_ROOT` is used for building php and use installed php, thus you need to ensure that `$PHPBREW_ROOT` points to somewhere that contains `build`, `php` directories.   `$PHPBREW_HOME` is used to store the version settings, it's used to read the bashrc inside  `.phpbrew` by default.

**Comment by RudyJessop** [comment]
Ok i fixed `$PHPBREW_ROOT` and `$PHPBREW_HOME` and i'm getting this error

![screen shot 2015-05-19 at 2 47 27 pm](https://cloud.githubusercontent.com/assets/700851/7711123/799319dc-fe36-11e4-8736-d47a36cf1338.png)

**Comment by c9s** [comment]
Hi @RudyJessop, please don't use `sudo` to execute phpbrew, which makes an isolated environment for phpbrew, (neither PHPBREW_ROOT nor PHPBREW won't work for you)

**Comment by c9s** [comment]
If you want to install system-wide php, please take a look at the Cookbook page in our wiki: https://github.com/phpbrew/phpbrew/wiki/Cookbook#install-phpbrew-into-system-wide-environment

**Comment by RudyJessop** [comment]
if i don't use `sudo` i get this error tho `Exception: Directory is not writable: /home/vagrant/.phpbrew//distfiles`

**Comment by marcioAlmada** [comment]
Please drop your entire `~/.phpbrew` folder and start over again, you might have done something with sudo at some point and that's why your folder is not writable now. Also, try to use the default folder structures as much as possible, conventions are helpful :)

**Comment by c9s** [comment]
maybe we should print a warning message when users try to run phpbrew by root user...

**Comment by RudyJessop** [comment]
@marcioAlmada same issue. removed it from vagrant user and root. did every as a root user as outlined here https://github.com/phpbrew/phpbrew/wiki/Cookbook#install-phpbrew-into-system-wide-environment with the same error in the screen i showed 5 days ago.

**Comment by c9s** [comment]
@RudyJessop I think you're running vagrant user to install files under a path that requires root permission.  You can run phpbrew with root, but not using vagrant user with sudo.

I would suggesting you run `sudo -i` to changing the current user into root, and setup a phpbrew and install php(s) under that root, then your vagrant user use phpbrew_home to use the built php.
