### ISSUE TITLE
The updates of php-releases.json are late

### ISSUE THREAD

**Issue by morozov** [phpbrew/phpbrew#504]
The list of available releases in PhpBrew is usually a few days behind the official list. At the moment, the latest versions of PHP 5.4, 5.5 and 5.6 are unavailable in PhpBrew.

What if we draft a script which updates the JSON file with the most recent data from http://php.net/releases/feed.php? Then someone with the commit permissions could schedule it as their cron job.

**Comment by c9s** [comment]
fyi: for now you can run:

    phpbrew update --official 

to get the latest releases

**Comment by morozov** [comment]
@c9s thanks, it worked for me. But why isn't it the default behavior? Why manually maintain another list of releases?

**Comment by marcioAlmada** [comment]
@morozov see here: https://github.com/phpbrew/phpbrew/issues/376

The `--official` flag will simply be ignored on next version and the default behavior of `phpbrew update` will be to fetch the newly added php.net's json endpoint. That custom `php-releases.json` file won't be useful anymore.

**Comment by morozov** [comment]
@marcioAlmada cool, thank you for explanation.
