### ISSUE TITLE
command too long: phpbrew()

### ISSUE THREAD

**Issue by greensn0w** [phpbrew/phpbrew#506]
I just installed phpbrew on OSX (latest).
I'm using ZSH with zprezto.

When running `phpbrew` i get this output:

> phpbrew:262: command too long: phpbrew () {\n\tif [[ -e bin/phpbrew ]]\n\tthen\n\t\tBIN='bin/phpbrew' \n\telse\n\t\tBIN=$(which phpbrew) \n\tfi\n\tlocal exit_status\n\tlocal short_option\n\texport SHELL\n\tif [[ `echo $1 | awk 'BEGIN{FS=""}{print $1}'` = '-' ]]\n\tthen\n\t\tshort_option=$1 \n\t\tshift\n\telse\n\t\tshort_option="" \n\tfi\n\tcase $1 in\n\t\t(use) if [[ -z "$2" ]]\n\t\t\tthen\n\t\t\t\tif [[ -z "$PHPBREW_PHP" ]]\n\t\t\t\tthen\n\t\t\t\t\techo "Currently using system php"\n\t\t\t\telse\n\t\t\t\t\techo "Currently using $PHPBREW_PHP"\n\t\t\t\tfi\n\t\t\telse\n\t\t\t\tif [[ ! -d "$PHPBREW_ROOT/php/$2" && $2 =~ $PHPBREW_VERSION_REGEX ]]\n\t\t\t\tthen\n\t\t\t\t\t_PHP_VERSION="php-$2" \n\t\t\t\telse\n\t\t\t\t\t_PHP_VERSION=$2 \n\t\t\t\tfi\n\t\t\t\tNEW_PHPBREW_PHP_PATH="$PHPBREW_ROOT/php/$_PHP_VERSION" \n\t\t\t\tif [ -d $NEW_PHPBREW_PHP_PATH ]\n\t\t\t\tthen\n\t\t\t\t\tcode=$(command $BIN env $_PHP_VERSION) \n\t\t\t\t\tif [ -z "$code" ]\n\t\t\t\t\tthen\n\t\t\t\t\t\texit_status=1 \n\t\t\t\t\telse\n\t\t\t\t\t\teval $code\n\t\t\t\t\t\t__phpbrew_set_path\n\t\t\t\t\tfi\n\t\t\t\telse\n\t\t\t\t\techo "php version: $_PHP_VERSION not exists."\n\t\t\t\tfi\n\t\t\tfi ;;\n\t\t(cd-src) local SOURCE_DIR=$PHPBREW_HOME/build/$PHPBREW_PHP\n\t\t\tif [[ -d $SOURCE_DIR ]]\n\t\t\tthen\n\t\t\t\tcd $SOURCE_DIR\n\t\t\tfi ;;\n\t\t(switch) if [[ -z "$2" ]]\n\t\t\tthen\n\t\t\t\techo "Please specify the php version."\n\t\t\telse\n\t\t\t\t__phpbrew_reinit $2\n\t\t\tfi ;;\n\t\t(lookup-prefix) if [[ -z "$2" ]]\n\t\t\tthen\n\t\t\t\tif [[ -n $PHPBREW_LOOKUP_PREFIX ]]\n\t\t\t\tthen\n\t\t\t\t\techo $PHPBREW_LOOKUP_PREFIX\n\t\t\t\tfi\n\t\t\telse\n\t\t\t\texport PHPBREW_LOOKUP_PREFIX=$(__phpbrew_set_lookup_prefix $2)\n\t\t\t\techo $PHPBREW_LOOKUP_PREFIX\n\t\t\t\t__phpbrew_update_config\n\t\t\tfi ;;\n\t\t(install-pyrus) echo "Installing pyrus..."\n\t\t\tcd $PHPBREW_BIN && wget --no-check-certificate -c http://pear2.php.net/pyrus.phar -O pyrus && chmod +x pyrus && cd -\n\t\t\thash -r ;;\n\t\t(install-phpunit) echo "Installing phpunit..."\n\t\t\tcd $PHPBREW_BIN && wget --no-check-certificate -c https://phar.phpunit.de/phpunit.phar -O phpunit && chmod +x phpunit && cd -\n\t\t\thash -r ;;\n\t\t(install-composer) echo "Installing composer..."\n\t\t\tcd $PHPBREW_BIN && wget --no-check-certificate -c http://getcomposer.org/composer.phar -O composer && chmod +x composer && cd -\n\t\t\thash -r ;;\n\t\t(install-onion) echo "Installing onion..."\n\t\t\tcd $PHPBREW_BIN\n\t\t\twget --no-check-certificate -c https://raw.github.com/c9s/Onion/master/onion -O onion\n\t\t\tchmod +x onion\n\t\t\tcd -\n\t\t\thash -r ;;\n\t\t(cd) case $2 in\n\t\t\t\t(var) local chdir=$PHPBREW_ROOT/php/$PHPBREW_PHP/var ;;\n\t\t\t\t(etc) local chdir=$PHPBREW_ROOT/php/$PHPBREW_PHP/etc ;;\n\t\t\t\t(dist) local chdir=$PHPBREW_ROOT/php/$PHPBREW_PHP ;;\n\t\t\t\t(build) local chdir=$PHPBREW_ROOT/build/$PHPBREW_PHP ;;\n\t\t\t\t(*) echo "$2 not found"\n\t\t\t\t\treturn 0 ;;\n\t\t\tesac\n\t\t\techo "Switching to $chdir, run 'cd -' to go back."\n\t\t\tcd $chdir\n\t\t\treturn 0 ;;\n\t\t(fpm) if ! [[ -z $3 ]]\n\t\t\tthen\n\t\t\t\t_PHP_VERSION=$3 \n\t\t\telse\n\t\t\t\t_PHP_VERSION=${PHPBREW_PHP} \n\t\t\tfi\n\t\t\tmkdir -p -p ${PHPBREW_ROOT}/php/${_PHP_VERSION}/var/run\n\t\t\tPHPFPM_BIN=${PHPBREW_ROOT}/php/${_PHP_VERSION}/sbin/php-fpm \n\t\t\tPHPFPM_PIDFILE=${PHPBREW_ROOT}/php/${_PHP_VERSION}/var/run/php-fpm.pid \n\t\t\tfpm_start () {\n\t\t\t\techo "Starting php-fpm..."\n\t\t\t\tlocal regex="^php-5\.2.*"\n\t\t\t\tif [[ ${_PHP_VERSION} =~ ${regex} ]]\n\t\t\t\tthen\n\t\t\t\t\t${PHPFPM_BIN} start\n\t\t\t\telse\n\t\t\t\t\t${PHPFPM_BIN} --php-ini ${PHPBREW_ROOT}/php/${_PHP_VERSION}/etc/php.ini --fpm-config ${PHPBREW_ROOT}/php/${_PHP_VERSION}/etc/php-fpm.conf --pid ${PHPFPM_PIDFILE} ${*:3}\n\t\t\t\tfi\n\t\t\t\tif [[ $? != "0" ]]\n\t\t\t\tthen\n\t\t\t\t\techo "php-fpm start failed."\n\t\t\t\tfi\n\t\t\t}\n\t\t\tfpm_stop () {\n\t\t\t\tlocal regex="^php-5\.2.*"\n\t\t\t\tif [[ ${PHPBREW_PHP} =~ ${regex} ]]\n\t\t\t\tthen\n\t\t\t\t\t${PHPFPM_BIN} stop\n\t\t\t\telif [[ -e ${PHPFPM_PIDFILE} ]]\n\t\t\t\tthen\n\t\t\t\t\techo "Stopping php-fpm..."\n\t\t\t\t\tkill $(cat ${PHPFPM_PIDFILE})\n\t\t\t\t\trm -i -f ${PHPFPM_PIDFILE}\n\t\t\t\tfi\n\t\t\t}\n\t\t\tcase $2 in\n\t\t\t\t(start) fpm_start ;;\n\t\t\t\t(stop) fpm_stop ;;\n\t\t\t\t(restart) fpm_stop\n\t\t\t\t\tfpm_start ;;\n\t\t\t\t(module) $PHPFPM_BIN --php-ini ${PHPBREW_ROOT}/php/${_PHP_VERSION}/etc/php.ini --fpm-config ${PHPBREW_ROOT}/php/${_PHP_VERSION}/etc/php-fpm.conf -m | less ;;\n\t\t\t\t(info) $PHPFPM_BIN --php-ini ${PHPBREW_ROOT}/php/${_PHP_VERSION}/etc/php.ini --fpm-config ${PHPBREW_ROOT}/php/${_PHP_VERSION}/etc/php-fpm.conf -i ;;\n\t\t\t\t(config) if [[ -n $EDITOR ]]\n\t\t\t\t\tthen\n\t\t\t\t\t\t$EDITOR ${PHPBREW_ROOT}/php/${_PHP_VERSION}/etc/php-fpm.conf\n\t\t\t\t\telse\n\t\t\t\t\t\techo "Please set EDITOR environment variable for your favor."\n\t\t\t\t\t\tnano ${PHPBREW_ROOT}/php/${_PHP_VERSION}/etc/php-fpm.conf\n\t\t\t\t\tfi ;;\n\t\t\t\t(help) $PHPFPM_BIN --php-ini ${PHPBREW_ROOT}/php/${_PHP_VERSION}/etc/php.ini --fpm-config ${PHPBREW_ROOT}/php/${_PHP_VERSION}/etc/php-fpm.conf --help ;;\n\t\t\t\t(test) $PHPFPM_BIN --php-ini ${PHPBREW_ROOT}/php/${_PHP_VERSION}/etc/php.ini --fpm-config ${PHPBREW_ROOT}/php/${_PHP_VERSION}/etc/php-fpm.conf --test ;;\n\t\t\t\t(*) echo "Usage: phpbrew fpm [start|stop|restart|module|test|help|config]" ;;\n\t\t\tesac ;;\n\t\t(env) if [[ -n "$2" ]]\n\t\t\tthen\n\t\t\t\texport PHPBREW_PHP=$2\n\t\t\tfi\n\t\t\techo "export PHPBREW_ROOT=$PHPBREW_ROOT"\n\t\t\techo "export PHPBREW_HOME=$PHPBREW_HOME"\n\t\t\tif [[ -n $PHPBREW_LOOKUP_PREFIX ]]\n\t\t\tthen\n\t\t\t\techo "export PHPBREW_LOOKUP_PREFIX=$PHPBREW_LOOKUP_PREFIX"\n\t\t\tfi\n\t\t\tif [[ -n $PHPBREW_PHP ]]\n\t\t\tthen\n\t\t\t\techo "export PHPBREW_PHP=$PHPBREW_PHP"\n\t\t\t\techo "export PHPBREW_PATH=$PHPBREW_ROOT/php/$PHPBREW_PHP/bin"\n\t\t\tfi ;;\n\t\t(off) unset PHPBREW_PHP\n\t\t\tunset PHPBREW_PATH\n\t\t\teval `$BIN env`\n\t\t\t__phpbrew_set_path\n\t\t\techo "phpbrew is turned off." ;;\n\t\t(switch-off) unset PHPBREW_PHP\n\t\t\tunset PHPBREW_PATH\n\t\t\teval `$BIN env`\n\t\t\t__phpbrew_set_path\n\t\t\t__phpbrew_reinit\n\t\t\techo "phpbrew is switched off." ;;\n\t\t(rehash) echo "Rehashing..."\n\t\t\t. ~/.phpbrew/bashrc ;;\n\t\t(purge) if [[ -z "$2" ]]\n\t\t\tthen\n\t\t\t\tcommand $BIN help\n\t\t\telse\n\t\t\t\t__phpbrew_remove_purge $2 purge\n\t\t\tfi ;;\n\t\t(*) command $PHPBREW_OVERRIDE_PHP $BIN $short_option "$@"\n\t\t\texit_status=$?  ;;\n\tesac\n\thash -r\n\treturn ${exit_status:-0}\n}

I hope someone can help me with that.
Everything worked just fine on ubuntu vivid and dumb OSX wont work ._.

**Comment by protomouse** [comment]
Same issue here after running self-update. Works fine in bash.

**Comment by protomouse** [comment]
Ok, so 08b85ebba6ce7a356ea64bbce0fe66d2a03cb023 is what breaks it. `which` is a zsh built-in, which returns the function body if the supplied argument is a function. I fixed it by supplying the full path to the which binary (/usr/bin/which), but it would be better to find a way to override the zsh built-in that doesn't hard-code like that.

**Comment by greensn0w** [comment]
What if we switch from `which` to `type` ?
We'd just have to detect if we are on zsh or bash and use this:
```shell
#BASH
type -P phpbrew

#ZSH
type -p phpbrew
```

It outputs something like this:
> phpbrew is /usr/bin/phpbrew
