### ISSUE TITLE
CliFramework dependency requires 5.4.0 no requirement for phpbres is being set.

### ISSUE THREAD

**Issue by DannyvdSluijs** [phpbrew/phpbrew#513]
I've just installed phpbrew using the README.md. And everthing goes correct untill I want to install a version. After some debugging I've found out that this is because of a combination of my enviromenment with phpbrew dependencies having a mismatch.

I'm using Ubuntu 12.04 with PHP 5.3.10 and the error is:
```
dvandersluijs@Vostro200-Danny:~$ phpbrew install 5.3.29 +defaultvi 
===> phpbrew will now build 5.3.29
PHP 5.3 requires +intl, enabled by default.
===> Loading and resolving variants...
Checking distribution checksum...
Checksum matched: 9469e240cbe6ac865aeaec89b253dd30
===> Distribution file was successfully extracted, skipping...
PHP Parse error:  syntax error, unexpected '[' in phar:///usr/bin/phpbrew/CLIFramework/ExceptionPrinter/DevelopmentExceptionPrinter.php on line 2
PHP Stack trace:
PHP   1. {main}() /usr/bin/phpbrew:0
PHP   2. require() /usr/bin/phpbrew:6
PHP   3. CLIFramework\Application->runWithTry() phar:///usr/bin/phpbrew/scripts/phpbrew-emb.php:2
PHP   4. Universal\ClassLoader\SplClassLoader->loadClass() phar:///usr/bin/phpbrew/scripts/phpbrew-emb.php:0
PHP   5. require() phar:///usr/bin/phpbrew/Universal/ClassLoader/SplClassLoader.php:2
PHP   6. Universal\ClassLoader\SplClassLoader->loadClass() phar:///usr/bin/phpbrew/Universal/ClassLoader/SplClassLoader.php:0
```

This is due to the fact that CLIframework uses short notation for arrays in https://github.com/c9s/CLIFramework/blob/master/src/CLIFramework/ExceptionPrinter/DevelopmentExceptionPrinter.php#L20 as per composer.json (https://github.com/c9s/CLIFramework/blob/master/composer.json#L6) this is correct as php 5.4.0 is required. Which actually breaks the purpose of phpbrew.

**Comment by c9s** [comment]
er. seems like we need to downgrade the php requirement in CLIFramework.

cc @marcioAlmada  @shinnya

**Comment by marcioAlmada** [comment]
Is it just the new array syntax?

**Comment by DannyvdSluijs** [comment]
I can't comment, this is blocking my current install. Are there unit test available, if so can run them on 12.04 with 5.3.10

**Comment by c9s** [comment]
@marcioAlmada currently yes.

**Comment by marcioAlmada** [comment]
I see you released the new version. Can you release phpbrew too with the updated deps?

**Comment by c9s** [comment]
sure

**Comment by c9s** [comment]
@marcioAlmada   `phprelease` script seems broken, this needs to be updated.    the release script it self describes the SOP, it's necessary to make it work.

**Comment by c9s** [comment]
@marcioAlmada seems that testInstallCommand doesn't catch the output very well?

https://travis-ci.org/phpbrew/phpbrew/builds/64193944

```
1) InstallCommandTest::testInstallCommand
Failed asserting that '    Variants:  +default +intl +xml
' contains "5.5.22".
/home/travis/build/phpbrew/phpbrew/tests/PhpBrew/Command/InstallCommandTest.php:74
/home/travis/build/phpbrew/phpbrew/tests/PhpBrew/Command/InstallCommandTest.php:29
```

**Comment by c9s** [comment]
But we actually have the output correct:

```
Starting test 'InstallCommandTest::testInstallCommand'.
* (system)
  php-5.5.22     
    Prefix:   /home/travis/build/phpbrew/phpbrew/.phpbrew/php/php-5.5.22
FSSSS
Starting test 'KnownCommandTest::testCommand'.
```

**Comment by marcioAlmada** [comment]
Strange. What changed? I've got a strange bug the other day of test that only failed on travis but passed on all OSs locally.

**Comment by c9s** [comment]
didn't change anything.... it's really strange. seems the output buffer isn't started ? maybe it's a phpunit issue (older phpunit on Travis CI)

**Comment by marcioAlmada** [comment]
Maybe. I'm sick of travis not providing us a docker image or a vagrant machine to check the environment at home. This feels like using a black box for testing.

**Comment by marcioAlmada** [comment]
@c9s I found it. It's an issue with phpunit's assertContains() and binary strings :sob:

**Comment by marcioAlmada** [comment]
This should be fixed already. Thanks for your report.

**Comment by DannyvdSluijs** [comment]
Fix confirmed!
