### ISSUE TITLE
phpbrew failed to install php version

### ISSUE THREAD

**Issue by MohamedQabbani** [phpbrew/phpbrew#519]
===> Building...

RuntimeException: Make failed.
Trace:

    0) PhpBrew\Tasks\BuildTask->run(PhpBrew\Build)
    1) PhpBrew\Command\InstallCommand->execute('5.4.0', '+default')
    2) call_user_func_array([PhpBrew\Command\InstallCommand, 'execute'], ['5.4.0', '+default'])
    3) CLIFramework\CommandBase->executeWrapper(['5.4.0', '+default'])
    4) CLIFramework\Application->run(['/usr/bin/phpbrew', 'install', '5.4.0', '+default'])
    5) CLIFramework\Application->runWithTry(['/usr/bin/phpbrew', 'install', '5.4.0', '+default'])
    6) require('phar:///usr/bin/phpbrew/scripts/phpbrew-emb.php')

**Comment by marcioAlmada** [comment]
Can you share your log in a gist? There is nearly 0 useful information here so we can help you.

**Comment by MohamedQabbani** [comment]
where log?

**Comment by marcioAlmada** [comment]
`cat $PHPBREW_HOME/build/php-5.4.40/build.log`

**Comment by MohamedQabbani** [comment]
cat: /build/php-5.4.40/build.log: No such file or directory

**Comment by marcioAlmada** [comment]
use the intended php version, `php-5.4.0` in your case.

**Comment by MohamedQabbani** [comment]
tail $PHPBREW_HOME/build/php-5.4.0/build.log

/root/.phpbrew/build/php-5.4.0/ext/dom/node.c:1900:40: error: dereferencing pointer to incomplete type
     RETVAL_STRINGL((char *) buf->buffer->content, ret, 1);
                                        ^
/root/.phpbrew/build/php-5.4.0/Zend/zend_API.h:571:20: note: in definition of macro ‘ZVAL_STRINGL’
   const char *__s=(s); int __l=l;   \
                    ^
/root/.phpbrew/build/php-5.4.0/ext/dom/node.c:1900:5: note: in expansion of macro ‘RETVAL_STRINGL’
     RETVAL_STRINGL((char *) buf->buffer->content, ret, 1);
     ^
make: *** [ext/dom/node.lo] Error 1

**Comment by marcioAlmada** [comment]
No idea what's going on. I recommend you to try some other minor version close to the one you want (`5.4.{1, 2, 3, ...}`). This seems to be a bad distribution.
