### ISSUE TITLE
Installing extensions from github

### ISSUE THREAD

**Issue by uda** [phpbrew/phpbrew#520]
I was trying to install an extension from github. but apparently phpbrew uses the old path: `https://github.com/someuser/somerepo/tarball/branch`, which yields a 404 page.

Also, using the URL with `.git` extension also yields an error, so the documentation should be updated.

**Comment by marcioAlmada** [comment]
Did the url changed recently? this worked a few days ago. I'll check your pull request :)

**Comment by marcioAlmada** [comment]
FYI `.git` is working too.
