### ISSUE TITLE
all phpbrew ext commands require source (build) files

### ISSUE THREAD

**Issue by akomm** [phpbrew/phpbrew#523]
If you clear your build directory and try to use phpbrew ext commands, you get the following error:  
`
Error: The ext directory '[home]/.phpbrew/build/[alias-or-version]/ext' does not exist.
It looks like you don't have the PHP source in [home]/.phpbrew/build/[alias-or-version] or you didn't extract the tarball.
Suggestion: Please install at least one PHP with your prefered version and switch to it.
`

Command **phpbrew ext config [extension]** for example should not require this, because it works on [home]/.phpbrew/php/[alias-or-version]/var/db/[extension]/*.ini files.

If I create an empty [home]/.phpbrew/build/[alias-or-version]/ext directory, without redownloading and extracting the sources, it works perfectly well.

Looks like there is a general check for the source directory if any ext command is executed, even though not every "sub command" requires it:

https://github.com/phpbrew/phpbrew/blob/develop/src/PhpBrew/Command/ExtensionCommand/BaseCommand.php#L24-L31

BaseCommand check for sources should be moved to a separated method and only invoked in a context, which requires source files. That way you can check on per-command or per-command-option-base, instead of doing it "globaly".

If you think this is a good idea, I would check it out and refactor and make a pull request (currently I can't from my location).

**Comment by marcioAlmada** [comment]
Oh, that's because we have some cases where the ext name on the catalog doesn't match the ext real name. But I guess in this case we can lax the check and just use the provided name on the command line to avoid the hassle.

PR welcome :)

**Comment by marcioAlmada** [comment]
fixed 9c17e6ede39defb527dd74f75e9b2f7e74898335

**Comment by marcioAlmada** [comment]
Release will come in a few hours.
