### ISSUE TITLE
cannot add extension 'mysqlnd' (configure error:can't find openssl evp.h)

### ISSUE THREAD

**Issue by ryh** [phpbrew/phpbrew#528]
I use `phpbrew install 5.6.9 +default+exif` to installed one, and set as global

I want to add sqlite mysql support without installing again,
so use `phpbrew extension install pdo_sqlite` (successfully done)
but install mysql shows can't find mysqlnd something,
then try installing mysqlnd report can't find openssl `evp.h`
`configure: error: Cannot find OpenSSL's <evp.h>`
evp.h  exists in /usr folder
```shell
/usr  find . -name evp.h
./include/openssl/evp.h
./local/Cellar/openssl/1.0.2a-1/include/openssl/evp.h
find: ./sbin/authserver: Permission denied
```
the default ./configure "--with-openssl=/usr"

is the configure file error or something?
```shell
OS X 10.10.3 (14D131) 
make -v
GNU Make 3.81 
cmake --verison
cmake version 3.2.2
 gcc -v
Configured with: --prefix=/Applications/Xcode.app/Contents/Developer/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix
```

**Comment by c9s** [comment]
You can't install pdo* extension as dynamic loading library (.so file), you must compile them with static linking while you're building the PHP. please reinstall your php with the variants.

**Comment by c9s** [comment]
If you're using homebrew, you might want link your openssl:

```
brew link openssl
```

**Comment by ryh** [comment]
thanks. :smile:

**Comment by mfn** [comment]
Had the same issue, but was required to run `brew link --force openssl`, otherwise I would get this from brew:
```
Warning: openssl is keg-only and must be linked with --force
Note that doing so can interfere with building software.
```
