### ISSUE TITLE
HTTP proxy in known command

### ISSUE THREAD

**Issue by Furgas** [phpbrew/phpbrew#530]
Option --http-proxy is available for `install` command but not for `known` and `update`. Maybe even more commands should support it (global option?).

**Comment by jhdxr** [comment]
`phpbrew help update` says it supports `--http-proxy` and `--http-proxy-auth`.

`phpbrew known` reads the local release list unless you specific `-u` or there is no data locally. but yes, it supports `--http-proxy` and `--http-proxy-auth` if your need fetch the list from remote source.

**Comment by Furgas** [comment]
Thanks. I must have been blind on `update` command. But this option is not supported for `known` command - I've changed the topic.
