### ISSUE TITLE
Module already loaded

### ISSUE THREAD

**Issue by sagikazarmark** [phpbrew/phpbrew#532]
If I install any extensions manually, I get the following error:

`PHP Warning:  Module 'xml' already loaded in Unknown on line 0`
(xml in this case which should be in fact installed by default)

**Comment by sagikazarmark** [comment]
BTW I am on 1.19.7

**Comment by sagikazarmark** [comment]
BTW I am on 1.19.7

**Comment by marcioAlmada** [comment]
What "manually" means in this case? `phpbrew ext install xml` or go to extension source and phpize...?

**Comment by sagikazarmark** [comment]
Sorry for missing info, `phpbrew ext install xml`

**Comment by marcioAlmada** [comment]
Ok, so you you installed xml as a bundled module - some variant like `+default` or `+xml` and then did `phpbrew ext install xml` at a later stage. The problem is that we currently don't check for bundled extensions before touching the `.ini` file and I guess we can improve this somehow.

I can't remember why we avoided this check in the past, let's see if it can be done now :)

**Comment by sagikazarmark** [comment]
Exact steps:

``` bash
$ phpbrew install 5.6.8
$ phpbrew ext install xml
```

**Comment by marcioAlmada** [comment]
> Exact steps:
>     $ phpbrew install 5.6.8
>     $ phpbrew ext install xml

Yes, the xml extension is installed by default if you don't give any variant too because the installers needs to read xml data from extensions.

**Comment by jhdxr** [comment]
I have ran into this problem as well. I cannot remember the steps clearly. it seems I installed an old php version, then use `phpbrew ext install` to install some extension, after that I installed another php with the extension
```
phpbrew install 5.5
phpbrew ext instan XXX
phpbrew install 5.6 +XXX
```
(XXX means one of the extensions)

**Comment by c9s** [comment]
Is it because we can't distinguish shared / static module?
