### ISSUE TITLE
'$ phpbrew known' the same as '$ phpbrew known --old'

### ISSUE THREAD

**Issue by vitaly-zdanevich** [phpbrew/phpbrew#534]
And I can't install version less than 5.3.

vitaly@vitaly-desktop:~$ phpbrew known
===> Fetching release list...
5.6: 5.6.10, 5.6.9, 5.6.8, 5.6.7, 5.6.6, 5.6.5, 5.6.4, 5.6.3 ...
5.5: 5.5.26, 5.5.25, 5.5.24, 5.5.23, 5.5.22, 5.5.21, 5.5.20, 5.5.19 ...
5.4: 5.4.42, 5.4.41, 5.4.40, 5.4.39, 5.4.38, 5.4.37, 5.4.36, 5.4.35 ...
5.3: 5.3.29, 5.3.28, 5.3.27, 5.3.26, 5.3.25, 5.3.24, 5.3.23, 5.3.22 ...
You can run `phpbrew update` to get a newer release list.

vitaly@vitaly-desktop:~$ phpbrew known --old
5.6: 5.6.10, 5.6.9, 5.6.8, 5.6.7, 5.6.6, 5.6.5, 5.6.4, 5.6.3 ...
5.5: 5.5.26, 5.5.25, 5.5.24, 5.5.23, 5.5.22, 5.5.21, 5.5.20, 5.5.19 ...
5.4: 5.4.42, 5.4.41, 5.4.40, 5.4.39, 5.4.38, 5.4.37, 5.4.36, 5.4.35 ...
5.3: 5.3.29, 5.3.28, 5.3.27, 5.3.26, 5.3.25, 5.3.24, 5.3.23, 5.3.22 ...
You can run `phpbrew update` to get a newer release list.

**Comment by marcioAlmada** [comment]
Fixed with 78c64a48fcb44637969187909600498383f42915 and released today.

    phpbrew self-update
    phpbrew update --old # fetch the releases again
    phpbrew known

\>>>

```
5.6: 5.6.10, 5.6.9, 5.6.8, 5.6.7, 5.6.6, 5.6.5, 5.6.4, 5.6.3 ...
5.5: 5.5.26, 5.5.25, 5.5.24, 5.5.23, 5.5.22, 5.5.21, 5.5.20, 5.5.19 ...
5.4: 5.4.42, 5.4.41, 5.4.40, 5.4.39, 5.4.38, 5.4.37, 5.4.36, 5.4.35 ...
5.3: 5.3.29, 5.3.28, 5.3.27, 5.3.26, 5.3.25, 5.3.24, 5.3.23, 5.3.22 ...
5.1: 5.1.6, 5.1.5, 5.1.4, 5.1.3, 5.1.2, 5.1.1, 5.1.0 ...
5.0: 5.0.5, 5.0.4, 5.0.3, 5.0.2, 5.0.1, 5.0.0 ...
```

Beware we don't give any help to install php `5.2` or below with **phpbrew** anymore. Good luck.
