### ISSUE TITLE
Undefined imagecreatetruecolor function (Problems with gd extension)

### ISSUE THREAD

**Issue by iwan-uschka** [phpbrew/phpbrew#536]
Hey there,

I know this issue is quite similar to https://github.com/phpbrew/phpbrew/issues/494, but I can't get it to work. I am running Mac OS X 10.10.3. I just installed phpbrew:

```
phpbrew install 5.5.26 +default +apxs2=/usr/local/opt/httpd24/bin/apxs +icu=/usr/local/opt/icu4c +debug +exif +phar +fpm +hash +intl +xmlrpc +zlib +session +kerberos +cgi +sqlite +mysql +mcrypt +mhash +openssl +gettext=/usr/local/opt/gettext
````

After that i installed gd

```
phpbrew ext install gd \
-- --with-libdir=lib/x86_64-linux-gnu \
--with-gd=shared \
--enable-gd-natf \
--with-jpeg-dir=/usr \
--with-png-dir=/usr`
```

I am using homebrew, not macports. With `php -r 'var_dump(gd_info());'` I get

```
array(11) {
  'GD Version' =>
  string(26) "bundled (2.1.0 compatible)"
  'FreeType Support' =>
  bool(false)
  'T1Lib Support' =>
  bool(false)
  'GIF Read Support' =>
  bool(true)
  'GIF Create Support' =>
  bool(true)
  'JPEG Support' =>
  bool(true)
  'PNG Support' =>
  bool(true)
  'WBMP Support' =>
  bool(true)
  'XPM Support' =>
  bool(false)
  'XBM Support' =>
  bool(true)
  'JIS-mapped Japanese Font Support' =>
  bool(false)
}
```

It's possible to run `php -a` > `imagecreatetruecolor(50,50);`.

But i get an error when running php script with apache (httpd24 installed with homebrew): `Call to undefined function imagecreatetruecolor()`. `info_php` tells me something about additional ini-file `/Users/iwan_uschka/.phpbrew/php/php-5.5.26/var/db/gd.ini`loaded and `gd support enabled`.

Any ideas why I can't get it to work with gd?
Thanks

**Comment by c9s** [comment]
The PHP built from phpbrew looks like, however it seems that you're not running phpbrew php.

You need to make sure your apache php is running the phpbrew php.  Use phpinfo() to show that information.
