### ISSUE TITLE
Running 'sudo php' uses system php, is it possible for this to use phpbrew version?

### ISSUE THREAD

**Issue by ivelrrat** [phpbrew/phpbrew#542]
I followed the system-wide guide and it seems everything works, except running `sudo php`

as root I ran `phpbrew install 5.4`
I can use 5.4 as root, 
I can use 5.4 as my user
but I can't use 5.4 under sudo

Should I be able to `sudo php`?

I'm on Ubuntu 14.04.1

**Comment by c9s** [comment]
No, you shouldn't use sudo with phpbrew, because phpbrew requires your environment variable in your current shell.  sudo will create another isolated environment.
