### ISSUE TITLE
phpbrew doesn't revert to system php version on apache2

### ISSUE THREAD

**Issue by stefanchiriac** [phpbrew/phpbrew#543]
I installed php 5.4.42 with apxs2, switched and restarted apache. Checked cli and phpinfo() and all was fine.
When I did `phpbrew switch-off` and restarted apache2, it only switched for cli. To change the php version in apache2 I had to manually change `/etc/apache2/mods-available/php5.load`. Now if I do `phpbrew switch php-5.4.42` it only switches cli and no longer apache2.

**Comment by c9s** [comment]
This is not supported. you have to change the config file manually.

**Comment by nelson6e65** [comment]
@c9s Still not supported? What files should I change?
