### ISSUE TITLE
Phpbrew timezone invalid

### ISSUE THREAD

**Issue by StagnantIce** [phpbrew/phpbrew#544]
In phpbrew: Europe/Moscow 2015-07-16 18:37:40
In php system: Europe/Moscow 2015-07-16 17:37:40

Phpbrew timezone invalid, how i can fix it?

**Comment by marcioAlmada** [comment]
This looks like a daylight savings time issue. Run `phpbrew config` to edit your ini settings accordingly. I recommend you to read this: http://solidlystated.com/scripting/php-timezone-settings-and-dst/

**Comment by StagnantIce** [comment]
Thank you for your reply.
Look, that i have in both php.ini files:
date.timezone = "Europe/Moscow"

I think, phpbrew don`t use system tzdate or somethink like that.

**Comment by marcioAlmada** [comment]
You can append any configure flag you wish like this:

`phpbrew install 5.6.10 \-- --with-system-tzdata=...`

**Comment by StagnantIce** [comment]
--with-system-tzdata set, but timezone invalid =(

**Comment by StagnantIce** [comment]
phpbrew ext install timezonedb Help on php 5.3.29, but on php 5.3.28 i have error:
PHP Notice:  Undefined variable: returnValue in phar:///usr/bin/phpbrew/PhpBrew/Utils.php on line 2

Notice: Undefined variable: returnValue in phar:///usr/bin/phpbrew/PhpBrew/Utils.php on line 2
PHP Warning:  system() has been disabled for security reasons in phar:///usr/bin/phpbrew/PhpBrew/Utils.php on line 2

Warning: system() has been disabled for security reasons in phar:///usr/bin/phpbrew/PhpBrew/Utils.php on line 2
PHP Notice:  Undefined variable: returnValue in phar:///usr/bin/phpbrew/PhpBrew/Utils.php on line 2

Notice: Undefined variable: returnValue in phar:///usr/bin/phpbrew/PhpBrew/Utils.php on line 2
Exception: Command failed: tar -C /home/git/.phpbrew/build/php-5.3.28/ext -xzf /home/git/.phpbrew/distfiles/timezonedb-2014.2.tgz returns 
Trace:

    0) PhpBrew\Utils::system('tar -C /home/git/.phpbrew/build/php-5.3.28/ext -xzf /home/git/.phpbrew/distfiles/timezonedb-2014.2.tgz')
    1) PhpBrew\Extension\ExtensionDownloader->download(PhpBrew\Extension\Provider\PeclProvider, '2014.2')
    2) PhpBrew\Command\ExtensionCommand\InstallCommand->execute('timezonedb', '2014.2')
    3) call_user_func_array([PhpBrew\Command\ExtensionCommand\InstallCommand, 'execute'], ['timezonedb', '2014.2'])
    4) CLIFramework\CommandBase->executeWrapper(['timezonedb', '2014.2'])
    5) CLIFramework\Application->run(['/usr/bin/phpbrew', 'ext', 'install', 'timezonedb', '2014.2'])
    6) CLIFramework\Application->runWithTry(['/usr/bin/phpbrew', 'ext', 'install', 'timezonedb', '2014.2'])
    7) require('phar:///usr/bin/phpbrew/scripts/phpbrew-emb.php')

**Comment by marcioAlmada** [comment]
Could not reproduce here with php 5.3.28 :(

```
$ phpbrew switch 5.3.28
$ phpbrew ext install timezonedb

===> Downloading from http://pecl.php.net/get/timezonedb-2015.5.tgz
===> /home/marcio/.phpbrew/distfiles/timezonedb-2015.5.tgz downloaded.
===> Extracting to /home/marcio/.phpbrew/build/php-5.3.28/ext...
[ ] timezonedb extension is disabled.
===> Installing timezonedb extension...
Log stored at: /home/marcio/.phpbrew/build/php-5.3.28/ext/timezonedb/build.log
Changing directory to /home/marcio/.phpbrew/build/php-5.3.28/ext/timezonedb
===> Phpize...
===> Configuring...
===> Building...
===> Running make all: make -C /home/marcio/.phpbrew/build/php-5.3.28/ext/timezonedb  all  >> /home/marcio/.phpbrew/build/php-5.3.28/ext/timezonedb/build.log 2>&1
===> Installing...
===> Running make install: make -C /home/marcio/.phpbrew/build/php-5.3.28/ext/timezonedb  install  >> /home/marcio/.phpbrew/build/php-5.3.28/ext/timezonedb/build.log 2>&1
===> Extension is installed.
===> Creating config file /home/marcio/.phpbrew/php/php-5.3.28/var/db/timezonedb.ini.disabled
===> Enabling extension timezonedb
[*] timezonedb extension is enabled.
Done.
```

Is you phpbrew the latest one?

**Comment by marcioAlmada** [comment]
> --with-system-tzdata set, but timezone invalid =(

This `--with-system-tzdata` flag seems obscure, the configure script rejects it. Are you sure this flag not just a distro related thing? The "timezonedb" approach seems to be a better idea. I hope we can make it work for you.

**Comment by marcioAlmada** [comment]
ping?

**Comment by StagnantIce** [comment]
I use php 5.3.29 now. Thank you for your help.
