### ISSUE TITLE
openssl extension not found

### ISSUE THREAD

**Issue by hebbet** [phpbrew/phpbrew#546]
Running Debian 7 with installed openssl (openssl version: OpenSSL 1.0.1e 11 Feb 2013)

when i execute phpbrew known it get:
openssl extension not found, to download releases file you need openssl.

**Comment by c9s** [comment]
$ phpbrew ext install openssl

**Comment by c9s** [comment]
You have to install the PHP with phpbrew first (it extracts the source code), the openssl extension is inside the source code directory.

**Comment by kremezion** [comment]
$ phpbrew ext install openssl
Error: PHPBREW_PHP environment variable is not defined.
  This extension command requires you specify a PHP version from your build list.
  And it looks like you haven't switched to a version from the builds that were built with PHPBrew.
Suggestion: Please install at least one PHP with your prefered version and switch to it.

**Comment by webghostx** [comment]
the same

**Comment by iugostudio** [comment]
I have same problem on Debian 8. Openssl installed but phpbrew do not see it. I run** phpbrew ext install openssl**, it was succesfully performed but **Exception: openssl extension not found, to download releases file you need openssl.** still exists
