### ISSUE TITLE
CLI colors

### ISSUE THREAD

**Issue by Lucaszz** [phpbrew/phpbrew#547]
Are any possibilities to enable it ?

cat ~/.phpbrew/php/php-5.5.27/etc/php.ini | grep cli_server.color
Gives me:
cli_server.color = On

But I still can't se colors on shell

**Comment by c9s** [comment]
What kind of color do you want? the console output color? you need to make sure that your terminal supports the ANSI console colors.

**Comment by Lucaszz** [comment]
This is an example:

When I run command on terminal:
php app/console cache:clear
Then output is:

Clearing the cache for the <info>dev</info> environment with ...

Text wrapped by "info" tag should be colorized.
It works on my native php, but it does not work with phpbrew.
Both php.ini are identical.

How can I enable colorizing for phpbrew ?

Example of CLI script:
https://github.com/symfony/FrameworkBundle/blob/master/Command/CacheClearCommand.php#L69

**Comment by marcioAlmada** [comment]
I doubt this is caused by phpbrew itself. Are you testing this against the same php version (from system and phpbrew)?

A deeper check. Please add a breakpoint on this line https://github.com/symfony/symfony/blob/2.8/src/Symfony/Component/Console/Formatter/OutputFormatter.php#L240 and check if `$this->isDecorated()` yields the same value on both environments. The console component might be doing some "clever" decision somewhere and disabling colors. But I'd like to confirm this before investigating more.

**Comment by marcioAlmada** [comment]
friendly ping

**Comment by Lucaszz** [comment]
Ok sorry for my delay, I was on vacation :)

Firstly I want to congrats for your amazing investigation. It was helpfully tip.

I noticed that:
https://github.com/symfony/Console/blob/master/Output/StreamOutput.php

StreamOutput::hasColorSupport method returns ```false``` when ```phpbrew switch 5.5.27```
and this method returns ```true``` when ```phpbrew off```

This is caused by missing ```posix_isatty()``` for phpbrew's php.

Are any possibilities to install ```posix_isatty``` with phpbrew  ?

**Comment by marcioAlmada** [comment]
Hi, ok you just need the posix extension. Run `phpbrew ext | grep posix`, if you get no output, proceed with `phpbrew ext install posix` :)

The strange thing is that `+posix` should be installed by default or if you use the `+default` variant. Just in case, can you post the output of `phpbrew list -v`?

Thanks.

**Comment by Lucaszz** [comment]
```phpbrew ext install posix``` enabled color in CLI for me thx.

**Comment by marcioAlmada** [comment]
That's great, thanks for reporting back.

**Comment by Oxicode** [comment]
+1 `phpbrew ext install posix`
