### ISSUE TITLE
Debian Jessie - configure failed

### ISSUE THREAD

**Issue by Pupp3tm4st3r** [phpbrew/phpbrew#548]
Hi there,

I´ve installed phpbrew on Debian Jessie for testing issues. First problem was, that libjpeg8-dev libjpeg8 are not available on debian jessie.

Second thing was, that whenever I want to build PHP with the option +all or +everything, I get one of the following errors:

PhpBrew\Exception\SystemCommandException: Configure failed: 1
Trace:

    0) PhpBrew\Tasks\ConfigureTask->run(PhpBrew\Build, ['--with-libdir=lib/x86_64-linux-gnu', '--enable-all', '--enable-dom', '--enable-libxml', '--enable-simplexml', '--enable-xml', '--enable-xmlreader', '--enable-xmlwriter', '--with-xsl', '--with-libxml-dir=/usr'])
    1) PhpBrew\Command\InstallCommand->execute('5.6.8', '+all')
    2) call_user_func_array([PhpBrew\Command\InstallCommand, 'execute'], ['5.6.8', '+all'])
    3) CLIFramework\CommandBase->executeWrapper(['5.6.8', '+all'])
    4) CLIFramework\Application->run(['/usr/bin/phpbrew', 'install', '5.6.8', '+all'])
    5) CLIFramework\Application->runWithTry(['/usr/bin/phpbrew', 'install', '5.6.8', '+all'])
    6) require('phar:///usr/bin/phpbrew/scripts/phpbrew-emb.php')

or

PhpBrew\Exception\SystemCommandException: Configure failed: 1
Trace:

    0) PhpBrew\Tasks\ConfigureTask->run(PhpBrew\Build, ['--disable-all', '--enable-phar', '--enable-session', '--enable-short-tags', '--enable-tokenizer', '--with-pcre-regex', '--with-zlib=/usr', '--with-libdir=lib/x86_64-linux-gnu', '--enable-dom', '--enable-libxml', '--enable-simplexml', '--enable-xml', '--enable-xmlreader', '--enable-xmlwriter', '--with-xsl', '--with-libxml-dir=/usr', '--enable-dba', '--enable-ipv6', '--enable-dom', '--enable-calendar', '--enable-wddx', '--enable-static', '--enable-inifile', '--enable-inline-optimization', '--enable-cli', '--enable-fpm', '--enable-ftp', '--enable-filter', '--enable-gcov', '--enable-maintainer-zts', '--enable-json', '--enable-hash', '--enable-exif', '--enable-mbstring', '--enable-mbregex', '--enable-libgcc', '--enable-pdo', '--enable-posix', '--enable-embed', '--enable-sockets', '--enable-debug', '--enable-phpdbg', '--enable-zip', '--enable-bcmath', '--enable-fileinfo', '--enable-ctype', '--enable-cgi', '--enable-soap', '--enable-pcntl', '--enable-intl', '--enable-phar', '--enable-session', '--enable-tokenizer', '--enable-opcache', '--with-imap-ssl', '--with-tidy', '--with-kerberos', '--with-xmlrpc', '--with-pcre-regex', '--with-pcre-dir=/usr', '--with-mhash=/usr', '--with-mcrypt=/usr', '--with-zlib=/usr', '--with-curl=/usr', '--with-readline=/usr', '--with-libedit=/usr', '--with-gd=shared,/usr', '--enable-gd-native-ttf', '--with-jpeg-dir=/usr', '--with-png-dir=/usr', '--with-freetype-dir=/usr', '--with-icu-dir=/usr', '--with-openssl=/usr', '--with-mysql=mysqlnd', '--with-mysqli=mysqlnd', '--with-pdo-mysql=mysqlnd', '--with-sqlite3', '--with-pdo-sqlite', '--with-pgsql', '--with-pdo-pgsql', '--enable-dom', '--enable-libxml', '--enable-simplexml', '--enable-xml', '--enable-xmlreader', '--enable-xmlwriter', '--with-xsl', '--with-libxml-dir=/usr', '--with-gettext=/usr', '--with-iconv', '--with-bz2=/usr', '--enable-shmop', '--enable-sysvsem', '--enable-sysvshm', '--enable-sysvmsg', '--with-gmp'])
    1) PhpBrew\Command\InstallCommand->execute('5.6.8', '+everything')
    2) call_user_func_array([PhpBrew\Command\InstallCommand, 'execute'], ['5.6.8', '+everything'])
    3) CLIFramework\CommandBase->executeWrapper(['5.6.8', '+everything'])
    4) CLIFramework\Application->run(['/usr/bin/phpbrew', 'install', '5.6.8', '+everything'])
    5) CLIFramework\Application->runWithTry(['/usr/bin/phpbrew', 'install', '5.6.8', '+everything'])
    6) require('phar:///usr/bin/phpbrew/scripts/phpbrew-emb.php')

Does anybody has this to?

Thanks and best regards
Simon

**Comment by marcioAlmada** [comment]
Hi, `+everything` requires you to install a lot of build dependencies. You will be more successful with the `--stdout` and solving error by error:

`phpbrew install --stdout <php-version> +everything`

You will be able to infer, by looking for the error messages, what missing packages you need to install. If you manage to have a dependency list for you env, please share with us on the wiki. It varies from OS to OS and it's nice to share ;)

**Comment by brunowego** [comment]
@marcioAlmada know how fix it?

```bash
[~] phpbrew install --stdout 5.6 +everything                                                                                                                               19:54:52
===> phpbrew will now build 5.6.12
===> Loading and resolving variants...
RuntimeException: libicu not found, please install libicu-dev or libicu library/development files.
Trace:

    0) PhpBrew\VariantBuilder->PhpBrew\{closure}(PhpBrew\Build)
    1) call_user_func_array(Closure, [PhpBrew\Build])
    2) PhpBrew\VariantBuilder->buildVariant(PhpBrew\Build, 'icu', true)
    3) PhpBrew\VariantBuilder->build(PhpBrew\Build)
    4) PhpBrew\Command\InstallCommand->execute('5.6', '+everything')
    5) call_user_func_array([PhpBrew\Command\InstallCommand, 'execute'], ['5.6', '+everything'])
    6) CLIFramework\CommandBase->executeWrapper(['5.6', '+everything'])
    7) CLIFramework\Application->run(['/usr/bin/phpbrew', 'install', '--stdout', '5.6', '+everything'])
    8) CLIFramework\Application->runWithTry(['/usr/bin/phpbrew', 'install', '--stdout', '5.6', '+everything'])
    9) require('phar:///usr/bin/phpbrew/scripts/phpbrew-emb.php')
```

**Comment by marcioAlmada** [comment]
Hi, your missing dependency might be http://site.icu-project.org/, try:

```bash
brew search icu # usually gives you 'icu4c', then:
brew install icu4c
```

After that, move on to the next errors. `+everything` usually requires many dependencies :stuck_out_tongue_winking_eye:

**Comment by brunowego** [comment]
Thanks for reply. I did this installation before, but continue the error.

```bash
[~] brew install icu4c                                                                                                                                                     21:25:12
Warning: icu4c-55.1 already installed
```

**Comment by marcioAlmada** [comment]
Did you try to [configure the lookup prefix](https://github.com/phpbrew/phpbrew/wiki/Cookbook#setting-up-prefered-lookup-prefix) already?

**Comment by brunowego** [comment]
Good answer @marcioAlmada, thanks! But now shows another error, any idea?

```bash
[~] phpbrew known                                                                                                                                                          21:41:02
PHP Fatal error:  Call to undefined function PhpBrew\json_decode() in phar:///usr/bin/phpbrew/PhpBrew/ReleaseList.php on line 2

Fatal error: Call to undefined function PhpBrew\json_decode() in phar:///usr/bin/phpbrew/PhpBrew/ReleaseList.php on line 2
```

**Comment by marcioAlmada** [comment]
That's because phpbrew itself requires the json_extension (to decode the official php release list). You need to install the json extension through your package manager.

**Comment by brunowego** [comment]
@marcioAlmada awesome, thanks again! :+1:

**Comment by c9s** [comment]
FYI, libicu prefix finder is now added to the support.
