### ISSUE TITLE
Content of the CHANGES.md differ from GitHub Releases.

### ISSUE THREAD

**Issue by svetlyak40wt** [phpbrew/phpbrew#550]
Why, are you abandoned adding github releases?

**Comment by marcioAlmada** [comment]
Hi. We are having problems with travis but this will be fixed soon.

**Comment by svetlyak40wt** [comment]
Do you have some sort of automatic translation from CHANGES.md file into the github releases?

**Comment by marcioAlmada** [comment]
Nope. Do you have any suggestion?

**Comment by svetlyak40wt** [comment]
Not yet.

Right now I'm interesting in a way you use github's releases and how do you synchronize it with markdown file. Seems, that most people in this situation just tried github releases once or twice and then returned back to writing plain text files.

What is your case?

**Comment by marcioAlmada** [comment]
Not a fan o github releases mainly because the CHANGELOG file is way more parseable. Also the changelog file is easily transported if you move a private repository to github or the contrary.

**Comment by svetlyak40wt** [comment]
I can't agree with the first part. In generic case, changelog file is not better parsable because there is a lot of version/date/file formats. I know what I'm saying, because I'm working on changelog parsing startup allmychanges.com.

But I completely agree with the second statement. Files are more convenient medium for writing and storing historical data.

However working on my project, rarely I find repositories which use both methods of storing release notes. And that's why I'm interested in your motivation.

**Comment by svetlyak40wt** [comment]
Idea to keep releases in sync with file sounds interesting. May be I'll implement something like that at allmychanges. Thank you.

**Comment by marcioAlmada** [comment]
I'd love to see that, have fun :+1:

**Comment by marcioAlmada** [comment]
The new tags will be pushed soon.

**Comment by svetlyak40wt** [comment]
Thank you, Márcio.
