### ISSUE TITLE
Update of php next fails with wget

### ISSUE THREAD

**Issue by aohorodnyk** [phpbrew/phpbrew#554]
Hello,

I installed php next (php7), it was installed from from repository, but now I want update my phpnext.

How I can update php next to latest commit/release?

Thanks

**Comment by c9s** [comment]
ping @marcioAlmada

**Comment by aohorodnyk** [comment]
@c9s It's not about this question, but gitter channel is live? Or I should leave from gitter channel?

**Comment by marcioAlmada** [comment]
Hi

When phpbrew finds a github download from a branch it will force a redownload. You should be able to update your `next` version by running the exact same command again:

`phpbrew install next as php-7.0.0`

**Comment by marcioAlmada** [comment]
Looks like there is an edge case. If you don't have curl extension, phpbrew will fallback to `wget` and it looks like the command used is never forcing to redownload:

https://github.com/phpbrew/phpbrew/blob/develop/src/PhpBrew/Downloader/UrlDownloader.php#L62

@c9s can we change from - this to +:

```patch
 // check for wget or curl for downloading the php source archive
 if ($this->isWgetCommandAvailable()) {
     $quiet = $this->logger->isQuiet() ? '--quiet' : '';
-        Utils::system("wget --no-check-certificate -c $quiet -O" . $targetFilePath . ' ' . $url);
+        Utils::system("wget --no-check-certificate -c $quiet -nc " . $targetFilePath . ' ' . $url);
 } elseif ($this->isCurlCommandAvailable()) {
     $silent = $this->logger->isQuiet() ? '--silent ' : '';
     Utils::system("curl -C - -L $silent -o" . $targetFilePath . ' ' . $url);

**Comment by marcioAlmada** [comment]
`-N` option seemed the most accurate 740835eb7bf89f6af390b3138e618d78012cf844.

**Comment by marcioAlmada** [comment]
> It's not about this question, but is gitter channel live? Or should I leave from gitter channel?

I'm not very fond to gitter. Opening a github issue is the fastest way to get support, even though it might take one or two days to get a reply.

**Comment by aohorodnyk** [comment]
Thanks
