### ISSUE TITLE
Proxy settings not taken into account without curl

### ISSUE THREAD

**Issue by MrTrustor** [phpbrew/phpbrew#556]
Hello,

The modifications done for issue #241 are not present anymore in src/PhpBrew/ReleaseList.php. When the curl module is not loaded, the proxy options are ignored.

Thank you!

**Comment by larsnystrom** [comment]
It's also not present in src/PhpBrew/Extension/ExtensionDownloader.php. That makes it hard to install xdebug behind a proxy.

**Comment by c9s** [comment]
This seems has been integrated into the extension downloader.

curl extension will be always required if you want to use the proxy settings.
