### ISSUE TITLE
Comments in /etc/timezone file are not stripped 

### ISSUE THREAD

**Issue by pczerkas** [phpbrew/phpbrew#557]
In https://github.com/phpbrew/phpbrew/blob/013b834d029521fa40a240aacd69d29085e1595d/src/PhpBrew/Console.php#L73
`trim(file_get_contents($tz))` call should also strip any comments from contents. Example /etc/timezone file:

```
# this is a comment line
Etc/UTC
```

**Comment by peter279k** [comment]
It's closed and because it's  resolved.
