### ISSUE TITLE
Cannot script PhpBrew

### ISSUE THREAD

**Issue by morozov** [phpbrew/phpbrew#559]
I'd like to script some PhpBrew use cases like installing new PHP version with PECL extensions. It looks like PhpBrew is heavily dependent on shell, so some of its commands cannot be executed from script:

```
↪  cat ./test 
#!/usr/bin/env bash

phpbrew use 5.6.12
↪  ./test 
You should not see this, if you see this, it means you didn't load the ~/.phpbrew/bashrc script, please check if bashrc is sourced in your shell.
```

Same is when `phpbrew` is combined with other unix tools. For instance, as a workaround for #558, the following script still doesn't work:

```
↪  phpbrew list | sed "s/[ \*]//g" | xargs -L1 phpbrew fpm restart
Did you mean 'off'? [Y/n] Exception: You should not see this, if you see this, it means you didn't load the ~/.phpbrew/bashrc script, please check if bashrc is sourced in your shell.
Trace:

    0) PhpBrew\Command\VirtualCommand->execute('restart', 'php-5.6.12')
    1) call_user_func_array([PhpBrew\Command\OffCommand, 'execute'], ['restart', 'php-5.6.12'])
    2) CLIFramework\CommandBase->executeWrapper(['restart', 'php-5.6.12'])
    3) CLIFramework\Application->run(['/usr/bin/phpbrew', 'fpm', 'restart', 'php-5.6.12'])
    4) CLIFramework\Application->runWithTry(['/usr/bin/phpbrew', 'fpm', 'restart', 'php-5.6.12'])
    5) require('phar:///usr/bin/phpbrew/scripts/phpbrew-emb.php')

xargs: phpbrew: exited with status 255; aborting
```

Is there a way to make PhpBrew more scripting-friendly?

**Comment by c9s** [comment]
You must load the ~/.phpbrew/bashrc in new shell environment. because you need to execute `phpbrew` as a shell function instead of the phar file.

**Comment by morozov** [comment]
> You must load the ~/.phpbrew/bashrc in new shell environment. because phpbrew is actually a shell function (not phar file)

@c9s thanks, it works for the test script. But what about `xargs`? I'm running the command in example manually from shell, but it doesn't work.

**Comment by c9s** [comment]
I guess it's because xargs execute command instead of calling the function?

[Sent from iPhone]

**Comment by c9s** [comment]
try while read version in the end:

```
.... | while read version ; do
     echo $version
done
```

**Comment by morozov** [comment]
Cool! It works:
```
phpbrew list | sed "s/[ \*]//g" | while read version ; do
    phpbrew fpm restart $version
done
```

**Comment by morozov** [comment]
@c9s thank you for the solution. Now I understand that `phpbrew` is a function, and this should be taken into consideration when it's used in scripts.

I'm fine with closing this issue as "Working as designed", unless you're aware of any way to improve user experience (i.e. instead of asking "please check if bashrc is sourced in your shell" which I did, detect if it's not an interactive terminal and provide with additional instructions).
