### ISSUE TITLE
How can I install phpbrew with mariadb?

### ISSUE THREAD

**Issue by MartyIX** [phpbrew/phpbrew#566]
Hi,

I have installed MariaDB 10 and I would like to install phpbrew. However the first step for installing phpbrew dependencies returns the following error:

```
me@me-1234:~$ sudo apt-get build-dep php5
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages have unmet dependencies:
 libmysqlclient-dev : Depends: libmysqlclient18 (= 5.6.25-0ubuntu0.15.04.1) but 10.0.21+maria-1~vivid is to be installed
E: Build-dependencies for php5 could not be satisfied.
```

Is there a solution for this?

Thanks!

**Comment by Ronmi** [comment]
As far as I know, `libmysqlclient-dev` does no conflict with `libmariadb-dev` (in Debian, should be same in Ubuntu), so it's okay to install both. Maybe you can try install `libmysqlclient-dev` to solve the dependency.

**Comment by MartyIX** [comment]
I gave up and I used Docker instead of phpbrew. I just wanted to try PHP 7 and I didn't want to break my system.

**Comment by c9s** [comment]
`sudo apt-get build-dep php5` is just a quick way to install the dependencies to build php5, you can manually install other dependencies that don't cause package conflict.
