### ISSUE TITLE
Installing PHP 7 fails with SystemCommandException

### ISSUE THREAD

**Issue by johnbillion** [phpbrew/phpbrew#567]
I'm attempting to install PHP 7 on OS X 10.10.3 with `phpbrew install next`. It fails with the following error:

	PhpBrew\Exception\SystemCommandException: Configure failed: 1
	Trace:
	
	0) PhpBrew\Tasks\ConfigureTask->run(PhpBrew\Build, ['--disable-all', '--enable-phar', '--enable-session', '--enable-short-tags', '--enable-tokenizer', '--with-pcre-regex', '--with-zlib=/usr', '--enable-bcmath', '--with-bz2=/usr', '--enable-calendar', '--enable-cli', '--enable-ctype', '--enable-dom', '--enable-fileinfo', '--enable-filter', '--enable-shmop', '--enable-sysvsem', '--enable-sysvshm', '--enable-sysvmsg', '--enable-json', '--enable-mbregex', '--enable-mbstring', '--with-mhash=/usr/local', '--enable-pcntl', '--with-pcre-regex', '--with-pcre-dir=/usr/local', '--enable-pdo', '--enable-phar', '--enable-posix', '--with-readline=/usr', '--with-libedit=/usr', '--enable-sockets', '--enable-tokenizer', '--enable-dom', '--enable-libxml', '--enable-simplexml', '--enable-xml', '--enable-xmlreader', '--enable-xmlwriter', '--with-xsl', '--with-libxml-dir=/usr', '--with-curl=/usr', '--enable-zip', '--with-openssl=yes'])
	1) PhpBrew\Command\InstallCommand->execute('next')
	2) call_user_func_array([PhpBrew\Command\InstallCommand, 'execute'], ['next'])
	3) CLIFramework\CommandBase->executeWrapper(['next'])
	4) CLIFramework\Application->run(['/usr/bin/phpbrew', 'install', 'next'])
	5) CLIFramework\Application->runWithTry(['/usr/bin/phpbrew', 'install', 'next'])
	6) require('phar:///usr/bin/phpbrew/scripts/phpbrew-emb.php')

Any idea what might be wrong?

Running the command as `phpbrew install next as php-7.0` has the same outcome.

Adding the `--debug` flag I get the following:

	./configure '--prefix=/Users/John/.phpbrew/php/php-master' '--with-config-file-path=/Users/John/.phpbrew/php/php-master/etc' '--with-config-file-scan-dir=/Users/John/.phpbrew/php/php-master/var/db' '--with-pear=/Users/John/.phpbrew/php/php-master/lib/php' '--disable-all' '--enable-phar' '--enable-session' '--enable-short-tags' '--enable-tokenizer' '--with-pcre-regex' '--with-zlib=/usr' '--enable-bcmath' '--with-bz2=/usr' '--enable-calendar' '--enable-cli' '--enable-ctype' '--enable-dom' '--enable-fileinfo' '--enable-filter' '--enable-shmop' '--enable-sysvsem' '--enable-sysvshm' '--enable-sysvmsg' '--enable-json' '--enable-mbregex' '--enable-mbstring' '--with-mhash=/usr/local' '--enable-pcntl' '--with-pcre-regex' '--with-pcre-dir=/usr/local' '--enable-pdo' '--enable-phar' '--enable-posix' '--with-readline=/usr' '--with-libedit=/usr' '--enable-sockets' '--enable-tokenizer' '--enable-dom' '--enable-libxml' '--enable-simplexml' '--enable-xml' '--enable-xmlreader' '--enable-xmlwriter' '--with-xsl' '--with-libxml-dir=/usr' '--with-curl=/usr' '--enable-zip' '--with-openssl=yes' >> /Users/John/.phpbrew/build/php-master/build.log 2>&1
	
	PhpBrew\Exception\SystemCommandException: Configure failed: 1
	Thrown from phar:///usr/bin/phpbrew/PhpBrew/Tasks/ConfigureTask.php at line 2:
	
	    1<?php
	>   2namespace PhpBrew\Tasks; use PhpBrew\Exception\SystemCommandException; use RuntimeException; use PhpBrew\CommandBuilder; use PhpBrew\Config; use PhpBrew\Build; class ConfigureTask extends BaseTask { public $optimizationLevel; public function setLogPath($path) { $this->logPath = $path; } public function setOptimizationLevel($optimizationLevel) { $this->optimizationLevel = $optimizationLevel; } public function run(Build $build, $variantOptions) { $extra = $build->getExtraOptions(); if (!file_exists( $build->getSourceDirectory() . DIRECTORY_SEPARATOR . 'configure')) { $this->debug("configure file not found, running buildconf script..."); $lastline = system('./buildconf', $status); if ($status !== 0) { throw new SystemCommandException("buildconf error: $lastline"); } } $prefix = $build->getInstallPrefix(); if ($this->optimizationLevel) { $o = $this->optimizationLevel; $cflags = getenv('CFLAGS'); putenv("CFLAGS=$cflags -O$o"); $_ENV['CFLAGS'] = "$cflags -O$o"; } $args = array(); $args[] = "--prefix=" . $prefix; if ($this->options->{'user-config'}) { $args[] = "--with-config-file-path={$prefix}/etc"; $args[] = "--with-config-file-scan-dir={$prefix}/var/db"; } else { $args[] = "--with-config-file-path={$prefix}/etc"; $args[] = "--with-config-file-scan-dir={$prefix}/var/db"; } $args[] = "--with-pear={$prefix}/lib/php"; if ($variantOptions) { $args = array_merge($args, $variantOptions); } $this->debug('Enabled variants: ' . join(', ', array_keys($build->getVariants()))); $this->debug('Disabled variants: ' . join(', ', array_keys($build->getDisabledVariants()))); foreach ((array) $this->options->patch as $patchPath) { $this->info("===> Applying patch file from $patchPath ..."); for ($i = 0; $i <= 16; $i++) { ob_start(); system("patch -p$i --dry-run < $patchPath", $return); ob_end_clean(); if ($return === 0) { system("patch -p$i < $patchPath"); break; } } } if ($build->isEnabledVariant('apxs2')) { $apxs2Checker = new \PhpBrew\Tasks\Apxs2CheckTask($this->logger); $apxs2Checker->check($build, $this->options); $apxs2Patch = new \PhpBrew\Tasks\Apxs2PatchTask($this->logger); $apxs2Patch->patch($build, $this->options); } foreach ($extra as $a) { $args[] = $a; } $cmd = new CommandBuilder('./configure'); $cmd->args($args); $buildLogPath = $build->getBuildLogPath(); if (file_exists($buildLogPath)) { $newPath = $buildLogPath . '.' . filemtime($buildLogPath); $this->info("Found existing build.log, renaming it to $newPath"); rename($buildLogPath,$newPath); } $this->info("===> Configuring {$build->version}..."); $cmd->setAppendLog(true); $cmd->setLogPath($buildLogPath); $cmd->setStdout($this->options->{'stdout'}); $this->logger->info("\n"); $this->logger->info("Use tail command to see what's going on:"); $this->logger->info("   $ tail -F $buildLogPath\n\n"); $this->debug($cmd->getCommand()); if ($this->options->nice) { $cmd->nice($this->options->nice); } if (!$this->options->dryrun) { $code = $cmd->execute(); if ($code != 0) { throw new SystemCommandException("Configure failed: $code", $buildLogPath); } } if (!$this->options->{'no-patch'}) { $patch64bit = new \PhpBrew\Tasks\Patch64BitSupportTask($this->logger, $this->options); if ($patch64bit->match($build)) { $patch64bit->patch($build); } } $build->setState(Build::STATE_CONFIGURE); } }
	PHP Notice:  Undefined offset: 2 in phar:///usr/bin/phpbrew/CLIFramework/ExceptionPrinter/DevelopmentExceptionPrinter.php on line 2
	
	Notice: Undefined offset: 2 in phar:///usr/bin/phpbrew/CLIFramework/ExceptionPrinter/DevelopmentExceptionPrinter.php on line 2
	    3
	
	Trace:
	
	    0) PhpBrew\Tasks\ConfigureTask->run(PhpBrew\Build, ['--disable-all', '--enable-phar', '--enable-session', '--enable-short-tags', '--enable-tokenizer', '--with-pcre-regex', '--with-zlib=/usr', '--enable-bcmath', '--with-bz2=/usr', '--enable-calendar', '--enable-cli', '--enable-ctype', '--enable-dom', '--enable-fileinfo', '--enable-filter', '--enable-shmop', '--enable-sysvsem', '--enable-sysvshm', '--enable-sysvmsg', '--enable-json', '--enable-mbregex', '--enable-mbstring', '--with-mhash=/usr/local', '--enable-pcntl', '--with-pcre-regex', '--with-pcre-dir=/usr/local', '--enable-pdo', '--enable-phar', '--enable-posix', '--with-readline=/usr', '--with-libedit=/usr', '--enable-sockets', '--enable-tokenizer', '--enable-dom', '--enable-libxml', '--enable-simplexml', '--enable-xml', '--enable-xmlreader', '--enable-xmlwriter', '--with-xsl', '--with-libxml-dir=/usr', '--with-curl=/usr', '--enable-zip', '--with-openssl=yes'])
	        from phar:///usr/bin/phpbrew/PhpBrew/Command/InstallCommand.php: 2
	
	    1) PhpBrew\Command\InstallCommand->execute('next')
	PHP Notice:  Undefined index: file in phar:///usr/bin/phpbrew/CLIFramework/ExceptionPrinter/DevelopmentExceptionPrinter.php on line 2
	
	Notice: Undefined index: file in phar:///usr/bin/phpbrew/CLIFramework/ExceptionPrinter/DevelopmentExceptionPrinter.php on line 2
	PHP Notice:  Undefined index: line in phar:///usr/bin/phpbrew/CLIFramework/ExceptionPrinter/DevelopmentExceptionPrinter.php on line 2
	
	Notice: Undefined index: line in phar:///usr/bin/phpbrew/CLIFramework/ExceptionPrinter/DevelopmentExceptionPrinter.php on line 2
	        from : 0
	
	    2) call_user_func_array([PhpBrew\Command\InstallCommand, 'execute'], ['next'])
	        from phar:///usr/bin/phpbrew/CLIFramework/CommandBase.php: 2
	
	    3) CLIFramework\CommandBase->executeWrapper(['next'])
	        from phar:///usr/bin/phpbrew/CLIFramework/Application.php: 2
	
	    4) CLIFramework\Application->run(['/usr/bin/phpbrew', '--debug', 'install', 'next'])
	        from phar:///usr/bin/phpbrew/CLIFramework/Application.php: 2
	
	    5) CLIFramework\Application->runWithTry(['/usr/bin/phpbrew', '--debug', 'install', 'next'])
	        from phar:///usr/bin/phpbrew/scripts/phpbrew-emb.php: 2
	
	    6) require('phar:///usr/bin/phpbrew/scripts/phpbrew-emb.php')
	        from /usr/bin/phpbrew: 6

**Comment by jhdxr** [comment]
this log usually means there is something wrong while compiling the php, and it's not somewrong with phpbrew. You should read the build log, which may locate in `~/.phpbrew/build/php-master/build.log` to figure out what happend.

**Comment by marcioAlmada** [comment]
@jhdxr thanks for helping with the issues :)

@johnbillion  I could not reproduce this, so it might be some required dependency on your environment. Please refer to our wiki or copy/paste your build log on a gist and share here.

**Comment by solcik** [comment]
These helped me.-)

brew install bison
brew install re2c
brew link bison --force

phpbrew install next as php-7.0.0RC3

**Comment by johnbillion** [comment]
Thank you, @solcik. I already had `re2c` installed, but installing `bison` fixed the issue for me, and PHP 7 installed correctly.

**Comment by marcioAlmada** [comment]
Just a reminder that `bison` is listed on the requirements section :) https://github.com/phpbrew/phpbrew/wiki/Requirement

**Comment by johnbillion** [comment]
It's not actually listed as a requirement for OS X, only Ubuntu and Fedora.

**Comment by marcioAlmada** [comment]
It's listed now. Thank you.
