### ISSUE TITLE
thoughs about refactoring downloading related

### ISSUE THREAD

**Issue by jhdxr** [phpbrew/phpbrew#571]
There are lots of issue about download, especially proxy related ( for example #556 ). and I see this one in the TODO.md
> Ability to switch curl, wget or pure php downloader.

So I think it's time to refactor the download part. 
I'm not sure if it's part of your plan, but if so I'm glad to do this part.

Here are some ideas I planned:
1. refactor `UrlDownloader` to support pure php download (`file_get_contents`?)
2. refactore `UrlDownloader` to add the proxy support for bash command (`wget`/`curl`) and pure php methods (using stream_context)
3. refactore `UrlDownloader` to add the ability to switch the download method.
4. refactore the related codes, using `UrlDownloader` or something based on it to deal with the network request, instead of doing their own downloading everywhere

**Comment by marcioAlmada** [comment]
Hi, I'm not having much time to push fixes and releases lately, but FYI this improvement would be really welcome!
