### ISSUE TITLE
opcode error with composer and phpunit

### ISSUE THREAD

**Issue by ciatog** [phpbrew/phpbrew#572]
I had PHP 5.5.28 installed on my Ubuntu machine with everything working as expected.

I decided to start using phpbrew to make upgrading to PHP 5.6 easier. To start with I just installed the same version of PHP that I have on my machine: phpbrew install 5.5.28 +default+dbs+debug+apxs2 (I also installed 5.6.12, with xdebug, and got the same errors)

After doing so everything worked great with 2 exceptions: phpunit and composer. Both commands run to completion but right at the end I get fatal opcode errors which cause issues with the CI server. 

As an example I get the following at the end of running phpunit (4.6.10):
PHP Fatal error:  Invalid opcode 65/16/8. in phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php on line 0

Fatal error: Invalid opcode 65/16/8. in phar:///usr/local/bin/phpunit/phpunit/TextUI/Command.php on line 0

Let me know if you need any further details. Any help would be greatly appreciated. Thanks

**Comment by jhdxr** [comment]
Did you installe eaccelerator or some similar?

**Comment by ciatog** [comment]
Hey jhdxr.

eaccellerator isn't installed. I did install uopz and decided to remove that temporarily and the fatal errors went away so it looks to be an issue with that and not phpbrew. 

Thanks for the response and I'll just go ahead and close the issue.

**Comment by jhdxr** [comment]
I think you may refer to krakjoe/uopz#19 , which has an explanation of this fatal error.
