### ISSUE TITLE
The url paths to download the php version is maybe not correct.

### ISSUE THREAD

**Issue by mikethejet** [phpbrew/phpbrew#573]
===> phpbrew will now build 5.4.16
You haven't set any variant. A default set of extensions will be installed for the minimum requirement:
[bcmath, bz2, calendar, cli, ctype, dom, fileinfo, filter, ipc, json, mbregex, mbstring, mhash, pcntl, pcre, pdo, phar, posix, readline, sockets, tokenizer, xml,ip, openssl]
Please run 'phpbrew variants' for more information.

===> Loading and resolving variants...
===> Downloading from http://www.php.net/get/php-5.4.16.tar.bz2/from/this/mirror
[==================================================================] 184.00/184.00B 100%
Redirecting to http://php.net/get/php-5.4.16.tar.bz2/from/this/mirror
The requested URL returned error: 404 Not Found

**Comment by c9s** [comment]
5.4.16 is not maintained on php.net anymore.
