### ISSUE TITLE
~/.phpbrew directory must be created before using phpbrew

### ISSUE THREAD

**Issue by netroby** [phpbrew/phpbrew#575]
```
Redirecting to https://secure.php.net/releases/index.php?json&version=5&max=100
PHP Warning:  file_put_contents(/home/huzhifeng/.phpbrew/php-releases.json): failed to open stream: No such file or directory in phar:///home/huzhifeng/ops-code/bin/phpbrew/PhpBrew/ReleaseList.php on line 2
Exception: Can't store release json file
Trace:

    0) PhpBrew\ReleaseL
```

fresh installed phpbrew will not auto create ~/.phpbrew directory, so installation was failed.

**Comment by marcioAlmada** [comment]
Did you `phpbrew init`?

**Comment by netroby** [comment]
This step can be automatic? i omit it

**Comment by marcioAlmada** [comment]
It probably can, but it could become a PITA to have the init check before every executed command, so the install instructions explicitly tell you to run `phpbrew init` during installation. Please check the installation guide and the wiki.

**Comment by jeff-h** [comment]
I know this issue is ancient, but I hit the same thing. I think it would be clearer if the `phpbrew init` instruction was moved into the Installation section. Happy to create a PR if you agree.

**Comment by morozov** [comment]
@jeff-h could you please provide more details about how the issue is reproducible? Maybe because of documenting we could fix it or at least improve the UX. Then document the remaining details.

**Comment by jeff-h** [comment]
Sure — it was 100% user error 🤪 Basically I didn't realise that running `phpbrew init` was a mandatory part of initial installation. A very minor shuffle of the documentation ([proposed PR](https://github.com/phpbrew/phpbrew/pull/1119)) makes it much clearer for me at least.
