### ISSUE TITLE
fmp doesn't stop nicely

### ISSUE THREAD

**Issue by x00** [phpbrew/phpbrew#580]
+default+fpm+pdo+mysql+curl+gd

php-5.3.3
php-5.3.29
php-5.4.41
php-5.4.43
php-5.5.9
php-5.5.26
php-5.6.9
php-5.6.12

Linux Mint 17 Qiana

when stopping it doesn't usually kill the process. They is usually three or more processes (one master)

I connect through 9000 port via nginx, not sure why that would be relevant but whatever. 

I have to `ps -aux | grep php-fpm` then manual `sudo kill -9` each process.

**Comment by c9s** [comment]
You ran `fpm stop` ?

**Comment by morozov** [comment]
Closing due to lack of feedback.
