### ISSUE TITLE
Issues with instalation

### ISSUE THREAD

**Issue by RybalkaDenis** [phpbrew/phpbrew#582]
sudo phpbrew install 5.4.5 +default +fpm
===> phpbrew will now build 5.4.5
===> Loading and resolving variants...
Checking distribution checksum...
Checksum matched: ffcc7f4dcf2b79d667fe0c110e6cb724
===> Distribution file was successfully extracted, skipping...
Found existing Makefile, running make clean to ensure everything will be rebuilt.
You can append --no-clean option after the install command if you don't want to rebuild.
===> Running make clean: make -C /home/d/.phpbrew/build/php-5.4.5 --quiet clean
Found existing build.log, renaming it to /home/d/.phpbrew/build/php-5.4.5/build.log.1442957565
===> Configuring 5.4.5...

Use tail command to see what's going on:
   $ tail -F /home/d/.phpbrew/build/php-5.4.5/build.log

===> Building...

PhpBrew\Exception\SystemCommandException: Make failed.
Trace:

    0) PhpBrew\Tasks\BuildTask->run(PhpBrew\Build)
    1) PhpBrew\Command\InstallCommand->execute('5.4.5', '+default', '+fpm')
    2) call_user_func_array([PhpBrew\Command\InstallCommand, 'execute'], ['5.4.5', '+default', '+fpm'])
    3) CLIFramework\CommandBase->executeWrapper(['5.4.5', '+default', '+fpm'])
    4) CLIFramework\Application->run(['/usr/bin/phpbrew', 'install', '5.4.5', '+default', '+fpm'])
    5) CLIFramework\Application->runWithTry(['/usr/bin/phpbrew', 'install', '5.4.5', '+default', '+fpm'])
    6) require('phar:///usr/bin/phpbrew/scripts/phpbrew-emb.php')

**Comment by RybalkaDenis** [comment]
P.S I've tried to modify my .bashrc(~/.phpbrew/bashrc was added in it ).
I might doing something wrong.

**Comment by c9s** [comment]
cat you paste the log? `/home/d/.phpbrew/build/php-5.4.5/build.log`

**Comment by c9s** [comment]
And I am not sure if 5.4.5 is working now, how about building the latest 5.4?

```
sudo phpbrew install 5.4 +default +fpm
```

**Comment by RybalkaDenis** [comment]
===> Building...
make >> /home/d/.phpbrew/build/php-5.4.0/build.log 2>&1

PhpBrew\Exception\SystemCommandException: Make failed.
Thrown from phar:///usr/bin/phpbrew/PhpBrew/Tasks/BuildTask.php at line 2:

    1<?php
>   2namespace PhpBrew\Tasks; use PhpBrew\Exception\SystemCommandException; use PhpBrew\CommandBuilder; use PhpBrew\Build; class BuildTask extends BaseTask { public function run(Build $build, $targets = array()) { if ($build->getState() >= Build::STATE_BUILD) { $this->info("===> Already built, skipping..."); return; } $this->info("===> Building..."); $cmd = new CommandBuilder('make'); $cmd->setAppendLog(true); $cmd->setLogPath($build->getBuildLogPath()); $cmd->setStdout($this->options->{'stdout'}); if (!empty($targets)) { foreach ($targets as $t) { $cmd->addArg($t); } } if ($this->options->nice) { $cmd->nice($this->options->nice); } if ($makeJobs = $this->options->{'jobs'}) { $cmd->addArg("-j{$makeJobs}"); } $this->debug($cmd->getCommand()); if (!$this->options->dryrun) { $startTime = microtime(true); $code = $cmd->execute(); if ($code != 0) { throw new SystemCommandException('Make failed.', $build->getBuildLogPath()); } $buildTime = round((microtime(true) - $startTime) / 60, 1); $this->info("Build finished: $buildTime minutes."); } $build->setState(Build::STATE_BUILD); } }
PHP Notice:  Undefined offset: 2 in phar:///usr/bin/phpbrew/CLIFramework/ExceptionPrinter/DevelopmentExceptionPrinter.php on line 2
    3

Trace:

    0) PhpBrew\Tasks\BuildTask->run(PhpBrew\Build)
        from phar:///usr/bin/phpbrew/PhpBrew/Command/InstallCommand.php: 2

    1) PhpBrew\Command\InstallCommand->execute('5.4.0', '+default', '+fpm')
PHP Notice:  Undefined index: file in phar:///usr/bin/phpbrew/CLIFramework/ExceptionPrinter/DevelopmentExceptionPrinter.php on line 2
PHP Notice:  Undefined index: line in phar:///usr/bin/phpbrew/CLIFramework/ExceptionPrinter/DevelopmentExceptionPrinter.php on line 2
        from : 0

    2) call_user_func_array([PhpBrew\Command\InstallCommand, 'execute'], ['5.4.0', '+default', '+fpm'])
        from phar:///usr/bin/phpbrew/CLIFramework/CommandBase.php: 2

    3) CLIFramework\CommandBase->executeWrapper(['5.4.0', '+default', '+fpm'])
        from phar:///usr/bin/phpbrew/CLIFramework/Application.php: 2

    4) CLIFramework\Application->run(['/usr/bin/phpbrew', '--debug', 'install', '5.4.0', '+default', '+fpm'])
        from phar:///usr/bin/phpbrew/CLIFramework/Application.php: 2

    5) CLIFramework\Application->runWithTry(['/usr/bin/phpbrew', '--debug', 'install', '5.4.0', '+default', '+fpm'])
        from phar:///usr/bin/phpbrew/scripts/phpbrew-emb.php: 2

    6) require('phar:///usr/bin/phpbrew/scripts/phpbrew-emb.php')
        from /usr/bin/phpbrew: 6

**Comment by RybalkaDenis** [comment]
Build.log
/bin/bash /home/d/.phpbrew/build/php-5.4.0/libtool --silent --preserve-dup-deps --mode=compile cc  -Iext/dom/ -I/home/d/.phpbrew/build/php-5.4.0/ext/$
/bin/bash /home/d/.phpbrew/build/php-5.4.0/libtool --silent --preserve-dup-deps --mode=compile cc  -Iext/dom/ -I/home/d/.phpbrew/build/php-5.4.0/ext/$
/bin/bash /home/d/.phpbrew/build/php-5.4.0/libtool --silent --preserve-dup-deps --mode=compile cc  -Iext/dom/ -I/home/d/.phpbrew/build/php-5.4.0/ext/$
/bin/bash /home/d/.phpbrew/build/php-5.4.0/libtool --silent --preserve-dup-deps --mode=compile cc  -Iext/dom/ -I/home/d/.phpbrew/build/php-5.4.0/ext/$
/bin/bash /home/d/.phpbrew/build/php-5.4.0/libtool --silent --preserve-dup-deps --mode=compile cc  -Iext/dom/ -I/home/d/.phpbrew/build/php-5.4.0/ext/$
/bin/bash /home/d/.phpbrew/build/php-5.4.0/libtool --silent --preserve-dup-deps --mode=compile cc  -Iext/dom/ -I/home/d/.phpbrew/build/php-5.4.0/ext/$
/bin/bash /home/d/.phpbrew/build/php-5.4.0/libtool --silent --preserve-dup-deps --mode=compile cc  -Iext/dom/ -I/home/d/.phpbrew/build/php-5.4.0/ext/$
/bin/bash /home/d/.phpbrew/build/php-5.4.0/libtool --silent --preserve-dup-deps --mode=compile cc  -Iext/dom/ -I/home/d/.phpbrew/build/php-5.4.0/ext/$
/home/d/.phpbrew/build/php-5.4.0/ext/dom/node.c: In function ‘dom_canonicalization’:
/home/d/.phpbrew/build/php-5.4.0/ext/dom/node.c:1898:21: error: dereferencing pointer to incomplete type
    ret = buf->buffer->use;
                     ^
In file included from /home/d/.phpbrew/build/php-5.4.0/main/php.h:38:0,
                 from /home/d/.phpbrew/build/php-5.4.0/ext/dom/node.c:26:
/home/d/.phpbrew/build/php-5.4.0/ext/dom/node.c:1900:40: error: dereferencing pointer to incomplete type
     RETVAL_STRINGL((char *) buf->buffer->content, ret, 1);
                                        ^
/home/d/.phpbrew/build/php-5.4.0/Zend/zend_API.h:571:20: note: in definition of macro ‘ZVAL_STRINGL’
   const char *__s=(s); int __l=l;   \
                    ^
/home/d/.phpbrew/build/php-5.4.0/ext/dom/node.c:1900:5: note: in expansion of macro ‘RETVAL_STRINGL’
     RETVAL_STRINGL((char *) buf->buffer->content, ret, 1);
     ^
make: *** [ext/dom/node.lo] Ошибка 1

**Comment by c9s** [comment]
Not sure why, but the build.log seems it's php's building issue, which does not belong to phpbrew.
