### ISSUE TITLE
$_ is always _phpbrewrc_load?

### ISSUE THREAD

**Issue by mfdj** [phpbrew/phpbrew#589]
I just started using phpbrew and noticed an unexpected behavior around BASH's `$_` [last-argument variable](http://tldp.org/LDP/abs/html/internalvariables.html). A quick demo use case, make a directory and change into it:
```
$ mkdir asdf && cd $_
```
It's a handy construct I use quite a bit. So imagine my surprise when I `source ~/.phpbrew/bashrc` and `echo $_` it's will always `_phpbrewrc_load`?

I'm pretty new to phpbrew so maybe it's a misconfiguration on my part but after checking out [pull #233](https://github.com/phpbrew/phpbrew/pull/233) it seems like some auto-loading magic. 

FWIW I also use `nvm` which is purely manual and `rbenv` which is purely magical — both work quite well. NVM uses `nvm use` to switch the version according to `.nvmrc` and ruby-env changes the version for you in a way that doesn't effect `$_`.

A small bit of feedback — overally, phpbrew is doing great work. Thanks to all the maintainers!

**Comment by GaryJones** [comment]
![screenshot 2016-02-18 15 58 58](https://cloud.githubusercontent.com/assets/88371/13149226/9b3288fc-d658-11e5-9f0a-952ea0ee0b3c.png)

I use Oh My Zsh, with the [SCD](https://github.com/robbyrussell/oh-my-zsh/blob/master/plugins/scd/scd) plugin, and I get the above screenshot issues, which is probably a symptom of the same issue mentioned.

**Comment by c9s** [comment]
The `_phpbrewrc_load` feature is disabled by default this year (I don't remember which release it includes).

the reload function was re-written because the previous one was buggy. If you still encounter this issue after running self-update, please ping me.

**Comment by c9s** [comment]
Not sure if it's related to `trap "_phpbrewrc_load" DEBUG` ?

**Comment by mfdj** [comment]
I just grabbed the newest (as of this comment https://github.com/phpbrew/phpbrew/tree/9bfdd118f89c13f8d3951741bf7b3c3f481be6a1) and can confirm the issue is resolved!

**Comment by c9s** [comment]
Thanks for confirming this issue. :)

Mark Fox <notifications@github.com> 於 2016年4月30日 星期六寫道：
