### ISSUE TITLE
bash: [: too many arguments

### ISSUE THREAD

**Issue by rtheunissen** [phpbrew/phpbrew#590]
During `source ~/.phpbrew/bashrc`, the script fails.

On line 470 of `bashrc`, 

```bash
[ -z "$PHPBREW_RC_DISCOVERY_ACROSS_FILESYSTEM" -a $prev_fs -ne 0 -a $curr_fs -ne $prev_fs ]
```

resolves to `[ -z '' -a 0 -ne 0 -a -ne 0 ]`, which causes the `too many arguments` error.

Might be because I updated to El Capitan recently.

**Comment by morozov** [comment]
@rtheunissen I don't have any of OSX, so I don't know what the problem on El Capitan might be. Is it a typo or there's really no value for `$curr_fs`?

**Comment by rtheunissen** [comment]
There was no `$curr_fs` because `/etc/profile` wasn't sourced by the system on startup.
