### ISSUE TITLE
Cannot install PHP 5.3.10

### ISSUE THREAD

**Issue by rmuktader** [phpbrew/phpbrew#591]
running `phpbrew install 5.3.10 +default` gives me  `Exception: Version 5.3.10 not found.` But I see this command in your documentation.  Did you stop supporting this php version?  If so, is there a way for me to still install it?

**Comment by marcioAlmada** [comment]
Hi, if you can't install a specific minor version try another minor one: `phpbrew install 5.3.29` or simply `phpbrew install 5.3`.

This happens because sometimes minor versions are moved around to the museum on php.net side.
