### ISSUE TITLE
phpbrew doesn't work !

### ISSUE THREAD

**Issue by Michael-Nourry** [phpbrew/phpbrew#593]
There is a problem with the json : 
(version 1.20.1)
 phpbrew known
RuntimeException: Can't decode release json, invalid JSON string: HTTP/1.1 200 OK
Content-Security-Policy: default-src 'none'
X-XSS-Protection: 1; mode=block
X-Frame-Options: deny
X-Conte
Trace:

    0) PhpBrew\ReleaseList->loadJson('HTTP/1.1 200 OK
Content-Security-Policy: default-src \'none\'
X-XSS-Protection: 1; mode=block
X-Frame-Options: deny
X-Content-Type-Options: nosniff
Strict-Transport-Security: max-age=31536000
ETag: "d3b269a3a27f21f45180fcfe862adc935e155c6e"
Content-Type: text/plain; charset=utf-8
........................

        "name": "PHP 5.3.6 (tar.bz2)"
        },
        "5.3.5": {
            "version": "5.3.5",
            "announcement": "http://php.net/releases/5_3_5.php",
            "date": "06 January 2011",
            "filename": "php-5.3.5.tar.bz2",
            "md5": "8aaf20c95e91f25c5b6a591e5d6d61b9",
            "name": "PHP 5.3.5 (tar.bz2)"
        }
    }
}')
    1) PhpBrew\ReleaseList->loadJsonFile('/root/.phpbrew/php-releases.json')
    2) PhpBrew\ReleaseList->loadLocalReleaseList()
    3) PhpBrew\Command\KnownCommand->execute()
    4) call_user_func_array([PhpBrew\Command\KnownCommand, 'execute'], [])
    5) CLIFramework\CommandBase->executeWrapper([])
    6) CLIFramework\Application->run(['/usr/bin/phpbrew', 'known'])
    7) CLIFramework\Application->runWithTry(['/usr/bin/phpbrew', 'known'])
    8) require('phar:///usr/bin/phpbrew/scripts/phpbrew-emb.php')

**Comment by Michael-Nourry** [comment]
If i run :+1: curl https://raw.githubusercontent.com/phpbrew/phpbrew/develop/assets/php-releases.json > ~/.phpbrew/php-releases.json
it's work ....

**Comment by marcioAlmada** [comment]
Please, upgrade your phpbrew with `phpbrew self-update` and use `phpbrew update` to fetch the release list. The `php-releases.json` was deprecated when `https://secure.php.net/releases/index.php?json&version=5&max=100` was created on php.net side.

Do not rely `php-releases.json` for anything, it will disappear from this repository sooner or later.

**Comment by Michael-Nourry** [comment]
Le 15/10/2015 19:09, Márcio Almada a écrit :
> Please, upgrade your phpbrew with |phpbrew self-update| and use |phpbrew
> update| to fetch the release list. The |php-releases.json| was
> deprecated when
> |https://secure.php.net/releases/index.php?json&version=5&max=100| was
> created on php.net side.
>
> Do not rely |php-releases.json| for anything, it will disappear from
> this repository sooner or later.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phpbrew/phpbrew/issues/593#issuecomment-148460302>.
>
Hello,
I did seflupdate and update but doesn't work
I'll test https://secure.php.net/releases/index.php?json&version=5&max=100

-- 
Michaël
