### ISSUE TITLE
Allow VersionDslParser to process Alpha/Beta/RC

### ISSUE THREAD

**Issue by kohenkatz** [phpbrew/phpbrew#599]
Right now, only release versions can be downloaded by providing the full URL to the download.

The following change to the Regular Expression in the VersionDslParser will also allow downloading Alpha, Beta, and Release Candidate versions:

    (php-(\d.\d+.\d+(?:(?:RC|alpha|beta)\d+)?)\.tar\.(?:gz|bz2))

Confirmed working at: http://www.phpliveregex.com/p/djz

**Comment by c9s** [comment]
Looks godd! Would be great if you can have a PR for this :)

**Comment by kohenkatz** [comment]
@c9s I'll do that.
