### ISSUE TITLE
apxs2 on El Capitan

### ISSUE THREAD

**Issue by aldoreyes** [phpbrew/phpbrew#606]
Hi,

Thanks for a great tool, I just updated to el capitan, and one of it's features is that it doesn't let you modify folders that belong to the OS or are related to it, not even using sudo.

My issue is that when I try to install a php version with variant apxs2 it gives me the following message:

```
Apache module dir /usr/libexec/apache2 is not writable.
Please consider using chmod to change the folder permission:
$ sudo chmod -R oga+rw /usr/libexec/apache2
```

The problem is that we can't change the permissions of that folder, I know there are [ways](http://apple.stackexchange.com/questions/208478/how-do-i-disable-system-integrity-protection-sip-aka-rootless-on-max-os-x-el) to disable this rootless feature, but I was wondering if there is a way to install the apache module without having to do this, from what I see this error happens when the libphpX.X.X.so file is  being created on this folder, not sure if there is already a way to set the output folder for the generated file so that we can set it to something else i.e. /usr/local/libexec/apache2.

Thanks

**Comment by williamukoh** [comment]
This issue hasn't been resolved?

**Comment by matzke** [comment]
references #553

**Comment by peter279k** [comment]
The issue is outdated and closed now.
