### ISSUE TITLE
OS X El Capitan (10.11.1) OpenSSL build issue

### ISSUE THREAD

**Issue by rmangino** [phpbrew/phpbrew#607]
I'm trying to use `phpbrew` for the first time to install php on OS X 10.11.1.

`$ phpbrew install 5.6.15 +default`

Failure:
`configure: error: Cannot find OpenSSL's libraries`
` ([full build log](https://gist.github.com/rmangino/2e2d9abc4db34946b2f2)) 

I've done `brew install openssl` which succeeds but reports:

`$ brew install openssl
==> Downloading https://homebrew.bintray.com/bottles/openssl-1.0.2d_1.el_capitan.bottle.tar.gz
Already downloaded: /Library/Caches/Homebrew/openssl-1.0.2d_1.el_capitan.bottle.tar.gz
==> Pouring openssl-1.0.2d_1.el_capitan.bottle.tar.gz
==> Caveats
A CA file has been bootstrapped using certificates from the system
keychain. To add additional certificates, place .pem files in
  /usr/local/etc/openssl/certs

and run
  /usr/local/opt/openssl/bin/c_rehash

This formula is keg-only, which means it was not symlinked into /usr/local.

Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include`

How can I get `phpbrew` to use those values?

Thanks!

**Comment by eazabi** [comment]
i have the same problem :( can someone help ?

**Comment by konomae** [comment]
Same here.
We should read this first: https://github.com/phpbrew/phpbrew/wiki/Trouble-Shooting:-Can't-build-PHP-on-OS-X-El-Capitan

I solved the problem in several ways.

## Extra Configure Options
If you don't want `brew link --force openssl`, you can override build config by using extra configure options.
https://github.com/phpbrew/phpbrew#extra-configure-options

```bash
$ phpbrew install 5.6.15 +default -- --with-openssl=/usr/local/opt/openssl

## By the way
## Using variant option with +default does not work:
## phpbrew install 5.6.15 +default +openssl=/usr/local/opt/openssl
```
PhpBrew generates configure option bellow:

```
--with-openssl=/usr --with-openssl=/usr/local/opt/openssl
```

## Force Link
You can use `brew link --force openssl`.
```bash
$ brew link --force openssl
$ phpbrew install 5.6.15 +default
```
PhpBrew generates configure option bellow:

```
--with-openssl=/usr/local
```
---

Generated configure options can be found here:
`~/.phpbrew/build/php-5.6.15/config.log`

**Comment by morozov** [comment]
@c9s please correct me if I'm wrong but in case of homebrew, `Utils::findIncludePrefix()` doesn't do its job for openssl. Instead of searching for `/usr/local/Cellar/openssl/1.0.2d_1/include/openssl/opensslv.h` to detect prefix, it searches for `/usr/local/Cellar/include/openssl/opensslv.h` and fails. I.e. in case of the homebrew lookup prefix, it misses the fact that homebrew isolates every package in its name/version subdirectory.

In the same way it seems not working for `curl` and most probably all other dependencies installed via homebrew.

**Comment by c9s** [comment]
@morozov you're correct. since homebrew isolated the packages in Cellar, I think the lookup prefix should be modified to support this...

**Comment by c9s** [comment]
I added more fallback paths to openssl variant, however I think the best solution is to lookup prefix through the command from homebrew.
