### ISSUE TITLE
404 on https://pecl.php.net/rest/r/mysql/5.3.29.xml (and others)

### ISSUE THREAD

**Issue by martijntraa** [phpbrew/phpbrew#608]
When trying to `phpbrew ext install mysql` I found out phpbrew fails to download `https://pecl.php.net/rest/r/mysql/5.3.29.xml` and therefor fails to build the mysql extension with the error `Exception: Invalid package version: mysql @`

I've also tried adding a different version number, like `5.3.23` or `5.4.45` or `stable`, but those 404 too. 

In simular fashion, `phpbrew ext known mysql` fails because `http://pecl.php.net/rest/r/mysql/allreleases.xml` returns a 404.

Is this a temporary problem? Is there any way I can work around this?

It appears this problem doesn't occur for the extensions `mysqli`, `pdo_mysql` and `pdo_sqlite`.

**Comment by c9s** [comment]
I think you're missing php source code on your file system. did you install any php via phpbrew? please make sure you've selected one php from the list.

**Comment by martijntraa** [comment]
I did compile/install a version using phpbrew:

    export PHPBREW_ROOT=/opt/phpbrew

    phpbrew install 5.3.29 \
    +default +dba +ipv6 +wddx +ftp +hash +exif +cgi +soap +session +imap \
    +tidy +xmlrpc +zlib +gettext +iconv -- \
    --with-gd \
    --with-config-file-path=/etc/php5.3/cgi \
    --with-config-file-scan-dir=/etc/php5.3/cgi/conf.d \
    --with-mysql-sock=/var/run/mysqld/mysqld.sock

    phpbrew use 5.3.29

    phpbrew ext install imagick
    phpbrew ext install apc
    phpbrew ext install pspell
    phpbrew ext install imap -- --with-imap-ssl --with-kerberos

This all compiles beautifully and I can use it without problems.

The directory `/opt/phpbrew/build/php-5.3.29/ext/mysql` has these files:

    -rw-r--r-- 1  4676 config.m4
    -rw-r--r-- 1   926 config.w32
    -rw-r--r-- 1    46 CREDITS
    -rw-r--r-- 1  8617 mysql.dsp
    -rw-r--r-- 1  4438 mysql.mak
    -rw-r--r-- 1  1505 mysql_mysqlnd.h
    -rw-r--r-- 1  1904 package.xml
    -rw-r--r-- 1 76666 php_mysql.c
    -rw-r--r-- 1  1420 php_mysql.h
    -rw-r--r-- 1  4078 php_mysql_structs.h
    drwxr-xr-x 2  4096 tests

So I at least have some source code. It may be incomplete, but I've got no reasons to believe it is. Could you elaborate on why you think I'm missing source code? How would this lead to a 404 from https://pecl.php.net ? The URL `https://pecl.php.net/rest/r/mysql/5.3.29.xml` also returns 404 from my workstation (which is a different machine than I use to build php).

Note that mysql is only an example since the problem also occurs on other extensions. A couple are mentioned in my first post.

**Comment by c9s** [comment]
When you run the extension installer, it will first check if the extension source exists in your build directory (by your current php version environment variable). If not, it will fallback to the pecl installer, however there is no such mysql extension on pecl site, therefore it gives you 404 error.

**Comment by martijntraa** [comment]
How can I check if all the needed source code exists in my build directory? I've already posted the contents of the `/ext/mysql` directory and it seems to be in good order. What causes phpbrew to think it's not complete?

**Comment by federivo** [comment]
@martijntraa I'm having the same issue. Did you find a solution for this?

**Comment by martijntraa** [comment]
@federivo I never found a way to install MySQL as a seperate extension.

Instead, I solved my particular problem by including it in the build with `+mysql` like so:
<pre>phpbrew install 5.3.29 \
+default +mysql +pdo +sqlite \
[... other options ...]</pre>
and by making adjustments on other parts of my system to match up.

I'm having trouble remembering what exact reason I had to prefer MySQL as an extension. What is your reason? Perhaps I'll remember when someone jogs my memory.

**Comment by federivo** [comment]
I installed without the +mysql variant (just forgot to add it) and tried to install it as separated, no other reason than that. I guess my solution is to reinstall with the variant (just like you did). But it would be nice to understand what the problem was.

Thank you for the quick response!
