### ISSUE TITLE
executing switch from bash fails

### ISSUE THREAD

**Issue by matthbull** [phpbrew/phpbrew#610]
Ive written a bash script that handles the apache2 switchover, this works fine.  

However, calling `phpbrew switch php-7.0.1` from bash results in an error as below.

>Invalid argument php-7.0.1

It doesnt matter if I feed in the version with a variable, or hard code it in, same result from bash.

running the command from normal command line works with no problem.

**extract from bash file**

    /usr/local/bin/phpbrew switch php-${version}

**Comment by Ronmi** [comment]
By looking into `$HOME/.phpbrew/bashrc`, you can find a bash function named `phprew` which acts as a wrapper to downloaded phpbrew script (`/usr/local/bin/phpbrew` in this case). So you might try source the `bashrc` file and run with that wrapper in your bash script:

```sh
source $HOME/.phpbrew/bashrc
phpbrew switch php-${version}
```

Hope this can be helpful.

**Comment by matthbull** [comment]
excellent, that fixed it. many thanks
