### ISSUE TITLE
phpinfo()/phpversion() is displaying system default version

### ISSUE THREAD

**Issue by bimsonz** [phpbrew/phpbrew#611]
Running phpbrew list and php -v returns the phpbrew set version of php but when i open a file and echo phpinfo or version im getting the system version of php.

I've not added anything to my php.ini file nor my vhosts.. is there something ive missed?

Thanks,
Zach

**Comment by marcioAlmada** [comment]
> [...] is there something ive missed?

Perhaps you missed the wiki https://github.com/phpbrew/phpbrew/wiki/Cookbook#apache2-support? ^^

**Comment by bimsonz** [comment]
Perfect, sorry i missed that. 
Worked a treat!
