### ISSUE TITLE
Cannot find OpenSSL's <evp.h>

### ISSUE THREAD

**Issue by hultberg** [phpbrew/phpbrew#612]
Hello

When running `phpbrew install 5.6.15 +mysql -- --with-openssl=/usr/include/openssl` I get the following error in build.log: `configure: error: Cannot find OpenSSL's <evp.h>` and running `ll /usr/include/openssl/ | grep "evp.h"` i get:
````
-rw-r--r--  1 root root  52791 juni  11 17:32 evp.h
````

Who is the wrong here?
Running Ubuntu 14.04.3 64-bit with elementary OS 0.3.1 Freya.
OpenSSL version: OpenSSL 1.0.1f 6 Jan 2014

**Comment by ifthenelse** [comment]
Samer error here while installing **php 5.4.45** with **Ubuntu 15.10 (x86)**
```zsh
$ phpbrew install php-5.4.45 +default -- --with-openssl=/usr/local/ssl/include/openssl
```
@hultberg did you try upgrading phpbrew and leveraging [Openssl support](https://github.com/phpbrew/phpbrew/wiki/Cookbook#openssl-support)?
```zsh
$ phpbrew install 5.6.15 +default +mysql +openssl=/usr/include/openssl
```
As mentioned [here](https://github.com/phpbrew/phpbrew/issues/111#issuecomment-158761650) on #111 I still get different errors though.

**Comment by hultberg** [comment]
Thanks @ifthenelse, this worked:
`$ phpbrew install 5.6.15 +default +mysql +openssl=/usr/include/openssl`

**Comment by jcrben** [comment]
My solution:
`phpbrew install 5.6.15 +openssl` which seems to install openssl independently

Running OSX:
`Darwin Kernel Version 15.5.0: Tue Apr 19 18:36:36 PDT 2016; root:xnu-3248.50.21~8/RELEASE_X86_64`

**Comment by yourwebmaker** [comment]
@jcrben .... it worked for me...thanks.

**Comment by arkid** [comment]
For the record anyone using ubuntu (I'm on 16.4), check you have libssl-dev  installed.  I didn't and installing this got me past that error configuring builds

**Comment by ramsey** [comment]
I had this problem on Amazon Linux. None of the above solutions worked for me. So, after finding this solution on the mongo-php-driver project (https://github.com/mongodb/mongo-php-driver/issues/299#issuecomment-232673238), I was able to use the following to symlink the required files and get PHP to build with OpenSSL:

```
sudo bash -c "mkdir -p /usr/local/openssl/include/openssl/ && ln -s /usr/include/openssl/evp.h /usr/local/openssl/include/openssl/evp.h && mkdir -p /usr/local/openssl/lib/ && ln -s /usr/lib64/libssl.a /usr/local/openssl/lib/libssl.a && ln -s /usr/lib64/libssl.so /usr/local/openssl/lib/"

phpbrew install 7.1.3 +openssl=/usr/local/openssl/
```

I am not recommending this as a permanent solution, but it is the only work-around that allowed me to proceed with the build.

**Comment by gregorskii** [comment]
I had this issue as well. I was pointing to the executable of openssl, not the full folder.

BAD:

```
phpbrew install 7.1 +default +mysql +fpm +openssl=/usr/local/bin/openssl
```

GOOD:

```
phpbrew install 7.1 +default +mysql +fpm +openssl=/usr/local/Cellar/openssl/1.0.2l
```

FYI if anyone comes across this issue and is trying the wrong path.

**Comment by frankli0324** [comment]
> 
> For compilers to find openssl you may need to set:
>   export LDFLAGS="-L/usr/local/opt/openssl/lib"
>   export CPPFLAGS="-I/usr/local/opt/openssl/include"
> 
from `brew info openssl`
