### ISSUE TITLE
"buildconf error:  use buildconf --force" when installing from Github tag

### ISSUE THREAD

**Issue by michelezamuner** [phpbrew/phpbrew#613]
When I try to install directly from a Github tag I get:
```
$ phpbrew install github:php/php-src@PHP-7.0.0 as php-7.0.0 +default +...
...
You should not run buildconf in a release package.
use buildconf --force to override this check.
PhpBrew\Exception\SystemCommandException: buildconf error: use buildconf --force to override this check.
Trace:
...
```

I also tried with php-src@PHP-5.4.45 (branch) and  php-7.0.0RC7 (tag), with the same result. Installing `next` version works fine.

When I install PHP from source manually I always run `buildconf --force` first, but it looks like phpbrew doesn't do that. Is this a problem with phpbrew or am I missing something when trying to install from Github?

**Comment by c9s** [comment]
I've submit a fix for this and shall be rolled out soon.

**Comment by Leuloch** [comment]
+1

**Comment by c9s** [comment]
I think this was released in the latest version. :)

Ednei Oliveira <notifications@github.com> 於 2015年12月2日 星期三寫道：
