### ISSUE TITLE
Updated OSX to El Capitan, new Apache config overwrote location of .so module

### ISSUE THREAD

**Issue by jlem** [phpbrew/phpbrew#614]
I had installed PHP 5.6.8 through phpbrew a while ago and it was working fine through apache, but when I updated to El Capitan, it seems to have broken my apache PHP support (CLI is fine). 

What is the location of the SO module that I can point my http.d conf to?

**Comment by c9s** [comment]
The built-in apache is also updated in El Capitan, you need to recompile them.
