### ISSUE TITLE
Jobs option on ext install

### ISSUE THREAD

**Issue by soullivaneuh** [phpbrew/phpbrew#615]
Would be nice to have `-j|--jobs` options on `ext install` command like it's done on `install`.

**Comment by morozov** [comment]
Given that you'll probably want to use the `-j` flag with both `install` and `ext install` commands, it's easier to do something like `export MAKEFLAGS="$MAKEFLAGS -j$(nproc)"` in your profile and get it applied globally (see [#1087](https://github.com/phpbrew/phpbrew/pull/1087/files#diff-354f30a63fb0907d4ad57269548329e3R18)).
