### ISSUE TITLE
php: error while loading shared libraries: libicui18n.so.52: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by matthbull** [phpbrew/phpbrew#620]
after upgrading to Ubuntu 15.10, from 15.4 I get the following error:

> php: error while loading shared libraries: libicui18n.so.52: cannot open shared object file: No such file or directory

libicui18n.so.52 exists on my system, but Im not sure where phpbrew is looking for it.  Can someone let me know so I can symlink it to the right location?

**Comment by c9s** [comment]
Can you show me the path of libicui18n.so? 

And did you use `-- --with-icu-dir=...` to specify the prefix of icu?

Can you also show me the `./configure ...` command generated in the console? you can use `phpbrew --debug install ...` command.

**Comment by matthbull** [comment]
hiya sorry for the delay.

turned out it was looking for the :i386 version, which I didnt have. Installed a library with it and then problem solved.   I didnt run it in --debug mode to start with.  Ill know for next time.

many thanks
