### ISSUE TITLE
self-update does not work (permission denied)

### ISSUE THREAD

**Issue by akomm** [phpbrew/phpbrew#621]
OS: ubuntu 14.04 lts.

Moving a new version of phpbrew from `/tmp` to `/usr/local/bin` failes, because of missing permissions.
The function `rename` is used to move. By default `/usr/local/bin` has no write permissions on group/global. I think rename is composed of two operations, remove targeted file & write new file. Writing a new file in a directory requires directory write permission. Having write permission on the file does not help in that case.

Maybe it is possible to use another method for updating the phar content, e. G: 
`fread/fwrite` or `file_get_contents/file_put_contents`.

**Comment by Ronmi** [comment]
Have you tried `sudo phpbrew self-update`?

AFAIK putting anything to `/usr/local/bin` needs root privilege by default. So you might not update the `/usr/local/bin/phpbrew` file without root privilege. If this is the case, `phpbrew` can (and should) do nothing with it.

Changing permission of anything in `/usr` might cause security risk. If you are the only one using `phpbrew` on your computer, you might want to try install `phpbrew` in your home directory (for example: I personally install it in `$HOME/bin`), and add that directory to search path in your shell configuration like `.bashrc`.

**Comment by marcioAlmada** [comment]
Exactly what @Ronmi said ^^, thanks for replying to issues here.

**Comment by akomm** [comment]
So why do you propose to install it in /usr/local/bin in the readme? I tend to install such things in my home directory anyway, but: I'v made the experience that its usually a bad idea to install things in home folder, if someone - usually for a good reason - proposes to install it in privileged locations. Usually not doing so lead to an obstacle course.

But thank you for explaining basic security concepts ;)

**Comment by StarveTheEgo** [comment]
Yes, why?
