### ISSUE TITLE
How to use composer with phpbrew?

### ISSUE THREAD

**Issue by nicocans** [phpbrew/phpbrew#622]
I installed phpbrew to use php 5.4 in Ubuntu 14.04. It works fine, except when I try to use composer, which ignores phpbrew and installs dependencies related to php 5.5.

Is there a way to force composer to be compatible with phpbrew config? I trying to add: php: "5.4" in my composer.json, but it says that this requirement is not possible with my php version.

**Comment by marcioAlmada** [comment]
Hi,

What do you get when you run `phpbrew list`? Don't forget that you must run `phpbrew use <php-version>` before running composer. You are probably still using the system php version.

**Comment by nicocans** [comment]
solved it: it was because of my composer.lock : I replaced it by the one on my server (php 5.4) and now I have no more errors in my vendor libraries.
thx!
