### ISSUE TITLE
PHP7 Installation fail with Apache2 patch

### ISSUE THREAD

**Issue by Cactucs** [phpbrew/phpbrew#623]
Enable installing PHP 7.

**Comment by imamassi** [comment]
phpbrew install github:php/php-src@PHP-7.0 as php-7.0.0

**Comment by markwu** [comment]
Phpbrew seems only get updates release from php.net for version 5

`https://secure.php.net/releases/index.php?json&version=5&max=100`

**Comment by markwu** [comment]
I got the following errors with `phpbrew install github:php/php-src@PHP-7.0 as php-7.0.0`

```
Build complete.
Don't forget to run 'make test'.

Installing PHP SAPI module:       apache2handler
/usr/local/Cellar/httpd24/2.4.17/build/instdso.sh SH_LIBTOOL='/usr/local/Cellar/apr/1.5.2/libexec/build-1/libtool' libs/libphp7.so /usr/local/Cellar/httpd24/2.4.17/libexec
/usr/local/Cellar/apr/1.5.2/libexec/build-1/libtool --mode=install install libs/libphp7.so /usr/local/Cellar/httpd24/2.4.17/libexec/
libtool: install: install libs/libphp7.so /usr/local/Cellar/httpd24/2.4.17/libexec/libphp7.so
install: libs/libphp7.so: No such file or directory
apxs:Error: Command failed with rc=4653056
.
make: *** [install-sapi] Error 1
```

There is no `libphp.so`, just `libphp7.0.1-dev.so` ... :(

**Comment by Cactucs** [comment]
When I run `phpbrew install github:php/php-src@PHP-7.0 as php-7.0.0` and
the use it I got php version 7.1.0

**Comment by imamassi** [comment]
I don't know the problem here, because it was fine on me, I installed 7.0.0 succesfully

**Comment by Ronmi** [comment]
Anyone willing give my PR a try? Just download [phpbrew from my repository](https://raw.githubusercontent.com/Ronmi/phpbrew/issue623_update_php7_info/phpbrew) and replace original `phpbrew` binary. That works for me.

**Comment by Leuloch** [comment]
I'm using Ubuntu 14.04 and when try:
phpbrew install github:php/php-src@PHP-7.0 as php-7.0.0

I get the following error:
```
configure: error: unrecognized option: `--no-check-certificate'
Try `./configure --help' for more information
```

**Comment by sebcbi1** [comment]
@Ronmi your build is running fine for me. i succesfully installed php 7.0.0 release tarball

**Comment by imamassi** [comment]
@Leuloch I got the same error too, but I don't know why it's still managed to install the php 7 after I checked with `phpbrew list`

**Comment by c9s** [comment]
Looks like something is calling `wget` with `--no-check-certificate` option, looks like pear for me.

**Comment by c9s** [comment]
OK here is the latest result, I switched into the build directory and manually ran `make install`, it shows me that:

```
~/.phpbrew/build/php-7.0.0/  % make install
Installing PHP CLI binary:        /home/c9s/.phpbrew/php/php-7.0.0/bin/
Installing PHP CLI man page:      /home/c9s/.phpbrew/php/php-7.0.0/php/man/man1/
Installing phpdbg binary:         /home/c9s/.phpbrew/php/php-7.0.0/bin/
Installing phpdbg man page:       /home/c9s/.phpbrew/php/php-7.0.0/php/man/man1/
Installing PHP CGI binary:        /home/c9s/.phpbrew/php/php-7.0.0/bin/
Installing PHP CGI man page:      /home/c9s/.phpbrew/php/php-7.0.0/php/man/man1/
Installing build environment:     /home/c9s/.phpbrew/php/php-7.0.0/lib/php/build/
Installing header files:          /home/c9s/.phpbrew/php/php-7.0.0/include/php/
Installing helper programs:       /home/c9s/.phpbrew/php/php-7.0.0/bin/
  program: phpize
  program: php-config
Installing man pages:             /home/c9s/.phpbrew/php/php-7.0.0/php/man/man1/
  page: phpize.1
  page: php-config.1
Installing PEAR environment:      /home/c9s/.phpbrew/php/php-7.0.0/lib/php/
--2015-12-05 10:22:34--  https://pear.php.net/install-pear-nozlib.phar
Resolving pear.php.net (pear.php.net)... 5.35.241.22
Connecting to pear.php.net (pear.php.net)|5.35.241.22|:443... connected.
ERROR: no certificate subject alternative name matches
	requested host name ‘pear.php.net’.
To connect to pear.php.net insecurely, use `--no-check-certificate'.
Makefile:451: recipe for target 'install-pear' failed
make: *** [install-pear] Error 5
```

**Comment by c9s** [comment]
This is where it broke 
https://gist.github.com/anonymous/bef8f14abcb5a2259e4c#file-makefile-L457

**Comment by markwu** [comment]
I use `phpbrew self-update develop` to get this develop version from @Ronmi 

The building process is fine, but installing process failed, I got the following errors:

```
Build complete.
Don't forget to run 'make test'.

Installing PHP SAPI module:       apache2handler
/usr/local/Cellar/httpd24/2.4.16/build/instdso.sh SH_LIBTOOL='/usr/local/Cellar/apr/1.5.2/libexec/build-1/libtool' libs/libphp7.so /usr/local/Cellar/httpd24/2.4.16/libexec
/usr/local/Cellar/apr/1.5.2/libexec/build-1/libtool --mode=install install libs/libphp7.so /usr/local/Cellar/httpd24/2.4.16/libexec/
libtool: install: install libs/libphp7.so /usr/local/Cellar/httpd24/2.4.16/libexec/libphp7.so
install: libs/libphp7.so: No such file or directory
apxs:Error: Command failed with rc=4653056
.
make: *** [install-sapi] Error 1
```

There is no `libphp7.so`, but `libphp7.0.0.so`.

**Comment by c9s** [comment]
Yeah I think there are two major issues:

1. The Apache patch is broken
2. Homebrew uses it's own isolated paths, so library path detection failed.

**Comment by c9s** [comment]
Apache2 patch is fixed on 1.20 branch

**Comment by bupy7** [comment]
Fix: phpbrew install github:php/php-src@PHP-7.0 as php-7.0.0 -- --with-apxs=/path/to/apxs

**Comment by c9s** [comment]
Already fixed.
