### ISSUE TITLE
Image not found

### ISSUE THREAD

**Issue by sumityadav** [phpbrew/phpbrew#627]
Any idea on how to fix this?

```
dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.55.dylib
  Referenced from: /Users/sumit/.phpbrew/php/php-5.6.14/bin/php
  Reason: image not found
Trace/BPT trap: 5
```

**Comment by sumityadav** [comment]
Not sure if this is the right way to fix it. 

Here is what I did:

```
$ brew uninstall icu4c
$ cd /usr/local/Library/Formula
$ git checkout e52ee0523e9f9bf94b8bb50bbcb426e120d20069 icu4c.rb
$ brew install icu4c
```

**Comment by c9s** [comment]
Looks like you need to recompile your php 5.6.14 ?

**Comment by sumityadav** [comment]
So goto the build directory and rebuild or there is an option to do it from phpbrew command?

**Comment by c9s** [comment]
You have to re-configure it, you can use the command below to see the variants used for your previous php build:

```sh
phpbrew list -v -d
```

And copy the variants to rebuild the php.

**Comment by c9s** [comment]
This command should work for you:

    cd $(phpbrew path build) && make clean && make
