### ISSUE TITLE
php7 not in known versions

### ISSUE THREAD

**Issue by hoshsadiq** [phpbrew/phpbrew#628]
So PHP7 is officially released, but it's not in the known list
```bash
$ phpbrew known
5.6: 5.6.16, 5.6.15, 5.6.14, 5.6.13, 5.6.12, 5.6.11, 5.6.10, 5.6.9 ...
5.5: 5.5.30, 5.5.29, 5.5.28, 5.5.27, 5.5.26, 5.5.25, 5.5.24, 5.5.23 ...
5.4: 5.4.45, 5.4.44, 5.4.43, 5.4.42, 5.4.41, 5.4.40, 5.4.39, 5.4.38 ...
5.3: 5.3.29, 5.3.28, 5.3.27, 5.3.26, 5.3.25, 5.3.24 ...
You can run `phpbrew update` to get a newer release list.

$ phpbrew update
===> Fetching release list...
[==================================================================] 184.00/184.00B 100%
Redirecting to https://secure.php.net/releases/index.php?json&version=5&max=100
5.6: 17 releases
5.5: 31 releases
5.4: 46 releases
5.3: 6 releases
===> Done

```

The URL has the parameter `version=5`, which is why it cannot find it. Removing it gives us a list that includes php7.

**Comment by Ronmi** [comment]
This issue is duplicated with #623

You can update your `phpbrew` to `develop` branch by running `phpbrew self-update develop`, or wait for 1.2 release. Both these has fixed the issue.

**Comment by c9s** [comment]
This is merged in master, scheduled for next release

**Comment by hoshsadiq** [comment]
Oh cool. When will the next release be released?
