### ISSUE TITLE
Error relating to the libmcrypt-dev package when installing requirements

### ISSUE THREAD

**Issue by henrywright** [phpbrew/phpbrew#638]
When running `apt-get install -y libmcrypt-dev libmcrypt4`, I get the following error:

```
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libmcrypt-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libmcrypt-dev' has no installation candidate
```

Ref: https://github.com/phpbrew/phpbrew/wiki/Requirement

**Comment by Ronmi** [comment]
I did some search on [Ubuntu](http://packages.ubuntu.com/search?keywords=libmcrypt-dev&searchon=names&suite=all&section=all) and [Debian](https://packages.debian.org/search?keywords=libmcrypt-dev&searchon=names&suite=all&section=all) to ensure the `libmcrypt-dev` is not removed or renamed, and you can see it is still there. So there must be something wrong in your apt cache or configuration.

OS community, like Ubuntu forum if you are using Ubuntu, might give you more detail information.

**Comment by henrywright** [comment]
Thanks for the info @Ronmi
