### ISSUE TITLE
No pecl in php/bin/ directory

### ISSUE THREAD

**Issue by Pupp3tm4st3r** [phpbrew/phpbrew#639]
Hi there,

is there a way to build a php version with phpbrew with working pecl? So that i can use pecl install xxxx not phpbrew ext install?

My phpbrew versions don´t have pecl unter /php/bin/

Best regards
Simon

**Comment by marcioAlmada** [comment]
Everything goes inside `~/.phpbrew/php/php-<version>/bin/`. You can quickly cd into your current php root dir with `phpbrew cd dist` then try to `ls` there. You will see:

```bash
bin  etc  include  lib  php  phpbrew_status  phpbrew.variants  var
```

**Comment by Pupp3tm4st3r** [comment]
Hi,

thanks for your fast reply. Yeah I meant the correct path (okay, in my setup it is /opt/phpbrew/php/php-x.x.xx/bin) but didn´t write it correctly. But under .../bin is now pecl. 

ls /opt/phpbrew/php/php-5.6.16/bin:

phar  phar.phar  php  php-cgi  php-config  phpize
