### ISSUE TITLE
Can't install pdo_dblib

### ISSUE THREAD

**Issue by nicocans** [phpbrew/phpbrew#643]
hello,

pdo_dblib is not enabled when pdo is. how to manage it?

$ phpbrew ext install pdo_dblib
===> Installing pdo_dblib extension...
Log stored at: /home/nico/.phpbrew/build/php-5.4.39/ext/pdo_dblib/build.log
Changing directory to /home/nico/.phpbrew/build/php-5.4.39/ext/pdo_dblib
===> Phpize...
===> Configuring...
Exception: Command failed: ./configure --with-php-config=/home/nico/.phpbrew/php/php-5.4.39/bin/php-config >> /home/nico/.phpbrew/build/php-5.4.39/ext/pdo_dblib/build.log 2>&1 returns 
Trace:

    0) PhpBrew\Utils::system('./configure --with-php-config=/home/nico/.phpbrew/php/php-5.4.39/bin/php-config >> /home/nico/.phpbrew/build/php-5.4.39/ext/pdo_dblib/build.log 2>&1', CLIFramework\Logger)
    1) PhpBrew\Extension\ExtensionInstaller->install(PhpBrew\Extension\M4Extension, [])
    2) PhpBrew\Extension\ExtensionManager->installExtension(PhpBrew\Extension\M4Extension, [])
    3) PhpBrew\Command\ExtensionCommand\InstallCommand->execute('pdo_dblib')
    4) call_user_func_array([PhpBrew\Command\ExtensionCommand\InstallCommand, 'execute'], ['pdo_dblib'])
    5) CLIFramework\CommandBase->executeWrapper(['pdo_dblib'])
    6) CLIFramework\Application->run(['/usr/local/bin/phpbrew', 'ext', 'install', 'pdo_dblib'])
    7) CLIFramework\Application->runWithTry(['/usr/local/bin/phpbrew', 'ext', 'install', 'pdo_dblib'])
    8) require('phar:///usr/local/bin/phpbrew/scripts/phpbrew-emb.php')

thx.

**Comment by nicocans** [comment]
I don't know if that helps, but the command to install dblib without phpbrew is : 
sudo apt-get install php5-sybase

**Comment by c9s** [comment]
apt-get install only install the prebuilt binary

Can you paste the build.log located at /home/nico/.phpbrew/build/php-5.4.39/ext/pdo_dblib/build.log  ?

**Comment by c9s** [comment]
I think the configure script failed to find your library path, you have to pass some extra options, use --debug flag to see the configure messages.

```
phpbrew --debug ext install ...
```

**Comment by c9s** [comment]
@nicocans looks like pdo_dblib requires some library, and php5-sybase contains the dependency you need.

**Comment by nicocans** [comment]
build.log:
Configuring for:
PHP Api Version:         20100412
Zend Module Api No:      20100525
Zend Extension Api No:   220100525

phpbrew --debug ext install pdo_dblib:
===> Installing pdo_dblib extension...
Extension path /home/nico/.phpbrew/build/php-5.4.39/ext/pdo_dblib
Log stored at: /home/nico/.phpbrew/build/php-5.4.39/ext/pdo_dblib/build.log
Changing directory to /home/nico/.phpbrew/build/php-5.4.39/ext/pdo_dblib
===> Phpize...
Running Command:phpize > /home/nico/.phpbrew/build/php-5.4.39/ext/pdo_dblib/build.log 2>&1
===> Configuring...
Appending argument: --with-php-config=/home/nico/.phpbrew/php/php-5.4.39/bin/php-config
Running Command:./configure --with-php-config=/home/nico/.phpbrew/php/php-5.4.39/bin/php-config
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /home/nico/.phpbrew/php/php-5.4.39
checking for PHP includes... -I/home/nico/.phpbrew/php/php-5.4.39/include/php -I/home/nico/.phpbrew/php/php-5.4.39/include/php/main -I/home/nico/.phpbrew/php/php-5.4.39/include/php/TSRM -I/home/nico/.phpbrew/php/php-5.4.39/include/php/Zend -I/home/nico/.phpbrew/php/php-5.4.39/include/php/ext -I/home/nico/.phpbrew/php/php-5.4.39/include/php/ext/date/lib
checking for PHP extension directory... /home/nico/.phpbrew/php/php-5.4.39/lib/php/extensions/no-debug-non-zts-20100525
checking for PHP installed headers prefix... /home/nico/.phpbrew/php/php-5.4.39/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... re2c
checking for re2c version... 0.13.5 (ok)
checking for gawk... no
checking for nawk... nawk
configure: error: Could not find /usr/lib/libsybdb.a|so
checking if nawk is broken... no
checking for PDO_DBLIB support via FreeTDS... yes, shared
Exception: Command failed: ./configure --with-php-config=/home/nico/.phpbrew/php/php-5.4.39/bin/php-config returns checking for PDO_DBLIB support via FreeTDS... yes, shared
Thrown from phar:///usr/local/bin/phpbrew/PhpBrew/Utils.php at line 2:

    1<?php
>   2namespace PhpBrew; use Exception; use CLIFramework\Logger; use RecursiveDirectoryIterator; use RecursiveIteratorIterator; class Utils { public static function canonicalizeBuildName($version) { if (!preg_match('/^php-/', $version)) { return 'php-' . $version; } return $version; } public static function support64bit() { $int = "9223372036854775807"; $int = intval($int); if ($int == 9223372036854775807) { return true; } elseif ($int == 2147483647) { return false; } else { return false; } } public static function findBinByPrefix($bin) { $prefixes = self::getLookupPrefixes(); foreach ($prefixes as $prefix) { $binPath = $prefix . DIRECTORY_SEPARATOR . 'bin' . DIRECTORY_SEPARATOR . $bin; if (file_exists($binPath)) { return $binPath; } $binPath = $prefix . DIRECTORY_SEPARATOR . 'sbin' . DIRECTORY_SEPARATOR . $bin; if (file_exists($binPath)) { return $binPath; } } return null; } public static function findLibDir() { $prefixes = array( '/opt', '/opt/local', '/usr', '/usr/local', ); if ($pathStr = getenv('PHPBREW_LOOKUP_PREFIX')) { $paths = explode(':', $pathStr); foreach ($paths as $path) { $prefixes[] = $path; } } $prefixes = array_reverse($prefixes); foreach($prefixes as $prefix) { if ($arch = self::detectArch($prefix)) { return "lib/$arch"; } } return NULL; } public static function detectArch($prefix) { $multiArchs = array( 'lib/lib64', 'lib/lib32', 'lib64', 'lib', 'lib/ia64-linux-gnu', 'lib/x86_64-linux-gnu', 'lib/x86_64-kfreebsd-gnu', 'lib/i386-linux-gnu', ); foreach ($multiArchs as $archName) { if (file_exists("$prefix/$archName")) { return $archName; } } return NULL; } public static function getLookupPrefixes() { $prefixes = array( '/opt', '/opt/local', '/opt/local/lib', '/usr', '/usr/lib', '/usr/local', '/usr/local/lib' ); if ($pathStr = getenv('PHPBREW_LOOKUP_PREFIX')) { $paths = explode(':', $pathStr); foreach ($paths as $path) { $prefixes[] = $path; } } foreach($prefixes as $prefix) { if ($arch = self::detectArch($prefix)) { $prefixes[] = "$prefix/$arch"; } } return array_reverse($prefixes); } public static function findIncludePath() { $files = func_get_args(); $prefixes = self::getLookupPrefixes(); foreach ($prefixes as $prefix) { foreach ($files as $file) { $dir = $prefix . DIRECTORY_SEPARATOR . 'include'; $path = $dir . DIRECTORY_SEPARATOR . $file; if (file_exists($path)) { return $dir; } } } return null; } public static function findLibPrefix() { $files = func_get_args(); $prefixes = self::getLookupPrefixes(); foreach ($prefixes as $prefix) { foreach ($files as $file) { $p = $prefix . DIRECTORY_SEPARATOR . $file; if (file_exists($p)) { return $prefix; } } } return null; } public static function findIncludePrefix() { $files = func_get_args(); $prefixes = self::getLookupPrefixes(); foreach ($prefixes as $prefix) { foreach ($files as $file) { if (file_exists($prefix . DIRECTORY_SEPARATOR . 'include' . DIRECTORY_SEPARATOR . $file)) { return $prefix; } } } return null; } public static function getPkgConfigPrefix($package) { $cmd = 'pkg-config --variable=prefix ' . $package; $process = new Process($cmd); $process->run(); return trim($process->getOutput()); } static public function system($command, $logger = NULL) { if (is_array($command)) { $command = join(' ', $command); } if ($logger) { $logger->debug("Running Command:" . $command); } $lastLine = system($command, $returnValue); if ($returnValue !== 0) { throw new Exception("Command failed: $command returns " . $lastLine); } return $returnValue; } public static function findBin($bin) { $path = getenv('PATH'); $paths = explode(PATH_SEPARATOR, $path); foreach ($paths as $path) { $f = $path . DIRECTORY_SEPARATOR . $bin; if (file_exists($f)) { while (is_link($f)) { $f = readlink($f); } return $f; } } return null; } public static function pipeExecute($command) { $proc = proc_open( $command, array( array("pipe","r"), array("pipe","w"), array("pipe","w"), ), $pipes ); return stream_get_contents($pipes[1]); } public static function startsWith($haystack, $needle) { return $needle === "" || strpos($haystack, $needle) === 0; } public static function endsWith($haystack, $needle) { return $needle === "" || substr($haystack, -strlen($needle)) === $needle; } public static function findLatestPhpVersion($version = null) { $foundVersion = false; $buildDir = Config::getBuildDir(); $hasPrefix = self::startsWith($version, 'php-'); if (is_dir($buildDir)) { if ($hasPrefix == true) { $version = str_replace('php-', '', $version); } $fp = opendir($buildDir); if ($fp !== false) { while ($file = readdir($fp)) { if ($file === '.' || $file === '..' || is_file($buildDir . DIRECTORY_SEPARATOR . $file) ) { continue; } $curVersion = strtolower(preg_replace('/^[\D]*-/', '', $file)); if (self::startsWith($curVersion, $version) && version_compare($curVersion, $foundVersion, '>=')) { $foundVersion = $curVersion; if (version_compare($foundVersion, $version, '=')) { break; } } } closedir($fp); } if ($hasPrefix == true && $foundVersion !== false) { $foundVersion = 'php-'.$foundVersion; } } return $foundVersion; } static public function recursive_unlink($path, Logger $logger) { $directoryIterator = new RecursiveDirectoryIterator($path, RecursiveDirectoryIterator::SKIP_DOTS); $it = new RecursiveIteratorIterator($directoryIterator, RecursiveIteratorIterator::CHILD_FIRST); foreach ($it as $file) { $logger->debug("Deleting " . $file->getPathname()); if ($file->isDir()) { rmdir($file->getPathname()); } else { unlink($file->getPathname()); } } if (is_dir($path)) { rmdir($path); } elseif (is_file($path)) { unlink($path); } } static public function editor($file) { $tty = exec("tty"); $editor = escapeshellarg(getenv('EDITOR') ?: 'nano'); exec("{$editor} {$file} > {$tty}"); } }
PHP Notice:  Undefined offset: 2 in phar:///usr/local/bin/phpbrew/CLIFramework/ExceptionPrinter/DevelopmentExceptionPrinter.php on line 2

Notice: Undefined offset: 2 in phar:///usr/local/bin/phpbrew/CLIFramework/ExceptionPrinter/DevelopmentExceptionPrinter.php on line 2
    3

Trace:

    0) PhpBrew\Utils::system('./configure --with-php-config=/home/nico/.phpbrew/php/php-5.4.39/bin/php-config', CLIFramework\Logger)
        from phar:///usr/local/bin/phpbrew/PhpBrew/Extension/ExtensionInstaller.php: 2

    1) PhpBrew\Extension\ExtensionInstaller->install(PhpBrew\Extension\M4Extension, [])
        from phar:///usr/local/bin/phpbrew/PhpBrew/Extension/ExtensionManager.php: 2

    2) PhpBrew\Extension\ExtensionManager->installExtension(PhpBrew\Extension\M4Extension, [])
        from phar:///usr/local/bin/phpbrew/PhpBrew/Command/ExtensionCommand/InstallCommand.php: 2

    3) PhpBrew\Command\ExtensionCommand\InstallCommand->execute('pdo_dblib')
PHP Notice:  Undefined index: file in phar:///usr/local/bin/phpbrew/CLIFramework/ExceptionPrinter/DevelopmentExceptionPrinter.php on line 2

Notice: Undefined index: file in phar:///usr/local/bin/phpbrew/CLIFramework/ExceptionPrinter/DevelopmentExceptionPrinter.php on line 2
PHP Notice:  Undefined index: line in phar:///usr/local/bin/phpbrew/CLIFramework/ExceptionPrinter/DevelopmentExceptionPrinter.php on line 2

Notice: Undefined index: line in phar:///usr/local/bin/phpbrew/CLIFramework/ExceptionPrinter/DevelopmentExceptionPrinter.php on line 2
        from : 0

    4) call_user_func_array([PhpBrew\Command\ExtensionCommand\InstallCommand, 'execute'], ['pdo_dblib'])
        from phar:///usr/local/bin/phpbrew/CLIFramework/CommandBase.php: 2

    5) CLIFramework\CommandBase->executeWrapper(['pdo_dblib'])
        from phar:///usr/local/bin/phpbrew/CLIFramework/Application.php: 2

    6) CLIFramework\Application->run(['/usr/local/bin/phpbrew', '--debug', 'ext', 'install', 'pdo_dblib'])
        from phar:///usr/local/bin/phpbrew/CLIFramework/Application.php: 2

    7) CLIFramework\Application->runWithTry(['/usr/local/bin/phpbrew', '--debug', 'ext', 'install', 'pdo_dblib'])
        from phar:///usr/local/bin/phpbrew/scripts/phpbrew-emb.php: 2

    8) require('phar:///usr/local/bin/phpbrew/scripts/phpbrew-emb.php')
        from /usr/local/bin/phpbrew: 6

**Comment by Ronmi** [comment]
The build log shows the sybase library `libsybdb.a` is missing. If you are using Debian , you can install `freetds-dev` via `apt-get` to obtain it. For Ubuntu, I guess it's the same. If not, you can visit Ubuntu's package list page to find out correct package name.

If build still fail after install sybase lib, it might be caused by library path problem. The best way is passing correct library path with `--with-libpath`, but you'll need a bit knowledgement about how autotools searching libs. A lazy and tricky way is making a symbolic link like `ln -s /path/to/your/libsybdb.a /usr/lib/`

Hope this can help you solve the problem :)

**Comment by nicocans** [comment]
it worked! freetds-dev was installed, and ln -s /usr/lib/x86_64-linux-gnu/libsybdb.a /usr/lib/ solved the problem.
thx!

**Comment by kdekooter** [comment]
This is the generic way I came up with to set the symlink: `dpkg -L freetds-dev | grep libsybdb.a | xargs -i ln -s {} /usr/lib`.

**Comment by swapnilsarwe-mnet** [comment]
> This is the generic way I came up with to set the symlink:

this worked like a charm - was unable to figure out the location of libsybda.a.
Your generic solution worked just fine.

**Comment by swapnilsarwe** [comment]
> This is the generic way I came up with to set the symlink:

this worked like a charm - was unable to figure out the location of libsybda.a.
Your generic solution worked just fine.
