### ISSUE TITLE
Insufficient arguments for command 'install'

### ISSUE THREAD

**Issue by reyhansofian** [phpbrew/phpbrew#645]
I'm trying to install phpunit using

    phpbrew install-phpunit

but it returns 

    Insufficient arguments for command 'install', which requires 1 arguments, 0 given.
    Expected argument prototypes:
        /usr/local/bin/phpbrew install [options] <version> <variants>

I'm running on Ubuntu 14.04. Is there a way to solve this?

**Comment by c9s** [comment]
Please run `phpbrew app get phpunit` instead.

**Comment by c9s** [comment]
You can try `phpbrew app` to see more php apps

**Comment by reyhansofian** [comment]
I see :smile:
I think you should update the readme then :smile: 
Thanks for your response
