### ISSUE TITLE
Php 7.0.1  cannot find OpenSSL's <evp.h>

### ISSUE THREAD

**Issue by neok** [phpbrew/phpbrew#646]
installing mysqlnd extension
`phpbrew ext install mysqlnd`
got this error

checking for pkg-config... /usr/bin/pkg-config
configure: error: Cannot find OpenSSL's <evp.h>
//Ubuntu 14.04

**Comment by j0rdn** [comment]
Installing 7.0.3 getting this same error

checking for pkg-config... /usr/bin/pkg-config
configure: error: Cannot find OpenSSL's libraries

**Comment by felipefrancisco** [comment]
Any updates on this? Still getting the  same error when trying to install 7.0.13.
`openssl` files are located on `/usr/include/openssl/` according to `locate evp.h`.

- `--with-openssl=/usr/include/openssl/`
- `--with-openssl-dir=/usr/include/openssl/`
- `+openssl=/usr/include/openssl/`
- Installing `libssl-dev`


I tried everything in the internet. Even tried the solutions on this thread:
https://github.com/mongodb/mongo-php-driver/issues/138

Still getting the same error.

```
===> Installing mysqlnd extension...
Extension path /root/.phpbrew/build/php-7.0.13/ext/mysqlnd
Log stored at: /root/.phpbrew/build/php-7.0.13/ext/mysqlnd/build.log
Changing directory to /root/.phpbrew/build/php-7.0.13/ext/mysqlnd
===> Phpize...
Running Command:phpize > /root/.phpbrew/build/php-7.0.13/ext/mysqlnd/build.log 2>&1
===> Configuring...
Appending argument: --with-php-config=/root/.phpbrew/php/php-7.0.13/bin/php-config
Running Command:./configure --with-php-config=/root/.phpbrew/php/php-7.0.13/bin/php-config
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu
checking for PHP prefix... /root/.phpbrew/php/php-7.0.13
checking for PHP includes... -I/root/.phpbrew/php/php-7.0.13/include/php -I/root/.phpbrew/php/php-7.0.13/include/php/main -I/root/.phpbrew/php/php-7.0.13/include/php/TSRM -I/root/.phpbrew/php/php-7.0.13/include/php/Zend -I/root/.phpbrew/php/php-7.0.13/include/php/ext -I/root/.phpbrew/php/php-7.0.13/include/php/ext/date/lib
checking for PHP extension directory... /root/.phpbrew/php/php-7.0.13/lib/php/extensions/no-debug-non-zts-20151012
checking for PHP installed headers prefix... /root/.phpbrew/php/php-7.0.13/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... gawk
checking whether to enable mysqlnd... yes, shared
checking whether to disable compressed protocol support in mysqlnd... yes
checking for the location of libz... no
checking for DSA_get_default_method in -lssl... no
checking for X509_free in -lcrypto... yes
checking for pkg-config... /usr/bin/pkg-config
configure: error: Cannot find OpenSSL's <evp.h>
Error: Command failed: ./configure --with-php-config=/root/.phpbrew/php/php-7.0.13/bin/php-config returns: checking for pkg-config... /usr/bin/pkg-config
PHP Notice:  Undefined variable: configureOptions in phar:///usr/local/bin/phpbrew/src/PhpBrew/Console.php on line 134

Notice: Undefined variable: configureOptions in phar:///usr/local/bin/phpbrew/src/PhpBrew/Console.php on line 134
PHP Warning:  join(): Invalid arguments passed in phar:///usr/local/bin/phpbrew/src/PhpBrew/Console.php on line 134

Warning: join(): Invalid arguments passed in phar:///usr/local/bin/phpbrew/src/PhpBrew/Console.php on line 134
Configure options: 
```

**Comment by felipefrancisco** [comment]
Found [an entry][1] on bugs.php.net describing a problem with `mysqlnd`'s `configure` file, maybe this could be related.

  [1]: https://bugs.php.net/bug.php?id=72363&edit=3

**Comment by resurtm** [comment]
@felipefrancisco Have you fixed your issue? Any news? Thanks!

**Comment by j0rdn** [comment]
What is your `$ openssl version`

**Comment by rbtsolis** [comment]
`sudo apt-get install libssl-dev`

**Comment by akoSalman** [comment]
[This](https://serverfault.com/questions/415458/how-to-solve-configure-error-cannot-find-openssls-evp-h#comment881428_544149) was the final solution for me.

**Comment by chippyash** [comment]
This is still a problem.  I simply cannot install mysqlnd and thus pdo_mysql under php 7.1.
$php -v
PHP 7.1.9 

$phpbrew -v
phpbrew 1.23.1 

$ phpbrew list
* php-7.1.9      
  php-7.0.17     
  php-5.6.31     
  php-5.6.30  

$ sudo apt install libssl-dev
libssl-dev is already the newest version (1.0.2g-1ubuntu4.10).

$ locate evp.h
/usr/include/openssl/evp.h
$ cat /etc/issue
Linux Mint 18.1 Serena \n \l
$ uname -a
Linux pc 4.4.0-112-generic #135-Ubuntu SMP Fri Jan 19 11:48:36 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

$phpbrew --debug ext install mysqlnd
...
configure: error: Cannot find OpenSSL's <evp.h>

$ phpbrew --debug ext install mysqlnd --with-openssl-dir=/usr
...
configure: error: Cannot find OpenSSL's <evp.h>

$ phpbrew --debug ext install mysqlnd --with-openssl=/usr
...
configure: error: Cannot find OpenSSL's <evp.h>

and all variants that I can think of

**Comment by morozov** [comment]
@chippyash why do you need to install `mysqlnd`? It's not a userland extension and can be only used as a dependency of `mysqli` or `pdo_mysql`.

Not sure about the latter, but the former cannot be installed alone without compiling PHP.

If you need `pdo_mysql`, please try `phpbrew install x.y.z +mysql`.

**Comment by chippyash** [comment]
@morozov I'm going to try a full install again.  This is about installing extensions.  Installing pdo_mysql extension *after* a version install requires mysqlnd to be installed. Hence the issues.  I'll let you know how we get on.

**Comment by chippyash** [comment]
@morozov 
phpbrew install 7.1 +default +sqlite +mysql +pdo
worked to install mysql and pdo

php -m
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
fileinfo
filter
hash
json
libxml
mbstring
mcrypt
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_sqlite
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tokenizer
xml
xmlreader
xmlwriter
xsl
zip
zlib

clearly mysqlnd is required for pdo_mysql.  So the question remains; why does installing the mysqlnd as an extension by itself fail, when a new PHP version install succeeds?

**Comment by morozov** [comment]
@chippyash because `mysqlnd` is not a userland extension. It's a dependency for `pdo_mysql`.

**Comment by chippyash** [comment]
@morozov Hi.  Yes, I see your point.  This issue has come up so many times over the years, that maybe it's time to change the documentation, perhaps re variants and add a warning notice ''If you think you want mysql support now or in the future, add +mysql +pdo to your variants when you install a PHP version.  You will not be able to install either as user extensions later"

Thoughts?

**Comment by morozov** [comment]
There's one more recurring issue with extension installer like #943 where PHPBrew cannot tell the difference between bundled and PECL extensions. UX-wise, I definitely agree that the behavior should be more clear and user-friendly. For every given extension there should be a known installation strategy.

I'm not a big fan of one-off workarounds. If PHPBrew just responded that `mysqld` cannot be installed (as well as any other potentially existing extension like that), it would be totally acceptable.

**Comment by chippyash** [comment]
I think that documentation re caveats is the way forward.  After all, if user just gets " mysqld cannot be installed" then chances are they'll end up here again asking the same questions. Ditto for imap (which I struggled with some while back too) and any other scenario that you guys know about.  If its in the docs, you can simply point at it and move on to more important things ;-)

Thanks for staying with it though! Appreciated.

**Comment by herb123456** [comment]
try this

```
PHP_OPENSSL=yes phpbrew ext install mysqlnd
```

**Comment by jpenna** [comment]
Installing with the `neutral` variant (no extension) worked. 

```
$ phpbrew --verbose install 5.6 +neutral  
```

Then you can install the extensions you need later.

**Comment by silentwarrior** [comment]
```
$ PHP_OPENSSL=yes phpbrew ext install mysqlnd
```

This does install it but when you install `mysqli` afterwards it fails to find `mysqlnd`, and trying to install `mysqlnd` without the `PHP_OPENSSL` flag again after that causes it to fail with the same error.

So, I am not sure whats going on here. Just that this - while it does install - doesnt fix the problem.

**Comment by SerheyDolgushev** [comment]
Sorry, but it is an issue for me too. Still unable to install `mysqlnd` to an existing PHP.

**Comment by SerheyDolgushev** [comment]
Just checked all the comments, and want to summarize them for future lazy persons like me:

You can not install `mysqlnd` as an extension to any version of existing PHP. If you installed any PHP without `mysqlnd` and trying to add `pdo_mysql` / `mysqli` - the only option is to reinstall the same version of PHP with `+pdo+mysql` flag.

@chippyash @morozov Please confirm if this is correct.

**Comment by morozov** [comment]
@SerheyDolgushev in my experience, `pdo_mysql` and `mysqli` can be only compiled as part of PHP, even if compiled as a shared library. So, technically yes, you need to reinstall PHP in order to compile them. Also, you're right, you don't want to install `mysqlnd` itself. You may want to install a MySQL extension `--with-mysqlnd`.

**Comment by 769344359** [comment]
https://zhuanlan.zhihu.com/p/20860808
