### ISSUE TITLE
Unable to find PDO package error after installation

### ISSUE THREAD

**Issue by amanmahajan26** [phpbrew/phpbrew#649]
Even after installing the pdo and mysql packages from the variants, I get this error when I try to access my site. Not able to figure out where is it trying to look for the pdo package.

**Comment by amitchhajer** [comment]
I am also having the same problem

**Comment by Ewan-GrandSlam** [comment]
I am also having this issue, I cant seem to get it to work no matter what I do.

**Comment by c9s** [comment]
It's weird, could you run phpbrew with debug mode? `phpbrew --debug install ...` and please paste your build log and commands

**Comment by c9s** [comment]
also, please provide your platform information

**Comment by webcrazy** [comment]
Hello @c9s 

I have the same error.I tried to install like this.
phpbrew install php-7.0.2 +default
phpbrew install php-7.0.2 +default +mysql +pdo. 

PDOException in Connector.php line 55:
could not find driver

Ubuntu 14.04 + Laravel
Thanks

**Comment by haegemon** [comment]
Same problem with Debian 8, at php-7.0.5

**Comment by haegemon** [comment]
Do you need debug information?

**Comment by c9s** [comment]
Yes i will need build log to inspect

**Comment by c9s** [comment]
Please run something like

    phpbrew --debug install --stdout php-7.0.2 +default +mysql +pdo

**Comment by haegemon** [comment]
Hi

Command and warnings:
```
pawel@pawel1:~$ phpbrew --debug install --stdout php-7.0.2 +default +mysql +pdo +fpm > ~/php_install.log
configure: WARNING: unrecognized options: --with-mysql
configure: WARNING: unrecognized options: --with-mysql
/home/pawel/.phpbrew/build/php-7.0.2/ext/curl/interface.c: In function ‘zif_curl_getinfo’:
/home/pawel/.phpbrew/build/php-7.0.2/ext/curl/interface.c:3014:7: warning: call to ‘_curl_easy_getinfo_err_curl_slist’ declared with attribute warning: curl_easy_getinfo expects a pointer to struct curl_slist * for this info [enabled by default]
/home/pawel/.phpbrew/build/php-7.0.2/ext/curl/interface.c:3048:9: warning: call to ‘_curl_easy_getinfo_err_curl_slist’ declared with attribute warning: curl_easy_getinfo expects a pointer to struct curl_slist * for this info [enabled by default]
/home/pawel/.phpbrew/build/php-7.0.2/ext/curl/interface.c: In function ‘_php_curl_setopt’:
/home/pawel/.phpbrew/build/php-7.0.2/ext/curl/interface.c:2627:4: warning: call to ‘_curl_easy_setopt_err_progress_cb’ declared with attribute warning: curl_easy_setopt expects a curl_progress_callback argument for this option [enabled by default]
/home/pawel/.phpbrew/build/php-7.0.2/ext/fileinfo/libmagic/funcs.c: In function ‘file_replace’:
/home/pawel/.phpbrew/build/php-7.0.2/ext/fileinfo/libmagic/funcs.c:441:2: warning: passing argument 2 of ‘convert_libmagic_pattern’ discards ‘const’ qualifier from pointer target type [enabled by default]
/home/pawel/.phpbrew/build/php-7.0.2/ext/fileinfo/libmagic/funcs.c:59:20: note: expected ‘char *’ but argument is of type ‘const char *’
PEAR package PHP_Archive not installed: generated phar will require PHP's phar extension be enabled.
```
File 
[php_install.txt](https://github.com/phpbrew/phpbrew/files/233356/php_install.txt)

Php-fpm available but without pdo, and any others extensions

**Comment by c9s** [comment]
@haegemon it seems the pdo_mysql is compiled into your php without warnings. I guess it's caused by the unix socket.

Here is the command:

    ./configure '--prefix=/home/pawel/.phpbrew/php/php-7.0.2' '--with-config-file-path=/home/pawel/.phpbrew/php/php-7.0.2/etc' '--with-config-file-scan-dir=/home/pawel/.phpbrew/php/php-7.0.2/var/db' '--disable-all' '--enable-phar' '--enable-session' '--enable-short-tags' '--enable-tokenizer' '--with-pcre-regex' '--with-zlib=/usr' '--with-libdir=lib/x86_64-linux-gnu' '--with-mysql=mysqlnd' '--with-mysqli=mysqlnd' '--with-pdo-mysql=mysqlnd' '--enable-pdo' '--enable-fpm' '--enable-dom' '--enable-libxml' '--enable-simplexml' '--enable-xml' '--enable-xmlreader' '--enable-xmlwriter' '--with-xsl' '--with-libxml-dir=/usr' '--enable-bcmath' '--with-bz2=/usr' '--enable-calendar' '--enable-cli' '--enable-ctype' '--enable-dom' '--enable-fileinfo' '--enable-filter' '--enable-shmop' '--enable-sysvsem' '--enable-sysvshm' '--enable-sysvmsg' '--enable-json' '--enable-mbregex' '--enable-mbstring' '--with-mhash' '--with-mcrypt=/usr' '--enable-pcntl' '--with-pcre-regex' '--with-pcre-dir=/usr' '--enable-phar' '--enable-posix' '--with-readline=/usr' '--enable-sockets' '--enable-tokenizer' '--with-curl=/usr' '--with-openssl=/usr' '--enable-zip'

And this is the configure result:

```
checking for MySQLi support... yes
checking whether to enable embedded MySQLi support... no
checking for specified location of the MySQL UNIX socket... no
checking for MySQL UNIX socket location... no
...
checking for Oracle Database OCI8 support... no
checking for MySQL support for PDO... yes
checking for MySQL UNIX socket location... no
checking for PDO includes... checking for PDO includes... /home/pawel/.phpbrew/build/php-7.0.2/ext
...
checking whether to enable mysqlnd... no
checking whether to disable compressed protocol support in mysqlnd... yes
```

**Comment by c9s** [comment]
For example, I use the config below to setup the unix socket connection for pdo mysql:

```
pdo_mysql.default_socket = /opt/local/var/run/mysql56/mysqld.sock
mysqli.default_socket = /opt/local/var/run/mysql56/mysqld.sock
```

**Comment by c9s** [comment]
For people who encountered this issue, please:

1. Paste your phpinfo() in gist.
2. Paste your build.log in gist.
2. Paste your build command and its output with `--debug` flag. `phpbrew --debug install 5.6 ....`

The steps above can help us solve your issues faster. Thank you :)

**Comment by c9s** [comment]
This looks related to http://stackoverflow.com/questions/35230495/phpbrew-not-connecting-to-mysql

**Comment by c9s** [comment]
The new phpbrew will now detect your mysql sock path automatically (commit f7fafeb)

**Comment by webcrazy** [comment]
OK for me now. thanks @c9s
