### ISSUE TITLE
5.3.29 and FPM

### ISSUE THREAD

**Issue by kojilab** [phpbrew/phpbrew#658]
Hi

Because of a project that works on 5.3.29 I need to install PHP FPM. Unfortunately the +fpm doesn't add php-fpm to ~/.phpbrew/php/php-5.3.29/sbin/.
How can I resolve this?
Thanks

**Comment by Ronmi** [comment]
Could you please provide your `phpbrew` version and full command line you used? Developers will need these information to figure out where goes wrong, thx.

**Comment by kojilab** [comment]
I fixed it by renaming the phpfm.dYm file I believe to phpfm or something like this
