### ISSUE TITLE
Command `lookup-prefix` not found

### ISSUE THREAD

**Issue by belaustegui** [phpbrew/phpbrew#659]
I'm installing *phpbrew* under Ubuntu 15.10. When I try to set the lookup prefix with the command `phpbrew lookup-prefix ubuntu` I get the following response:

    phpbrew lookup-prefix ubuntu
    Did you mean 'self-update'? [Y/n]

When I run *phpbrew* without arguments, I can't find the `lookup-prefix` among the available commands. Is it not required anymore? Or has it been replaced for another command?

**Comment by c9s** [comment]
You didnt load the bash file, you need it to run phpbrew

Please check the document

Cristian Álvarez Belaustegui <notifications@github.com> 於 2016年1月17日 星期日寫道：

**Comment by belaustegui** [comment]
You are 100% right, my bad.
I didn't have the line `[[ -e ~/.phpbrew/bashrc ]] && source ~/.phpbrew/bashrc` in my *.bashrc*. It is now solved.
