### ISSUE TITLE
phpbrew switch from bash script inside docker container

### ISSUE THREAD

**Issue by jmaciasportela** [phpbrew/phpbrew#660]
I have this script that runs on docker container init (ubuntu 14.04):

``` bash
#!/bin/bash

echo =================
echo PHPBREW MANAGER
echo =================

phpbrew list
source $HOME/.phpbrew/bashrc
phpbrew switch $OC_PHP
php -v
```

And this is the output when is executed (content of OC_PHP env variable is 7.0.2):

```bash
~ > root@73203a1c7787 [php:5.5.31-phpbrew]
# ./phpbrew-manager.sh
=================
PHPBREW MANAGER
=================
Available PHP versions
  php-7.0.2
  php-5.6.17
 *php-5.5.31
  php-5.4.45
PHP 7.0.2 (cli) (built: Jan 17 2016 17:36:31) ( NTS DEBUG )
Copyright (c) 1997-2015 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2015 Zend Technologies
```

It seems to work fine but after that, bash prompt still showing the original version:

```bash
~ > root@73203a1c7787 [php:5.5.31-phpbrew]
#
``` 

If I do phpbrew switch directly from command line, it works fine, but I need to do it from this bash script to run different docker containers with different versions.

**Comment by Ronmi** [comment]
AFAIK `switch` command need *full* version name like `php-7.0.2` in previous version. Not sure if it behaves the same in current version, but I think it worth to try.

**Comment by jmaciasportela** [comment]
It seems not necessary anymore:

```bash
~ > root@73203a1c7787 [php:7.0.2 -phpbrew]
# phpbrew list
* php-7.0.2      
  php-5.6.17     
  php-5.5.31     
  php-5.4.45     
~ > root@73203a1c7787 [php:7.0.2 -phpbrew]
# phpbrew switch 5.4.45
~ > root@73203a1c7787 [php:5.4.45-phpbrew]
# php -v
PHP 5.4.45 (cli) (built: Jan 17 2016 17:47:53) (DEBUG)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
~ > root@73203a1c7787 [php:5.4.45-phpbrew]
```

**Comment by Ronmi** [comment]
@jmaciasportela yeah you are right, and I found the answer.

By looking into https://github.com/phpbrew/phpbrew/blob/master/shell/bashrc#L163 , the `switch` command will reconfigure your environment variables, which happends in a subshell (your script). So you'll need to source the `bashrc` file again in your current shell.

**Comment by jmaciasportela** [comment]
Solved. Thank you !
