### ISSUE TITLE
RuntimeException when compiling any PHP version

### ISSUE THREAD

**Issue by Kharag** [phpbrew/phpbrew#661]
Hello,

I have an issue when trying to install any PHP version.

<code>phpbrew install php-5.5.31 +default+mysql+pgsql+mb+fpm+gd -- --with-gd=shared --with-jpeg-dir=/usr --with-png-dir=/usr --enable-gd-native-ttf --with-freetype-dir=/usr/include/freetype2/freetype 

===> phpbrew will now build 5.5.31

===> Loading and resolving variants...

===> Downloading from http://www.php.net/get/php-5.5.31.tar.bz2/from/this/mirror
Redirecting to http://php.net/distributions/php-5.5.31.tar.bz2
[==================================================================] 13.03/13.03MB 100%

===> /opt/distfiles/php-5.5.31.tar.bz2 downloaded.

===> Extracting /opt/distfiles/php-5.5.31.tar.bz2 to /opt/tmp/php-5.5.31

RuntimeException: Unable to find /opt/tmp/php-src-php-5.5.31

Trace:

    0) PhpBrew\Tasks\ExtractTask->extract(PhpBrew\Build, '/opt/distfiles/php-5.5.31.tar.bz2', '/opt/build')
    1) PhpBrew\Command\InstallCommand->execute('php-5.5.31', '+default+mysql+pgsql+mb+fpm+gd', '--', '--with-gd=shared', '--with-jpeg-dir=/usr', '--with-png-dir=/usr', '--enable-gd-native-ttf', '--with-freetype-dir=/usr/include/freetype2/freetype')
    2) call_user_func_array([PhpBrew\Command\InstallCommand, 'execute'], ['php-5.5.31', '+default+mysql+pgsql+mb+fpm+gd', '--', '--with-gd=shared', '--with-jpeg-dir=/usr', '--with-png-dir=/usr', '--enable-gd-native-ttf', '--with-freetype-dir=/usr/include/freetype2/freetype'])
    3) CLIFramework\CommandBase->executeWrapper(['php-5.5.31', '+default+mysql+pgsql+mb+fpm+gd', '--', '--with-gd=shared', '--with-jpeg-dir=/usr', '--with-png-dir=/usr', '--enable-gd-native-ttf', '--with-freetype-dir=/usr/include/freetype2/freetype'])
    4) CLIFramework\Application->run(['/usr/bin/phpbrew', 'install', 'php-5.5.31', '+default+mysql+pgsql+mb+fpm+gd', '--', '--with-gd=shared', '--with-jpeg-dir=/usr', '--with-png-dir=/usr', '--enable-gd-native-ttf', '--with-freetype-dir=/usr/include/freetype2/freetype'])
    5) CLIFramework\Application->runWithTry(['/usr/bin/phpbrew', 'install', 'php-5.5.31', '+default+mysql+pgsql+mb+fpm+gd', '--', '--with-gd=shared', '--with-jpeg-dir=/usr', '--with-png-dir=/usr', '--enable-gd-native-ttf', '--with-freetype-dir=/usr/include/freetype2/freetype'])
    6) require('phar:///usr/bin/phpbrew/scripts/phpbrew-emb.php')
</code>

I checked, the folder is not there. There is only the php-5.5.31.tar file, no folder or anything.
I tried to manually unpack the file - no dice.

Any help would be greatly appreciated.

**Comment by jhdxr** [comment]
try `tar -C /opt/tmp/php-5.5.31 -xf /opt/distfiles/php-5.5.31.tar.bz2`, is there any error message?

**Comment by Kharag** [comment]
Unpacking does work, but the script fails anyways:

<code>
===> phpbrew will now build 5.5.31

---> Parsing variants from command arguments '+default+mysql+pgsql+mb+fpm+gd -- --with-gd=shared --with-jpeg-dir=/usr --with-png-dir=/usr --enable-gd-native-ttf --with-freetype-dir=/usr/include/freetype2/freetype'
===> Loading and resolving variants...

Checking distribution checksum...
Checksum matched: ebb66ad8e2bcf1a966b10d86e81a0119
===> Extracting /opt/distfiles/php-5.5.31.tar.bz2 to /opt/tmp/php-5.5.31

===> Removing /opt/build/php-5.5.31

RuntimeException: Unable to remove /opt/build/php-5.5.31.
Thrown from phar:///usr/bin/phpbrew/src/PhpBrew/Tasks/ExtractTask.php at line 54:


   51            $this->info("===> Removing $extractedDir");

   52            system("rm -rf $extractedDir", $ret);

   53            if ($ret !== 0) {

\>  54                throw new RuntimeException("Unable to remove $extractedDir.");

   55            }

   56        }

   57

   58        $this->info("===> Moving $extractedDirTemp to $extractedDir");


Trace:


    0) PhpBrew\Tasks\ExtractTask->extract(PhpBrew\Build, '/opt/distfiles/php-5.5.31.tar.bz2', '/opt/build')
        from phar:///usr/bin/phpbrew/src/PhpBrew/Command/InstallCommand.php: 336

    1) PhpBrew\Command\InstallCommand->execute('php-5.5.31', '+default+mysql+pgsql+mb+fpm+gd', '--', '--with-gd=shared', '--with-jpeg-dir=/usr', '--with-png-dir=/usr', '--enable-gd-native-ttf', '--with-freetype-dir=/usr/include/freetype2/freetype')
        from : 0

    2) call_user_func_array([PhpBrew\Command\InstallCommand, 'execute'], ['php-5.5.31', '+default+mysql+pgsql+mb+fpm+gd', '--', '--with-gd=shared', '--with-jpeg-dir=/usr', '--with-png-dir=/usr', '--enable-gd-native-ttf', '--with-freetype-dir=/usr/include/freetype2/freetype'])
        from phar:///usr/bin/phpbrew/vendor/corneltek/cliframework/src/CLIFramework/CommandBase.php: 845

    3) CLIFramework\CommandBase->executeWrapper(['php-5.5.31', '+default+mysql+pgsql+mb+fpm+gd', '--', '--with-gd=shared', '--with-jpeg-dir=/usr', '--with-png-dir=/usr', '--enable-gd-native-ttf', '--with-freetype-dir=/usr/include/freetype2/freetype'])
        from phar:///usr/bin/phpbrew/vendor/corneltek/cliframework/src/CLIFramework/Application.php: 398

    4) CLIFramework\Application->run(['/usr/bin/phpbrew', '--debug', 'install', 'php-5.5.31', '+default+mysql+pgsql+mb+fpm+gd', '--', '--with-gd=shared', '--with-jpeg-dir=/usr', '--with-png-dir=/usr', '--enable-gd-native-ttf', '--with-freetype-dir=/usr/include/freetype2/freetype'])
        from phar:///usr/bin/phpbrew/vendor/corneltek/cliframework/src/CLIFramework/Application.php: 282

    5) CLIFramework\Application->runWithTry(['/usr/bin/phpbrew', '--debug', 'install', 'php-5.5.31', '+default+mysql+pgsql+mb+fpm+gd', '--', '--with-gd=shared', '--with-jpeg-dir=/usr', '--with-png-dir=/usr', '--enable-gd-native-ttf', '--with-freetype-dir=/usr/include/freetype2/freetype'])
        from phar:///usr/bin/phpbrew/scripts/phpbrew-emb.php: 2

    6) require('phar:///usr/bin/phpbrew/scripts/phpbrew-emb.php')
        from /usr/bin/phpbrew: 97
</code>

The permissions are correct as far as I can check, they match the other folders still in there...
If I remove the folder, the scripts will complain about a missing configure (ofc, I deleted it..)

<code>
===> phpbrew will now build 5.5.31

---> Parsing variants from command arguments '+default+mysql+pgsql+mb+fpm+gd -- --with-gd=shared --with-jpeg-dir=/usr --with-png-dir=/usr --enable-gd-native-ttf --with-freetype-dir=/usr/include/freetype2/freetype'
===> Loading and resolving variants...

Checking distribution checksum...
Checksum matched: ebb66ad8e2bcf1a966b10d86e81a0119
===> Extracting /opt/distfiles/php-5.5.31.tar.bz2 to /opt/tmp/php-5.5.31

===> Moving /opt/tmp/php-5.5.31 to /opt/build/php-5.5.31

Source Directory: /opt/build/php-5.5.31
Writing variant info to /opt/php/php-5.5.31/phpbrew.variants

configure file not found, running './buildconf --force'...

Error: buildconf error: 
Configure options: --disable-all --enable-phar --enable-session --enable-short-tags --enable-tokenizer --with-pcre-regex --with-zlib=/usr --with-libdir=lib/x86_64-linux-gnu --with-mysql=mysqlnd --with-mysqli=mysqlnd --with-pdo-mysql=mysqlnd --with-pgsql --with-pdo-pgsql --enable-fpm --with-gd=shared,/usr --enable-gd-native-ttf --with-jpeg-dir=/usr --with-png-dir=/usr --with-freetype-dir=/usr --enable-dom --enable-libxml --enable-simplexml --enable-xml --enable-xmlreader --enable-xmlwriter --with-xsl --with-libxml-dir=/usr --enable-mbstring --enable-mbregex --enable-bcmath --with-bz2=/usr --enable-calendar --enable-cli --enable-ctype --enable-dom --enable-fileinfo --enable-filter --enable-shmop --enable-sysvsem --enable-sysvshm --enable-sysvmsg --enable-json --with-mhash=/usr --with-mcrypt=/usr --enable-pcntl --with-pcre-regex --with-pcre-dir=/usr --enable-pdo --enable-phar --enable-posix --with-readline=/usr --with-libedit=/usr --enable-sockets --enable-tokenizer --with-curl=/usr --with-openssl=/usr --enable-zip
</code>

**Comment by c9s** [comment]
I guess your `/opt` is on another device or is it ramdisk or ssd?

**Comment by c9s** [comment]
Looks like the extraction failed on /opt/tmp, thus it can't find the file to move.

I might need your tar version and the debug output (phpbrew --debug install ...)

If you get a change to come back, please ping me
