### ISSUE TITLE
cannot install apc

### ISSUE THREAD

**Issue by kojilab** [phpbrew/phpbrew#662]
Whether I switch to php7 or 5.6.16 I am getting this

===> Downloading from http://pecl.php.net/get/APC-3.1.13.tgz
[==================================================================] 167.57/167.57KB 100%
===> /Users/oliviermoratin/.phpbrew/distfiles/APC-3.1.13.tgz downloaded.
===> Extracting to /Users/oliviermoratin/.phpbrew/build/php-5.6.16/ext...
===> Installing apc extension...
Log stored at: /Users/oliviermoratin/.phpbrew/build/php-5.6.16/ext/apc/build.log
Changing directory to /Users/oliviermoratin/.phpbrew/build/php-5.6.16/ext/apc
===> Phpize...
===> Configuring...
===> Building...
===> Running make all: make -C /Users/oliviermoratin/.phpbrew/build/php-5.6.16/ext/apc  all  >> /Users/oliviermoratin/.phpbrew/build/php-5.6.16/ext/apc/build.log 2>&1
Exception: Command failed: make -C /Users/oliviermoratin/.phpbrew/build/php-5.6.16/ext/apc  all  >> /Users/oliviermoratin/.phpbrew/build/php-5.6.16/ext/apc/build.log 2>&1 returns 
Trace:

    0) PhpBrew\Utils::system(['make', '-C', '/Users/oliviermoratin/.phpbrew/build/php-5.6.16/ext/apc', '', 'all', ' >> /Users/oliviermoratin/.phpbrew/build/php-5.6.16/ext/apc/build.log 2>&1'], CLIFramework\Logger)
    1) PhpBrew\Tasks\MakeTask->make('/Users/oliviermoratin/.phpbrew/build/php-5.6.16/ext/apc', 'all')
    2) PhpBrew\Tasks\MakeTask->run(PhpBrew\Extension\PeclExtension)
    3) PhpBrew\Extension\ExtensionInstaller->install(PhpBrew\Extension\PeclExtension, [])
    4) PhpBrew\Extension\ExtensionManager->installExtension(PhpBrew\Extension\PeclExtension, [])
    5) PhpBrew\Command\ExtensionCommand\InstallCommand->execute('apc')
    6) call_user_func_array([PhpBrew\Command\ExtensionCommand\InstallCommand, 'execute'], ['apc'])
    7) CLIFramework\CommandBase->executeWrapper(['apc'])
    8) CLIFramework\Application->run(['/usr/local/bin//phpbrew', 'ext', 'install', 'apc'])
    9) CLIFramework\Application->runWithTry(['/usr/local/bin//phpbrew', 'ext', 'install', 'apc'])
    10) require('phar:///usr/local/bin/phpbrew/scripts/phpbrew-emb.php')

**Comment by kojilab** [comment]
used apcu and it worked

**Comment by marcioAlmada** [comment]
AFAIK `apc` is not available for php 5.5+, `apcu` is the right choice in your case :)

**Comment by alexisprevot** [comment]
Hi, I got the same error but on apcu. What can I do to fix it please ?

===> Downloading from http://pecl.php.net/get/apcu-5.1.3.tgz
[==================================================================] 105.88/105.88KB 100%
===> /home/alexis/.phpbrew/distfiles/apcu-5.1.3.tgz downloaded.
===> Extracting to /home/alexis/.phpbrew/build/php-5.6.4/ext...
===> Installing apcu extension...
Log stored at: /home/alexis/.phpbrew/build/php-5.6.4/ext/apcu/build.log
Changing directory to /home/alexis/.phpbrew/build/php-5.6.4/ext/apcu
===> Phpize...
===> Configuring...
===> Building...
===> Running make all: make -C /home/alexis/.phpbrew/build/php-5.6.4/ext/apcu  all  >> /home/alexis/.phpbrew/build/php-5.6.4/ext/apcu/build.log 2>&1
Exception: Command failed: make -C /home/alexis/.phpbrew/build/php-5.6.4/ext/apcu  all  >> /home/alexis/.phpbrew/build/php-5.6.4/ext/apcu/build.log 2>&1 returns 
Trace:

    0) PhpBrew\Utils::system(['make', '-C', '/home/alexis/.phpbrew/build/php-5.6.4/ext/apcu', '', 'all', ' >> /home/alexis/.phpbrew/build/php-5.6.4/ext/apcu/build.log 2>&1'], CLIFramework\Logger)
    1) PhpBrew\Tasks\MakeTask->make('/home/alexis/.phpbrew/build/php-5.6.4/ext/apcu', 'all')
    2) PhpBrew\Tasks\MakeTask->run(PhpBrew\Extension\PeclExtension)
    3) PhpBrew\Extension\ExtensionInstaller->install(PhpBrew\Extension\PeclExtension, [])
    4) PhpBrew\Extension\ExtensionManager->installExtension(PhpBrew\Extension\PeclExtension, [])
    5) PhpBrew\Command\ExtensionCommand\InstallCommand->execute('apcu', 'stable')
    6) call_user_func_array([PhpBrew\Command\ExtensionCommand\InstallCommand, 'execute'], ['apcu', 'stable'])
    7) CLIFramework\CommandBase->executeWrapper(['apcu', 'stable'])
    8) CLIFramework\Application->run(['/usr/local/bin/phpbrew', 'ext', 'install', 'apcu', 'stable'])
    9) CLIFramework\Application->runWithTry(['/usr/local/bin/phpbrew', 'ext', 'install', 'apcu', 'stable'])
    10) require('phar:///usr/local/bin/phpbrew/scripts/phpbrew-emb.php')

**Comment by olyckne** [comment]
Same problem here with installing apcu on php 5.6.14.
Looks like it tries to install apcu 5.1.3 which only works on php 7. 
Installing apcu 4.0.10 manually works

**Comment by roman-1983** [comment]
For php 5.6.21 this worked for me:

    phpbrew ext install apcu 4.0.11
