### ISSUE TITLE
Installation stuck with +apxs2 if php5.load.bak~ exists due to a previous installation

### ISSUE THREAD

**Issue by balazswmann** [phpbrew/phpbrew#665]
Hi!

I just noticed a weird thing and I thought I mention it.

I have Ubuntu 14.04 LTS and the latest version (1.20.5) of phpbrew. When I try to install a php version for the first time with the +apxs2 modifier everything works perfectly and the installation process successfully completes, but if I try to install and compile another php version with +apxs2 then the installation process "stuck" after the successful build process and after the "Installing..." text appears in the console. The situation is the same if I use the debug mode, I don't get any information about what happening. The installation process just stuck at that point and there is no timeout with error messages as I experienced.

What I figured out is that the above mentioned problem can be connected with the php5.load.bak~ backup file (located in /etc/apache2/mods-available on my computer) which is created before the php5.load file will be modified due to the +apxs2 modifier. So every time when the +apxs2 modifier used, the php5.load file will be modified, therefore a backup file (php5.load.bak~) will be created from it first. What I experienced is that if this backup file exists before a new installation, then the installation process will stuck as I mentioned earlier. But, if I remove the backup file before a new installation then the installation won't "stuck". That's all.

I hope this description will help.

**Comment by c9s** [comment]
Sorry this mechanism is designed in PHP system, Apache SAPI will modify the php5.load file automatically, this can't be fixed from phpbrew.
