### ISSUE TITLE
Problem switch php version

### ISSUE THREAD

**Issue by tokar86a** [phpbrew/phpbrew#666]
Hi

I end up whit this error when i try to switch:

root@Server1:~# phpbrew switch 5.6.17
You should not see this, if you see this, it means you didn't load the ~/.phpbrew/bashrc script, please check if bashrc is sourced in your shell.

I am not sure what i should check or change.

**Comment by Ronmi** [comment]
[This wiki page](https://github.com/phpbrew/phpbrew/wiki/Troubleshooting#you-should-not-see-this-please-check-if-bashrc-is-sourced-in-your-shell) can solve your problem.
