### ISSUE TITLE
Installing ext memcached or redis fails on php 7x

### ISSUE THREAD

**Issue by mirfilip** [phpbrew/phpbrew#673]
I have successfully installed `php-7.0.3` and wanted to install memcached and redis extensions. Both of them fail at the same step:
```
./common.h:3:10: fatal error: 'ext/standard/php_smart_str.h' file not found
#include <ext/standard/php_smart_str.h>
```
The problem stems from the fact `php_smart_str.h` is known as `php_smart_string.h` starting from php7. Clearly, the wrong sources are being used. I will use `redis` as an example:
```
phpbrew ext install redis latest
===> Downloading from http://pecl.php.net/get/redis-2.2.7.tgz
(...)
```
http://pecl.php.net/package/redis/2.2.7 has a release date of `2015-03-03` and mentions "PHP Version: PHP version 6.0.0 or older" for dependency. 

In comparison, installing [php70-redis](https://github.com/Homebrew/homebrew-php/blob/master/Formula/php70-redis.rb) via `brew` takes the sources from [official php7 branch of phpredis](https://github.com/phpredis/phpredis/tree/php7) which works fine.

In my experience, it's not uncommon for php7 extensions to maintain a separate release cycle from different branch, especially if backward compatibility needs to be broken.

Is phpbrew totally dependant upon `PECL` packages? Can we use other source?

**EDIT**:
[Wiki](https://github.com/phpbrew/phpbrew/wiki/Extension-Installer) mentions the possibility to install ext from a repository:
`phpbrew ext install https://github.com/c9s/cssmin.git` - this, however, doesn't seem to have an option to point at particular branch. Also, it seems to always append`archive/master.tar.gz`. If that command accepted github notation of `https://github.com/<<vendor>>/<<package>>/archive/<<branch_name>>.zip` - it would be an ok-ish workaround.

**Comment by Tuurlijk** [comment]
The magic command seems to be:

```bash
phpbrew ext install https://github.com/phpredis/phpredis php7
```

**Comment by Tuurlijk** [comment]
As for memcached:

```bash
phpbrew ext install https://github.com/php-memcached-dev/php-memcached php7 -- --disable-memcached-sasl
```

**Comment by mirfilip** [comment]
@Tuurlijk yaaay! Never thought of that. I think I will contribute to FAQ.

**Comment by mirfilip** [comment]
[Troubleshooting section](https://github.com/phpbrew/phpbrew/wiki/Troubleshooting#i-cannot-install-extension-x-with-php-7) updated with some info.

**Comment by ve3** [comment]
Memcached error:

> Exception: Command failed: ./configure '--disable-memcached-sasl' --with-php-config=/opt/phpbrew/php/php-7.0.0/bin/php-config >> /opt/phpbrew/build/php-7.0.0/ext/memcached/build.log 2>&1 returns

**Comment by mirfilip** [comment]
@ve3 inspect the `/opt/phpbrew/build/php-7.0.0/ext/memcached/build.log`. You'll probably find some errors there to point you to what's wrong.

**Comment by ve3** [comment]
> Configuring for:
> PHP Api Version:         20151012
> Zend Module Api No:      20151012
> Zend Extension Api No:   320151012
> checking for grep that handles long lines and -e... /bin/grep
> checking for egrep... /bin/grep -E
> checking for a sed that does not truncate output... /bin/sed
> checking for cc... cc
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.out
> checking for suffix of executables... 
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C compiler... yes
> checking whether cc accepts -g... yes
> checking for cc option to accept ISO C89... none needed
> checking how to run the C preprocessor... cc -E
> checking for icc... no
> checking for suncc... no
> checking whether cc understands -c and -o together... yes
> checking for system library directory... lib
> checking if compiler supports -R... no
> checking if compiler supports -Wl,-rpath,... yes
> checking build system type... x86_64-unknown-linux-gnu
> checking host system type... x86_64-unknown-linux-gnu
> checking target system type... x86_64-unknown-linux-gnu
> checking for PHP prefix... /opt/phpbrew/php/php-7.0.0
> checking for PHP includes... -I/opt/phpbrew/php/php-7.0.0/include/php -I/opt/phpbrew/php/php-7.0.0/include/php/main -I/opt/phpbrew/php/php-7.0.0/include/php/TSRM -I/opt/phpbrew/php/php-7.0.0/include/php/Zend -I/opt/phpbrew/php/php-7.0.0/include/php/ext -I/opt/phpbrew/php/php-7.0.0/include/php/ext/date/lib
> checking for PHP extension directory... /opt/phpbrew/php/php-7.0.0/lib/php/extensions/no-debug-non-zts-20151012
> checking for PHP installed headers prefix... /opt/phpbrew/php/php-7.0.0/include/php
> checking if debug is enabled... no
> checking if zts is enabled... no
> checking for re2c... re2c
> checking for re2c version... 0.13.5 (ok)
> checking for gawk... no
> checking for nawk... nawk
> checking if nawk is broken... no
> checking whether to enable memcached support... yes, shared
> checking for libmemcached... yes, shared
> checking whether to enable memcached session handler support... yes
> checking whether to enable memcached igbinary serializer support... no
> checking whether to enable memcached json serializer support... no
> checking whether to enable memcached msgpack serializer support... no
> checking whether to enable memcached sasl support... no
> checking whether to enable memcached protocol support... no
> checking whether to use system FastLZ bibrary... no
> checking for ZLIB... yes, shared
> checking for pkg-config... /usr/bin/pkg-config
> checking for zlib location... /usr
> checking for session includes... /opt/phpbrew/php/php-7.0.0/include/php
> checking for memcached session support... enabled
> checking for memcached igbinary support... disabled
> checking for memcached msgpack support... disabled
> checking for libmemcached location... configure: error: memcached support requires libmemcached. Use --with-libmemcached-dir=<DIR> to specify the prefix where libmemcached headers and library are located

**Comment by mirfilip** [comment]
`checking for libmemcached location... configure: error: memcached support requires libmemcached.`

libmemcached is a dependency for [php extension](https://github.com/php-memcached-dev/php-memcached)

**Comment by c9s** [comment]
Cookbook updated https://github.com/phpbrew/phpbrew/wiki/PHP7

**Comment by vpArth** [comment]
> `checking for libmemcached location... configure: error: memcached support requires libmemcached.`

Library package required.

For Ubuntu:
```sh
apt install libmemcached-dev
```
