### ISSUE TITLE
Bash completion problem

### ISSUE THREAD

**Issue by mirfilip** [phpbrew/phpbrew#674]
I see [there is a bash completion script](https://github.com/phpbrew/phpbrew/blob/master/completion/bash/_phpbrew) but I'm not sure how it is distributed. I've installed `phpbrew` from `brew` but the competion script seems not to be the part of the package.

I did `cd /usr/local/share/bash-completion/completions && curl -O https://raw.githubusercontent.com/phpbrew/phpbrew/master/completion/bash/_phpbrew` and started the new terminal window but the completion doesn't seem to work. Any ideas?

**Comment by c9s** [comment]
Does sourcing the file directly under the terminal work for you?

**Comment by c9s** [comment]
I mean you can download it and source it in your .bash_profile or .bashrc

**Comment by mirfilip** [comment]
Pardon me, that was me being a noob.
`curl -O https://raw.githubusercontent.com/phpbrew/phpbrew/master/completion/bash/_phpbrew` command (which I always use in such circumstances) ended up with downloading HTML site instead of a file, not sure why.

Of course it works both my and your way. Thanks @c9s
