### ISSUE TITLE
/usr/bin/env: php: file or directory not found

### ISSUE THREAD

**Issue by ricardochaves** [phpbrew/phpbrew#675]
I'm using Ubuntu Server 14. I did a fresh install of the OS.
Following the application of this [link](https://github.com/phpbrew/phpbrew/wiki/Requirement).
Phpbrew downloaded, installed.
When trying to run the init, or any other command, it writes this message:

`/usr/bin/env: php: file or directory not found`

I do not know what can be wrong, follow the step by step wiki and it did not work.

**Comment by c9s** [comment]
Seems you don't have a system php to execute phpbrew?
