### ISSUE TITLE
Error: "E: Unable to find a source package for php5"

### ISSUE THREAD

**Issue by UTANdev** [phpbrew/phpbrew#676]
I got an error at the very first step of the requirements:

```
$ sudo apt-get build-dep php5
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to find a source package for php5
```

I'm running Linux Mint 17.3 and PHP 5.5.9 is already installed -- so do I even have to run this first command? If I do have to run apt-get build, what's preventing me to do so? Thanks.

**Comment by Ronmi** [comment]
Do you have any source entry (deb-src) in your /etc/apt/sources.list ? If
not, apt cannot find any source package to download. You can check mint
forum to find out correct settings for mint.

BTW, you can manually install dependencies without running apt-get
build-deps, but it will be a lot of works.

UTAN Dev <notifications@github.com> 於 2016年2月13日週六 00:24 寫道：

> I got an error at the very first step of the requirements:
>
> $ sudo apt-get build-dep php5
> Reading package lists... Done
> Building dependency tree
> Reading state information... Done
> E: Unable to find a source package for php5
>
> I'm running Linux Mint 17.3 and PHP 5.5.9 is already installed -- so do I
> even have to run this first command? If I do, what's wrong? Thanks.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/phpbrew/phpbrew/issues/676>.
>
-- 

Ronmi Ren <ronmi.ren@gmail.com>

**Comment by UTANdev** [comment]
Thanks for your help. For reference, I was able to solve the problem: Mint Menu>Software Sources>(input password)>Official Repositories>Enable source code repositories
