### ISSUE TITLE
Issue with bashrc file

### ISSUE THREAD

**Issue by sumityadav** [phpbrew/phpbrew#679]
I updated my mac for latest stuff but it seem it broke phpbrew.

This is what I did.
```
brew update; brew upgrade --all; brew cleanup; npm install npm -g; npm update -g; sudo gem update --system; sudo gem update
```

Now when I open the new tab on my mac I get the following issue:

```
-bash: [: too many arguments
-bash: [: too many arguments
-bash: which: command not found
-bash: grep: command not found
-bash: grep: command not found
-bash: cut: command not found
-bash: tr: command not found
```

When I comment out the source ```~/.phpbrew/bashrc``` it reverts to system php and nothing works.

Any suggestions?

**Comment by c9s** [comment]
Looks like your $PATH environment variable was modified, so `grep`, `which` is not found. please dump you ~/.phpbrew/init file

**Comment by c9s** [comment]
I guess is also related to 86672c0e507b595c9b97bbaf7b24e38954ddf739

Please help us verify this fix when you have some time. If it still occurs, please reopen this issue.
