### ISSUE TITLE
bashrc breaks "cd -" on zsh

### ISSUE THREAD

**Issue by weierophinney** [phpbrew/phpbrew#680]
I use zsh, and recently noticed that `cd -` always changes to the `/` directory. I was unsure what was causing the issue, so I removed everything from my `.zshrc` and started enabling things one by one to determine what was causing the behavior. Re-enabling the `source $HOME/.phpbrew/bashrc` was the one that caused it.

In looking through that file's history, I found patch 84f50c9e0, submitted as part of #583; reverting that patch fixes the behavior for me.

**Comment by c9s** [comment]
@chadrien do you have an idea of this? I also encountered this issue. I thought the rc feature should be enabled manually.

**Comment by chadrien** [comment]
I'll take a look at it, at least to check that `cd -` remains unbroken on manual enabling and to fix it if it's not
