### ISSUE TITLE
Use phive (https://phar.io/) for installing apps

### ISSUE THREAD

**Issue by boekkooi** [phpbrew/phpbrew#682]
Hi there,

I just came across PHIVE (The PHAR Installation and Verification Environment) and it reminded me that the current `phpbrew app` command and that it could use some more love.
So I was wondering maybe phpbrew should use PHIVE instead of trying to build a custom app store. 

Would you be interested in a PR that replaces the current app store with PHIVE?

Cheers,
Warnar

**Comment by c9s** [comment]
Sure! That would be great!

Warnar Boekkooi <notifications@github.com> 於 2016年2月26日 星期五寫道：

**Comment by chadrien** [comment]
Maybe a way to achieve this would be:

* when installing a fresh copy of phpbrew, don't do anything more than we already do
* when running `phpbrew app get` for the first time, download PHIVE
* when running `phpbrew app get` simply proxy the command arguments to `phive install`

`phpbrew help app` should say that phpbrew is using PHIVE and display a link to the PHIVE documentation.

@c9s @marcioAlmada thoughts?

**Comment by morozov** [comment]
There's no need to integrate PHIVE into PHPBrew. The two tools can be used independently (see #1088).
