### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by NerdGuruDevelopers** [phpbrew/phpbrew#686]
Can I get a paypal or bitcoin address to buy the author of PHPBrew a drink? I appreciate the work and it saved me a bunch of time.

**Comment by c9s** [comment]
Hi! you can buy a drink for @marcioAlmada, he did a lot of works!

**Comment by c9s** [comment]
Hi @NerdGuruDevelopers 

Thank you for the kindness. I've discussed with @marcioAlmada, and we think there are more people this money. It would be great if you don't mind donating to the ICCF: https://iccf.nl/news.html  This project is helping children in Uganda.

Best, c9s
