### ISSUE TITLE
.phpbrew dir  does not make

### ISSUE THREAD

**Issue by strawberry-shortcake** [phpbrew/phpbrew#687]
Hi
thank you for providing great tool!
I installed this tool. 
And I type "phpbrew init",but nothing happend.
Just "???" was shown on my terminal.
So,there isn't .phpbrew dir in my home dir yet.
If someone have an idea,please tell me how to init.

-environment-
mac osX el capitan
php 5.3.29

**Comment by c9s** [comment]
That's weird, please run:

```
which phpbrew
```

To see where is your phpbrew located.

**Comment by strawberry-shortcake** [comment]
Thanks for respond about it.
I already run that command.
It returns "/usr/local/bin//phpbrew".
This response is same as some commands that I can currently use .

**Comment by strawberry-shortcake** [comment]
I already resolved this.
It was a problem of environmental-dependent .
Thanks.
