### ISSUE TITLE
Is phpbrew totally broken on OS X 10.11.2 Xcode 7.2.1 Homebrew full updated?

### ISSUE THREAD

**Issue by bhaines** [phpbrew/phpbrew#688]
Attempt to install 5.6.14 or 5.6.15 and I get:
`configure: error: Cannot find OpenSSL's <evp.h>`
hint: it's installed. specifying its location doesn't help

cd to:
~/.phpbrew/build/php-5.6.15
...and run: 
./configure --with-openssl
...works.

Attempt to install 5.6.19 and get:
`configure: error: Cannot find enchant`
hint: it's installed.

No amount of searching generates a fix for either problem.

I can't believe I'm the only PHP developer with a current OS X installation.

I've spent three evenings on this with no love. What should my expectations be? Should this just work or must I start submitting pull requests.

**Comment by c9s** [comment]
See here https://github.com/phpbrew/phpbrew/wiki/Trouble-Shooting:-Can't-build-PHP-on-OS-X-El-Capitan

**Comment by c9s** [comment]
And this one https://github.com/phpbrew/phpbrew/issues/607

**Comment by bhaines** [comment]
Yeah, none of that works.

So again. Is the intention to support OS X & Homebrew? If it is, I'll help.

**Comment by c9s** [comment]
I think so. There are some isssues for looking up include paths with
homebrew.

I don't know homebrew, but phpbrew works pretty well with Macports.

bhaines <notifications@github.com> 於 2016年3月12日 星期六寫道：

**Comment by c9s** [comment]
I re-visited this issue again, and I still don't encounter this issue. that's weird. maybe you can try the latest release.

**Comment by c9s** [comment]
My `evp.h` was located in `/opt/local/include/openssl/evp.h`, and I think the `configure` didn't find your evp.h because it doesn't know how to find it (because homebrew install openssl in different location)

Maybe `--with-openssl={prefix}` would help
