### ISSUE TITLE
Debug/Variant as a version ?

### ISSUE THREAD

**Issue by Jurigag** [phpbrew/phpbrew#691]
I just wonder if you can add ability like build variant(or globally any variant with +debug) as an other php version like for example php-7.0.4-debug ? +debug is pretty much hard slowing php, and sometimes you need it if you are developing PHP Extension(phalcon contributor here) and pretty much in others situations you dont need it and performance cost it's sometimes like 2-3 times.

**Comment by marcioAlmada** [comment]
Hi,

Did you try `phpbrew install 7.0.4 +default+debug --as php-7.0.4-debug`?

After switching with `phpbrew switch 7.0.4-debug` running `php -v` should output:

```
PHP 7.0.4 (cli) (built: Mar 18 2016 15:00:19) ( NTS DEBUG )
[...]
```


:wink:

**Comment by Jurigag** [comment]
Oh damn i didnt, i guess im too lazy, thanks for that ! :D Thanks for this tip.

**Comment by marcioAlmada** [comment]
Actually the command is: `phpbrew install 7.0.4 as 7.0.4-debug +default+debug`

**Comment by marcioAlmada** [comment]
You're welcome.

**Comment by marcioAlmada** [comment]
Yes, `[[ -e ~/.phpbrew/bashrc ]] && source ~/.phpbrew/bashrc` should go on your `.bashrc` or equivalent.

**Comment by Jurigag** [comment]
But i dont know where is .bashrc, when i added it to /bash/.bashrc in beginng i have many errors and have to add path to PATH(like it resets or something). i have .phpbrew installed under /root/.phpbrew

**Comment by marcioAlmada** [comment]
what are the errors?

**Comment by Jurigag** [comment]
Like those:

```
The command could not be located because '/bin:/usr/bin' is not included in the PATH environment variable
```

After adding 
```
[[ -e ~/.phpbrew/bashrc ]] && source ~/.phpbrew/bashrc
```
To /root/.bashrc

/etc/enviroment looks like this:
```
PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/bin"
```

**Comment by c9s** [comment]
Looks like something related to #694 ?

**Comment by c9s** [comment]
Hi @Jurigag, please help us verify this issue when you have some time. :) if it still occurs, please reopne this issue.

**Comment by Jurigag** [comment]
Already done, actually i did what was wrote just after doing `phpbrew init` i don't know what so i just put

```
export PHPBREW_SET_PROMPT=1
export PHPBREW_RC_ENABLE=1
source /root/.phpbrew/bashrc
```

to /root/.bashrc
