### ISSUE TITLE
No variants installed

### ISSUE THREAD

**Issue by CaredduMattia** [phpbrew/phpbrew#692]
I install php 5.6.19 with the following command : 
`phpbrew install 5.6.19 +mysql +json +curl +intl +cli +mcrypt +pdo +xml +zip +ftp +exif +ctype               +session +zlib +openssl +apxs2 +bcmath +bz2 +calendar +dom +fileinfo               +filter +ipc +mbregex +mbstring +mhash +pcntl +pcre +phar +posix +readline               +sockets +tokenizer  -- --with-libdir=lib64 --with-libdir=lib64 
`

Now if i look in php.ini for example I don't have any mysql.so enable.
php --ini return the no additional ini file is parsed.

But if i check using phpinfo(); all extensions seems to work.
How this is possible?

**Comment by c9s** [comment]
You won't have `mysql.so`, it's statically compiled into php.
