### ISSUE TITLE
Installing variant as new version don't build apache module

### ISSUE THREAD

**Issue by Jurigag** [phpbrew/phpbrew#693]
Well when using:

```
phpbrew install 7.0.4 as 7.0.4-debug +default+dbs+debug+apxs2
```

There is no libphp7.0.4-debug.so in /usr/lib/apache2/modules
My guess it's already cheking if libphp7.0.4.so exists, and then not building it ?

Oh sry - it's building it, but as libphp7.0.4.so

**Comment by c9s** [comment]
Sorry, there won't be a `libphp7.0.4-debug.so` file. The name is not customizable, it's programmed in PHP's build system.

**Comment by Jurigag** [comment]
Yea i dealed with it myself. Just changed name to debug myself
