### ISSUE TITLE
Can't install ext curl.

### ISSUE THREAD

**Issue by CaredduMattia** [phpbrew/phpbrew#696]
I'm having a issue trying to install curl extension.
If i try to install : 
`phpbrew ext install curl`
I get : 

> Exception: Invalid package version: curl with version 'stable'.

So I try to list all known version of curl ext : 
`phpbrew ext known curl`
But then i get another error : 

> PHP Warning:  file_get_contents(http://pecl.php.net/rest/r/curl/allreleases.xml): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
 in phar:///usr/bin/phpbrew/src/PhpBrew/Extension/ExtensionDownloader.php on line 99

Warning: file_get_contents(http://pecl.php.net/rest/r/curl/allreleases.xml): failed to open stream: HTTP request failed! HTTP/1.1 404 Not Found
 in phar:///usr/bin/phpbrew/src/PhpBrew/Extension/ExtensionDownloader.php on line 99
PHP Warning:  array_map(): Argument #2 should be an array in phar:///usr/bin/phpbrew/src/PhpBrew/Extension/Provider/PeclProvider.php on line 103

Warning: array_map(): Argument #2 should be an array in phar:///usr/bin/phpbrew/src/PhpBrew/Extension/Provider/PeclProvider.php on line 103

The url for file_get_contents http://pecl.php.net/rest/r/curl/allreleases.xml don't exists.
So how can I install curl ?
Thanks.

**Comment by c9s** [comment]
Curl extension is bundled in php source, you have to install it when you're building your php.

**Comment by c9s** [comment]
This should be fixed, there will be a fallback downloader when installing extension.

**Comment by c9s** [comment]
Please reopen if this still occurs.
