### ISSUE TITLE
Missing the option to install 5.3.29

### ISSUE THREAD

**Issue by rsantellan** [phpbrew/phpbrew#697]
I have done: **phpbrew known --old** showing this:
`
7.0: 7.0.4, 7.0.3, 7.0.2, 7.0.1, 7.0.0 ...
5.6: 5.6.19, 5.6.18, 5.6.17, 5.6.16, 5.6.15, 5.6.14, 5.6.13, 5.6.12 ...
5.5: 5.5.33, 5.5.32, 5.5.31, 5.5.30, 5.5.29, 5.5.28, 5.5.27, 5.5.26 ...
5.4: 5.4.45, 5.4.44, 5.4.43, 5.4.42, 5.4.41, 5.4.40, 5.4.39, 5.4.38 ...
You can run `phpbrew update` to get a newer release list.
`
I don't show the 5.3 version any more. Trying to install it show this:
`
rodrigo@rodrigo ~/proyectos/ $ phpbrew install 5.3.29 +default
Exception: Version 5.3.29 not found.
Trace:

    0) PhpBrew\Command\InstallCommand->execute('5.3.29', '+default')
    1) call_user_func_array([PhpBrew\Command\InstallCommand, 'execute'], ['5.3.29', '+default'])
    2) CLIFramework\CommandBase->executeWrapper(['5.3.29', '+default'])
    3) CLIFramework\Application->run(['/usr/local/bin/phpbrew', 'install', '5.3.29', '+default'])
    4) CLIFramework\Application->runWithTry(['/usr/local/bin/phpbrew', 'install', '5.3.29', '+default'])
    5) require('phar:///usr/local/bin/phpbrew/scripts/phpbrew-emb.php')
`
How can I enable it back?

**Comment by xorti** [comment]
Just figure it out!
@rsantellan run `phpbrew update --old` after that you will see all the available versions.
```
# phpbrew update --old
===> Fetching release list...
7.0: 5 releases
5.6: 20 releases
5.5: 34 releases
5.4: 46 releases
5.3: 30 releases
5.2: 17 releases
5.1: 7 releases
5.0: 6 releases
===> Done
```

**Comment by rsantellan** [comment]
That fix it! You should add it to the usage instructions!!

Thank you!
