### ISSUE TITLE
can't install GD support 

### ISSUE THREAD

**Issue by sumic** [phpbrew/phpbrew#698]
i use :phpbrew install php5.4.45 +default+gd+mysql+pdo
`Zend/zend_list.lo Zend/zend_indent.lo Zend/zend_builtin_functions.lo Zend/zend_sprintf.lo Zend/zend_ini.lo Zend/zend_qsort.lo Zend/zend_multibyte.lo Zend/zend_ts_hash.lo Zend/zend_stream.lo Zend/zend_iterators.lo Zend/zend_interfaces.lo Zend/zend_exceptions.lo Zend/zend_strtod.lo Zend/zend_gc.lo Zend/zend_closures.lo Zend/zend_float.lo Zend/zend_string.lo Zend/zend_signal.lo Zend/zend_objects.lo Zend/zend_object_handlers.lo Zend/zend_objects_API.lo Zend/zend_default_classes.lo Zend/zend_execute.lo sapi/apache2handler/mod_php5.lo sapi/apache2handler/sapi_apache2.lo sapi/apache2handler/apache_config.lo sapi/apache2handler/php_functions.lo main/internal_functions.lo -lcrypt -lz -lexslt -lresolv -lcrypt -ledit -ltermcap -lmcrypt -lltdl -lcurl -lbz2 -lz -lcrypto -lssl -lcrypto -lrt -lm -ldl -lnsl -lxml2 -lcurl -lxml2 -lxml2 -lcrypt -lxml2 -lxml2 -lxml2 -lxslt -lxml2 -lcrypt  -o libphp5.4.45.la
/bin/bash /home/sumic/.phpbrew/build/php-5.4.45/libtool --silent --preserve-dup-deps --mode=compile cc -I/usr/include -Iext/gd/ -I/home/sumic/.phpbrew/build/php-5.4.45/ext/gd/ -DPHP_ATOM_INC -I/home/sumic/.phpbrew/build/php-5.4.45/include -I/home/sumic/.phpbrew/build/php-5.4.45/main -I/home/sumic/.phpbrew/build/php-5.4.45 -I/home/sumic/.phpbrew/build/php-5.4.45/ext/date/lib -I/home/sumic/.phpbrew/build/php-5.4.45/ext/ereg/regex -I/usr/include/libxml2 -I/usr/local/include -I/usr/include/freetype2 -I/home/sumic/.phpbrew/build/php-5.4.45/ext/mbstring/oniguruma -I/home/sumic/.phpbrew/build/php-5.4.45/ext/mbstring/libmbfl -I/home/sumic/.phpbrew/build/php-5.4.45/ext/mbstring/libmbfl/mbfl -I/home/sumic/.phpbrew/build/php-5.4.45/TSRM -I/home/sumic/.phpbrew/build/php-5.4.45/Zend    -g -O2 -fvisibility=hidden   -c /home/sumic/.phpbrew/build/php-5.4.45/ext/gd/gd.c -o ext/gd/gd.lo 
/bin/bash /home/sumic/.phpbrew/build/php-5.4.45/libtool --silent --preserve-dup-deps --mode=compile cc -I/usr/include -Iext/gd/ -I/home/sumic/.phpbrew/build/php-5.4.45/ext/gd/ -DPHP_ATOM_INC -I/home/sumic/.phpbrew/build/php-5.4.45/include -I/home/sumic/.phpbrew/build/php-5.4.45/main -I/home/sumic/.phpbrew/build/php-5.4.45 -I/home/sumic/.phpbrew/build/php-5.4.45/ext/date/lib -I/home/sumic/.phpbrew/build/php-5.4.45/ext/ereg/regex -I/usr/include/libxml2 -I/usr/local/include -I/usr/include/freetype2 -I/home/sumic/.phpbrew/build/php-5.4.45/ext/mbstring/oniguruma -I/home/sumic/.phpbrew/build/php-5.4.45/ext/mbstring/libmbfl -I/home/sumic/.phpbrew/build/php-5.4.45/ext/mbstring/libmbfl/mbfl -I/home/sumic/.phpbrew/build/php-5.4.45/TSRM -I/home/sumic/.phpbrew/build/php-5.4.45/Zend    -g -O2 -fvisibility=hidden   -c /home/sumic/.phpbrew/build/php-5.4.45/ext/gd/gdcache.c -o ext/gd/gdcache.lo 
/bin/bash /home/sumic/.phpbrew/build/php-5.4.45/libtool --silent --preserve-dup-deps --mode=compile cc -I/usr/include -Iext/gd/ -I/home/sumic/.phpbrew/build/php-5.4.45/ext/gd/ -DPHP_ATOM_INC -I/home/sumic/.phpbrew/build/php-5.4.45/include -I/home/sumic/.phpbrew/build/php-5.4.45/main -I/home/sumic/.phpbrew/build/php-5.4.45 -I/home/sumic/.phpbrew/build/php-5.4.45/ext/date/lib -I/home/sumic/.phpbrew/build/php-5.4.45/ext/ereg/regex -I/usr/include/libxml2 -I/usr/local/include -I/usr/include/freetype2 -I/home/sumic/.phpbrew/build/php-5.4.45/ext/mbstring/oniguruma -I/home/sumic/.phpbrew/build/php-5.4.45/ext/mbstring/libmbfl -I/home/sumic/.phpbrew/build/php-5.4.45/ext/mbstring/libmbfl/mbfl -I/home/sumic/.phpbrew/build/php-5.4.45/TSRM -I/home/sumic/.phpbrew/build/php-5.4.45/Zend    -g -O2 -fvisibility=hidden   -c /home/sumic/.phpbrew/build/php-5.4.45/ext/gd/libgd/gd_compat.c -o ext/gd/libgd/gd_compat.lo 
/home/sumic/.phpbrew/build/php-5.4.45/ext/gd/libgd/gd_compat.c: In function ‘gdJpegGetVersionInt’:
/home/sumic/.phpbrew/build/php-5.4.45/ext/gd/libgd/gd_compat.c:14:9: error: ‘JPEG_LIB_VERSION’ undeclared (first use in this function)
  return JPEG_LIB_VERSION;
         ^
/home/sumic/.phpbrew/build/php-5.4.45/ext/gd/libgd/gd_compat.c:14:9: note: each undeclared identifier is reported only once for each function it appears in
/home/sumic/.phpbrew/build/php-5.4.45/ext/gd/libgd/gd_compat.c: In function ‘gdJpegGetVersionString’:
/home/sumic/.phpbrew/build/php-5.4.45/ext/gd/libgd/gd_compat.c:19:9: error: ‘JPEG_LIB_VERSION’ undeclared (first use in this function)
  switch(JPEG_LIB_VERSION) {
         ^
make: *** [ext/gd/libgd/gd_compat.lo] Error 1`

**Comment by c9s** [comment]
This is not related to phpbrew
