### ISSUE TITLE
Unable to install APC

### ISSUE THREAD

**Issue by ve3** [phpbrew/phpbrew#702]
This install command `phpbrew ext install APC`

It show me error.

> Exception: Command failed: make -C /opt/phpbrew/build/php-5.6.20/ext/apc all >> /opt/phpbrew/build/php-5.6.20/ext/apc/build.log 2>&1 returns

**Comment by jhdxr** [comment]
plz paste your `/opt/phpbrew/build/php-5.6.20/ext/apc/build.log` here

**Comment by ve3** [comment]
> Configuring for:
> PHP Api Version:         20131106
> Zend Module Api No:      20131226
> Zend Extension Api No:   220131226
> checking for grep that handles long lines and -e... /bin/grep
> checking for egrep... /bin/grep -E
> checking for a sed that does not truncate output... /bin/sed
> checking for cc... cc
> checking whether the C compiler works... yes
> checking for C compiler default output file name... a.out
> checking for suffix of executables... 
> checking whether we are cross compiling... no
> checking for suffix of object files... o
> checking whether we are using the GNU C compiler... yes
> checking whether cc accepts -g... yes
> checking for cc option to accept ISO C89... none needed
> checking how to run the C preprocessor... cc -E
> checking for icc... no
> checking for suncc... no
> checking whether cc understands -c and -o together... yes
> checking for system library directory... lib
> checking if compiler supports -R... no
> checking if compiler supports -Wl,-rpath,... yes
> checking build system type... x86_64-unknown-linux-gnu
> checking host system type... x86_64-unknown-linux-gnu
> checking target system type... x86_64-unknown-linux-gnu
> checking for PHP prefix... /opt/phpbrew/php/php-5.6.16
> checking for PHP includes... -I/opt/phpbrew/php/php-5.6.16/include/php -I/opt/phpbrew/php/php-5.6.16/include/php/main -I/opt/phpbrew/php/php-5.6.16/include/php/TSRM -I/opt/phpbrew/php/php-5.6.16/include/php/Zend -I/opt/phpbrew/php/php-5.6.16/include/php/ext -I/opt/phpbrew/php/php-5.6.16/include/php/ext/date/lib
> checking for PHP extension directory... /opt/phpbrew/php/php-5.6.16/lib/php/extensions/no-debug-non-zts-20131226
> checking for PHP installed headers prefix... /opt/phpbrew/php/php-5.6.16/include/php
> checking if debug is enabled... no
> checking if zts is enabled... no
> checking for re2c... re2c
> checking for re2c version... 0.13.5 (ok)
> checking for gawk... no
> checking for nawk... nawk
> checking if nawk is broken... no
> checking whether to enable APC support... yes, shared
> checking whether we should enable cache request file info... no
> checking whether we should use mmap... yes
> checking whether we should use semaphore locking instead of fcntl... no
> checking whether we should use pthread mutex locking... yes
> pthread mutexs are supported!
> checking whether we should use pthread read/write locking... no
> checking whether the target compiler supports builtin atomics... yes
> checking whether we should use spin locks... no
> checking whether we should enable memory protection... no
> checking for zend_set_lookup_function_hook... no
> checking for sigaction... yes
> checking for union semun... no
> checking whether we should enable valgrind support... checking for ANSI C header files... yes
> checking for sys/types.h... yes
> checking for sys/stat.h... yes
> checking for stdlib.h... yes
> checking for string.h... yes
> checking for memory.h... yes
> checking for strings.h... yes
> checking for inttypes.h... yes
> checking for stdint.h... yes
> checking for unistd.h... yes
> yes
> checking valgrind/memcheck.h usability... no
> checking valgrind/memcheck.h presence... no
> checking for valgrind/memcheck.h... no
> checking for shm_open in -lrt... yes
> checking whether to include code coverage symbols... no
> checking for ld used by cc... /usr/bin/ld
> checking if the linker (/usr/bin/ld) is GNU ld... yes
> checking for /usr/bin/ld option to reload object files... -r
> checking for BSD-compatible nm... /usr/bin/nm -B
> checking whether ln -s works... yes
> checking how to recognize dependent libraries... pass_all
> checking dlfcn.h usability... yes
> checking dlfcn.h presence... yes
> checking for dlfcn.h... yes
> checking the maximum length of command line arguments... 1572864
> checking command to parse /usr/bin/nm -B output from cc object... ok
> checking for objdir... .libs
> checking for ar... ar
> checking for ranlib... ranlib
> checking for strip... strip
> checking if cc supports -fno-rtti -fno-exceptions... no
> checking for cc option to produce PIC... -fPIC
> checking if cc PIC flag -fPIC works... yes
> checking if cc static flag -static works... yes
> checking if cc supports -c -o file.o... yes
> checking whether the cc linker (/usr/bin/ld -m elf_x86_64) supports shared libraries... yes
> checking whether -lc should be explicitly linked in... no
> checking dynamic linker characteristics... GNU/Linux ld.so
> checking how to hardcode library paths into programs... immediate
> checking whether stripping libraries is possible... yes
> checking if libtool supports shared libraries... yes
> checking whether to build shared libraries... yes
> checking whether to build static libraries... no
> 
> creating libtool
> appending configuration tag "CXX" to libtool
> configure: creating ./config.status
> config.status: creating config.h
> make: Entering directory '/opt/phpbrew/build/php-5.6.16/ext/apc'
> /bin/bash /opt/phpbrew/build/php-5.6.16/ext/apc/libtool --mode=compile cc  -I. -I/opt/phpbrew/build/php-5.6.16/ext/apc -DPHP_ATOM_INC -I/opt/phpbrew/build/php-5.6.16/ext/apc/include -I/opt/phpbrew/build/php-5.6.16/ext/apc/main -I/opt/phpbrew/build/php-5.6.16/ext/apc -I/opt/phpbrew/php/php-5.6.16/include/php -I/opt/phpbrew/php/php-5.6.16/include/php/main -I/opt/phpbrew/php/php-5.6.16/include/php/TSRM -I/opt/phpbrew/php/php-5.6.16/include/php/Zend -I/opt/phpbrew/php/php-5.6.16/include/php/ext -I/opt/phpbrew/php/php-5.6.16/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /opt/phpbrew/build/php-5.6.16/ext/apc/apc.c -o apc.lo 
> mkdir .libs
>  cc -I. -I/opt/phpbrew/build/php-5.6.16/ext/apc -DPHP_ATOM_INC -I/opt/phpbrew/build/php-5.6.16/ext/apc/include -I/opt/phpbrew/build/php-5.6.16/ext/apc/main -I/opt/phpbrew/build/php-5.6.16/ext/apc -I/opt/phpbrew/php/php-5.6.16/include/php -I/opt/phpbrew/php/php-5.6.16/include/php/main -I/opt/phpbrew/php/php-5.6.16/include/php/TSRM -I/opt/phpbrew/php/php-5.6.16/include/php/Zend -I/opt/phpbrew/php/php-5.6.16/include/php/ext -I/opt/phpbrew/php/php-5.6.16/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /opt/phpbrew/build/php-5.6.16/ext/apc/apc.c  -fPIC -DPIC -o .libs/apc.o
> /opt/phpbrew/build/php-5.6.16/ext/apc/apc.c: In function ‘apc_search_paths’:
> /opt/phpbrew/build/php-5.6.16/ext/apc/apc.c:352:55: warning: passing argument 2 of ‘php_stream_locate_url_wrapper’ from incompatible pointer type [-Wincompatible-pointer-types]
>      wrapper = php_stream_locate_url_wrapper(filename, &path_for_open, 0 TSRMLS_CC);
>                                                        ^
> In file included from /opt/phpbrew/php/php-5.6.16/include/php/main/php.h:398:0,
>                  from /opt/phpbrew/build/php-5.6.16/ext/apc/apc.h:61,
>                  from /opt/phpbrew/build/php-5.6.16/ext/apc/apc.c:34:
> /opt/phpbrew/php/php-5.6.16/include/php/main/php_streams.h:552:28: note: expected ‘const char **’ but argument is of type ‘char **’
>  PHPAPI php_stream_wrapper *php_stream_locate_url_wrapper(const char *path, const char **path_for_open, int options TSRMLS_DC);
>                             ^
> /opt/phpbrew/build/php-5.6.16/ext/apc/apc.c:416:20: warning: assignment discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
>          exec_fname = zend_get_executed_filename(TSRMLS_C);
>                     ^
> /bin/bash /opt/phpbrew/build/php-5.6.16/ext/apc/libtool --mode=compile cc  -I. -I/opt/phpbrew/build/php-5.6.16/ext/apc -DPHP_ATOM_INC -I/opt/phpbrew/build/php-5.6.16/ext/apc/include -I/opt/phpbrew/build/php-5.6.16/ext/apc/main -I/opt/phpbrew/build/php-5.6.16/ext/apc -I/opt/phpbrew/php/php-5.6.16/include/php -I/opt/phpbrew/php/php-5.6.16/include/php/main -I/opt/phpbrew/php/php-5.6.16/include/php/TSRM -I/opt/phpbrew/php/php-5.6.16/include/php/Zend -I/opt/phpbrew/php/php-5.6.16/include/php/ext -I/opt/phpbrew/php/php-5.6.16/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /opt/phpbrew/build/php-5.6.16/ext/apc/php_apc.c -o php_apc.lo 
>  cc -I. -I/opt/phpbrew/build/php-5.6.16/ext/apc -DPHP_ATOM_INC -I/opt/phpbrew/build/php-5.6.16/ext/apc/include -I/opt/phpbrew/build/php-5.6.16/ext/apc/main -I/opt/phpbrew/build/php-5.6.16/ext/apc -I/opt/phpbrew/php/php-5.6.16/include/php -I/opt/phpbrew/php/php-5.6.16/include/php/main -I/opt/phpbrew/php/php-5.6.16/include/php/TSRM -I/opt/phpbrew/php/php-5.6.16/include/php/Zend -I/opt/phpbrew/php/php-5.6.16/include/php/ext -I/opt/phpbrew/php/php-5.6.16/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /opt/phpbrew/build/php-5.6.16/ext/apc/php_apc.c  -fPIC -DPIC -o .libs/php_apc.o
> /bin/bash /opt/phpbrew/build/php-5.6.16/ext/apc/libtool --mode=compile cc  -I. -I/opt/phpbrew/build/php-5.6.16/ext/apc -DPHP_ATOM_INC -I/opt/phpbrew/build/php-5.6.16/ext/apc/include -I/opt/phpbrew/build/php-5.6.16/ext/apc/main -I/opt/phpbrew/build/php-5.6.16/ext/apc -I/opt/phpbrew/php/php-5.6.16/include/php -I/opt/phpbrew/php/php-5.6.16/include/php/main -I/opt/phpbrew/php/php-5.6.16/include/php/TSRM -I/opt/phpbrew/php/php-5.6.16/include/php/Zend -I/opt/phpbrew/php/php-5.6.16/include/php/ext -I/opt/phpbrew/php/php-5.6.16/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /opt/phpbrew/build/php-5.6.16/ext/apc/apc_cache.c -o apc_cache.lo 
>  cc -I. -I/opt/phpbrew/build/php-5.6.16/ext/apc -DPHP_ATOM_INC -I/opt/phpbrew/build/php-5.6.16/ext/apc/include -I/opt/phpbrew/build/php-5.6.16/ext/apc/main -I/opt/phpbrew/build/php-5.6.16/ext/apc -I/opt/phpbrew/php/php-5.6.16/include/php -I/opt/phpbrew/php/php-5.6.16/include/php/main -I/opt/phpbrew/php/php-5.6.16/include/php/TSRM -I/opt/phpbrew/php/php-5.6.16/include/php/Zend -I/opt/phpbrew/php/php-5.6.16/include/php/ext -I/opt/phpbrew/php/php-5.6.16/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /opt/phpbrew/build/php-5.6.16/ext/apc/apc_cache.c  -fPIC -DPIC -o .libs/apc_cache.o
> /opt/phpbrew/build/php-5.6.16/ext/apc/apc_cache.c: In function ‘_apc_cache_user_update’:
> /opt/phpbrew/build/php-5.6.16/ext/apc/apc_cache.c:818:63: error: ‘IS_CONSTANT_INDEX’ undeclared (first use in this function)
>              switch(Z_TYPE_P((*slot)->value->data.user.val) & ~IS_CONSTANT_INDEX) {
>                                                                ^
> /opt/phpbrew/build/php-5.6.16/ext/apc/apc_cache.c:818:63: note: each undeclared identifier is reported only once for each function it appears in
> /opt/phpbrew/build/php-5.6.16/ext/apc/apc_cache.c:820:22: error: ‘IS_CONSTANT_ARRAY’ undeclared (first use in this function)
>                  case IS_CONSTANT_ARRAY:
>                       ^
> Makefile:186: recipe for target 'apc_cache.lo' failed
> make: *** [apc_cache.lo] Error 1
> make: Leaving directory '/opt/phpbrew/build/php-5.6.16/ext/apc'

**Comment by jhdxr** [comment]
apc is not compatibled with php 5.6 (see php/php-src@82ecdcd ) 

maybe you can use [APCu](https://github.com/krakjoe/apcu) as an alternative.
