### ISSUE TITLE
invalid option: --as

### ISSUE THREAD

**Issue by matthbull** [phpbrew/phpbrew#704]
running this in terminal (according to [documentation](https://github.com/phpbrew/phpbrew/wiki/Cookbook)) results in an exception.

    $ phpbrew install --like php-7.0.3 --as php-7.0.5 7.0.5

> GetOptionKit\Exception\InvalidOptionException: Invalid option: --as

substituting `--alias` as the documentation seems to suggest, results in a similar error.

**Comment by c9s** [comment]
The `--alias` option seems removed. 

Try this one: `phpbrew install 7.0.5 like 7.0.5-debug as aaa`

**Comment by c9s** [comment]
cookbook updated. 

fyi: https://github.com/phpbrew/phpbrew/wiki/Semantic-Install

**Comment by matthbull** [comment]
many thanks for that.
