### ISSUE TITLE
Extensions installation issue for 5.3 and 5.4

### ISSUE THREAD

**Issue by webmasterpf** [phpbrew/phpbrew#707]
Hi,

I would to use this app to manage different PHP versions on my LAMP Server (ubuntu 14.04) but I ran into fails every the same like :

```
Error: Configure failed: 1
Configure options: --disable-all --enable-phar --enable-session --enable-short-tags --enable-tokenizer --with-pcre-regex --with-zlib=/usr --with-libdir=lib/i386-linux-gnu --enable-dom --enable-libxml --enable-simplexml --enable-xml --enable-xmlreader --enable-xmlwriter --with-xsl --with-libxml-dir=/usr --enable-bcmath --enable-calendar --enable-cli --enable-ctype --enable-dom --enable-fileinfo --enable-filter --enable-shmop --enable-sysvsem --enable-sysvshm --enable-sysvmsg --enable-json --enable-mbregex --enable-mbstring --with-mhash --with-mcrypt --enable-pcntl --with-pcre-regex --enable-pdo --enable-phar --enable-posix --with-readline=/usr --enable-sockets --enable-tokenizer --with-curl=/usr --with-openssl=/usr --enable-zip 
```
So I think there is a miss-setting (?) in my $PATH or in my php.ini perhaps..
If someone could hepl me on this.

thanks

**Comment by jhdxr** [comment]
hello, plz paste your log here. The log should located in `~/.phpbrew/build/XXXXX/build.log`, where `XXXXX` means the php version, e.g. `php-7.0.5`

 
------------------ Original ------------------

**Comment by webmasterpf** [comment]
this is the end of file:
$ tail -F /home/webmaster/.phpbrew/build/php-5.4.45/build.log
```
checking size of short... (cached) 2
checking size of long... (cached) 4
checking for an ANSI C-conforming const... yes
checking whether time.h and sys/time.h may both be included... yes
checking for working alloca.h... (cached) yes
checking for alloca... (cached) yes
checking for working memcmp... yes
checking for stdarg.h... (cached) yes
checking for mcrypt support... yes
configure: error: mcrypt.h not found. Please reinstall libmcrypt.
```

**Comment by jhdxr** [comment]
as the logs says, `mcrypt.h` is missing. try `apt-get install libmcrypt-dev`

**Comment by webmasterpf** [comment]
this seem to fix it but there are a lot of things that's gone wild :
```
Error: Configure failed: 1
Configure options: --disable-all --enable-phar --enable-session --enable-short-tags --enable-tokenizer --with-pcre-regex --with-zlib=/usr --with-libdir=lib/i386-linux-gnu --enable-dom --enable-libxml --enable-simplexml --enable-xml --enable-xmlreader --enable-xmlwriter --with-xsl --with-libxml-dir=/usr --enable-bcmath --with-bz2 --enable-calendar --enable-cli --enable-ctype --enable-dom --enable-fileinfo --enable-filter --enable-shmop --enable-sysvsem --enable-sysvshm --enable-sysvmsg --enable-json --enable-mbregex --enable-mbstring --with-mhash --with-mcrypt=/usr --enable-pcntl --with-pcre-regex --enable-pdo --enable-phar --enable-posix --with-readline=/usr --enable-sockets --enable-tokenizer --with-curl=/usr --with-openssl=/usr --enable-zip
Last 5 lines in the log file:
checking for gzgets in -lz... yes
checking whether to enable bc style precision math functions... yes
checking for BZip2 support... yes
checking for BZip2 in default path... not found
configure: error: Please reinstall the BZip2 distribution
Please checkout the build log file for more details:
         tail /home/webmaster/.phpbrew/build/php-5.4.45/build.log

```

**Comment by jhdxr** [comment]
It's the same problem like mcrypt, the develpment files are missing. try `apt-get install bzip2-devel`, you can google for the package names if there is anything more missing.

 
------------------ Original ------------------

**Comment by webmasterpf** [comment]
ok so I need to install all the dev versions for missing extensions ?

**Comment by jhdxr** [comment]
yes. you need all this files to compile the source.
 
 
------------------ 原始邮件 ------------------
发件人: "webmasterpf"; 
发送时间: 2016年4月25日(星期一) 下午5:55
收件人: "phpbrew/phpbrew"; 
抄送: "江湖大虾仁"; "Comment"; 
主题: Re: [phpbrew/phpbrew] Extensions installation issue for 5.3 and 5.4(#707)

 


ok so I need to install all the dev versions for missing extensions ? 
 
&mdash;

**Comment by webmasterpf** [comment]
I found on launchpad the right name for dev version : libbz2-dev

**Comment by webmasterpf** [comment]
Install was find for 5.4.45 but fail for 5.3.29 : 
```
Error: Make failed.
Configure options: --disable-all --enable-phar --enable-session --enable-short-tags --enable-tokenizer --with-pcre-regex --with-zlib=/usr --with-libdir=lib/i386-linux-gnu --enable-intl --enable-dom --enable-libxml --enable-simplexml --enable-xml --enable-xmlreader --enable-xmlwriter --with-xsl --with-libxml-dir=/usr --enable-bcmath --with-bz2=/usr --enable-calendar --enable-cli --enable-ctype --enable-dom --enable-fileinfo --enable-filter --enable-shmop --enable-sysvsem --enable-sysvshm --enable-sysvmsg --enable-json --enable-mbregex --enable-mbstring --with-mhash --with-mcrypt=/usr --enable-pcntl --with-pcre-regex --enable-pdo --enable-phar --enable-posix --with-readline=/usr --enable-sockets --enable-tokenizer --with-curl=/usr --with-openssl=/usr --enable-zip
```
end of log:
```
/usr/bin/ld: ext/intl/msgformat/msgformat_helpers.o: undefined reference to symbol '__gxx_personality_v0@@CXXABI_1.3'
//usr/lib/i386-linux-gnu/libstdc++.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [sapi/cgi/php-cgi] Erreur 1
```
so what do I do ?

**Comment by c9s** [comment]
This is related to GCC and libstdc++, can you paste the full log in gist?

webmasterpf <notifications@github.com> 於 2016年4月25日 星期一寫道：

**Comment by c9s** [comment]
See
http://stackoverflow.com/questions/6045809/problem-with-g-and-undefined-reference-to-gxx-personality-v0

http://www.serverphorums.com/read.php?7,369479

webmasterpf <notifications@github.com> 於 2016年4月25日 星期一寫道：

**Comment by webmasterpf** [comment]
https://gist.github.com/webmasterpf/9e0033a3ea21be7dc873e399a5b27e03

**Comment by c9s** [comment]
"I just hacked my Ubuntu PHP-from-source installer to touch up the
Makefile by prepending -lstdc++ to EXTRA_LIBS. That does the job."

webmasterpf <notifications@github.com> 於 2016年4月25日 星期一寫道：

**Comment by webmasterpf** [comment]
For now, I would to test `phpbrew use php-5.4.45` but this no take effect accordingly to my Drupal report for my PHP version actually in use...so what I missed ? Then will see about fixing 5.3.29

**Comment by c9s** [comment]
The above comment already mentioned the solution. Go into your build dir, edit Makefile and fix the EXTRA_LIB

**Comment by webmasterpf** [comment]
this is the line in my makefile for 5.4.45 for example : `
EXTRA_LIBS = -lcrypt -lz -lexslt -lresolv -lcrypt -lreadline -lncurses -lmcrypt -lltdl -lcurl -lbz2 -lz -lcrypto -lssl -lcrypto -lrt -lm -ldl -lnsl -lxml2 -lcurl -lxml2 -lxml2 -lcrypt -lxml2 -lxml2 -lxml2 -lxslt -lxml2 -lcrypt`
so I add `-lstdc` but no changes to use PHP 5.4.45, do I restart apache ?

**Comment by jhdxr** [comment]
both `phpbrew use` and `phpbrew switch` only effect php in terminal, including php-cli and php-fpm, and you can use `php -v` to test if you have succeed in switching the version.
If you want to switch the php version of the web server (apache) and you are not using php-fpm, then you have to edit the config file of your web server manually. For more details, refer to your web server's manual.

**Comment by webmasterpf** [comment]
yes I found this : http://stackoverflow.com/questions/34320576/installing-multiple-php-versions-on-ubuntu-server
in cli, it's actually working but Apache doesn't switch as you said it.
```
$ phpbrew use php-5.4.45
webmaster@vm-server1:~$ php -v
PHP 5.4.45 (cli) (built: Apr 25 2016 12:08:17)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
```
So the phpbrew doesn't work for php 5.3.29 but good for 5.4.45

**Comment by jhdxr** [comment]
well, you didn't catch my point. If you want to switch the version which apache use, you have to edit config file of apache manually. phpbrew only modify the config file when you build php with `--apxs2`

**Comment by webmasterpf** [comment]
I understand but actually I fix the issue to install with` -apxs2` extension.Then I will edit the apache config file as you ask. :)

**Comment by webmasterpf** [comment]
with [this](https://github.com/phpbrew/phpbrew/issues/226#issuecomment-170124212) I can change php version used by Apache but after changing my apps (Drupal) doesn't work.. :/  Perhaps I need to do somme symlinks ?

**Comment by jhdxr** [comment]
There are various reasons which break the apps. You'd better turn to the developers of the apps.

**Comment by c9s** [comment]
After changing the EXTRA_LIBS, you have to run `make`

**Comment by webmasterpf** [comment]
@c9s  And how can I do that ?

**Comment by c9s** [comment]
@webmasterpf I've included the patch in the latest phpbrew, run `self-update` and re-install your php again, it should work for you.

```
phpbrew self-update
phpbrew clean -a {version}
phpbrew --debug install {version} .... variants
```

Please paste me the build.log if you still encounter the issue.

**Comment by webmasterpf** [comment]
I'm a noob in this so some help is needed ;) , after self-update, I'm facing an issue :
```
phpbrew clean -a {5.4.45}
Invalid argument {5.4.45}
webmaster@vm-server1:~$ phpbrew clean -a {version}
Invalid argument {version}
webmaster@vm-server1:~$ phpbrew list
* (system)
  php-5.5.9
  php-5.4.45
webmaster@vm-server1:~$ phpbrew clean -a {php-5.4.45}
Invalid argument {php-5.4.45}
```

**Comment by webmasterpf** [comment]
the log for 5.5.9 : https://gist.github.com/webmasterpf/38787e108b17945d053d8e62c9504df3

**Comment by c9s** [comment]
I guess its broken by my some commit in this morning, would you mind try that again?

**Comment by c9s** [comment]
phpbrew clean php-5.5.9 

You need prefix because its build name

**Comment by c9s** [comment]
If php-5.6.20 is not in the list, that means it could be failed install. Please paste me the build.log :)

**Comment by webmasterpf** [comment]
According to my Drush error (drupal) I think the issue come from this file : 
` /home/webmaster/.phpbrew/php/php-5.4.45/etc/php.ini`
And how can I use the default php version on my system ?

**Comment by c9s** [comment]
Simply run phpbrew off
