### ISSUE TITLE
Patch task improvement

### ISSUE THREAD

**Issue by c9s** [phpbrew/phpbrew#709]
- [x] Add description method for each Patch class
- [x] Use One patch task to patch the files. (should have methods for different build phases)
- [x] Patches might happen before `configure` or after `configure` or `post make`
- [x] Implement `RemoteDiffPatchRule`
- [x] Implement `LocalDiffPatchRule`
- [x] Add more php patches from homebrew-php and macports php
  - [x] php53 patch https://github.com/Homebrew/homebrew-php/blob/master/Formula/php53.rb
  - [x] php70 patch https://github.com/Homebrew/homebrew-php/blob/master/Formula/php70.rb

**Comment by c9s** [comment]
Hi @shinnya, @marcioAlmada  I've refactored the current patch classes and unit tests, could you help me test the new patch kit on develop branch when you have some time to try?

And I think it's time to implement `patch -p0` to improve the build experience since we have a better patch integration. :)

**Comment by c9s** [comment]
Looks fine, I've merged into master

**Comment by marcioAlmada** [comment]
Hi, not having much time but this worked nicely!

**Comment by c9s** [comment]
@marcioAlmada Thanks!
