### ISSUE TITLE
style ci?

### ISSUE THREAD

**Issue by jhdxr** [phpbrew/phpbrew#715]
[style ci](https://styleci.io/) can help us improve our code style. what's more important, it can help us avoid some syntax error on old php platform, for example. `[]` will be converted to `array()`

I've test it on my fork repo (jhdxr/phpbrew) and it looks good. However, the first fix commit will include 109 changed files(jhdxr/phpbrew#1) which looks like a huge edit.

**Comment by c9s** [comment]
Sounds good. :) could you explain more about how it works and how does it change our work flow? Thanks

**Comment by c9s** [comment]
Does that means we have to abandon travis ci ?

**Comment by jhdxr** [comment]
of course not. travis ci focus on the build and test, while style ci just focus on the code style. so they can co-exists. 

it works like travis ci, if we enable it (and of course, configure is also needed), it will give a report to each commit/pr to indicate if the code style is good, and it can provide a pr to fix the code style if needed (so we don't need to care about code style any more)

**Comment by c9s** [comment]
got it, I think we can give it a try if you're interested in working on it. :)
