### ISSUE TITLE
Error notice in new 1.20.1 release

### ISSUE THREAD

**Issue by markwu** [phpbrew/phpbrew#716]
### Output

```
mark@osx:~$ phpbrew install 5.6.21 +default +mysql +gettext=/usr/local/opt/gettext +iconv +ftp +exif +dba +openssl +soap +apxs2=/usr/local/bin/apxs
===> phpbrew will now build 5.6.21
===> Loading and resolving variants...
sh: ../Cellar/mysql/5.7.12/bin/mysql_config: No such file or directory
PHP Notice:  Undefined offset: 0 in phar:///usr/local/Cellar/phpbrew/1.21.1/libexec/phpbrew/src/PhpBrew/VariantBuilder.php on line 392
```

### Expected Result

```
No error messages
```

### Command

    phpbrew install 5.6.21 +default +mysql +gettext=/usr/local/opt/gettext +iconv +ftp +exif +dba +openssl +soap +apxs2=/usr/local/bin/apxs

### Platform

OSX 10.11.4

Running PHP: 

    PHP 5.6.20

Installing PHP:

    PHP 5.6.21

**Comment by markwu** [comment]
It seems `Utils::findBin('mysql_config')` get the symbolic information through `readlink`, but `readlink` return a related path instead of absolute path.

`mysql_config@ -> ../Cellar/mysql/5.7.12/bin/mysql_config`

**Comment by markwu** [comment]
Maybe you should consider use the following script to get real path to avoid this kind of errors.

```
realpath(readlink('/usr/local/bin/mysql_config'))
```

This will return `/usr/local/Cellar/mysql/5.7.12/bin/mysql_config`, instead of `../Cellar/mysql/5.7.12/bin/mysql_config`

**Comment by jhdxr** [comment]
thanks for your report, we will fix this bug in next release.

**Comment by c9s** [comment]
Yes, thanks @markwu for reporting this 👍

**Comment by c9s** [comment]
@jhdxr could you run `make` to update the phar on github? thanks!  (I am outside right now, don't have a laptop to update the release)

**Comment by c9s** [comment]
The composer.lock file was updated for release, so you could do composer
install and we could have the same dependencies

xiami <notifications@github.com> 於 2016年4月30日 星期六寫道：

**Comment by jhdxr** [comment]
@c9s  I have updated the phar file without bumping version, is it ok?

**Comment by c9s** [comment]
yes, it should be fine. we can bump the version later.

**Comment by c9s** [comment]
thank you all :)

**Comment by markwu** [comment]
I confirmed the bug fixed in new released phpbrew.phar, thanks for your hard works.
