### ISSUE TITLE
Class 'Symfony\Component\Yaml\Yaml' not foundphp

### ISSUE THREAD

**Issue by icfr** [phpbrew/phpbrew#718]
### Output

> ===> phpbrew will now build 5.6.21
===> Loading and resolving variants...
PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Yaml\Yaml' not found in phar:///usr/local/bin/phpbrew/PhpBrew/Config.php:2
Stack trace:
#0 phar:///usr/local/bin/phpbrew/PhpBrew/Config.php(2): PhpBrew\Config::getConfig()
#1 phar:///usr/local/bin/phpbrew/PhpBrew/VariantBuilder.php(2): PhpBrew\Config::getConfigParam('variants')
#2 phar:///usr/local/bin/phpbrew/PhpBrew/Command/InstallCommand.php(3): PhpBrew\VariantBuilder->__construct()
#3 [internal function]: PhpBrew\Command\InstallCommand->execute('5.6.21', '+default', '+apxs2', '+mysql', '+pdo', '+curl')
#4 phar:///usr/local/bin/phpbrew/CLIFramework/CommandBase.php(2): call_user_func_array(Array, Array)
#5 phar:///usr/local/bin/phpbrew/CLIFramework/Application.php(2): CLIFramework\CommandBase->executeWrapper(Array)
#6 phar:///usr/local/bin/phpbrew/PhpBrew/Console.php(2): CLIFramework\Application->run(Array)
#7 phar:///usr/local/bin/phpbrew/scripts/phpbrew-emb.php(2): PhpBrew\Console->runWithTry(Array)
#8 /usr/local/bin/phpbrew(7): require('phar:///usr/loc...')
#9 {ma in phar:///usr/local/bin/phpbrew/PhpBrew/Config.php on line 2

### Command
phpbrew install 5.6.21  +default +apxs2 +mysql +pdo +curl

### Platform

OS:

Ubuntu 16.04 LTS

PHP:
PHP 7.0.4-7ubuntu2 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies

phpbrew - 1.21.1
cliframework core: 2.5.4

**Comment by c9s** [comment]
Looks like something happened before

**Comment by c9s** [comment]
Please run `phpbrew self-update` and try the re-compiled phar file.

**Comment by icfr** [comment]
it's ok thanks :)

**Comment by c9s** [comment]
Thanks

**Comment by c9s** [comment]
@jhdxr looks like the YAML installed on your machine is different?
