### ISSUE TITLE
phpbrew config not edit the right php.ini

### ISSUE THREAD

**Issue by xstable** [phpbrew/phpbrew#722]
```
phpbrew use 5.6.21
phpbrew config 
```
- Change entry: date.timezone and set any Value you want. 
- Save
- Check Setting with phpinfo() (is not set)

Only way to edit the right file is to edit:
```
nano ~/.phpbrew/php/php-5.6.21/etc/php.ini
```

**Comment by c9s** [comment]
Since your build name is `php-5.6.21`, you need to `phpbrew use php-5.6.21` and `phpbrew config`

**Comment by xstable** [comment]
I have done this. Maybe I've describe it wrong or with missing details in the issue, but I was on 5.6.21

-------- Ursprüngliche Nachricht --------
Von: Yo-An Lin <notifications@github.com> 
Datum: 01.05.2016  14:02  (GMT+01:00) 
An: phpbrew/phpbrew <phpbrew@noreply.github.com> 
Cc: Samuel Suther <info@suther.de>, Author <author@noreply.github.com> 
Betreff: Re: [phpbrew/phpbrew] phpbrew config not edit the right php.ini
  (#722) 

Since your build name is php-5.6.21, you need to phpbrew use php-5.6.21 and phpbrew config

**Comment by c9s** [comment]
OK, i will confirm this later

Samuel Suther <notifications@github.com> 於 2016年5月1日 星期日寫道：

**Comment by c9s** [comment]
What's the phpbrew version?   Can you run self-update again?  I can't reproduce this issue

**Comment by c9s** [comment]
Can't reproduce
