### ISSUE TITLE
Curl extension not loaded on Ubuntu 16.04

### ISSUE THREAD

**Issue by redaxmedia** [phpbrew/phpbrew#727]
Dear PHPBrew team,

I suggest to investigate the Ubuntu 16.04 release in combination with PHPBrew - the "curl extension" could not be loaded by PHPBrew.

## Output

```
# WARNING: curl extension might be required for fetching data.
* php-7.0.6
```

### Expected Result

```
* php-7.0.6
```

### Command

```
phpbrew list
```

### Platform

OS:

Ubuntu 16.04
Running PHP: 7.0.3

**Comment by c9s** [comment]
Are you running system php? (installed from apt-get?)

Or did you build the php with +curl variant?

**Comment by c9s** [comment]
`curl` variant might be required to run phpbrew, so if you build your php without curl, phpbrew will show this warning message, it's expected.

**Comment by redaxmedia** [comment]
Curl is installed on the system, but maybe it does not work with the PHP7 version? I build each PHP version with +dbs +mb and +default.

Ssome debug information:

![ow4ddm jpg](https://cloud.githubusercontent.com/assets/1835397/15096634/594efb1c-1502-11e6-8de1-5dfe59cd3291.png)

**Comment by c9s** [comment]
Whats your phpbrew version? Can you run self-update?

**Comment by c9s** [comment]
Try add --debug flag after 'phpbrew'

**Comment by c9s** [comment]
And please paste your build log in gist.

**Comment by redaxmedia** [comment]
I have phpbrew 1.21.4 installed, the self-update command worked perfect as it is using curl from the system I guess.

**PHP 5.6.21**

phpbrew info: http://pastebin.com/Z5weD97e
build.log: [build.txt](https://github.com/phpbrew/phpbrew/files/253850/build.txt)

**Comment by c9s** [comment]
Looks like you didnt compile the php with curl variant?

And when you run ext install curl, phpize failed

I need that build log

redaxmedia <notifications@github.com> 於 2016年5月8日 星期日寫道：

**Comment by redaxmedia** [comment]
I posted the build.txt in the comment before ... check it out

**Comment by c9s** [comment]
No the one you posted is the build log of php, when you run ext install , there is another build log, inside your ext/curl/build.log

**Comment by c9s** [comment]
No not that one, the one you posted is the build log of php, and which shows the php is not compiled with curl. (hence the message is correct)

When you run ext install , there is another build log, in the ext/curl/build.log under your build directory.

**Comment by redaxmedia** [comment]
$ cat /home/redaxmedia/.phpbrew/build/php-5.6.21/ext/curl/build.log

<pre>
Configuring for:
PHP Api Version:         20131106
Zend Module Api No:      20131226
Zend Extension Api No:   220131226
Cannot find autoconf. Please check your autoconf installation and the
$PHP_AUTOCONF environment variable. Then, rerun this script.
</pre>

Installing autoconf via <code>sudo apt-get install autoconf</code> solved the issue. Thank you

**Comment by c9s** [comment]
You're welcome, hope it helps you.
