### ISSUE TITLE
phpbrew must init command everytime the pc reboot.

### ISSUE THREAD

**Issue by ve3** [phpbrew/phpbrew#731]
I use [Install phpbrew into system-wide environment.](https://github.com/phpbrew/phpbrew/wiki/Cookbook#install-phpbrew-into-system-wide-environment)
Installed some php versions such as 5.6.0, 5.6.21.
When i reboot the pc and use command

```
phpbrew list
```

It show me "Please install at least one PHP with your prefered version."
I have to run command `phpbrew init` and `export PHPBREW_ROOT=/opt/phpbrew` and `source ~/.phpbrew/bashrc` everytime I restart my pc (virtualbox).

How to make it automatic start?

One more question.
When I look into (root)~/.phpbrew/init file. I see these 2 lines.
```
# DO NOT EDIT THIS FILE
???
```
Is it correctly with "???" line?

**Comment by c9s** [comment]
looks like duplicated issue from #732

**Comment by jhdxr** [comment]
which OS and php do you use?

**Comment by ve3** [comment]
Utunbu 14.04.
I'm confused about installation instruction I just don't know what file to edit and where is .bashrc file.
It's OK now.

However I copy the whole file content of ~/.phpbrew/init from my old virtualbox installation. I don't know why there is "???" in that file.
