### ISSUE TITLE
phpbrew returns ??? in the console.  The detect_unicode setting needs to be turned off for php 5.3

### ISSUE THREAD

**Issue by ve3** [phpbrew/phpbrew#732]
I have already tried to install PHP 5.3.29, 5.3.28 with this command.

```
phpbrew install 5.3.29 +default +dbs +mb +xmlrpc +gettext +openssl +apxs2=/usr/bin/apxs2 +exif +iconv
```

It was successfully installed but when I **use** or **switch** to PHP 5.3.29 and run command such as `phpbrew --help`
I got this response.

```
root@ubuntu:~# phpbrew
```

```
???root@ubuntu:~#
```

And all phpbrew command return ???root@....

I have to reboot PC and edit ~/.phpbrew/init to change from 5.3.29 to newer version such as 5.6.0.

How to make 5.3.xx installed properly?

**Comment by c9s** [comment]
I think this is related to phar file. does it work for composer.phar too?

**Comment by c9s** [comment]
I think you can run `reset` to clear the wrong characters.

**Comment by c9s** [comment]
try

```
~/.phpbrew/php/php-5.3.29/bin/php --version
~/.phpbrew/php/php-5.3.29/bin/php composer.phar 
```

**Comment by c9s** [comment]
looks like your php 5.3 was successfully built and installed. but it does support phar very well. I don't know why

**Comment by ve3** [comment]
Ok. I will leave it with php5.2 in the trash can then. :-D

All other versions are working fine. 5.4, 5.5, 5.6, 7.0

**Comment by c9s** [comment]
Yeah I just tried this 

```
~/.phpbrew/php/php-5.3.29/bin/php /Users/c9s/.phpbrew/bin/composer                               !12822
```
And I got

```
???+?
```

**Comment by c9s** [comment]
I guess the packed phar is different from which 5.3 can support.

**Comment by c9s** [comment]
Thanks for reporting this, I think we can keep it as backlog.

**Comment by jhdxr** [comment]
It's wierd. It works fine on my centOS 7 x64. (php 5.3.29 +default). maybe it's platform related problem. btw, #731 seems using php 5.6 which should be ok as @ve3 reported.

**Comment by c9s** [comment]
I can reproduce on my OS X, this issue is only for php 5.3,  php 5.4 works totally fine with composer and phpbrew.

**Comment by isapa1984** [comment]
After some research, I discovered it's the php directive **detect_unicode** the cause of the problem. Setting it to **Off** in _php.ini_ solved the issue. It's enabled by default. It must be some issue present in all versions of php until 5.3 concerning Phar and this setting.

**Comment by c9s** [comment]
@isapa1984 Thanks for the research you did.   does `detect_unicode` need to be turn off for all versions? or just for 5.3?

Thanks!

**Comment by isapa1984** [comment]
@c9s Good question. I could only test for 5.3.13.

**Comment by c9s** [comment]
OK, I think detect_unicode should be on for versions > 5.3.  I will consider about turning off this for 5.3

**Comment by c9s** [comment]
@isapa1984 could you try 1.22 release to see if this issue is solved? thanks! :)

**Comment by ve3** [comment]
Oops!
`phpbrew install 5.3.29`

> PHP Fatal error:  Allowed memory size of 33554432 bytes exhausted (tried to allocate 72 bytes) in phar:///usr/bin/phpbrew/src/PhpBrew/PatchKit/RegExpPatchRule.php on line 99

**Comment by c9s** [comment]
only 32MB memory available ?

**Comment by ve3** [comment]
Yes

**Comment by c9s** [comment]
I have no idea with this unless you adjusted memory_limit to higher value X)

**Comment by morozov** [comment]
Closing as a general PHAR/PHP issue. I cannot think of anything that could be done on the application side.
