### ISSUE TITLE
Ubuntu 16.04 - working fine in CLI, does not as an Apache2 module

### ISSUE THREAD

**Issue by sschuchlenz** [phpbrew/phpbrew#738]
I've set up a new Ubuntu 16.04 (which comes with PHP7) and need to install a 5.x version of PHP. Installation works fine, no errors when building and `libphp5.4.12.so` exists in `/usr/lib/apache2/modules` (folder and file are chmodded correctly).

The Apache2 module is active and `/etc/apache2/mods-enabled/php5.load` contains

`LoadModule php5_module        /usr/lib/apache2/modules/libphp5.4.12.so`

The problem is that PHP code is shown as code in the browser and it seems that PHP 5.4.12 is not executed on Apache2. I followed all steps in the cookbook and troubleshooting sections but to no avail.

### Command

`phpbrew --debug install 5.4.12 +apxs2 +mysql +debug`

### Platform

OS: Ubuntu 16.04

Running PHP: PHP 7.0.4-7ubuntu2 (cli) ( NTS )
Installing PHP: 5.4.12

**Comment by jhdxr** [comment]
do you have
`AddHandler application/x-httpd-php .php`
in your apache config file?

**Comment by sschuchlenz** [comment]
@jhdxr now this is really humiliating ;)

I was indeed missing the Handler for PHP in `mime.conf` - thanks for pointing that out.
