### ISSUE TITLE
PHP Not Installing

### ISSUE THREAD

**Issue by maksudr** [phpbrew/phpbrew#740]
Hey guys, I am having issues trying to install a PHP installation to my computer.
 But no matter what PHP version I used I cannot get it to install, I have also tried to use phpbrew install 5.4.0 +default --with-libedit but just get an error.
  
### Output

m1:.phpbrew m1$ phpbrew install 5.4.0 +default
===> phpbrew will now build 5.4.0
===> Loading and resolving variants...
Checking distribution checksum...
Checksum matched: 04bb6f9d71ea86ba05685439d50db074
===> Distribution file was successfully extracted, skipping...
Found existing Makefile, running make clean to ensure everything will be rebuilt.
You can append --no-clean option after the install command if you don't want to rebuild.
===> Running make clean: /usr/bin/make -C '/Users/m1/.phpbrew/build/php-5.4.0' --quiet 'clean'
===> Checking patches...
Checking patch for replace apache php module name with custom version name
Found existing build.log, renaming it to /Users/m1/.phpbrew/build/php-5.4.0/build.log.1463269787
===> Configuring 5.4.0...

Use tail command to see what's going on:
   $ tail -F /Users/m1/.phpbrew/build/php-5.4.0/build.log

Error: Configure failed:

Warning: join(): Invalid arguments passed in phar:///usr/local/bin/phpbrew/src/PhpBrew/Console.php on line 134
Configure options: 
The last 5 lines in the log file:
checking for readline support... yes

checking for tgetent in -lncurses... yes

checking for readline in -lreadline... yes

checking for rl_pending_input in -lreadline... no

configure: error: invalid readline installation detected. Try --with-libedit instead.

Please checkout the build log file for more details:
	 tail /Users/m1/.phpbrew/build/php-5.4.0/build.log

### Expected Result

PHP to install.

### Command
phpbrew install 5.4.0 +default

### Build Log

checking for getgrgid_r... yes
checking for working ttyname_r() implementation... no, posix_ttyname() will be thread-unsafe
checking for utsname.domainname... no
checking for PSPELL support... no
checking for libedit readline replacement... no
checking for readline support... yes
checking for tgetent in -lncurses... yes
checking for readline in -lreadline... yes
checking for rl_pending_input in -lreadline... no
configure: error: invalid readline installation detected. Try --with-libedit instead.

### Platform

OS: OSX Yosemite

Running PHP: Couldn't install.

Installing PHP: 5.4.0

**Comment by c9s** [comment]
Use this instead 

```
phpbrew install 5.4.0 +default -- --with-libedit
```

**Comment by maksudr** [comment]
Thank you for this. Also if I want to update the variants of a build version I have already installed how do I update the variants? Do I need to uninstall the version of PHP and reinstall it again? 

So say I ran this first: phpbrew -d install 5.5.30 +default -- --with-libedit 
I would then run: phpbrew -d install 5.5.30 +default+dbs+debug -- --with-libedit

**Comment by c9s** [comment]
Yes, it will clean up your previous build and start a new build.
