### ISSUE TITLE
.phpbrew/bashrc problem when using self-update

### ISSUE THREAD

**Issue by mirfilip** [phpbrew/phpbrew#742]
I was at `1.20.1`, installed via brew. I don't update with brew because it has a dependency on `php`, which I don't want to have installed via brew. When using `self-update` here's the output:
### Output

```
Updating phpbrew /usr/local/Cellar/phpbrew/1.20.1/libexec/phpbrew.phar from master...
######################################################################## 100.0%
Version updated.
Checking directory /Users/me/.phpbrew
Directory /Users/me/.phpbrew is already created.
Checking directory /Users/me/.phpbrew
Directory /Users/me/.phpbrew is already created.
Checking directory /Users/me/.phpbrew/register
Directory /Users/me/.phpbrew/register is already created.
Checking directory /Users/me/.phpbrew/build
Directory /Users/me/.phpbrew/build is already created.
Checking directory /Users/me/.phpbrew/php
Directory /Users/me/.phpbrew/php is already created.
Creating .metadata_never_index to prevent SpotLight indexing
Initialization successfully finished!
<=====================================================>
Phpbrew environment is initialized, required directories are created under

    /Users/me/.phpbrew

Paste the following line(s) to the end of your ~/.bashrc and start a
new shell, phpbrew should be up and fully functional from there:

    source /Users/me/.phpbrew/bashrc

To enable PHP version info in your shell prompt, please set PHPBREW_SET_PROMPT=1
in your `~/.bashrc` before you source `~/.phpbrew/bashrc`

    export PHPBREW_SET_PROMPT=1

To enable .phpbrewrc file searching, please export the following variable:

    export PHPBREW_RC_ENABLE=1


For further instructions, simply run `phpbrew` to see the help message.

Enjoy phpbrew at $HOME!!

<=====================================================>
phpbrew - 1.21.6
cliframework core: 2.5.4
```

I have `./phpbrew/bashrc` sourced in my `.bash_profile`. Now, when I source the `.bash_profile` (or open a new terminal window) I get:
`-bash: Invalid: command not found`

I traced it to be a problem of `.phpbrew/bashrc` since when I comment it out, sourcing stops reporting this to stderr. I looked at `bashrc` but I don't see anything suspicious. I don't know if update touches the file, nor I have an old `bashrc` to compare.

When running commands like `phpbrew switch`, I also get such output, that can be a clue.

I also tried removing `bashrc` and re-running the `self-update`, same problem.
Any ideas?
### Platform

OS: OS X 10.11.4 (15E65)

Running PHP: 
7.0.3

**Comment by mirfilip** [comment]
Ok, I tracked it a bit further. This is a culprit part of `.phpbrew/bashrc`:
```
function __phpbrew_load_user_config()
{
    # load user-defined config
    if [[ -f $PHPBREW_HOME/init ]]; then
        . $PHPBREW_HOME/init
        __phpbrew_set_path
    fi
}
```

In my case:
```
$ cat ~/.phpbrew/init
# DO NOT EDIT THIS FILE
Invalid argument 7.0
```

If I remove it, all is fine. This, however, can indicate there is some bug in the other place as `Invalid argument 7.0` doesn't look right :)

**Comment by jdrsqrd** [comment]
I am also having this issue. Any help or workaround available?

**Comment by jhdxr** [comment]
@c9s I didn't find the tag 1.20.1, and I fail to reproduce this problem with version 1.20.2. Can you reproduce this issue?

**Comment by jhdxr** [comment]
@jdrsqrd remove or rename ~/.phpbrew/init, then executing `phpbrew switch XXX` where XXX is one of the available php version(those you have installed)

**Comment by c9s** [comment]
I think the bug was in `__phpbrew_update_config` function

```
    command $BIN env $VERSION >> "$PHPBREW_HOME/init"
```

**Comment by jdrsqrd** [comment]
@jhdxr I did that and the bashrc seems to work fine but now I'm still seeing this issue:
`root@host:~# phpbrew list`
`* (system)`
`  php-5.3.29`
`root@host:~# phpbrew switch 5.3.29`
`root@host:~# phpbrew list`
`???root@host:~# source .bashrc `
`root@host:~# phpbrew list`
`???root@host:~# php -v`
`PHP 5.3.29 (cli) (built: May 30 2016 09:59:32) `
`Copyright (c) 1997-2014 The PHP Group`
`Zend Engine v2.3.0, Copyright (c) 1998-2014 Zend Technologies`

**Comment by c9s** [comment]
@jdrsqrd your issue seems related to #732, it's caused by the phar file, php 5.4 should be able to run the commands.

the phar file generated by 5.4 seems not backward compatible anymore. I guess there was something changed in the phar extension.

**Comment by c9s** [comment]
@jdrsqrd  see this comment https://github.com/phpbrew/phpbrew/issues/732#issuecomment-220046824

**Comment by c9s** [comment]
@jhdxr I think we need to add a check before writing output from env command to the `init` file.

**Comment by jdrsqrd** [comment]
@c9s that worked. thanks.

**Comment by jdrsqrd** [comment]
Also thanks for this dope plugin.

**Comment by jhdxr** [comment]
@c9s agreed, but I fail to come up with any solution to check the output valid or not.

**Comment by c9s** [comment]
the new cliframework logger write error message to stderr instead of stdout, so the error message won't be written to the init file.

**Comment by mirfilip** [comment]
@c9s When setting up a new machine, I just run into the same problem I originally reported.
Things done:
```
$ brew install phpbrew
...
$ phpbrew self-update
...
phpbrew - 1.22.6
cliframework core: 2.5.4
$ rm $PHPBREW_HOME/init
$ phpbrew list
  php-7.1.0
* php-7.0.14
$ phpbrew switch 7.1 // Note I used the wrong notation, as I'm constantly confused by php install 7.1 // working fine but phpbrew switch 7.1 not having that feature
$ phpbrew switch 7.1
-bash: Invalid: command not found
$ cat $PHPBREW_HOME/init
# DO NOT EDIT THIS FILE
Invalid argument 7.1
```

This still looks buggy, right?

**Comment by mirfilip** [comment]
@c9s could this be reopened, since it's not fixed?

**Comment by c9s** [comment]
just reopended this issue, but I don't have time to check the root cause

**Comment by guox191** [comment]
type the full name may work fine: 
`$ phpbrew switch php-7.1.0`

**Comment by Izzur** [comment]
I come to this problem too and it happen because i didn't properly switch off phpbrew
As a workaround I do

`phpbrew switch php-X.X.X && phpbrew switch-off`

Change X.X.X to your installed php version listed in `phpbrew list`

**Comment by mirfilip** [comment]
@guox191 @Izzur this is totally unrelated.

The main problem is `__phpbrew_update_config` fn writes some error msgs to `~/.phpbrew/init. This is a general problem, but [probably fixed](https://github.com/phpbrew/phpbrew/issues/742#issuecomment-222524094)

**Comment by peter279k** [comment]
The issue resolved probably and closed now.
