### ISSUE TITLE
how to add ioncube loader to phpbrew php?

### ISSUE THREAD

**Issue by alexswww** [phpbrew/phpbrew#762]
### Ioncube loader location

/usr/lib/php5/20100525+lfs/ioncube_loader_lin_5.4.so
### Configuration

/root/.phpbrew/php/php-5.6.22/etc/php.ini

```
...
zend_extension = /usr/lib/php5/20100525+lfs/ioncube_loader_lin_5.4.so
...
```
### Expected Result

Added ioncube, but when I checked <?php phpinfo() ?> - no "ioncube"

here is gif-illustration https://i.gyazo.com/eb3841f1c2a10c71557a76b6d2d3ecd4.gif
### Platform

OS: 

```
e.g. Linux vm2150. 3.2.0-4-686-pae #1 SMP Debian 3.2.65-1+deb7u2 i686 GNU/Linux
```

Running PHP: 5.6.22

Installing PHP: 5.6.22

**Comment by jhdxr** [comment]
did you restart your web server (apache) ?
btw, make sure you have edit the correct config file. (you can find the loaded php.ini in `phpinfo()`)

**Comment by zeyser** [comment]
Do you resolve your problem Alex? Have the same issue.

**Comment by peter279k** [comment]
The issue is outdated and closed now.
