### ISSUE TITLE
Filter_var Error 

### ISSUE THREAD

**Issue by orlandocoelho** [phpbrew/phpbrew#764]
I'm having getting a fatal error in my application stating that there is no module, put in php -m the module is it.

Error message:

Fatal error: Call to undefined function filter_var () in /vagrant/dev/aperti/system/core/Input.php on line 560

```
PHP -m

$ Php -m
[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
gives you
Sun
ereg
fileinfo
filter
hash
intl
json
libxml
mbstring
mcrypt
mhash
mysql
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_pgsql
pgsql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
standard
SYSVMSG
SYSVSEM
SYSVSHM
tokenizer
xml
xmlreader
xmlwriter
xsl
zip
zlib

[Zend Modules]

PHP -v

/> @ Vagrant vagrant-ubuntu-trusty-64 [php: 03/05/29-phpbrew]
$ Php -v
PHP 5.3.29 (cli) (built: 23 Jun 2016 13:31:57) (DEBUG)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2014 Zend Technologies
```

phpinfo on apache this with the same version perfectly.

Thank you in advance.

**Comment by c9s** [comment]
It looks like the "filter" extension was enabled and compiled into the php.

can you show me the path of php executable?

`which php`

http://php.net/manual/en/function.filter-var.php

**Comment by peter279k** [comment]
The issue is outdated and closed now.
