### ISSUE TITLE
Cannot find phplib5.3.28 in user/lib/apache2/modules

### ISSUE THREAD

**Issue by emfluenceindia** [phpbrew/phpbrew#767]
First of all I am sorry if the formatting is not perfect as I am not very sure how to format the problem I am having with installing `PHP-5.3.28`. I am installing `PHP 5.3.28 ` in Ubuntu 14.04 LTS. Before installing 5.3.28 I installed `PHP-5.3.29`. For both cases I used `phpbrew` command from CLI.

### Output
Source directory: /home/subrara/.phpbrew/build/php-5.3.28
Congratulations! Now you have PHP with 5.3.28 as php-5.3.28

* We found that you enabled 'mysql' variant, you might need to setup your
  'pdo_mysql.default_socket' or 'mysqli.default_socket' in your php.ini file.

* To configure your installed PHP further, you can edit the config file at
    /home/subrara/.phpbrew/php/php-5.3.28/etc/php.ini

To use the newly built PHP, try the line(s) below:

    $ phpbrew use php-5.3.28

Or you can use switch command to switch your default php to php-5.3.28:

    $ phpbrew switch php-5.3.28

Enjoy!

```
...
```

### Expected Result
I was looking for a file called `phplib5.3.28.so` under my `/usr/lib/modules/` folder but its not there! However `phplib5.3.29.so` is already residing there, which must have been added when I first installed `PHP-5.3.29`. Why the file was not created with 5.3.28 installation? By the way. there is another `.so` file called `phplib5.so` but I believe this is not the one I am looking for as it looks more generic for `php5` and not sub-verison specific.

### Reason I am looking for phplib5.3.28.so file under /usr/lib/moduels folder
I created a page with `phpinfo()` which says the PHP version is 5.3.29 i.e. the one I installed before.
I used commands `phpbrew use php-5.3.28` and `phpbrew switch php-5.3.28`. When I run `php -v` CLI gives me the desired version info, i.e. 5.3.28!

Inside `/etc/apache2/mods-enabled` there is a file called `php5.load` which contains the following line:
`LoadModule php5_module        /usr/lib/apache2/modules/libphp5.3.29.so`. So I thought if I have the `.so` file for `php-5.3.28` then I probably updating `php5.load` with that `.so` file might do the trick! But unfortunately the file `phplib5.3.28.so` does not at all exist!! **And because it is there I cannot tell `apache` to use version 5.3.28.**

### Why installing 5.3.28 when I already have 5.3.29
The problem is when I installed `php 5.3.29` I used `sudo phpbrew install 5.3.29 +default`. I am very new to Linux and PHP so may be `sudo` caused some issues. Moreover using only `+default` did not install variant `mysql` (or may be not compiled!). Because I can connect to the database server, see available databases, use a database etc. I then tried to install `mysql` as an extension but it failed. So I decided to installed a separate version i.e. 5.3.28.

### Command
```
    phpbrew --debug install php-5.3.28 +curl +mysql +default
```
### Platform

    OS: Ubuntu 14.04LTS

Running PHP: 5.3.29 (as per phpinfo())
Installing PHP: 5.3.28

PHP version (as per `phpinfo()`)
![screenshot from 2016-06-30 16 40 15](https://cloud.githubusercontent.com/assets/11072678/16486294/6eede57e-3ee1-11e6-9783-4c5def8015b0.png)

PHP version (as per CLI)
![screenshot from 2016-06-30 16 41 19](https://cloud.githubusercontent.com/assets/11072678/16486320/8cc903da-3ee1-11e6-8388-348168722374.png)

I restarted apache2 several times: `sudo service apache2 restart` with no effect. `phpinfo()` still shows 5.3.29.

I am not sure whether this would be treated as an issue or a question. But whatever it is, I request you to please suggest me a work around... I am completely screwed up and stuck!

**Comment by jhdxr** [comment]
you need to add `+apxs2` to enable apache2 support

**Comment by subtata-emfluence** [comment]
Yes, this works :) Thank you!
