### ISSUE TITLE
Cannot install PHP 5.5.0 (bad URL)

### ISSUE THREAD

**Issue by loopj** [phpbrew/phpbrew#769]
### Output

```
Downloading http://www.php.net/get/php-5.5.0.tar.bz2/from/this/mirror via curl extension
CurlKit\CurlException: (22) The requested URL returned error: 404 Not Found at [http://www.php.net/get/php-5.5.0.tar.bz2/from/this/mirror:The requested URL returned error: 404 Not Found]
```

### Command

Paste your phpbrew install command here (be sure to install with `--debug` flag, e.g. `phpbrew --debug install`)

    phpbrew install php-5.5.0

**Comment by jhdxr** [comment]
according to http://php.net/releases/ ,it seems most of the vesions reached their eol have been move to museum.php.net and no longer be available on php.net

**Comment by jhdxr** [comment]
@c9s I've fix this issue and ci tests, could you review these commits and release a version ASAP? because this problem leads to most of the old version cannot be instlled.

**Comment by c9s** [comment]
sure thing

**Comment by c9s** [comment]
1.22.5 released in 56300713fe9f99084a52987d624579d92c2b1844

**Comment by jhdxr** [comment]
It's weird, I cannot find that commit in my sourcetree, and `self-update`  still download 1.22.4

**Comment by c9s** [comment]
I got 1.22.5

**Comment by jhdxr** [comment]
yeah, it works now
