### ISSUE TITLE
Can't install GD library

### ISSUE THREAD

**Issue by owwo** [phpbrew/phpbrew#774]
### Expected Result

```
Error: PHPBREW_PHP environment variable is not defined.
  This extension command requires you specify a PHP version from your build list.
  And it looks like you haven't switched to a version from the builds that were built with PHPBrew.
Suggestion: Please install at least one PHP with your prefered version and switch to it.
```

### Command

    phpbrew ext enable gd

### Platform

OS:
    Linux Mint 17.3

Running PHP: 
    php-5.3.29

Installing PHP:
    php-5.3.29

**Comment by c9s** [comment]
As the message said, you have to install at least one php with phpbrew and remember to source the environment file (~/.phpbrew/bashrc) or run `eval $(phpbrew env)`

**Comment by owwo** [comment]
thanks
