### ISSUE TITLE
Implement the GIT downloader

### ISSUE THREAD

**Issue by fruitl00p** [phpbrew/phpbrew#78]
Since PHP development has shifted from SVN to GIT a new downloader must be thought up. 
this might also be the right moment to remove the getSvnVersions to 'getVersions' (since SVN has nothing to do with it anymore, they're just going to be branches in the GIT repo)

One might go as far and redefine PhpSource:

- getReleaseManagers / versionCompare / getVersionInfo remain as is
- getReleases($stableOnly=false) (
via listing of branches in the GIT repo and if $stableOnly == true, filter out everything not on  the http://www.php.net/distributions/ page)

The actual downloader would use the getReleases information and checkout specific versions as requested. The snapshotreleases would be obsolete by 'getReleaseByCommit` (which again the actual downloader could also use internally)

By moving away from anything but GIT and the 'git way' it would simplify alot of the innerworkings of what it has to do to get the code for the requested 'release' (which is actually just a commit state on the GIT repo)

**Comment by c9s** [comment]
I am closing this to design a whole new Git installer for PHP.
