### ISSUE TITLE
Please reinstall BZip2 distribution

### ISSUE THREAD

**Issue by crysaro** [phpbrew/phpbrew#786]
I have bzip2 installed in my Ubuntu already:
 .. Bzip2 is already the newest version (1.0.6-8).

I also have added the path where I found my bzip.
PATH=$PATH:/bin:/sbin

### Output

```
...  BZip2 in default path.. not found
Configure error: Please reinstall the BZip2 distribution.
```

### Expected result
```
...BZip2 in default path.. found

```

### Command

phpbrew install 5.3.3 +default +mysql

### Build Log

 checking whether to enable bc style precision math functions... yes
checking for BZip2 support... yes
checking for BZip2 in default path... not found
configure: error: Please reinstall the BZip2 distribution

### Platform

OS:

  Ubuntu LTS 16.04.1

Running PHP: 7.0.8

Installing PHP: 5.3.3

**Comment by jhdxr** [comment]
you need the header files to compile php, not the binaries.
try `sudo apt-get libbz2-dev`

**Comment by crysaro** [comment]
Thanks! That fixed the issue bu I got more errors after that one gt fixed:

Error: configure: error: mcrypt.h not found. Please reinstall libmcrypt
Fix   : apt install libmcrypt-dev

Error: configure: error: xslt-config not found. Please reinstall the libxslt >= 1.1.0 distribution
Fix   : apt install libxslt-dev

After those I got stuck with another error which I described here: https://github.com/phpbrew/phpbrew/issues/787

**Comment by jhbsk** [comment]
@jhdxr Thanks so much for this! I believe that should be `sudo apt-get install libbz2-dev`

**Comment by redhat-raptor** [comment]
On fedora 25 I had to: `sudo dnf install bzip2-devel`

**Comment by PhilippWitzmann** [comment]
centos: yum install bzip2-devel

**Comment by austingray** [comment]
macOS: `xcode-select --install`

**Comment by phoenixg** [comment]
@austingray 已经安装了 xcode 命令行，还是报这样的错

**Comment by dmitrykramer** [comment]
> @austingray 已经安装了 xcode 命令行，还是报这样的错

I have installed the xcode command line and still report this error

**Comment by alex-moreno** [comment]
Mac instructions: 

```brew install BZip2```

**Comment by rawleyfowler** [comment]
openSUSE: `sudo zypper install libbz2-devel`
