### ISSUE TITLE
Error: Make failed: .. Makefile: 630: recipe for target 'ext/dom/node.lo' failed

### ISSUE THREAD

**Issue by crysaro** [phpbrew/phpbrew#787]
### Output
Checking patch for openssl dso linking patch
===> Building...
make >> /root/.phpbrew/build/php-5.3.3/build.log 2>&1
Error: Make failed:
The last 5 lines in the log file:
/root/.phpbrew/build/php-5.3.3/ext/dom/node.c:1903:21: error: dereferencing pointer to incomplete type ‘xmlBuf {aka struct _xmlBuf}’

    ret = buf->buffer->use;

                     ^

Makefile:630: recipe for target 'ext/dom/node.lo' failed

make: *** [ext/dom/node.lo] Error 1

Please checkout the build log file for more details:
  tail /root/.phpbrew/build/php-5.3.3/build.log
...
```


### Expected Result

```
...
```

### Command


   phpbrew --debug install 5.3.3 +default +mysql

[phpbrew-build-copy.log.txt](https://github.com/phpbrew/phpbrew/files/463144/phpbrew-build-copy.log.txt)



### Build Log

    gist here

### Platform

OS:

    e.g. OS X 10.7, Ubuntu 14.04

Running PHP:  7.0.8

Installing PHP: 5.3.3

**Comment by jhdxr** [comment]
https://github.com/phpbrew/phpbrew/issues/492#issuecomment-97069703

**Comment by crysaro** [comment]
Thanks again! It worked again!

But I got a new error which I posted here: https://github.com/phpbrew/phpbrew/issues/788

I'm looking at these now :

https://github.com/phpbrew/phpbrew/issues/26
https://github.com/phpbrew/phpbrew/issues/330
