### ISSUE TITLE
Process stuck when tried to install phpcs

### ISSUE THREAD

**Issue by williamn** [phpbrew/phpbrew#789]
### Output

```
Downloading https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar via curl extension
[================================================================= ] 495.95/507.87KB 98%
```
### Expected Result

```
Downloading https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar via curl extension
[================================================================= ] 507.87/507.87KB 100%
Changing permissions to 0755
Downloaded at /home/william/.phpbrew/bin/phpcs
```
### Command

```
phpbrew --debug install php-7.0.10 +default +fpm +pgsql
```
### Build Log

https://gist.github.com/williamn/027f15fd25a80046750822a902dea473
### Platform

Elementary OS 0.4 Loki (Built on "Ubuntu 16.04 LTS")
## Running PHP:

PHP 7.0.10 (cli) (built: Sep 13 2016 17:04:40) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
## Installing PHP:
- php-7.0.10  
- php-5.4.45  
- php-5.3.29

**Comment by morozov** [comment]
@williamn could you try reproducing it again? If it's reproduced, could you try using `curl` or `wget` in CLI and see if it's not a network problem?

**Comment by williamn** [comment]
@morozov I can confirm it is now working as expected in phpbrew 1.22.8
