### ISSUE TITLE
support needed, trying to use jenkins CI with phpbrew

### ISSUE THREAD

**Issue by Gamesh** [phpbrew/phpbrew#790]
I'm trying to use phpbrew with [jenkins](https://jenkins.io/) to run unit tests with different PHP versions and so on. But i can't get it to work. I Did a system-wide install of phpbrew following this guide https://github.com/phpbrew/phpbrew/wiki/Installing-PHPBrew-into-System-wide-Environment

i tried to add the `source /opt/phpbrew/bashrc` to /etc/profile, to /etc/profile.d/jenkins.sh but that does not seem to work, jenkins user has no .bashrc in it's home directory and it's located in /var/lib/jenkins. if i switch to jenkins user `sudo su jenkins` it seems to run on BASH.
`echo $SHELL` and `echo $BASH` both output _/bin/bash_

Jenkins executes a shell script like this:
`/bin/bash /tmp/hudson5038516934025552595.sh`
in this script i try to use `phpbrew use php-7.0.11`, but it prints out:
`You should not see this, if you see this, it means you didn't load the ~/.phpbrew/bashrc script, please check if bashrc is sourced in your shell.`

if i add change it to:

``` bash
source /opt/phpbrew/bashrc
phpbrew use php-7.0.11
```

it works, but i can't find a way to make it permanent.
Jenkins is a Java process that runs as daemon under Debian Linux.

any help would be appreciated, as Jenkins is one of most popular CI tools out there.

**Comment by felixflu** [comment]
We had the same problem. The reason is that the shell is terminated after that build step and your changes are lost. What i did, was to use the ENVInject plugin for jenkins to prepend the desired phpversion in the path. 
`PATH=/var/lib/jenkins/.phpbrew/php/php-5.6.20/bin:$PATH`
But i think this is a very hackish way, may be there are better solutions?
Also be aware of side effects. But at the moment it is working.

**Comment by thomas-lange-smf** [comment]
Hi,
I am currently running into this issue. 
What prevented you from starting phpbrew via a shell script? Did you find a more viable option?
Like:

File: phpswitch

```
#!/usr/bin/env bash
source /opt/phpbrew/bashrc
phpbrew $@

```

**Comment by thomas-lange-smf** [comment]
I ended up with this, because we did not want to use phpbrew globaly:

File: `/usr/share/phpswitch`
```
#!/usr/bin/env bash
if [ -e ~/.phpbrew/bashrc ]; then
        source ~/.phpbrew/bashrc
        phpbrew $@
else
        echo "PhpBrew not installed or initialised for user"
        echo "Please do so following:"
        echo "https://github.com/phpbrew/phpbrew"
fi

```

**Comment by peter279k** [comment]
The issue is outdated and closed now.
