### ISSUE TITLE
Cannot install PHP with OpenSSL on Ubuntu

### ISSUE THREAD

**Issue by morozov** [phpbrew/phpbrew#793]
The excerpt from the installation procedure is the following:
```
↪  phpbrew --debug install 5.6.26 +neutral+openssl
...
./configure '--cache-file='\''/home/morozov/.phpbrew/cache/config.cache'\''' '--prefix=/home/morozov/.phpbrew/php/php-5.6.26' '--with-config-file-path=/home/morozov/.phpbrew/php/php-5.6.26/etc' '--with-config-file-scan-dir=/home/morozov/.phpbrew/php/php-5.6.26/var/db' '--with-openssl=/usr' '--enable-dom' '--enable-libxml' '--enable-simplexml' '--enable-xml' '--enable-xmlreader' '--enable-xmlwriter' '--with-xsl' '--with-libxml-dir=/usr' '--enable-opcache' '--with-pear=/home/morozov/.phpbrew/php/php-5.6.26/lib/php' >> /home/morozov/.phpbrew/build/php-5.6.26/build.log 2>&1
...
configure: error: Cannot find OpenSSL's libraries
```

The most important part is `./configure --with-openssl=/usr`. If I run `./configure --with-openssl` without the prefix, the configuration process finishes successfully.

What happens internally:

1. Variant builder [detects](https://github.com/phpbrew/phpbrew/blob/1.22.5/src/PhpBrew/VariantBuilder.php#L550-L550) the `/usr` prefix by looking up `openssl/opensslv.h` and passes it to the command line.
2. The configure script [looks for](https://github.com/php/php-src/blob/php-5.6.26/acinclude.m4#L2360-L2368) `include/openssl/evp.h` and `libssl.so` and fails to find the latter.
3. The reason is that on Ubuntu `libssl.so` is located at `/usr/lib/x86_64-linux-gnu/libssl.so`, not at `/usr/lib/libssl.so` where it's looked for:
    ```
    ↪  apt-cache policy libssl-dev
    libssl-dev:
      Installed: 1.0.2g-1ubuntu4.5
      Candidate: 1.0.2g-1ubuntu4.5
      Version table:
     *** 1.0.2g-1ubuntu4.5 500
            500 http://us.archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages
            500 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages
            100 /var/lib/dpkg/status
         1.0.2g-1ubuntu4 500
            500 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 Packages

    ↪  dpkg-query -L libssl-dev | grep 'evp.h\|libssl.so'
    /usr/include/openssl/evp.h
    /usr/lib/x86_64-linux-gnu/libssl.so
    ```
4. If the `/usr` prefix is not specified, then the `pkg-config` [finds](https://github.com/php/php-src/blob/php-5.6.26/acinclude.m4#L2335-L2343) the library files, and the lookup described on step 2 does not happen.
5. It might work in case if `VariantBuilder::build()` could properly detect the libdir as `--with-libdir=lib/x86_64-linux-gnu`, but it can't because it searches for `/usr/x86_64-linux-gnu` and fails to find it.

The easiest solution would be to make *#*5 work properly, but a more fundamental question is, why duplicate the logic of the PHP build script in phpbrew? A proper solution could be to detect if `pkg-config` is available and only search for the library in non-standard directories like `/usr/local/opt` in this case.

Sorry for such a long writeup. What do maintainers think on that?

**Comment by jhdxr** [comment]
thanks for your analysis.

phpbrew tries to set / check every possible option, because those options may change on different php versions, and different distributions while phpbrew wants to offer a standard and simple way to solve this issue. It's why phpbrew appending so many options.

**Comment by ashnazg** [comment]
For googlers:  I had to use `+default -- --with-openssl`... `+openssl` didn't help... `--with-openssl=dir` didn't help.
