### ISSUE TITLE
Phpbrew switch not working with short versions

### ISSUE THREAD

**Issue by evilebottnawi** [phpbrew/phpbrew#796]
I can use:
```shell
phpbrew install -j $(nproc) 5.6;
```
And i get latest `5.6` version (now `5.6.26`).
But if i use 
```shell
phpbrew switch 5.6
```
I got error about not installed version. Can we use short version for `switch` and `use` command. Get latest  installed version?

**Comment by redshark1802** [comment]
Hi,

you can use  ```phpbrew install -j $(nproc) 5.6 as 5.6``` when installing.

**Comment by evilebottnawi** [comment]
@redshark1802 thanks

**Comment by jhdxr** [comment]
Users should be aware of the version they currently use clearly. 
and if you want to use alias, @redshark1802 already showed you the way.
