### ISSUE TITLE
Cannot install curl extension

### ISSUE THREAD

**Issue by hisnameishb** [phpbrew/phpbrew#797]
### Output
# WARNING: curl extension might be required for fetching data.
===> Installing curl extension...
Extension path /home/myname/.phpbrew/build/php-5.6.25/ext/curl
Log stored at: /home//.phpbrew/build/php-5.6.25/ext/curl/build.log
Changing directory to /home/myname/.phpbrew/build/php-5.6.25/ext/curl
===> Phpize...
Running Command:phpize > /home/myname/.phpbrew/build/php-5.6.25/ext/curl/build.log 2>&1
===> Configuring...
Appending argument: --with-php-config=/home/myname/.phpbrew/php/php-5.6.25/bin/php-config
Running Command:./configure --with-php-config=/home/myname/.phpbrew/php/php-5.6.25/bin/php-config
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for a sed that does not truncate output... /bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... i686-pc-linux-gnu
checking host system type... i686-pc-linux-gnu
checking target system type... i686-pc-linux-gnu
checking for PHP prefix... /home/myname/.phpbrew/php/php-5.6.25
checking for PHP includes... -I/home/myname/.phpbrew/php/php-5.6.25/include/php -I/home/myname/.phpbrew/php/php-5.6.25/include/php/main -I/home/myname/.phpbrew/php/php-5.6.25/include/php/TSRM -I/home/myname/.phpbrew/php/php-5.6.25/include/php/Zend -I/home/myname/.phpbrew/php/php-5.6.25/include/php/ext -I/home/myname/.phpbrew/php/php-5.6.25/include/php/ext/date/lib
checking for PHP extension directory... /home/myname/.phpbrew/php/php-5.6.25/lib/php/extensions/no-debug-non-zts-20131226
checking for PHP installed headers prefix... /home/myname/.phpbrew/php/php-5.6.25/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... re2c
checking for re2c version... 0.16 (ok)
checking for gawk... gawk
checking for cURL support... yes, shared
checking for cURL in default path... not found
configure: error: Please reinstall the libcurl distribution -
    easy.h should be in <curl-dir>/include/curl/
Error: Command failed: ./configure --with-php-config=/home/myname/.phpbrew/php/php-5.6.25/bin/php-config returns: checking for cURL in default path... not found
myname@box:~$ curl
curl: try 'curl --help' or 'curl --manual' for more information

### Expected Result
curl-extension to be installed.
Th local curl command is installed an found when executed in shell:
$ curl
curl: try 'curl --help' or 'curl --manual' for more information

### Command
phpbrew --debug ext install curl

### Build Log
deleted

### Platform
OS: Ubuntu 16.04
Running PHP: phpbrew installed 5.6.25
Installing PHP: none from the distro

**Comment by morozov** [comment]
@hisnameishb, on Ubuntu 16.04 you'll have to `apt install libcurl4-openssl-dev` (or maybe `apt install libcurl4-gnutls-dev`) in order to install libcurl which ext-curl depends on.

**Comment by hisnameishb** [comment]
@morozov
Thank you, your solution works perfect.
