### ISSUE TITLE
phpbrew each doesn't allow the usage of Composer scripts

### ISSUE THREAD

**Issue by raphaelstolt** [phpbrew/phpbrew#800]
When trying to run a Composer script via `phpbrew each 'composer test'` from a local Git repository I get the following output.

```
Run composer test for php-[7.0.4, 5.6.19, 5.5.33, 5.4.45]. Proceed? [Yes/no]> Yes
Running `composer test` for php-7.0.4:
Did you mean 'compile'? [Y/n] n
Command composer not found. available commands are: help, zsh, bash, meta, compile, archive, github:build-topics, app, init, known, install, list, use, switch, each, config, info, env, extension, variants, path, cd, download, clean, update, ctags, fpm, list-ini, self-update, remove, purge, off, switch-off

Please try the command below to see the details:

    /usr/local/bin/phpbrew help

```
### Expected Result

The Composer test script ran against the installed versions. Motivation behind this is to run tests or specs against all PHP versions managed by PHPBrew, kind of a local Travis CI.

```
Run composer test for php-[7.0.4, 5.6.19, 5.5.33, 5.4.45]. Proceed? [Yes/no]> Yes
Running `composer test` for php-7.0.4:
Output of composer test
```
### Platform

OS X El Capitain
phpbrew - 1.22.5
cliframework core: 2.5.4

**Comment by morozov** [comment]
@raphaelstolt it looks like according to [the original idea](https://github.com/phpbrew/phpbrew/issues/66#issuecomment-51802673) and the [implementation](https://github.com/phpbrew/phpbrew/blob/1.22.5/src/PhpBrew/Command/EachCommand.php#L58), `phpbrew each` runs a phpbrew command, not a shell one (I assume there's no phpbrew built-in `composer` command).

As a [workaround](https://github.com/phpbrew/phpbrew/issues/559#issuecomment-129909286), one may use something like:
```bash
phpbrew list | sed "s/[ \*]//g" | while read version ; do
    phpbrew use $version && php --version
done
```

**Comment by mirfilip** [comment]
That would be an awesome feature. I use it constantly for:
1. Comparing how my project runs on different version the project supports. Think [3v4l](https://3v4l.org/) but local.
2. Checking the health of my php installations. It so happens that once in a while I do `brew cleanup` that removes some old version of dependencies that some older php versions need. E.g. everytime I install new php, it is compiled against currently linked version of `icu4c`. As I update them, there are many versions of `icu4c` which `brew cleanup` garbage collects. Granted, I shouldn't remove dependencies so blindly or just recompile every php version everytime the dependency changes (to ensure it's compiled against the newest version) - but it's a pain.
3. Running the project against many different flavours of the same php version. I have many builds of the same version, just with different settings. Being able to `phpbrew each "foo.php"` would be so convenient.

I'm currently using sth like @morozov suggests:
```shell
phpbrew list --dir | grep "Prefix" | awk '{print $2}' | while read basePath; do "$basePath/bin/php" -v ; done
```

**Comment by morozov** [comment]
To me it would make sense to change the behavior of the `each` command (which is a BC breaking change).

Instead of executing a PhpBrew command (which doesn't always work (e.g. `phpbrew each fpm restart` doesn't)), it could execute a shell command. It would simplify running non-phpbrew commangs (e.g. `phpunit`) against all installed PHP builds. The PhpBrew commands, in turn, could be executed as `phpbrew each phpbrew do something`.

Looks like if `each` is moved out of PHP to the shell level, it can be implemented about the same easily as the examples above and will also fix the issue with `phpbrew each fpm`.

@jhdxr, @c9s what do you think?

**Comment by c9s** [comment]
Hi @morozov  Sorry for the late reply, I am fine with the proposal. 👍
