### ISSUE TITLE
Add a clone-from option to install command

### ISSUE THREAD

**Issue by raphaelstolt** [phpbrew/phpbrew#801]
Having a `clone-from` option for the install command would allow to easily install new PHP versions from an existing version with the same configuration as the clone source.

Assuming we have `php-5.6.27` installed and want to have `php-7.0.12` with the same configuration, a `phpbrew install 7.0.12 --clone-from 5.6.27` would ease installation of new versions a lot.

**Comment by morozov** [comment]
@raphaelstolt are you looking for something like `install like`?

https://github.com/phpbrew/phpbrew/blob/522f600ab8152bb59b5fba4b3c7e31b10dab99d5/src/PhpBrew/Command/InstallCommand.php#L161

**Comment by raphaelstolt** [comment]
Yes seems like an implementation of the desired feature; though I haven't tried it really yet. 

Btw a display of the available options and arguments when issuing `phpbrew <command> --help` would be really userfriendly.

**Comment by morozov** [comment]
@raphaelstolt you can try `phpbrew help <command>`.

**Comment by peter279k** [comment]
The issue is outdated and closed now.
