### ISSUE TITLE
Solution install ldap on ubuntu 16.04 x64

### ISSUE THREAD

**Issue by afranioce** [phpbrew/phpbrew#802]
### Output

```
configure: error: Cannot find ldap.h
```
### Expected Result

```
===> Enabling extension ldap
[*] ldap extension is enabled.
Done.
```
### Command

```
sudo apt-get install libldap2-dev
phpbrew --debug ext install ldap -- --with-libdir=lib/x86_64-linux-gnu
```
### Platform

OS:

```
Ubuntu 16.04
```

**Comment by jhdxr** [comment]
could you upload your whole log, and try `locate ldap.h` to see where the header file is.

**Comment by peter279k** [comment]
I try to reproduce the issue and run same commands in the `Ubuntu 18.04`. They're as follows:

- Running the `sudo apt-get install libldap2-dev` command to install the development library for LDAP.
- Running the `phpbrew --debug ext install ldap -- --with-libdir=lib/x86_64-linux-gnu` to install the extension.
And related command outputs are as follows:

```sh
......
===> Installing...
Installing shared extensions:     /root/.phpbrew/php/php-5.6.40/lib/php/extensions/no-debug-non-zts-20131226/
Installed extension library: /usr/lib/php/20170718/ldap.so
===> Extension is installed.
===> Creating config file /root/.phpbrew/php/php-5.6.40/var/db/ldap.ini.disabled
/root/.phpbrew/php/php-5.6.40/var/db/ldap.ini.disabled is created.
===> Enabling extension ldap
[*] ldap extension is enabled.
Done.
root@ubuntu-s-4vcpu-8gb-amd-sgp1-01:~#
```
