### ISSUE TITLE
[Share] Can't switch PHP version from 5 to 7 with Apache2 on Ubuntu

### ISSUE THREAD

**Issue by dotku** [phpbrew/phpbrew#808]
## Action
- Install PHP7 by phpbrew succesfully (It might required at least 1GB Memory during the installation compiler process; fail installation on Digital Ocean 512MB enviroment)
- Restart Apache 2.0

### Output
The Apache would still using PHP5

### Expected Result

It should display PHP7

### Platform

OS: Ubuntu 14.04

Running PHP: 5.0
Installing PHP: 7.0-dev

### Solution

```
sudo apt-get install libapache2-mod-php7.0
sudo a2dismod php5.0 ; sudo a2enmod php7.0 ; sudo service apache2 restart
```

**Comment by peter279k** [comment]
It's the solution and it's not the issue.
