### ISSUE TITLE
After upgrade to 1.22.6, I got error messages when source .phpbrew/bashrc

### ISSUE THREAD

**Issue by markwu** [phpbrew/phpbrew#809]
### Output

```
Last login: Thu Nov 10 01:29:47 on ttys001
: command not found
: command not found
: command not found
'bash: /Users/mark/.phpbrew/bashrc: line 17: syntax error near unexpected token `
'bash: /Users/mark/.phpbrew/bashrc: line 17: `function __phpbrew_set_path()
```

### Expected Result

```
No errors
```

### Platform

OS:

    OSX 10.11.6

Running PHP: 

    PHP-5.6.27

**Comment by markwu** [comment]
I try to re-generate `bashrc` from 1.22.5 and replace the new one, everything works again.

**Comment by jhdxr** [comment]
thanks for your report. It seems for some reason, which I'm still looking for, the line separator for `bashrc` changed from `lf` to `crlf`, and was packed into `phpbrew.phar`, then released.

I have fixed this problem and update the phar, `phpbrew self-update` should receive the correct phar.

sorry for the inconvenience。

**Comment by markwu** [comment]
Thanks, I confirmed this issue fixed.
