### ISSUE TITLE
Can't install xdebug on Ubuntu 16.04 in Php 5.3.29

### ISSUE THREAD

**Issue by susanaml** [phpbrew/phpbrew#812]
### Output

Downloading https://pecl.php.net/rest/r/xdebug/2.2.7.xml via curl extension
[==================================================================] 1.64/1.64KB 100%
Violación de segmento (`core' generado)

I try install extension with --debug but not show anything else

### Expected Result

```
...
```

### Command

phpbrew ext install xdebug 2.2.7

### Build Log

Log installation php 5.3.29
Installing PHP SAPI module:       cgi
Installing PHP CGI binary: /home/susana/.phpbrew/php/php-5.3.29/bin/
Installing PHP CLI binary:        /home/susana/.phpbrew/php/php-5.3.29/bin/
Installing PHP CLI man page:      /home/susana/.phpbrew/php/php-5.3.29/man/man1/
Installing shared extensions:     /home/susana/.phpbrew/php/php-5.3.29/lib/php/extensions/no-debug-zts-20090626/
Installing build environment:     /home/susana/.phpbrew/php/php-5.3.29/lib/php/build/
Installing header files:          /home/susana/.phpbrew/php/php-5.3.29/include/php/
Installing helper programs:       /home/susana/.phpbrew/php/php-5.3.29/bin/
  program: phpize
  program: php-config
Installing man pages:             /home/susana/.phpbrew/php/php-5.3.29/man/man1/
  page: phpize.1
  page: php-config.1
Installing PEAR environment:      /home/susana/.phpbrew/php/php-5.3.29/lib/php/
[PEAR] Archive_Tar    - already installed: 1.3.12
[PEAR] Console_Getopt - already installed: 1.3.1
[PEAR] Structures_Graph- already installed: 1.0.4
[PEAR] XML_Util       - already installed: 1.2.3
[PEAR] PEAR           - already installed: 1.9.5

### Platform

OS: Ubuntu 16.04 

Running PHP: 

Installing PHP:

php -m (5.3.29)

[PHP Modules]
bcmath
bz2
calendar
Core
ctype
curl
date
dom
ereg
fileinfo
filter
hash
iconv
intl
json
libxml
mbstring
mcrypt
mhash
mysql
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
pdo_pgsql
pdo_sqlite
pgsql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
sockets
SPL
sqlite3
standard
sysvmsg
sysvsem
sysvshm
tidy
tokenizer
xml
xmlreader
xmlwriter
xsl
zip
zlib

[Zend Modules] 

Php local machine

php -v
PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.8-0ubuntu0.16.04.3, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.5.0rc1, Copyright (c) 2002-2016, by Derick Rethans

**Comment by morozov** [comment]
Segmentation fault usually points to the bug in PHP or extensions. PHP 5.3 is EOL, so there's probably nothing can be done.
