### ISSUE TITLE
Proxy support for pecl extensions

### ISSUE THREAD

**Issue by larsnystrom** [phpbrew/phpbrew#815]
Pecl extensions can't be installed behind a proxy. I've already filed a ticket here: https://github.com/phpbrew/PEARX/issues/7

There seems to be some support in PEARX for using downloaders the same way phpbrew use downloaders (the `PhpBrew\Downloader` classes), but the `PhpBrew\Extension\Provider\PeclProvider` doesn't pass the downloader on to the PEARX class. (https://github.com/phpbrew/phpbrew/blob/master/src/PhpBrew/Extension/Provider/PeclProvider.php#L37)

### Output

```
$ phpbrew ext install mailparse
PHP Warning:  file_get_contents(http://pecl.php.net/channel.xml): failed to open stream: No route to host in phar:///<path>/phpbrew/vendor/corneltek/pearx/src/PEARX/Core.php on line 35
...
```

### Expected Result

The pecl extension should be downloaded through a proxy.

### Platform

OS:

    Ubuntu 16.04

Running PHP: 

    PHP 7.0.6

**Comment by c9s** [comment]
The downloader proxy option seems already added last year.

**Comment by jhdxr** [comment]
@c9s looks like PEARX doesn't support proxy yet (https://github.com/phpbrew/PEARX/blob/master/src/PEARX/Core.php#L35), which will lead a problem [here](https://github.com/phpbrew/phpbrew/blob/master/src/PhpBrew/Extension/Provider/PeclProvider.php#L37).

Maybe we should share `Downloader` with PEARX as well.

**Comment by peter279k** [comment]
The issue is resolved and closed now.
