### ISSUE TITLE
Is it possible to add a variant after installing php?

### ISSUE THREAD

**Issue by felipefrancisco** [phpbrew/phpbrew#816]
Is it possible to add a variant after installing php or do I have to recompile/rebuild it if I forgot to add a variant?

**Comment by jhdxr** [comment]
it depends, if you just need to add an extension, you can use `phpbrew ext install ` command, see https://github.com/phpbrew/phpbrew/wiki/Extension-Installer.
if you forgot to add any variant relating to php core, for example, `+cli`, I think the only choice is to rebuild the whole php.

**Comment by c9s** [comment]
yes it's possible.

You can do `phpbrew --debug install 5.6 as 5.6-dev like 5.6-dev +fpm +debug`

Where `5.6-dev` is your existing build name. And the first `5.6` will be expanded to 5.6.31 or something.

**Comment by c9s** [comment]
Hi @felipefrancisco 

yes it's possible.

You can do `phpbrew --debug install 5.6 as 5.6-dev like 5.6-dev +fpm +debug`

Where `5.6-dev` is your existing build name. And the first `5.6` will be expanded to 5.6.31 or something.
