### ISSUE TITLE
unsintall\remove\delete\purge PHPBrew completely

### ISSUE THREAD

**Issue by amitscout** [phpbrew/phpbrew#817]
Hi, I have Ubuntu 14.04 and I've recently installed PHPBrew.
I'm trying to completely wipe out PHPBrew (The PHP versions are already deleted).
Is there a command to remove PHPBrew ? (Not the PHP version..they are already gone).
Or must it be done manually?

Thank you in advance.

**Comment by jhdxr** [comment]
I don't there is a command to remove phpbrew itself for now.

you just need to remove two things:
1. the `phpbrew` phar (`which phpbrew` will help you to find where it is)
2. configuration and some other stuff located under your home folder (`~/.phpbrew`)



and if you don't mind, could you tell me why you want remove phpbrew completely?

**Comment by amitscout** [comment]
Thanks.
I wanted to remove PHPbrew because the version was not identified by the Apache server.

**Comment by c9s** [comment]
Simply to `rm -rf ~/.phpbrew` and remove the line for loading phpbrew env settings from your .profile
