### ISSUE TITLE
PHP 5.2.17 phpbrew command fail with syntax error

### ISSUE THREAD

**Issue by zemnet** [phpbrew/phpbrew#818]
### Output

```
PHP Parse error:  syntax error, unexpected T_STRING, expecting T_CONSTANT_ENCAPSED_STRING or '(' in /usr/bin/phpbrew on line 8
```

### Command

```
phpbrew --debug ext install gd
```

```
phpbrew list
```

### Platform
OS: Ubuntu 14.04 64b
Running PHP: 5.2.17
PHP.INI with detect_unicode=off patch

**Comment by jhdxr** [comment]
sorry, phpbrew needs php 5.3+ to run. (phar was introduced since php 5.3)

**Comment by zemnet** [comment]
thanks.
but how can I install GD extension into old 5.2.17 version?

**Comment by jhdxr** [comment]
http://php.net/manual/en/image.installation.php
