### ISSUE TITLE
Uncaught Error: Call to undefined function Symfony\Component\Yaml\ctype_digit

### ISSUE THREAD

**Issue by Gamesh** [phpbrew/phpbrew#819]
### Output

```
PHP Fatal error:  Uncaught Error: Call to undefined function Symfony\Component\Yaml\ctype_digit() in phar:///usr/bin/phpbrew/vendor/symfony/yaml/Inline.php:504
Stack trace:
#0 phar:///usr/bin/phpbrew/vendor/symfony/yaml/Inline.php(248): Symfony\Component\Yaml\Inline::evaluateScalar('--with-libdir=l...', Array)
#1 phar:///usr/bin/phpbrew/vendor/symfony/yaml/Inline.php(71): Symfony\Component\Yaml\Inline::parseScalar('--with-libdir=l...', NULL, Array, 19, true, Array)
#2 phar:///usr/bin/phpbrew/vendor/symfony/yaml/Parser.php(506): Symfony\Component\Yaml\Inline::parse('--with-libdir=l...', false, false, false, Array)
#3 phar:///usr/bin/phpbrew/vendor/symfony/yaml/Parser.php(117): Symfony\Component\Yaml\Parser->parseValue('--with-libdir=l...', false, false, false, 'sequence')
#4 phar:///usr/bin/phpbrew/vendor/symfony/yaml/Parser.php(225): Symfony\Component\Yaml\Parser->parse('- --with-libdir...', false, false, false)
```

### Expected Result

```
Successfull instalation of predefined extension in config.yml
```

### Command

phpbrew ext install +ituvs --debug

### config.yml
```yml
extensions:
  ituvs:
    xdebug: stable
```
### Build Log

no build log available.

### Platform

OS:

Centos 6.8 x64

Running PHP: 
php 5.5
Installing PHP:
php 7.1

phpbrew - 1.22.6
cliframework core: 2.5.4

**Comment by jhdxr** [comment]
phpbrew rely on `Symfony/yaml`, which needs the ctype extension to run. could you check does your php support ctype?

**Comment by Gamesh** [comment]
it appears it's not 
```
php -r "var_dump(function_exists('ctype_digit'));"
bool(false)
```

i just installed php 7.1 with phpbrew, the php.net docs say that it should be included by default, but somehow it's not

`phpbrew ext install ctype`
 solved the problem, but if extension installation depends on ctype module maybe it should be installed by default by phpbrew or at least a warning that ctype module is required for extension installation, like the curl does:
```
# WARNING: curl extension might be required for fetching data.
```

**Comment by vladkras** [comment]
I've just installed `php-ctype` extension and the problem has resolved

**Comment by chimu123** [comment]
Can any one help me to how to install php-ctype extension in php module

**Comment by vladkras** [comment]
@chimu123 depends on your operating system, php version and type (devel, fpm, cgi, etc.) 
But I guess [StackOverflow](https://stackoverflow.com/search?q=install+php-ctype) is the better place to ask such questions
