### ISSUE TITLE
mv operation not permitted in macOS

### ISSUE THREAD

**Issue by cyseria** [phpbrew/phpbrew#824]
### Expected Result

```
mv: rename phpbrew to /usr/bin/phpbrew: Operation not permitted
```

### Command

    sudo mv phpbrew /usr/bin/phpbrew

### Platform

OS:

    macOS Sierra

and then ... I search on google, and find after OS X 10.11, there are some restrictions even running as root.

- you can't modify anything in `/System`,` /bin`, `/sbin` , or `/usr` (except `/usr/local`); or any of the built-in apps and utilities. Only Installer and software update can modify these areas, and even they only do it when installing Apple-signed packages.

**Comment by c9s** [comment]
looks like the doc needs to be updated.

**Comment by 758gianni** [comment]
look at this
https://stackoverflow.com/a/38435256/14722616

add 'local' to statement 

it should be '/usr/local/bin/phpbrew'

**Comment by peter279k** [comment]
The issue is resolved and closed now.
