### ISSUE TITLE
getting error 

### ISSUE THREAD

**Issue by flik** [phpbrew/phpbrew#825]
### Output

```
source ~/.phpbrew/phpbrew.fish
bash: /home/flikx/.phpbrew/phpbrew.fish: line 18: syntax error near unexpected token `--description'
bash: /home/flikx/.phpbrew/phpbrew.fish: line 18: `  function export --description 'Set global variable. Alias for set -g, made for bash compatibility''

```

### Expected Result

```
...
```

### Command

Paste your phpbrew install command here (be sure to install with `--debug` flag, e.g. `phpbrew --debug install`)

    phpbrew --debug install php-5.x.x +openssl -- --....

### Build Log

    gist here

### Platform

OS:

    e.g. OS X 10.7, Ubuntu 14.04

Running PHP: 

Installing PHP:

**Comment by peter279k** [comment]
The issue is outdated and closed now.
