### ISSUE TITLE
Does phpbrew work on macOS Sierra?

### ISSUE THREAD

**Issue by shinokada** [phpbrew/phpbrew#828]
I installed phpbrew on macOS Sierra. I installed php-5.6.29 and 7.1.0. When I go to localhost/phpinfo.php, it shows raw code. <?php phpinfo(); ?> etc. So how can I make it work on Sierra? Any suggestions?

**Comment by jhdxr** [comment]
Did you execute the install command with `+apxs2`? 
btw, you need turn off rootless before you build php.

**Comment by c9s** [comment]
It seems that you didn't setup your php well. the OS X built-in apache2 doesn't support php. You will have to install one manually.

Please come back to re-open this issue if this was not resolved.
