### ISSUE TITLE
extensions are not installing and error is coming

### ISSUE THREAD

**Issue by flik** [phpbrew/phpbrew#830]
### Output

```
# WARNING: curl extension might be required for fetching data.
Error: PHPBREW_PHP environment variable is not defined.
  This extension command requires you specify a PHP version from your build list.
  And it looks like you haven't switched to a version from the builds that were built with PHPBrew.
Suggestion: Please install at least one PHP with your prefered version and switch to it.

```

### Expected Result

```
...
```

### Command

Paste your phpbrew install command here (be sure to install with `--debug` flag, e.g. `phpbrew --debug install`)

sudo phpbrew ext install apcu

### Build Log

    gist here

### Platform

OS:

 Ubuntu 14.04

Running PHP: PHP 5.5.38 (cli) (built: Dec 19 2016 07:47:16) 

Installing PHP:

**Comment by billxcode** [comment]
have you try this command ? @flik 

> phpbrew ext install php_curl

**Comment by flik** [comment]
I have already installed curl in this way but still facing the same issue.

**Comment by billxcode** [comment]
can you show me result of this command 

> phpbrew list

**Comment by peter279k** [comment]
The issue is outdated and closed now.
