### ISSUE TITLE
phpbrewswitch shell script not work for current shell client

### ISSUE THREAD

**Issue by shine0565** [phpbrew/phpbrew#831]
I want to write a shell script for phpbrew switch, then i can do some another things, like change fpm listening port change, service nginx restart...

My code was that:
/etc/profile.d/phpbrew.sh
```
export PHPBREW_ROOT=/opt/phpbrew
export PHPBREW_HOME=/opt/phpbrew
source /opt/phpbrew/bashrc
export EDITOR=vim
```

/usr/local/bin/phpbrewswitch
```
#!/usr/bin/env bash
VERSION=$1
source /etc/profile.d/phpbrew.sh
phpbrew switch $1

source /etc/profile.d/phpbrew.sh
phpbrew list
```

when i run 
```
# phpbrewswitch 5.6.29
  php-7.0.14     
* php-5.6.29     
  php-5.4.45     

# php -v
PHP 5.4.45 (cli) (built: Dec 24 2016 13:30:53) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
```

i reopen another shell client
```
# php -v
PHP 5.6.29 (cli) (built: Dec 24 2016 14:09:55) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
```

i think the problem is related to the current enviroment variables, i'm not good at the linux system.
what should i do?

os: centos7

**Comment by billxcode** [comment]
@shine0565 that is normal thing. terminal doesnt read automatically changes environment at all. you must open new window shell or new tab shell to take effect of your new configuration.

**Comment by shine0565** [comment]
ok, thank you very much
