### ISSUE TITLE
dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.57.dylib

### ISSUE THREAD

**Issue by xujiajun** [phpbrew/phpbrew#832]
hello,who can give me help? thanks.

### Output

```
➜  ~ phpbrew
dyld: Library not loaded: /usr/local/opt/icu4c/lib/libicui18n.57.dylib
  Referenced from: /Users/xujiajun/.phpbrew/php/php-5.6.26/bin/php
  Reason: image not found
```

### Expected Result

```
fix this issue

```

### Platform

OS:

    e.g. OS X 10.11.6
Running PHP: 

Installing PHP:

php-5.6.26

**Comment by billxcode** [comment]
@xujiajun  actually this problem was fixed in [here](https://github.com/Homebrew/homebrew-php/issues/1710)

**Comment by c9s** [comment]
looks like your library image was updated, but your compiled php is not updated with the latest version. you need to reconfigure and reinstall.
