### ISSUE TITLE
How to install on MacOS Sierra?

### ISSUE THREAD

**Issue by HittmanA** [phpbrew/phpbrew#833]
I am using MacOS Sierra (10.12) and after I follow the install instructions I still can not use phpbrew. It says that the command is not found. Also every time I try to do the `sudo mv phpbrew /usr/bin/phpbrew` command it says that the Operation is not permitted. How do I install this on a Mac?

**Comment by bpineda** [comment]
I just did a fresh install on MacOS Sierra, and I had to do 

sudo mv phpbrew /usr/local/bin

And it worked like a charm

**Comment by HittmanA** [comment]
thanks!

**Comment by nrebhun** [comment]
For those looking for additional understanding on this issue, I suggest reading more about Apple's System Integrity Protection, a feature introduced in OS X 10.11 El Capitan:

https://support.apple.com/en-us/HT204899

**Comment by naxhh** [comment]
Just followed all the steps on MacOs Sierra and I found out this command not working:

```
brew link --force openssl

Warning: Refusing to link: openssl
Linking keg-only openssl means you may end up linking against the insecure,
deprecated system OpenSSL while using the headers from Homebrew's openssl.
Instead, pass the full include/library paths to your compiler e.g.:
  -I/usr/local/opt/openssl/include -L/usr/local/opt/openssl/lib
```

What I should do from here to get https working?

```
$ phpbrew known
===> Fetching release list...
Downloading https://secure.php.net/releases/index.php?json&version=7&max=100 via curl extension
Downloading https://secure.php.net/releases/index.php?json&version=5&max=100 via curl extension

Warning: file_put_contents(/Users/ignacio.tolstoy/.phpbrew/php-releases.json): failed to open stream: No such file or directory in phar:///usr/local/bin/phpbrew/src/PhpBrew/ReleaseList.php on line 129
Exception: Can't store release json file
Trace:

    0) PhpBrew\ReleaseList->save()
    1) PhpBrew\ReleaseList->fetchRemoteReleaseList(GetOptionKit\OptionResult)
    2) PhpBrew\Tasks\FetchReleaseListTask->fetch()
    3) PhpBrew\Command\KnownCommand->execute()
    4) call_user_func_array([PhpBrew\Command\KnownCommand, 'execute'], [])
    5) CLIFramework\CommandBase->executeWrapper([])
    6) CLIFramework\Application->run(['/usr/local/bin/phpbrew', 'knoq'])
    7) PhpBrew\Console->runWithTry(['/usr/local/bin/phpbrew', 'knoq'])
    8) require('phar:///usr/local/bin/phpbrew/scripts/phpbrew-emb.php')
```

**Comment by c9s** [comment]
@naxhh Have you executed `phpbrew init` ?

**Comment by NigelGreenway** [comment]
@naxhh I ran `sudo brew link --force openssl`. Not ideal or possibly advisable but it solved this issue which I was having...

**Comment by naxhh** [comment]
@c9s so.. it was just that! thanks a lot I must misread that step :)

**Comment by morozov** [comment]
Closing as resolved.
