### ISSUE TITLE
Typo and correction on the README file

### ISSUE THREAD

**Issue by bpineda** [phpbrew/phpbrew#834]
The README file refers to the fish config file as

```
~./config/fish/config.fish
```
And it should be

```
~/.config/fish/config.fish
```

Also, on newer MacOS systems, the instruction:

```
sudo mv phpbrew /usr/bin/phpbrew
```

should be:

```
sudo mv phpbrew /usr/local/bin/phpbrew
```

The corrections are way simple and I can do them myself.

**Comment by jhdxr** [comment]
fixed, thank you
