### ISSUE TITLE
Customer Patch Version Support of PHP

### ISSUE THREAD

**Issue by ihipop** [phpbrew/phpbrew#835]
Suggest if I have to run an  old Application in an obsolete php Version,
and I will have to back-port secure patch to the version
How Can I install from the source  that is patched against the previous PHP (eg:5.3.88) without replace the old  one. and keep it managed by `phpbrew` as version `5.3.88-p1` instead of `5.3.88`

**Comment by ihipop** [comment]
I think that the version problem could use this solution:
 `phpbrew install  PHPVERSION as PHPVERSION-p1` 
this should work
But  Howto install from a Customer PHP Source Directory that is already Patched?

**Comment by c9s** [comment]
Not sure if `--build-dir {dir} --no-clean` helps?

**Comment by ihipop** [comment]
@c9s seeems would working
maybe  a more stand way is that I have to generate a stand path file and apply to official source when calling `phpbrew install 
PHPVERSION --patch diff.patch`
