### ISSUE TITLE
cannot start Apache with PHP lower than 7.0 after installed PHP 7.1.0

### ISSUE THREAD

**Issue by ve3** [phpbrew/phpbrew#836]
I was installed Apache 2, PHP 5.4, 5.5, 5.6, 7.0 with phpbrew.

I was be able to switch version of PHP on Apache using [this comment](https://github.com/phpbrew/phpbrew/issues/226#issuecomment-47221197) and it works perfectly.

After I installed PHP 7.1.0, and switch to Apache -> PHP 7.1.0 everything works fine.
Switch to PHP 7.0.0 still works fine.
Switch to PHP 5.6.29 or lower and Apache cannot start and here is the log found in /var/log/apache2/error.log

> [Sun Jan 15 16:03:26.422951 2017] [mpm_prefork:notice] [pid 7642] AH00171: Graceful restart requested, doing restart
> AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.1.1. Set the 'ServerName' directive globally to suppress this message
> [Sun Jan 15 16:03:26.510214 2017] [core:notice] [pid 7642] AH00060: seg fault or similar nasty error detected in the parent process

Uninstall or remove or purge cannot make it back to work.

**Comment by Pupp3tm4st3r** [comment]
Did you look at the conf-enabled directory? Maybe theres 2 php configurations enabled.

**Comment by ve3** [comment]
Nope, only one.

**Comment by jhdxr** [comment]
could you upload your apache config file?

**Comment by ve3** [comment]
Sorry, I was removed the whole OS. (I use virtual box on Windows host and Ubuntu as guest pc.)

**Comment by jhdxr** [comment]
It's fine. I'm closing this issue and if your run into it again just reopen this one or create a new issue.

btw, php 5.x and php 7.x use different module name in apache config file, like
`LoadModule php7_module xxxxxxxxx` and
`LoadModule php5_module xxxxxxxxx`

it may be the reason why your apache fails to work.
