### ISSUE TITLE
configure: error: Your system does not support systemd.

### ISSUE THREAD

**Issue by rgagnon** [phpbrew/phpbrew#837]
when I do : 

```
phpbrew install 5.4.23 +default +fpm

```

### Output

```
configure: error: Your system does not support systemd.
```

### Platform

OS:

    No LSB modules are available.
    Distributor ID:	Ubuntu
    Description:	Ubuntu 16.04.1 LTS
    Release:	16.04
    Codename:	xenial

**Comment by c9s** [comment]
I thought 16.04 should have systemd.

**Comment by c9s** [comment]
Check this out 

https://bugs.php.net/bug.php?id=69237&edit=1

**Comment by peter279k** [comment]
The issue seems to be resolved and closed now.
