### ISSUE TITLE
pcntl lib not accessible by Apache after install for php 5.6.29

### ISSUE THREAD

**Issue by bozhidarc** [phpbrew/phpbrew#840]
### Output
When I access the PHP file through Apache the following error shows. In CLI evething is fine.
```
Fatal error: Call to undefined function pcntl_exec() in test.php on line 13
```

### Command

Phpbrew install command

    phpbrew --debug install 5.6 +pcntl+default+dbs+mcrypt+apxs2=/usr/bin/apxs2

### Build Log

    https://gist.github.com/bozhidarc/d60da9dad6e15875bb7f8aa5e205b3be

### Platform

OS:

    Ubuntu 14.04.1 LTS

Running PHP: 
    PHP 5.5
Installing PHP:
    PHP 5.6.29

**Comment by jhdxr** [comment]
phpbrew  won't switch the version apache use for now, so you may use `phpinfo()` to find if you are running the correct version.

**Comment by c9s** [comment]
I think you need to restart your apache to reload the php module.

**Comment by morozov** [comment]
@bozhidarc were you able to resolve the issue?

**Comment by peter279k** [comment]
The issue is outdated and will be closed.
