### ISSUE TITLE
phpbrew switch from shell script not working properly

### ISSUE THREAD

**Issue by landwire** [phpbrew/phpbrew#843]
### Script
        source ~/.phpbrew/bashrc
	phpbrew list
	phpbrew switch 5.6.30
	phpbrew list
	#phpbrew switch php-${newversion}

### Platform

OS:
OS X 10.11.6

I am trying to use "phpbrew switch $version" from a shell script like above. For testing purposes I hardcoded 5.6.30 (and also tried 7.1.1), but php is not being switched properly. It looks like it's doing something as the * on "phpbrew list" changes, but when I check with "which php" the php version actually has not changed. If I run the command in the shell directly it works without a problem and "which php" and my prompt show the correct "switched" php version.
Any ideas? 

See attached file for output. My prompt also shows the current php version correctly...

![screen shot 2017-02-03 at 01 21 38](https://cloud.githubusercontent.com/assets/1001202/22574543/c1842810-e9af-11e6-9595-d57eee9bf1a0.png)

**Comment by jhdxr** [comment]
which shell client do you use?

**Comment by landwire** [comment]
I use iterm2 with zsh

**Comment by c9s** [comment]
You changed the environment variable inside the script, it won't change the parent environment, therefore, you won't get the current result after running the script.

**Comment by c9s** [comment]
the only way to fix that is, use `source` command to source the script, not to run it in a new bash process.

```
. testscript
```

**Comment by landwire** [comment]
Ok, thanks. Shame it cannot be done from a script.

I have written a script for switching the apache php versions (installed with phpbrew) easily. It's my first bash script, but it seems to be working ok, at least on OSX El Capitan.
It's here in case anyone is interested. If you find it useful you can link it somewhere on your readme.md maybe: https://github.com/landwire/phpbrew-apache-php-switcher

**Comment by c9s** [comment]
@landwire you will have to load it as a function in your shell, and call that function to modify the environment variable, not a script file.
