### ISSUE TITLE
Error on: phpbrew ext install yaml

### ISSUE THREAD

**Issue by landwire** [phpbrew/phpbrew#844]
### Output

```
...
```phpbrew ext install yaml
Warning: Some extension won't be able to be built with php7. If the extension
supports php7 in another branch or new major version, you will need to specify
the branch name or version name explicitly.

For example, to install memcached extension for php7, use:

    phpbrew ext install github:php-memcached-dev/php-memcached php7 -- --disable-memcached-sasl

Downloading https://pecl.php.net/rest/r/yaml/stable.txt via curl extension
[==================================================================] 5.00/5.00B 100%
Downloading https://pecl.php.net/rest/r/yaml/1.3.0.xml via curl extension
[==================================================================] 1.06/1.06KB 100%
Downloading https://pecl.php.net/rest/r/yaml/stable.txt via curl extension
[==================================================================] 5.00/5.00B 100%
Downloading https://pecl.php.net/rest/r/yaml/1.3.0.xml via curl extension
[==================================================================] 1.06/1.06KB 100%
Downloading http://pecl.php.net/get/yaml-1.3.0.tgz via curl extension
[==================================================================] 36.21/36.21KB 100%
===> Extracting to /Users/sascha/.phpbrew/build/php-7.1.1/ext...
===> Installing yaml extension...
Log stored at: /Users/sascha/.phpbrew/build/php-7.1.1/ext/yaml/build.log
Changing directory to /Users/sascha/.phpbrew/build/php-7.1.1/ext/yaml
===> Phpize...
===> Configuring...
Error: Command failed: ./configure --with-php-config=/Users/sascha/.phpbrew/php/php-7.1.1/bin/php-config >> /Users/sascha/.phpbrew/build/php-7.1.1/ext/yaml/build.log 2>&1 returns:
╭─ 00:19:12  PHP 7.1.1  ⬢ 7.5.0   ~ 



### Platform

OS:

 10.11.6

Running PHP: 

7.1.1

**Comment by c9s** [comment]
Could you cat your log at `/Users/sascha/.phpbrew/build/php-7.1.1/ext/yaml/build.log`

**Comment by landwire** [comment]
at /Users/sascha/.phpbrew/build/php-7.1.1/ext/yaml/build.log
Configuring for:
PHP Api Version:         20160303
Zend Module Api No:      20160303
Zend Extension Api No:   320160303
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-apple-darwin15.6.0
checking host system type... x86_64-apple-darwin15.6.0
checking target system type... x86_64-apple-darwin15.6.0
checking for PHP prefix... /Users/sascha/.phpbrew/php/php-7.1.1
checking for PHP includes... -I/Users/sascha/.phpbrew/php/php-7.1.1/include/php -I/Users/sascha/.phpbrew/php/php-7.1.1/include/php/main -I/Users/sascha/.phpbrew/php/php-7.1.1/include/php/TSRM -I/Users/sascha/.phpbrew/php/php-7.1.1/include/php/Zend -I/Users/sascha/.phpbrew/php/php-7.1.1/include/php/ext -I/Users/sascha/.phpbrew/php/php-7.1.1/include/php/ext/date/lib
checking for PHP extension directory... /Users/sascha/.phpbrew/php/php-7.1.1/lib/php/extensions/no-debug-non-zts-20160303
checking for PHP installed headers prefix... /Users/sascha/.phpbrew/php/php-7.1.1/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... re2c
checking for re2c version... 0.15.3 (ok)
checking for gawk... no
checking for nawk... no
checking for awk... awk
checking if awk is broken... no
checking whether to enable LibYAML suppot... yes, shared
checking for yaml headers... not found
configure: error: Please install libyaml

**Comment by c9s** [comment]
You have to install libyaml and provide the prefix, e.g.  `phpbrew ext install yaml -- --with-yaml=....`

Use `phpbrew ext show yaml` to find out the options.

**Comment by c9s** [comment]
Please come back again and re-open this issue if this can't solve your problem.
