### ISSUE TITLE
Can't restart apache2 after installing a version of PHP with phpbrew

### ISSUE THREAD

**Issue by siick** [phpbrew/phpbrew#847]
Hello,
I was a user of phpbrew on Ubuntu 14.04, i found it very useful and quite easy to use. Now i want to install differents versions of PHP for a project. I'm now on Ubuntu 16.04.
So i've installed phpbrew with that requirements (https://coderwall.com/p/hguzxa/phpbrew-on-ubuntu-16-04-php7) and my versions of PHP which are php-7.1.2, php-7.0.16 and php-5.6.30
All went fluently during installation of each version with that command line
```
phpbrew install 5.6.30 +default +mysql +pdo +apxs2=/usr/bin/apxs2 +mb
```
When i switch php version it's ok and i see the right version when i do
```
php -i
```
But when i restart my apache server i'm facing a problem
```
sudo service apache2 restart
Job for apache2.service failed because the control process exited with error code. See "systemctl status apache2.service" and "journalctl -xe" for details.
```
And this the output of 
```
systemctl status apache2.service
```
### Output

```
● apache2.service - LSB: Apache2 web server
   Loaded: loaded (/etc/init.d/apache2; bad; vendor preset: enabled)
  Drop-In: /lib/systemd/system/apache2.service.d
           └─apache2-systemd.conf
   Active: failed (Result: exit-code) since mer. 2017-03-01 16:09:49 CET; 1min 19s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 6878 ExecStart=/etc/init.d/apache2 start (code=exited, status=1/FAILURE)

mars 01 16:09:49 xnovx-xnovx apache2[6878]:  * The apache2 configtest failed.
mars 01 16:09:49 xnovx-xnovx apache2[6878]: Output of config test was:
mars 01 16:09:49 xnovx-xnovx apache2[6878]: [Wed Mar 01 16:09:49.821923 2017] [:crit] [pid 6888:tid 140147377301376] Apache is running a threaded MPM, but your PHP Module is not compiled to be threadsafe.  You need to recompile PHP.
mars 01 16:09:49 xnovx-xnovx apache2[6878]: AH00013: Pre-configuration failed
mars 01 16:09:49 xnovx-xnovx apache2[6878]: Action 'configtest' failed.
mars 01 16:09:49 xnovx-xnovx apache2[6878]: The Apache error log may have more information.
mars 01 16:09:49 xnovx-xnovx systemd[1]: apache2.service: Control process exited, code=exited status=1
mars 01 16:09:49 xnovx-xnovx systemd[1]: Failed to start LSB: Apache2 web server.
mars 01 16:09:49 xnovx-xnovx systemd[1]: apache2.service: Unit entered failed state.
mars 01 16:09:49 xnovx-xnovx systemd[1]: apache2.service: Failed with result 'exit-code'.
```
I can see the problem is there "Apache is running a threaded MPM, but your PHP Module is not compiled to be threadsafe.  You need to recompile PHP" but i clearly don't know what to do :/

### Platform

OS:

    Ubuntu 16.04 x64

Running PHP: none

Installing PHP: php-7.1.2, php-7.0.16 and php-5.6.30

Thanks in advance for the help

**Comment by siick** [comment]
Ok, i've tried to reinstall Apache2. Now the web server is starting OK but it does not read php :/ and i have nothing when i go to see my /var/log/apache2/error.log after loading my HTML page containing php.

**Comment by nikola3244** [comment]
I came here to look for a totally unrelated issue, but I encountered your problem before.

Here's what solved it for me:
>In /etc/httpd/conf/httpd.conf, comment the line:
`#LoadModule mpm_event_module modules/mod_mpm_event.so`
and uncomment the line:
`LoadModule mpm_prefork_module modules/mod_mpm_prefork.so`

>because libphp7.so included with php-apache does not work with `mod_mpm_event`, but will only work `mod_mpm_prefork` instead.
As an alternative, you can use `mod_proxy_fcgi`

Hope it works for you!


(btw, this issue is not related to phpbrew in any way)

**Comment by siick** [comment]
Ok thanks!
