### ISSUE TITLE
Cannot install php 5.4 on Ubuntu 16.04 

### ISSUE THREAD

**Issue by MurKit** [phpbrew/phpbrew#848]
# WARNING: curl extension might be required for fetching data.
===> phpbrew will now build 5.4.45
You haven't set any variant. A default set of extensions will be installed for the minimum requirement:
[bcmath, bz2, calendar, cli, ctype, dom, fileinfo, filter, ipc, json, mbregex, mbstring, mhash, pcntl, pcre, pdo, phar, posix, readline, sockets, tokenizer, xml, curl, zip, openssl]
Please run 'phpbrew variants' for more information.

===> Loading and resolving variants...
Checking distribution checksum...
Checksum matched: 185f67f1ca652b18bc0cca9d7edbde7c
===> Distribution file was successfully extracted, skipping...
Source Directory: /home/sasha/.phpbrew/build/php-5.4.45
Found existing Makefile, running make clean to ensure everything will be rebuilt.
You can append --no-clean option after the install command if you don't want to rebuild.
===> Running make clean: /usr/bin/make -C '/home/sasha/.phpbrew/build/php-5.4.45' --quiet 'clean'
Running Command:/usr/bin/make -C '/home/sasha/.phpbrew/build/php-5.4.45' --quiet 'clean'
Writing variant info to /home/sasha/.phpbrew/php/php-5.4.45/phpbrew.variants
===> Checking patches...
Checking patch for replace apache php module name with custom version name
Enabled variants: [bcmath, bz2, calendar, cli, ctype, dom, fileinfo, filter, ipc, json, mbregex, mbstring, mhash, pcntl, pcre, pdo, phar, posix, readline, sockets, tokenizer, xml, curl, zip, openssl]
Disabled variants: []
Found existing build.log, renaming it to /home/sasha/.phpbrew/build/php-5.4.45/build.log.1488382833
===> Configuring 5.4.45...

Use tail command to see what's going on:
   $ tail -F /home/sasha/.phpbrew/build/php-5.4.45/build.log

./configure '--cache-file='\''/home/sasha/.phpbrew/cache/config.cache'\''' '--prefix=/home/sasha/.phpbrew/php/php-5.4.45' '--with-config-file-path=/home/sasha/.phpbrew/php/php-5.4.45/etc' '--with-config-file-scan-dir=/home/sasha/.phpbrew/php/php-5.4.45/var/db' '--disable-all' '--enable-phar' '--enable-session' '--enable-short-tags' '--enable-tokenizer' '--with-pcre-regex' '--with-zlib=/usr' '--with-libdir=lib/x86_64-linux-gnu' '--enable-bcmath' '--with-bz2=/usr' '--enable-calendar' '--enable-cli' '--enable-ctype' '--enable-dom' '--enable-fileinfo' '--enable-filter' '--enable-shmop' '--enable-sysvsem' '--enable-sysvshm' '--enable-sysvmsg' '--enable-json' '--enable-mbregex' '--enable-mbstring' '--with-mhash' '--enable-pcntl' '--with-pcre-regex' '--with-pcre-dir=/usr' '--enable-pdo' '--enable-phar' '--enable-posix' '--with-readline=/usr' '--enable-sockets' '--enable-tokenizer' '--enable-dom' '--enable-libxml' '--enable-simplexml' '--enable-xml' '--enable-xmlreader' '--enable-xmlwriter' '--with-xsl' '--with-libxml-dir=/usr' '--enable-zip' '--with-openssl=yes' '--with-pear=/home/sasha/.phpbrew/php/php-5.4.45/lib/php' '--enable-zend-signals' >> /home/sasha/.phpbrew/build/php-5.4.45/build.log 2>&1
===> Checking patches...
Checking patch for php5.3.29 multi-sapi patch.
Checking patch for php5.3.x on 64bit machine when intl is enabled.
Checking patch for openssl dso linking patch
===> Building...
make >> /home/sasha/.phpbrew/build/php-5.4.45/build.log 2>&1
Error: Make failed:
The last 5 lines in the log file:
/home/sasha/.phpbrew/build/php-5.4.45/ext/openssl/xp_ssl.c:355: undefined reference to `SSLv3_server_method'

/home/sasha/.phpbrew/build/php-5.4.45/ext/openssl/xp_ssl.c:343: undefined reference to `SSLv3_client_method'

collect2: error: ld returned 1 exit status

Makefile:239: recipe for target 'sapi/cli/php' failed

make: *** [sapi/cli/php] Error 1

Please checkout the build log file for more details:
	 tail /home/sasha/.phpbrew/build/php-5.4.45/build.log

OS:

   Ubuntu 16.04

**Comment by juuuuuu** [comment]
Same problem here.

**Comment by c9s** [comment]
Looks like the openssl API was changed on Ubuntu 16. This couldn't be fixed without some patches for PHP.
