### ISSUE TITLE
Curl extension not installed

### ISSUE THREAD

**Issue by drgomesp** [phpbrew/phpbrew#85]
Curl extension is not being installed with the `+default` option. Is that normal?

When I try to disable it, I get this output:

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/Users/drgomesp/.phpbrew/php/php-5.4.14/lib/php/extensions/no-debug-non-zts-20100525/curl.so' - dlopen(/Users/drgomesp/.phpbrew/php/php-5.4.14/lib/php/extensions/no-debug-non-zts-20100525/curl.so, 9): image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/Users/drgomesp/.phpbrew/php/php-5.4.14/lib/php/extensions/no-debug-non-zts-20100525/curl.so' - dlopen(/Users/drgomesp/.phpbrew/php/php-5.4.14/lib/php/extensions/no-debug-non-zts-20100525/curl.so, 9): image not found in Unknown on line 0
Extension curl is already disabled.
```

If I try to install it, here is the output:

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/Users/drgomesp/.phpbrew/php/php-5.4.14/lib/php/extensions/no-debug-non-zts-20100525/curl.so' - dlopen(/Users/drgomesp/.phpbrew/php/php-5.4.14/lib/php/extensions/no-debug-non-zts-20100525/curl.so, 9): image not found in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library '/Users/drgomesp/.phpbrew/php/php-5.4.14/lib/php/extensions/no-debug-non-zts-20100525/curl.so' - dlopen(/Users/drgomesp/.phpbrew/php/php-5.4.14/lib/php/extensions/no-debug-non-zts-20100525/curl.so, 9): image not found in Unknown on line 0
===> Installing curl extension...
===> Phpizing...
===> Configuring...
sh: ./configure: No such file or directory
===> Building...
make: *** No targets specified and no makefile found.  Stop.
===> Installing...
make: *** No rule to make target `install'.  Stop.
===> Extension is installed.
===> Enabling extension
Done
```

How can I solve this?

**Comment by larsnystrom** [comment]
Installing libcurl4-openssl-dev solved this problem for me on Ubuntu 14.04.

**Comment by alpharder** [comment]
@larsnystrom @steveoliver You may want to see my see my script that installs phpbrew and all of its dependencies: https://github.com/alpharder/phpgrant/blob/master/install_vagrant.sh

**Comment by gsouf** [comment]
Had also issue for installing curl ext. Installing libcurl3-openssl-dev fixed it.

The error output I got was not expressive enough imo: 
```
configure: error: Please reinstall the libcurl distribution -
    easy.h should be in <curl-dir>/include/curl/
```

**Comment by c9s** [comment]
Hi! could you help me update the wiki requirement? Thanks~

**Comment by gsouf** [comment]
@c9s  I updated ubuntu section of https://github.com/phpbrew/phpbrew/wiki/Requirement (i only use debian, I cant help with fedora, mac and centOS because package name mays be different)

**Comment by minhaj-resgef** [comment]
I was in similar issue with curl functions not available to use in php, now got it working.
(debian 8) I installed libcurl4-gnutls-dev, php5-dev 
and then built php again, 
installed the curl extension with phpbrew ext install curl
then curl came in php!

**Comment by williamokano** [comment]
@minhaj-resgef thanks, worked for me too.

Linux mint
