### ISSUE TITLE
phpbrew command not working

### ISSUE THREAD

**Issue by wibicms** [phpbrew/phpbrew#858]
I remove phpbrew in ~/.phpbrew and /usr/local/bin/phpbrew, when I want to reinstall and  i follow the instructions, but when i type:
phpbrew or 
phpbrew init

the output is nothing, there is no error or anyhing, only ???My-MBP:
### Platform

OS:

    e.g. OS X 10.12.4

Running PHP: 5.3

Installing PHP: 5.3

**Comment by jhdxr** [comment]
what do you mean 
>the output is nothing

did you add executable mod to phpbrew (`chmod +x phpbrew`) ?

**Comment by c9s** [comment]
did you set PATH ?

**Comment by c9s** [comment]
closed for now since not responding.
