### ISSUE TITLE
something wrong 

### ISSUE THREAD

**Issue by yygxlin** [phpbrew/phpbrew#859]
### Output

```
lchdeMacBook-Pro:~ lch$ phpbrew switch 7.1.3
You should not see this, if you see this, it means you didn't load the ~/.phpbrew/bashrc script, please check if bashrc is sourced in your shell.
```

i have add [[ -e ~/.phpbrew/bashrc ]] && source ~/.phpbrew/bashrc to 
.bashrc

**Comment by jhdxr** [comment]
plz read `README.md`

did you execute `phpbrew init`?

**Comment by yygxlin** [comment]
i did ,but not helpful
and i have give it up ,so sad

**Comment by GaryJones** [comment]
@yygxlin My understanding is you'd want:
```sh
phpbrew switch php-7.1.3
```

The `switch` command takes the _name_ of the install, rather than just the number. Run `phpbrew list` to see the installed PHPs.

**Comment by morozov** [comment]
`phpbrew switch` can work with and without the `php-` prefix same as `phpbrew use`.

**Comment by peter279k** [comment]
The issue is outdated and will be closed.
