### ISSUE TITLE
memcached extension build broken with PHP 5.5.38

### ISSUE THREAD

**Issue by klarkc** [phpbrew/phpbrew#864]
### Output (building)

```
/home/klarkc/.phpbrew/build/php-5.5.38/ext/memcached/php_memcached.h:23:33: fatal error: Zend/zend_smart_str.h: No such file or directory
```

### Command

Paste your phpbrew install command here (be sure to install with `--debug` flag, e.g. `phpbrew --debug install`)
  `phpbrew --debug install 5.5 +default +mysql +intl +iconv`
  `phpbrew --debug ext install --redownload memcached -- --disable-memcached-sasl`

### Build Log

    https://gist.github.com/klarkc/5703b2a50cec31f8fea99be6fb9a6abf
    
### Platform

OS: Ubuntu 16.04.2 LTS

Running PHP: 5.5.38

Installing PHP: 5.5.38

**Comment by c9s** [comment]
You are installing a wrong version of memcached


I would suggest you to check the pecl page.

Walker Gusmão <notifications@github.com>於 2017年4月18日 週二，23:32寫道：

**Comment by mnvx** [comment]
I have this problem too
Ubuntu 18.04
PHP 5.6.36

**Comment by peter279k** [comment]
After trying to do the `memcached` extension installation, it doesn't have the issue when building the `PHP 5.6` version in Ubuntu 18.04.

Here are the steps to do this:

- Prepare fresh and clean Ubuntu 18.04
- Install required packages with the `apt-get install` command (including the `libmemcached-dev` installation).
- Install and configure the PHPBrew.
- Running the `phpbrew install 5.6 +default` to build the latest `PHP 5.6` version.
- After building the above PHP version is completed, running the `phpbrew ext install memecached 2.2.0`.
And running command output is as follows:

```sh
$ phpbrew install 5.6 +default
$ phpbrew switch php-5.6.40
$ phpbrew ext install memcached 2.2.0
......
===> Phpize...
===> Configuring...
===> Building...
===> Running make all: /usr/bin/make -C '/root/.phpbrew/build/php-5.6.40/ext/memcached' 'all'  >> '/root/.phpbrew/build/php-5.6.40/ext/memcached/build.log' 2>&1
===> Installing...
===> Running make install: /usr/bin/make -C '/root/.phpbrew/build/php-5.6.40/ext/memcached' 'install'  >> '/root/.phpbrew/build/php-5.6.40/ext/memcached/build.log' 2>&1
===> Extension is installed.
===> Creating config file /root/.phpbrew/php/php-5.6.40/var/db/memcached.ini.disabled
===> Enabling extension memcached
[*] memcached extension is enabled.
Done.
```

The latest memcached extension is not supported for the PHP 5.6 version and it should specify correct version for the `PHP 5.6` version.
