### ISSUE TITLE
When build error with openssl

### ISSUE THREAD

**Issue by C1tas** [phpbrew/phpbrew#866]
### Output

```
...
/home/r7/.phpbrew/build/php-5.6.30/ext/openssl/openssl.c:5316:17: error: storage size of ‘cipher_ctx’ isn’t known

  EVP_CIPHER_CTX cipher_ctx;

                 ^~~~~~~~~~

/home/r7/.phpbrew/build/php-5.6.30/ext/openssl/openssl.c:5316:17: warning: unused variable ‘cipher_ctx’ [-Wunused-variable]

make: *** [Makefile:626: ext/openssl/openssl.lo] Error 1

```

### Expected Result

```
...
```

### Command

Paste your phpbrew install command here (be sure to install with `--debug` flag, e.g. `phpbrew --debug install`)

    phpbrew --debug install php-5.x.x +openssl -- --....

### Build Log

    the same as top

### Platform

OS:

    archlinux

OpenSSL 1.1.0e  16 Feb 2017

how can i fix this problem, when i seach for this, i can't get a recent fix

**Comment by jhdxr** [comment]
php 5.x doesn't support openssl 1.1.0 or above.
you may have to downgrade your openssl, or using the latest php.

reference: https://bugs.php.net/bug.php?id=72360

**Comment by jhdxr** [comment]
I'm closing this issue since it's a php issue rather than phpbrew issue.

**Comment by Buccleuch** [comment]
I've used php7.1 and get the same error as above when running `phpbrew install`

`error: storage size of ‘cipher_ctx’ isn’t known`

**Comment by C1tas** [comment]
@Buccleuch, I fix this by use old version openssl, I bak the current version openssl and copy old version to current version's folder, after built it i move the bak to before

**Comment by Buccleuch** [comment]
@C1tas I downgraded to openssl version OpenSSL 0.9.8zi-dev and still get the same error on both php7.1 and php5.6. Which version of openssl enabled you to avoid the error?

**Comment by C1tas** [comment]
I just use openssl 1.0 
the current version is 
1.0.2.l-1
--

and 
```
#!/bin/bash
if [ ! -d /opt/openssl ]; then
	sudo cp -r /usr/include/openssl /opt/
	sudo cp -r /usr/include/openssl-1.0 /opt/
else
	echo "already backup"
fi

if [ "$1" = "old" ]; then
	sudo rm -rf /usr/include/openssl
	sudo cp -r /opt/openssl-1.0/openssl /usr/include/
	echo "now use openssl-1.0"
else
	sudo rm -rf /usr/include/openssl
	sudo cp -r /opt/openssl /usr/include
	echo "now use openssl"
fi
```
I use the script in arch linux then it works well for me

**Comment by C1tas** [comment]
@Buccleuch ok, I test it about nowdays, I get a new way
in archlinux there is a openssl-1.0 in /usr/lib/
and if you use
`PKG_CONFIG_PATH=/usr/lib/openssl-1.0/pkgconfig ./configure --prefix=/tmp/php5 --with-openssl`
`PKG_CONFIG_PATH=/usr/lib/openssl-1.0/pkgconfig make`
`PKG_CONFIG_PATH=/usr/lib/openssl-1.0/pkgconfig make install`

it works well

**Comment by zsxsoft** [comment]
```bash
export PKG_CONFIG_PATH=/usr/lib/openssl-1.0/pkgconfig
phpbrew --debug install 5.5 +default +openssl=shared
```

A better solution
![image](https://user-images.githubusercontent.com/2398785/38424164-bebfdd34-39e2-11e8-8363-46401e14a29b.png)
