### ISSUE TITLE
How to inegrate ioncube(or another extenstion) into phpbrew php version?

### ISSUE THREAD

**Issue by zeyser** [phpbrew/phpbrew#868]
### Problem: 
I can't install ioncube as php extension.

### What I have already done:
- Download from http://www.ioncube.com/loaders.php my version of extension (Linux 64 tar.gz v6.0.9 2017-1-26)
- Unpack all and put ioncube_loader_lin_5.6.so to `/home/kpot/.phpbrew/php/php-5.6.24-last/lib/php/extensions/debug-zts-20131226`
- Add `extension=/home/kpot/.phpbrew/php/php-5.6.24-last/lib/php/extensions/debug-zts-20131226/ioncube_loader_lin_5.6.so` in php.ini
- Restart server with `sudo service apache2 restart`
- When apply php -v got this `PHP Warning:  PHP Startup: Unable to load dynamic library '/home/kpot/.phpbrew/php/php-5.6.24-last/lib/php/extensions/debug-zts-20131226/ioncube_loader_lin_5.6.so' - /home/kpot/.phpbrew/php/php-5.6.24-last/lib/php/extensions/debug-zts-20131226/ioncube_loader_lin_5.6.so: undefined symbol: executor_globals in Unknown on line 0`
after phpinfo() can't find anything associated with ioncube

### Additional information:

- **uname -a**  `Linux KpoT 4.4.0-75-generic #96~14.04.1-Ubuntu SMP Thu Apr 20 11:06:30 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux`
- **php -i | grep extension_dir** `extension_dir => /home/kpot/.phpbrew/php/php-5.6.24-last/lib/php/extensions/debug-zts-20131226 => /home/kpot/.phpbrew/php/php-5.6.24-last/lib/php/extensions/debug-zts-20131226`
- **phpbrew - 1.21.6**

**Comment by morozov** [comment]
@zeyser the error message you're getting most probably means your extension is incompatible with the PHP you're trying to load it into:
> PHP Warning: PHP Startup: Unable to load dynamic library '/home/kpot/.phpbrew/php/php-5.6.24-last/lib/php/extensions/debug-zts-20131226/ioncube_loader_lin_5.6.so' - /home/kpot/.phpbrew/php/php-5.6.24-last/lib/php/extensions/debug-zts-20131226/ioncube_loader_lin_5.6.so: undefined symbol: executor_globals in Unknown on line 0

Most probably, the incompatibility is between NTS and ZTS builds of the extension and the PHP which it's being installed onto. See a [similar issue](https://github.com/remicollet) for reference.

**Comment by zeyser** [comment]
First of all. When you unpack your archive with ioncube, pay attension to files with _ts at the end. In my case I have php with thread safe enabled(phpinfo()), so you must choose exactly that files. Second problem occurs when php was compiled with debug. You must recompile your php without it.

**Comment by popovserhii** [comment]
### How to install ionCube on PHP 5.6 with PHPBrew

Install required PHP version without `-debug` mode, ionCube does not support it
```bash
$ phpbrew install php-5.6.40 +default +mysql +pdo +fpm +gd +gettext +iconv +intl -debug -openssl
```
Use needable PHP version
```bash
$ phpbrew use php-5.6.40
```

Check your php version with `php -v` 
```bash
$ php -v
PHP 5.6.40 (cli) (built: Jun  6 2019 16:09:30) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
```

[Download](https://www.ioncube.com/loaders.php) archive with ionCube extensions.
Unpack file `ioncube_loader_lin_5.6.so` to `/home/popov/.phpbrew/php/php-5.6.40/lib/php/extensions/no-debug-non-zts-20131226`. Pay attension to files with _**_ts**_ at the end (**Thread Safety** mode).

Create file `00_ioncube.ini` under `/home/popov/.phpbrew/php/php-5.6.40/var/db` with next content
```
$ cat /home/popov/.phpbrew/php/php-5.6.40/var/db/00_ioncube.ini
zend_extension=ioncube_loader_lin_5.6.so
```

Run `php -v`, you should see that ionCube is enabled
```bash
$ php -v
PHP 5.6.40 (cli) (built: Jun  6 2019 16:09:30) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.3.5, Copyright (c) 2002-2019, by ionCube Ltd.
```

If you use `fpm` run `phpbrew fpm restart`

**Comment by kemexyz** [comment]
Just tried the solution posted by popovserhii. Worked with the not _ts (thread safe) version.
