### ISSUE TITLE
Support for windows or cygwin

### ISSUE THREAD

**Issue by jenish2014** [phpbrew/phpbrew#874]
Hi everyone,

I was wondering if phpbrew supports windows system, if not is it possible using cygwin?

**Comment by jhdxr** [comment]
No, I don't think phpbrew can work on Windows, even with cygwin. The libraries and tools used to compile php on Windows are different from those on Linux.

**Comment by jenish2014** [comment]
So, just to be clear the issue [236](https://github.com/phpbrew/phpbrew/issues/236) is not implemented.

**Comment by jhdxr** [comment]
yep, and IMHO I don't think it would be implemented. 

You need to install visual studio along with Windows SDK to compile php on Windows, and you have to install different versions of VS. You can refer to [here](https://wiki.php.net/internals/windows/stepbystepbuild) and [here](https://wiki.php.net/internals/windows/stepbystepbuild_sdk_2) for more information. And these steps are different from those on *nix.

Phpbrew follows the steps of building php on *nix, so it's why it cannot be used on Windows. And even [the mannual](http://php.net/manual/bg/install.windows.building.php) indicates cygwin can be used, but in fact it can't. PHP ITSELF CANNOT BE COMPILED THROUGH CYGWIN, for now.
