### ISSUE TITLE
system wide install

### ISSUE THREAD

**Issue by Geniks** [phpbrew/phpbrew#875]
trying to make an install script to install a php version, system-wide
here is the part of the script
`curl -L -O https://github.com/phpbrew/phpbrew/raw/master/phpbrew
chmod +x phpbrew
mv phpbrew /bin/phpbrew

phpbrew init
export PHPBREW_ROOT=/opt/phpbrew      # php dist files and build files are stored here
export PHPBREW_HOME=/root/.phpbrew    # your configuration files.
echo "export PHPBREW_ROOT=/opt/phpbrew" >> ~/.phpbrew/init
echo "export PHPBREW_HOME=/root/.phpbrew" >> ~/.phpbrew/init
source ~/.phpbrew/bashrc

phpbrew install php-5.6.30 -- --with-mysql --enable-maintainer-zts --enable-sockets --with-openssl --with-pdo-mysql
phpbrew switch php-5.6.30
phpbrew ext install pthreads 2.0.10`

after that, writing `which php` links to
`/usr/bin/php`
and `phpbrew list`
`Please install at least one PHP with your prefered version.`

does someone have an idea how to make this work for ALL users ?
because the tutorial on the github is not working

thanks

**Comment by c9s** [comment]
After your run `phpbrew init` and install the loader in your bash profile, did you open a new shell to reload the profile ?

**Comment by Geniks** [comment]
no since its in a bash script but that's why I used
`source ~/.phpbrew/bashrc`
to reload variables

thanks for your answer

**Comment by c9s** [comment]
Try

    eval $(phpbrew env)
    phpbrew rehash

**Comment by Geniks** [comment]
Where do you want I try that ?
I tried after the script I made, so the eval returns nothing and for the rehash :
`phpbrew rehash
Did you mean 'bash'? [Y/n] n
Command rehash not found. available commands are: help, zsh, bash, meta, compile, archive, github:build-topics, app, init, known, install, list, use, switch, each, config, info, env, extension, variants, path, cd, download, clean, update, ctags, fpm, list-ini, self-update, remove, purge, off, switch-off

Please try the command below to see the details:

        /bin/phpbrew help
`

**Comment by c9s** [comment]
@Geniks it shows the message because you didn't load the phpbrew bash function, and so the executed command in the phar file itself, not the bash function.

the rehash command is actually a bash function.
