### ISSUE TITLE
Apply style-ci only on master

### ISSUE THREAD

**Issue by c9s** [phpbrew/phpbrew#878]
Hi @jhdxr 

Would you mind if we just apply style-ci on master?

Since I will be working on new branch and commit frequently, the notification emails are pretty annoying.

I used to commit a lot and then apply php-cs-fixer at one time.

**Comment by jhdxr** [comment]
Sure. However I checked the docs of styleci, there is only [a page](https://styleci.readme.io/docs/excluding-branches) about excluding branches, and it seems we cannot make disabled as default seeting while enabling on the master. So I suggest you disable styleci on the branch which you are working on. You can disable it at https://styleci.io/repos/2468290.

btw, there is also some options about email notification, see [here](https://styleci.readme.io/docs/notification-emails-2)

**Comment by jhdxr** [comment]
I've disabled styleci on develop and 2.0, but I guess you need to disable it again if you create a new branch.

**Comment by c9s** [comment]
Oh ok thanks!

xiami <notifications@github.com>於 2017年5月18日 週四，01:31寫道：
