### ISSUE TITLE
➜  ~ phpbrew #WARNING: it seems you are running PHPBrew under MacOS 10.11 or above with rootless enabled. it's recommended turn off rootless before your continue, or you may experience some issues.

### ISSUE THREAD

**Issue by xujiajun** [phpbrew/phpbrew#879]
### Output

```
➜  ~ phpbrew
#WARNING: it seems you are running PHPBrew under MacOS 10.11 or above with rootless enabled. it's recommended turn off rootless before your continue, or you may experience some issues.
```

### Expected Result

```
no WARNING
```

### Command

curl -L -O https://github.com/phpbrew/phpbrew/raw/master/phpbrew
chmod +x phpbrew
sudo mv phpbrew /usr/local/bin

### Platform

OS:

OS X 10.12.5 

ps:

➜  ~ csrutil status
System Integrity Protection status: disabled.

please give me some help.thanks

**Comment by mountpoint** [comment]
The same issue. Need to fix it.

**Comment by bikashrai** [comment]
I have got the same issue. anybody have any updates?

**Comment by akoel** [comment]
Same issue here. Why are not more having this issue or signalling this?

**Comment by mountpoint** [comment]
@c9s Do you see this problem?

**Comment by wesleyvicthor** [comment]
same annoying issue!

**Comment by SpikeShape** [comment]
I am getting this message on OS X 10.10.5.

**Comment by ram0l** [comment]
Same here .. brand new MacOS 10.12.6 (16G29)

**Comment by wdeer** [comment]
Same here .. MacOS 10.13

**Comment by leehblue** [comment]
Same here - MacOS 10.13

**Comment by ramsey** [comment]
I'm having the same issue on macOS 10.13.1.

**Comment by sleepm** [comment]
For fish shell users, add following lines to your ~/.config/fish/config.fish file:

source ~/.phpbrew/phpbrew.fish

i just run this command, forget add it..
solved..

**Comment by wujunze** [comment]
I am getting this message on OS X 10.13.2
