### ISSUE TITLE
phpbrew init on Ubuntu 16 & 17.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [phpbrew/phpbrew#886]
PHP Brew init not working on new ubuntu 17, found this link with instructions on getting it to work as php5 no longer in apt-get.

https://coderwall.com/p/hguzxa/phpbrew-on-ubuntu-16-04-php7

I will do a paste of the text on the page linked above just in-case.

When installing PHPBrew on a brand spanking new setup of ubuntu 16.04 the requirements page (that explains for php5) is not very handy to get things started smoothly. This is a minimalist setup you can use in order to install a +default variant of php7 via PHPBrew

```bash
sudo apt-get update
sudo apt-get install php7.0 php7.0-curl php7.0-json php7.0-cgi
sudo apt-get install php7.0-fpm autoconf automake libxml2-dev libcurl4-openssl-dev libssl-dev openssl gettext libicu-dev libmcrypt-dev libmcrypt4 libbz2-dev libreadline-dev gettext build-essential libmhash-dev libmhash2 libicu-dev libxslt-dev
phpbrew install php-7.0.9 +default+mcrypt+zlib+sockets+soap+mhash+fpm+openssl
```

**Comment by morozov** [comment]
@LiamKarlMitchell the dependencies for Ubuntu 16.04 are listed in [wiki](https://github.com/phpbrew/phpbrew/wiki/Requirement#ubuntu-1604) (looks like they are borrowed from the list you provided). Thanks for the heads up.
