### ISSUE TITLE
I cannot find readline.h

### ISSUE THREAD

**Issue by oNdsen** [phpbrew/phpbrew#889]
### Output

```
checking for libedit readline replacement... yes
configure: error: Please reinstall libedit - I cannot find readline.h
```

### Expected Result

compiled php version

### Command

```
$ phpbrew --debug install 7.0 +everything
```

### Build Log

```
https://gist.github.com/oNdsen/f6231c0aef5a7492427a0689219fd518
```

### Platform

OS:
Debian GNU/Linux 8 (jessie)

Running PHP:
doesnt matter. tried with 5.6, 7.0, 7.1

Installing PHP:
tryed each one of the following versions:
7.1.7, 7.0.21, 7.0.20, 5.6.31

### Comment

this problem exists on 3 different debian servers. each server has allready compiled php versions installed (on january, via same phpbrew installation).
what ive done:

```
$ phpbrew update
$ phpbrew --debug install 7.0 +everything
```

so, readline is installed. i just cannot compile a new php version after i updated phpbrew (doesnt matter with or without extensions).

```
root@web01:~# apt-get install libedit2 libreadline6 libreadline6-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libedit2 is already the newest version.
libreadline6 is already the newest version.
libreadline6-dev is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.
```

```
root@web01:~# find / -name "readline.h"
/usr/include/readline/readline.h

```

**Comment by mzalazar** [comment]
Try:
apt-get install libedit-dev

**Comment by ZeeCoder** [comment]
This fixed it for me: https://stackoverflow.com/questions/23085076/readline-readline-h-file-not-found#23085474

Run `sudo apt-get install libreadline-dev `

**Comment by arifikhsan** [comment]
so many errors

**Comment by mclucario** [comment]
Under Fedora 29 you need "readline-devel" to build. Maybe we should add that to the requirements since the default phpbrew install 7.0 includes that extension.

**Comment by auzzieplague** [comment]
on **OSX** installed missing dependency through brew
**brew install readline**
