### ISSUE TITLE
Error: Install 7.0.0, 7.0.2, 7.0.21 always return PHP 7.3.0-dev

### ISSUE THREAD

**Issue by ngocdb** [phpbrew/phpbrew#890]
I am using PhpBrew (phpbrew 1.22.5) on Ubuntu 14.04

I use the below command to install php 7 (for example 7.0.0, 7.0.2, 7.0.21)

> phpbrew install next as php-7.0.0 +default +dbs +apxs2 +gd +iconv +intl +mcrypt +soap +mb

Everything goes well & the install finished. 

But if I check the version, it always is PHP 7.3.0-dev

> 
> $ php -v
> PHP 7.3.0-dev (cli) (built: Jul 27 2017 15:55:34) ( NTS )
> Copyright (c) 1997-2017 The PHP Group
> Zend Engine v3.3.0-dev, Copyright (c) 1998-2017 Zend Technologies

Check in /usr/lib/apache2/modules/, there is a new so file named libphp7.3.0-dev.so

====>
I want to get the exact version as I use with phpbrew, what is the problem ? Please help....

**Comment by jhdxr** [comment]
if you want to install php 7.1, you should use `phpbrew install 7.1`
`phpbrew install next as php-7.0.0` means you want to install php from git repo, containing the lasted code, which is php 7.3 now, and give it an alias called php-7.0.0

btw, the latest phpbrew is 1.22.8, maybe you need `phpbrew selfupdate` first.

**Comment by ngocdb** [comment]
Yes, @jhdxr  you are right, thank you a lot
