### ISSUE TITLE
"struct flock" error during installation of PHP next (7.2)

### ISSUE THREAD

**Issue by johnbillion** [phpbrew/phpbrew#891]
### Output

```
Error: Configure failed:
The last 5 lines in the log file:
checking for mmap() using shm_open() shared memory support... no

checking for mmap() using regular file shared memory support... no

checking "whether flock struct is linux ordered"... "no"

checking "whether flock struct is BSD ordered"... "no"

configure: error: Don't know how to define struct flock on this system, set --enable-opcache=no
```

### Expected Result

Installation succeeds :-)

### Command

    phpbrew --debug install next as next

### Build Log

https://gist.github.com/johnbillion/f158af43a433e961ecfe9026344527f6

### Platform

OS: macOS 10.12.3 (16D32)

Running PHP: `7.1.0`

Installing PHP: `next`

**Comment by jhdxr** [comment]
you need the corresponding libs to build php with those extensions.
you may refer to the relative bugs on php.net, for example:
https://bugs.php.net/bug.php?id=65423
https://bugs.php.net/bug.php?id=69827

I'm closing this issue since it's not a problem related to phpbrew it self, but if you have more ideas about it, feel free to reopen this issue.

**Comment by johnbillion** [comment]
Thanks for the reply.

You'll note that I've not specified any extensions during installation, and I have already installed the [PHPBrew Requirements](https://github.com/phpbrew/phpbrew/wiki/Requirement).

Is there a missing requirement for PHP 7.2? All other PHP version, including 7.1, install without a problem.

**Comment by jhdxr** [comment]
Phpbrew will install several extensions for the minimum requirements if you don't specify any variant. You can find out which extensions are installed from you log:

>  You haven't set any variant. A default set of extensions will be installed for the minimum requirement:
	[bcmath, bz2, calendar, cli, ctype, dom, fileinfo, filter, ipc, json, mbregex, mbstring, mhash, pcntl, pcre, pdo, phar, posix, readline, sockets, tokenizer, xml, curl, zip, openssl, opcache, fpm, gettext, hash, exif, ftp, mysql, mcrypt]
	Please run 'phpbrew variants' for more information.

>./configure '--cache-file=/Users/john/.phpbrew/cache/config.cache' '--prefix=/Users/john/.phpbrew/php/next' '--with-config-file-path=/Users/john/.phpbrew/php/next/etc' '--with-config-file-scan-dir=/Users/john/.phpbrew/php/next/var/db' '--disable-all' '--enable-phar' '--enable-session' '--enable-short-tags' '--enable-tokenizer' '--with-pcre-regex' '--with-zlib=/usr' '--enable-bcmath' '--with-bz2=/usr' '--enable-calendar' '--enable-cli' '--enable-ctype' '--enable-dom' '--enable-fileinfo' '--enable-filter' '--enable-shmop' '--enable-sysvsem' '--enable-sysvshm' '--enable-sysvmsg' '--enable-json' '--enable-mbregex' '--enable-mbstring' '--with-mhash=/usr/local' '--enable-pcntl' '--with-pcre-regex' '--with-pcre-dir=/usr/local' '--enable-pdo' '--enable-phar' '--enable-posix' '--with-readline=/usr/local/opt/readline' '--enable-sockets' '--enable-tokenizer' '--enable-dom' '--enable-libxml' '--enable-simplexml' '--enable-xml' '--enable-xmlreader' '--enable-xmlwriter' '--with-xsl' '--with-libxml-dir=/usr/local/opt/libxml2' '--with-curl=/usr' '--enable-zip' '--with-openssl=/usr/local/opt/openssl' '--enable-opcache' '--enable-fpm' '--with-gettext=/usr/local/opt/gettext' '--enable-hash' '--enable-exif' '--enable-ftp' '--with-mysqli=mysqlnd' '--with-pdo-mysql=mysqlnd' '--with-mysql-sock=/tmp/mysql.sock' '--with-mcrypt=/usr/local' '--with-pear=/Users/john/.phpbrew/php/next/lib/php' >> /Users/john/.phpbrew/build/next/build.log 2>&1
	
If you want to build a php without any extension, you can try `phpbrew install xxxx +neutral`, which will pass `--disable-all` to `configure`.


And yes, the requirements may change with the update of php or OS, especially for a version still under development.
