### ISSUE TITLE
Install errors showing when running php command line

### ISSUE THREAD

**Issue by jreason** [phpbrew/phpbrew#893]
Hi,

I have a strange issue.
Upon installing some extensions i had some problems.
I have since managed to get these extensions installed and they are now working correctly.

However, everytime i run any php command using command line, i am presented with these error messages before i get the result of the command line.

Any ideads?

php -v
**PHP Warning:  Module 'ftp' already loaded in Unknown on line 0

Warning: Module 'ftp' already loaded in Unknown on line 0
PHP Warning:  PHP Startup: Invalid library (maybe not a PHP library) 'pdo.so' in Unknown on line 0

Warning: PHP Startup: Invalid library (maybe not a PHP library) 'pdo.so' in Unknown on line 0**
PHP 7.1.4 (cli) (built: Jun  6 2017 10:32:25) ( ZTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

**Comment by jhdxr** [comment]
because you have already compiled these extensions into the php binary (static extension), then you load the same extensions (shared extensions) using ini options.

**Comment by jreason** [comment]
thanks @jhdxr so how do i go about fixing this?

**Comment by morozov** [comment]
@jreason you can try disabling the shared extensions: `phpbrew ext disable ftp`, `phpbrew ext disable pdo`.

**Comment by jreason** [comment]
@morozov thanks, thats done the trick!
