### ISSUE TITLE
How to use php5.3 on Ubuntu 16.04 for apache2 

### ISSUE THREAD

**Issue by MurKit** [phpbrew/phpbrew#894]
I have built php5.3 on Ubuntu 16.04 with +apxs2

My file /etc/apache2/mods-available/php5.load contains a line:

LoadModule php5_module        /usr/lib/apache2/modules/libphp5.3.24.so

But how do I tell apache to use this file? Or am I missing something? In the /etc/apache2/mods-available directory there are files:

php5.6.conf
php5.6.load
php5.load
php7.0.conf
php7.0.load
php7.1.conf
php7.1.load
php7.load

I can easily switch between php version like this:

sudo a2dismod php7.0 ; sudo a2enmod php5.6 ; sudo service apache2 restart

If I use sudo a2enmod php5 and restart apache, I just get blank pages. During the restart, I have some errors in /var/log/apache2/error.log:

[Thu Aug 17 14:51:23.080615 2017] [mpm_prefork:notice] [pid 23406] AH00169: caught SIGTERM, shutting down
[Thu Aug 17 14:51:24.241579 2017] [mpm_prefork:notice] [pid 25009] AH00163: Apache/2.4.18 (Ubuntu) PHP/5.3.24 configured -- resuming normal operations
[Thu Aug 17 14:51:24.241658 2017] [core:notice] [pid 25009] AH00094: Command line: '/usr/sbin/apache2'

sudo phpbrew install 5.3.29  +bz2 +calendar +cli +ctype +dom +iconv +fileinfo +filter +ipc +json +mbregex +mbstring +mhash +mcrypt +pcntl +pcre +pdo +phar +posix +readline +sockets +tokenizer +xml +curl +zip +mysql +debug +apxs2

### Build Log
https://gist.github.com/MurKit/c941bc229d53fcd650724985c66fceb3

**Comment by MurKit** [comment]
Ok I have found the solution. Strange it is mentioned only in one place on Stackoverflow.

I have added a line to the end of /etc/apache2/mods-available/php5.load file, so it looks like this:

LoadModule php5_module        /usr/lib/apache2/modules/libphp5.3.24.so
AddType application/x-httpd-php .php

**Comment by morozov** [comment]
@MurKit thank you for reporting this. I've updated the [wiki page](https://github.com/phpbrew/phpbrew/wiki/Cookbook#apache2-support).
