### ISSUE TITLE
Problem with each ext install

### ISSUE THREAD

**Issue by MurKit** [phpbrew/phpbrew#895]
$ phpbrew each 'ext install gd -- --with-libdir=lib/i386-linux-gnu --with-gd=shared --enable-gd-native-ttf --with-freetype-dir=/usr --with-jpeg-dir=/usr --with-png-dir=/usr --with-xpm-dir=/usr'
Run ext install gd -- --with-libdir=lib/i386-linux-gnu --with-gd=shared --enable-gd-native-ttf --with-freetype-dir=/usr --with-jpeg-dir=/usr --with-png-dir=/usr --with-xpm-dir=/usr for php-[5.4.44, 5.3.24]. Proceed? [Yes/no]> Y
PHP Fatal error:  Class 'PhpBrew\PhpBrew' not found in phar:///usr/local/bin/phpbrew/src/PhpBrew/Command/EachCommand.php on line 55

Fatal error: Class 'PhpBrew\PhpBrew' not found in phar:///usr/local/bin/phpbrew/src/PhpBrew/Command/EachCommand.php on line 55

Ubuntu 16.04 Using php5.3.24

**Comment by morozov** [comment]
@MurKit the `each` command will be significantly reworked in the next release. Please see #888 for details. You can try it by checking out the "development" branch.

**Comment by morozov** [comment]
Closing since #888 is now released.
