### ISSUE TITLE
dependency problem

### ISSUE THREAD

**Issue by jhdxr** [phpbrew/phpbrew#896]
there are several problems in composer.json:
1. universal/universal requires php>=5.4
2. doctrine/inflector v1.2.0 requires php ^7.0 (inherit from corneltek/cliframework 4.0.x-dev)

@c9s maybe we should revert the changes to `composer.json`?

**Comment by morozov** [comment]
It's actually a good question whether PHPBrew should be able to run on ancient PHP versions. The only reason to that I can think of is that when you are on PHP 5.3, you should be able to `phpbrew use` some other version. And at this moment, PHPBrew will be run by PHP 5.3. If we can somehow make sure that the `phpbrew` command is always executed by a compatible `php` binary, we can bump the requirements. It will help writing cleaner code, using modern dependencies, and so on.

Thoughs?

**Comment by jhdxr** [comment]
Currently we ask user to execute `phpbrew.phar` directly, which depends on the environment php obviously. We may install a minimum build-in php, and write a `phpbrew.sh` to call the phar with the build-in php. The advantages are that phpbrew itself doesn't need to support old php any more, and a missing extension (json for example) wouldn't be a problem any more as well. But before doing this, we have to make sure the build-in php wouldn't affect users' environment. and we have to decide which version / type(build from source? binary?) of php we would choose as the build-in php.

**Comment by morozov** [comment]
If it was possible to compile a php binary completely statically, we could build the latest stable version and (optionally?) shipt it with PHPBrew.

On the other hand, most of the modern Linux distributions have at least PHP 7.0 in their repositories, and it's any way needed to start PHPBrew for the first time. We can have a small shell wrapper which knows about PHPBrew-managed versions and can find the binary to work through.

**Comment by c9s** [comment]
we can do that. Or I can loweer the requirement of the universal package

**Comment by c9s** [comment]
Installing Prebuilt phps is something I wanted to do for a long time :p

**Comment by morozov** [comment]
Or, what if we do the following:
1. Identify the set of commands which should be able to execute on a non-supported version of PHP (ideally, without PHP at all) like `use`, `use $version` and `version`.
2. Implement them without relying on the framework or even in bash.
3. For the rest of commands, check if the PHP version is compatible in runtime.

For the reference, see https://github.com/sebastianbergmann/phpunit/issues/2563.

**Comment by jhdxr** [comment]
currently we already have a set of commands in pure shell commands, but to be honest I don't like to move more commands into shell, because I'm a fan of fish-shell, so whenever the bash script changes, I have to made the corresponding changes as well. o(╯□╰)o

**Comment by jhdxr** [comment]
@c9s If you don't mind please lower the version on the master branch, to make the ci green. and we can do the prebuilt things on develop branch, for a major release.

**Comment by c9s** [comment]
@jhdxr ok I will handle this

**Comment by c9s** [comment]
the doctrine/inflector is actually required by codegen with "*", so I think it could be restricted on the phpbrew side.

**Comment by morozov** [comment]
@c9s mind looking at #912?
