### ISSUE TITLE
extension install stack

### ISSUE THREAD

**Issue by aklizrum** [phpbrew/phpbrew#900]
after install php5.6.23
```
phpbrew install 5.6.23 +default+pdo+mysql+intl+icu+gd+iconv -- --with-openssl=$HOME/.openssl-1.0
```

i try to install some extension: xdebug, memcached, but nothing happens
```
phpbrew ext install xdebug                                                                      
Downloading https://pecl.php.net/rest/r/xdebug/stable.txt via curl extension
```
OS: Archlinux

**Comment by jhdxr** [comment]
please paste the full log.

 and if these two logs are everything you got, then you may try other downloader, for example
`phpbrew ext install --downloader=wget xdebug`

**Comment by aklizrum** [comment]
With `--downloader=wget` extensions are starting to download. Thanks!
