### ISSUE TITLE
5.3.29 Wont Install on OSX El Cap

### ISSUE THREAD

**Issue by sheanhoxie** [phpbrew/phpbrew#901]
### Output

```
Error: Make failed:
The last 5 lines in the log file:
ext/intl/intl_convert.h:28:6: note: candidate function not viable: no known conversion from 'const char16_t *' to 'const UChar *' (aka 'const int *') for 3rd argument

void intl_convert_utf16_to_utf8(
     ^

2 warnings and 8 errors generated.

make: *** [ext/intl/msgformat/msgformat_helpers.lo] Error 1
```

### Expected Result

```
Congratulations! Now you have PHP with 5.3.29 as php-5.3.29
```

### Command

```
phpbrew install 5.3.29 +default +openssl +intl +fpm
```

### Build Log

[Build Log Gist](https://gist.github.com/sheanhoxie/c53476baef0c02a43ed9a30a86f06934)

### Platform

OS: OS X 10.11.6

Running PHP: 5.5.38

Installing PHP: 5.3.29

**Other Notes**
I've already successfully installed 7.1.9, 7.0.12, and 5.6.31

**Comment by jhdxr** [comment]
phpbrew compiles php from the souce. I guess some header files (which php depends on) are too new for the old php.

**Comment by sheanhoxie** [comment]
Where can I start looking regarding the header files? I'd like to see if I can find a workaround or fix for this, but I dont even know where to begin looking

**Comment by augustohp** [comment]
@sheanhoxie Take a look at issue #899, it is probably a problem with a [*breaking change* in `icu4c` version `59.*`][1] - meaning you want the previous version installed to compile PHP.

[1]: https://github.com/Homebrew/homebrew-php/issues/4383

I don't know if the following will work for you, but you should do something like this:

```
$ echo "Unlinks bad icu4c ... " && brew unlink icu4c
$ echo  "Installs good icu4c along existing one" && brew install --force https://raw.githubusercontent.com/ilovezfs/homebrew-core/d2485c72643aa7e6aec0da9ced3aa66401ae42ce/Formula/icu4c.rb
$ [[ 2 -eq "$(brew info icu4c | grep Cellar | grep 58 | wc -l)" ]] && echo "Success" || echo "Failure"
$ echo "Your install command ..."
$ phpbrew install 5.3.29 +default +openssl +intl +fpm -- --with-icu-dir=/usr/local/Cellar/icu4c/58.2/

**Comment by sheanhoxie** [comment]
@augustohp Thanks for the help. Unfortunately it didnt work. Here's my logs in case that helps

**Errors**
.phpbrew/build/php-5.3.29/Zend/zend_language_parser.y:48.1-5: invalid directive: `%code'

.phpbrew/build/php-5.3.29/Zend/zend_language_parser.y:48.7-14: syntax error, unexpected identifier

make: *** [.phpbrew/build/php-5.3.29/Zend/zend_language_parser.c] Error 1

[Gist of build.log](https://gist.github.com/sheanhoxie/642cecefe6f2b80c27310521532f9500)

**Comment by steveoliver** [comment]
@sheanhoxie Did you ever get 5.3.29 installed?

**Comment by sheanhoxie** [comment]
@steveoliver No, trying to get the environment setup using Docker atm

**Comment by jakesyl** [comment]
Can we apply the same fix to phpbrew that was applied to fix  https://github.com/Homebrew/homebrew-php/issues/4383
