### ISSUE TITLE
tar: Cannot connect to C: resolve failed Error: Extract failed on Window

### ISSUE THREAD

**Issue by samsoft00** [phpbrew/phpbrew#902]
### Output

```
==] 14.32/14.32MB 100%
===> Extracting C:/Users/Swifta System/.phpbrew\distfiles\php-5.6.30.tar.bz2 to C:/Users/Swifta System/.phpbrew\build\tmp.1505004305\php-5.6.30
tar: Cannot connect to C: resolve failed
Error: Extract failed:

```

### Command

Paste your phpbrew install command here (be sure to install with `--debug` flag, e.g. `phpbrew --debug install`)

    phpbrew --debug install php-7.1

### Platform

OS:

    e.g. Window 10

Running PHP: 5.6.30

Installing PHP: 7.1

tar: Cannot connect to C: resolve failed Error: Extract failed on Window, please what can i do? Thanks

**Comment by jhdxr** [comment]
sorry, phpbrew only works on *nix only. see #874 and #236 for more information.
You may try it with cygwin or WSL, but I still doubt the compiling of php itself will fail.
