### ISSUE TITLE
System wide installation - /opt/phpbrew/bashrc not found

### ISSUE THREAD

**Issue by iamnimnul** [phpbrew/phpbrew#903]
Hi there,

I am trying to install System wide phpbrew using guide from https://github.com/phpbrew/phpbrew/wiki/Installing-PHPBrew-into-System-wide-Environment

I am following instructions and have some questions:

1)
> Now export phpbrew paths to your desired paths, edit your ~/.phpbrew/bashrc
> export PHPBREW_ROOT=/opt/phpbrew      # php dist files and build files are stored here
> export PHPBREW_HOME=/root/.phpbrew    # your configuration files.

It's not clear if it should be added at the top or bottom of the file. Any difference?

2. 
> Now your php(s) will be installed under the /opt/phpbrew path, to allow your system users to use php(s) built by phpbrew, you need to export PHPBREW_ROOT and PHPBREW_HOME environment in /etc/bashrc or in /etc/profile.d/phpbrew for bash users, before they load the phpbrew/bashrc file.
> export PHPBREW_ROOT=/opt/phpbrew
> export PHPBREW_HOME=$HOME/.phpbrew
> source /opt/phpbrew/bashrc

When I log in as any user on the machine I can see `-bash: /opt/phpbrew/bashrc: No such file or directory` just after MOTD. 
Looks like file `/opt/phpbrew/bashrc` is not created at any stage and there are no instructions how to initialise it.

### Output

```
-bash: /opt/phpbrew/bashrc: No such file or directory
```

### Platform

OS:
Ubuntu 16.04

Running PHP: 
PHP 7.0.22-0ubuntu0.16.04.1

**Comment by ryan-lange** [comment]
Initializing using the `--root` argument no longer seems to fix this issue. `/opt/phpbrew/bashrc` still does not exist.

**Comment by peter279k** [comment]
I use the latest stable PHPBrew version and it seems the `--root` option usage is fixed. The issue will be closed.
