### ISSUE TITLE
Error PHP 5.2.17 with oci8

### ISSUE THREAD

**Issue by rduarte** [phpbrew/phpbrew#904]
I'm running phpbrew in a Vagrant box with Ubuntu 12.04 32bits to run a old system developed using PHP 5.2.X and Oracle with oci8 module.

After a fresh install of Ubuntu and install some dev/build packages, I got some errors installing this version of PHP, which ones I fixed with those patches (attached).

[disable_sslv2.patch.txt](https://github.com/phpbrew/phpbrew/files/1298137/disable_sslv2.patch.txt)
[gmp.patch.txt](https://github.com/phpbrew/phpbrew/files/1298138/gmp.patch.txt)
[zip.patch.txt](https://github.com/phpbrew/phpbrew/files/1298139/zip.patch.txt)

Ok, fine!

Now when I tried to compile with oci8 module:
`sudo phpbrew install php-5.2.17 +default +apxs2=/usr/bin/apxs2 -- --with-oci8=instantclient,/opt/oracle/instantclient_12_2`

I got this error:
checking PHP version... 5.2.17, ok
checking size of long int... 4
checking Oracle Instant Client directory... /opt/oracle/instantclient_12_2
checking Oracle Instant Client SDK header directory... /opt/oracle/instantclient_12_2/sdk/include
checking Oracle Instant Client version... configure: error: Oracle Instant Client libraries not found

But, the files are there:
`$ ls /opt/oracle/instantclient_12_2/`
adrci         genezi                 libclntsh.so       libnnz12.so  libocci.so.12.1  libocijdbc12.so  liboramysql12.so  sdk      xstreams.jar
BASIC_README  libclntshcore.so.12.1  libclntsh.so.12.1  libocci.so   libociei.so      libons.so        ojdbc8.jar        uidrvci

Any suggestions?

**Comment by morozov** [comment]
@rduarte I wouldn't be surprised if the oci8 extension from PHP 5.2 was incompatible with Oracle client 12.2 to the extent that it cannot detect its version. There's ~11 years between their release dates:
```
checking Oracle Instant Client version... configure: error: Oracle Instant Client libraries not found
```
I'd suggest trying to install the same ancient Oracle libraries or installing PHP without the OCI extension and then debugging the autogenerated `configure` script:
```
$ phpbrew install php-5.2.17 +default +apxs2=/usr/bin/apxs2
$ phpbrew use php-5.2.17
$ phpbrew ext install oci8 -- --with-oci8=instantclient,/opt/oracle/instantclient_12_2
```
The `configure` script will be in the `$HOME/.phpbrew/build/php-5.2.17/ext/oci8` directory. You can try finding your error message there and seeing why exactly it's displayed.

**Comment by rduarte** [comment]
I could not use `phpbrew ext install oci8`. Every time I used I got a lot of interrogation chars (???????).

I installed oci8 module with pecl:
`echo 'instantclient,/opt/oracle/instantclient_12_2' | pecl install oci8-1.4.10`
