### ISSUE TITLE
Probably not related but there is a virus problem

### ISSUE THREAD

**Issue by erdemece** [phpbrew/phpbrew#910]
Hi, earlier I installed phpbrew on bash on windows. then I found tweaking.com installed itself on my computer. then I did a malwarebyte scan and it found this

https://imgur.com/a/kjefg

Any idea how is this possible?

Thanks.

**Comment by morozov** [comment]
@erdemece any reason you think it's because of PHPBrew? Did you find the malware immediately after installing it?

**Comment by jhdxr** [comment]
to be honest, I think it's just because the file is recently created, and got affected.

**Comment by jhdxr** [comment]
I'm closing this issue since It's has been answered [here](https://github.com/Microsoft/BashOnWindows/issues/2508#issuecomment-330735557)

This is just a false-postive.
