### ISSUE TITLE
Let phpbrew know the pitfalls

### ISSUE THREAD

**Issue by chippyash** [phpbrew/phpbrew#914]
This is a feature request, driven off the back of https://github.com/phpbrew/phpbrew/issues/749

Simply put: Phpbrew needs to 'know' the common pitfalls of installing extra extensions.

It works fine if you install everything at the start.  But woe betide you if you then try to install extra extensions on back versions.

Maybe the answer is that for back versions we just install everything, but that means keeping compatible back versions available.

Anyway, the point is that 'how do I install mysql support' has come up enough times, with common pitfalls that it needs addressing in the phpbrew code base.

**Comment by peter279k** [comment]
The issue is outdated and it's not necessary to do that. It will be closed.

The developers should know extra pitfall extensions from the official PHP website because there're many extensions to check.

I think we don't have to maintain the huge extension lists to resolve above issue.
