### ISSUE TITLE
phpbrew + blackfire.io?

### ISSUE THREAD

**Issue by reafle** [phpbrew/phpbrew#922]
Hi, I got a little bit lost while trying to install [blackfire.io](https://blackfire.io/docs/up-and-running/installation). 

They have their own repositories for most common OSes, and also there seems to be a way to install it manually, but:

```
If you need to install the stack manually because every other installation methods 
failed, please contact us and mention your platform and PHP version.

In the meantime, continue the following steps and you will be guided 
through manual installation.

You are strongly advised to use the other installation methods available if possible as 
they give you seamless upgrade methods.
```

Is this achievable with phpbrew extension manager?

**Comment by morozov** [comment]
@reafle to install the extension, you can:
1.  Start from https://blackfire.io/docs/up-and-running/installation#install-probe-.
2. Download the extension by choosing "Linux Binary".
3. Rename the downloaded file to `blackfire.so` and move it to the extension directory.
5. Enable the extension (make sure you're using PHPBrew 1.23 or newer).

In my case it is:
```
$ wget https://packages.blackfire.io/binaries/blackfire-php/1.18.0/blackfire-php-linux_amd64-php-71.so
$ mv blackfire-php-linux_amd64-php-71.so ~/.phpbrew/php/php-7.1.10/lib/php/extensions/no-debug-non-zts-20160303/blackfire.so
$ phpbrew ext enable blackfire
```

**Comment by reafle** [comment]
Great, thanks! Version 1.23 rocks!

I wonder Is there a non-hacky way to map the version of `blackfire-php-linux_amd64-php-71.so` to `php-7.1.10` so that the correct extension retrieval could be automated. 

Would it be plausible to someday have blackfire installation through phpbrew via `ext install` or maybe even `app get` ?

**Comment by jhdxr** [comment]
I'm afraid not. `app get` is used to install something written in pure php, and `ext install` is for extension on [pecl.php.net](//pecl.php.net), which requires open-source.
