### ISSUE TITLE
Can't build PHP 5.2.17: mysql_config not found

### ISSUE THREAD

**Issue by skerit** [phpbrew/phpbrew#932]
I'm unable to build php 5.2.
5.3 does work, but the old site I have to run doesn't work under it.

### Output

```
===> phpbrew will now build 5.2.17
===> Loading and resolving variants...
Checking distribution checksum...
Checksum matched: b27947f3045220faf16e4d9158cbfe13
===> Distribution file was successfully extracted, skipping...
Found existing Makefile, running make clean to ensure everything will be rebuilt.
You can append --no-clean option after the install command if you don't want to rebuild.
===> Running make clean: /usr/bin/make -C '/home/skerit/.phpbrew/build/php-5.2.17' --quiet 'clean'
===> Checking patches...
Checking patch for replace apache php module name with custom version name
Found existing build.log, renaming it to /home/skerit/.phpbrew/build/php-5.2.17/build.log.1511819935
===> Configuring 5.2.17...


Use tail command to see what's going on:
   $ tail -F /home/skerit/.phpbrew/build/php-5.2.17/build.log


Error: Configure failed:
The last 5 lines in the log file:
checking for mysql_close in -lmysqlclient... yes

checking for MySQLi support... yes

checking whether to enable embedded MySQLi support... no

mysql_config not found

configure: error: Please reinstall the mysql distribution

Please checkout the build log file for more details:
	 tail /home/skerit/.phpbrew/build/php-5.2.17/build.log

```

### Command

    phpbrew install --old 5.2.17 +default +fpm+cgi+gd+pdo+mysql +openssl=shared -- --with-openssl-dir=/usr/include/openssl --enable-force-cgi-redirect --enable-fastcgi 

### Platform

OS: Ubuntu 16.04

**Comment by morozov** [comment]
```
mysql_config not found

configure: error: Please reinstall the mysql distribution
```
Could you double-check if `mysql_config` is actually installed? If not, `apt-get install libmysqlclient-dev` should help.

**Comment by alpipego** [comment]
The only thing that worked for me was:

```
~/.phpbrew/build/php-5.2.17$ make
~/.phpbrew/build/php-5.2.17$ make install
``` 

after that, I can change to `5.2.17`.

**Comment by alpipego** [comment]
@skerit there is some more information in https://github.com/phpbrew/phpbrew/issues/492

**Comment by alpipego** [comment]
I took a look at how automattic does it: https://github.com/Automattic/jetpack/blob/master/tests/install-php-phpunit.sh#L52-L57

Download these two patches:
https://raw.githubusercontent.com/Automattic/jetpack/master/tests/patches/openssl.patch
https://raw.githubusercontent.com/Automattic/jetpack/master/tests/patches/node.patch

(if you need `fpm`, download and apply the fpm patch as well: https://php-fpm.org/downloads/php-5.2.17-fpm-0.5.14.diff.gz).

and apply them (update the paths if necessary - and of course check the variants needed):

```
phpbrew install --patch ~/.phpbrew/build/node.patch --patch ~/.phpbrew/build/openssl.patch 5.2.17 +default+mysql+pdo+openssl -- --enable-spl --with-mysqli=/usr/bin/mysql_config --with-pdo-mysql=/usr
```

**Comment by peter279k** [comment]
Actually, the issue is outdated and it will be closed now.
