### ISSUE TITLE
Message in terminal  -bash: ~/.phpbrew/bashrc: No such file or directory.

### ISSUE THREAD

**Issue by MaximStrutinskiy** [phpbrew/phpbrew#935]
I have this message after removing phpbrew
` -bash: /home/andersen/.phpbrew/bashrc: No such file or directory `

**Comment by morozov** [comment]
When you set up PHPBrew, you should have added [PHPBrew initialization code](https://github.com/phpbrew/phpbrew#setting-up) `.bashrc`, `.profile` or some file like those. It may look like `source ~/.phpbrew/bashrc` or `. source ~/.phpbrew/bashrc`.

You need to find and remove it.

**Comment by MaximStrutinskiy** [comment]
I remove this folder "~/.phpbrew/bashrc"
Found one file ".bashrc", in "~/", but when remove - my php version (in terminal) is changing.

**Comment by morozov** [comment]
@MaximStrutinskiy you need to remove the `source ~/.phpbrew/bashrc` _line_ from your `.bashrc`, not the file itself.

> my php version (in terminal) is changing

What does it change to? If you want to remove PHPBrew, your PHP version will roll back to the system-installed one.

**Comment by MaximStrutinskiy** [comment]
Ty, it's help.
