### ISSUE TITLE
PHPBrew breaks when installing old PHP version (5.2.17)

### ISSUE THREAD

**Issue by Bazze** [phpbrew/phpbrew#94]
phpbrew seems to break totally when installing an old PHP version (I've only tested with 5.2.17 though).

I run the following command:
```
phpbrew install --old 5.2.17 +default
```

It succeeds, but then when trying to run phpbrew again I get the following message:
```
sebastian ~$ phpbrew help

Warning: Unexpected character in input:  '\' (ASCII=92) state=1 in /usr/bin/phpbrew on line 4

Warning: Unexpected character in input:  '\' (ASCII=92) state=1 in /usr/bin/phpbrew on line 4

Parse error: syntax error, unexpected T_STRING in /usr/bin/phpbrew on line 4
sebastian ~$
```
I've got the latest version of phpbrew and I'm using Ubuntu 12.10. When installing php-5.4.16 everything works fine. What could be the issue?

**Comment by blackakula** [comment]
@Fyb3roptik, I have the same issue. I want this to be fixed. Reopen please

**Comment by c9s** [comment]
phpbrew requires 5.3+ to run the phpbrew phar files, please use php 5.3 to run phpbrew.

Please note that you can build 5.2 with phpbrew, but you can't run phpbrew with php 5.2.

**Comment by blackakula** [comment]
@c9s, I understand this. The only versions that I need are 5.6 and 5.2. I've installed phpbrew for this purpose. But the only way to switch back from 5.2 is to delete `.phpbrew/init` file. Because phpbrew not working after switching to 5.2:

```
$ /usr/bin/php5 /usr/bin/phpbrew switch 5.6.6
You should not see this, if you see this, it means you didn't load the ~/.phpbrew/bashrc script, please check if bashrc is sourced in your shell.

**Comment by c9s** [comment]
ah, it's because the "phpbrew" is actually a shell function that executes phpbrew phar file. to solve this, we have to provide an option to inject the specified php path for running phpbrew.

**Comment by blackakula** [comment]
> provide an option to inject the specified php path for running phpbrew

It would be great! Thanks.

**Comment by c9s** [comment]
the fix would make sense, but I am currently working on other projects, might not have time to work on it in less than 3 month.. XD let's see if anyone would like to open a pull request for this. :)

**Comment by marcioAlmada** [comment]
Hi

I'll have some time for this today. Maybe we can add an alias that makes phpbrew always executed by system php?

```bash
PHPBREW_SYSTEMPHP=$(whereis -b php | cut -d' ' -f 2-2)
PHPBREW_PHAR=$(whereis -b phpbrew | cut -d' ' -f 2-2)
alias 'phpbrew'="$PHPBREW_SYSTEMPHP $PHPBREW_PHAR"
```

**Comment by marcioAlmada** [comment]
Let me know if above solution seems portable enough :smile:

**Comment by marcioAlmada** [comment]
Ok, we can't use an alias for obvious reasons - and passing system php by default breaks extension installer. But I have a workaround.

**Comment by marcioAlmada** [comment]
Wth 802a16f you can specify the php binary to run phpbrew:

```bash
PHPBREW_OVERRIDE_PHP=/usr/bin/php phpbrew
```

**Comment by marcioAlmada** [comment]
This shall be fixed now

**Comment by marcioAlmada** [comment]
Suggestion still welcome if somebody gets a better idea :)

**Comment by c9s** [comment]
@marcioAlmada++

**Comment by shinnya** [comment]
:+1:

**Comment by aamm19** [comment]
How can i install the "patch" for the php override.

Sorry for reviving old thread

**Comment by MisatoTremor** [comment]
@aamm19 (and others)
To fix a broken state you could temporarily edit ~/.phpbrew/bashrc
Find the function __phpbrew_update_config and alter the line
```sh
command $BIN env $VERSION >> "$PHPBREW_HOME/init"
```
to 
```sh
command /usr/bin/php5 $BIN env $VERSION >> "$PHPBREW_HOME/init"
```
Then execute
```sh
rm ~/.phpbrew/init
source ~/.phpbrew/bashrc
PHPBREW_OVERRIDE_PHP=/usr/bin/php5 phpbrew switch php-X.Y.ZZZ
```

Don't forget to revert the change made to ~/.phpbrew/bashrc
