### ISSUE TITLE
Could not resolve host: us1.php.net

### ISSUE THREAD

**Issue by sam452** [phpbrew/phpbrew#940]
### Output
Checking distribution checksum...
Checksum mismatch: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855 != f9ce3361ab99dce8f3f2fba663695ac9b18a3579bc8014dc280368d1577d87c4
Re-Downloading...
Downloading http://www.php.net/get/php-7.1.12.tar.bz2/from/this/mirror via curl extension
Redirecting to http://us1.php.net/distributions/php-7.1.12.tar.bz2
CurlKit\CurlException: (6) Could not resolve host: us1.php.net at [http://us1.php.net/distributions/php-7.1.12.tar.bz2:Could not resolve host: us1.php.net]
Thrown from phar:///usr/bin/phpbrew/vendor/corneltek/curlkit/src/CurlKit/CurlDownloader.php at line 153:

### Expected Result

To start the downloads and start the build

### Command

phpbrew --debug install -j $(nproc) 7.1.12 +default+dbs +gd +apxs2=/usr/bin/apxs2 +fpm +cli +bcmath +bz2 +calendar +ctype +dom +fileinfo +filter +ipc +json +mbregex +mbstring +mhash +pcre +pdo +phar +posix +readline +sockets +tokenizer +xml +curl +zip +openssl=yes +mysql +session +soap +fpm +xml_all +exif +zts

### Build Log

No logs generated

### Platform

OS: Ubuntu 14.04

    e.g. OS X 10.7, Ubuntu 14.04

Running PHP: 
CLI 7.0.0
Installing PHP:
7.1.2 as well as 7.2.0

While my issue is that my local nor any remote server I run can ping to us1.php.net, my issue seems to be the checksum mismatch. I'm unsure how to get past that so that I never need to be redirected to a server that is offline. I've searched for this in the issues and I've tried different times of the day as well but no luck. Am I having bad luck?, sam

**Comment by morozov** [comment]
> Am I having bad luck?

Yes. During the last month, I've seen this exact issue (Could not resolve host: us1.php.net) at least a couple of times.

> I'm unsure how to get past that so that I never need to be redirected to a server that is offline

As you can see, it's the http://www.php.net/get which redirects to http://us1.php.net/ so we cannot do anything about that. Furthermore, the server is not really offline. All the times I saw this issue, a subsequent invocation of `phpbrew install ...` succeeded. Not sure which kind of a DNS issue it is.

It could and should be solved on the HTTP client side in PHPBrew, but I don't have plans for that.

**Comment by sam452** [comment]
Yes, I understand and will keep trying to install. At least this should be found in searches so others will know. This ticket may be closed.
