### ISSUE TITLE
php7 imap The requested URL returned error: 404 Not Found

### ISSUE THREAD

**Issue by andrzepakula** [phpbrew/phpbrew#943]
Hi. I am tried install imap ext for php7.0 or php7.1 and receives such an error. What I am doing wrong and how to install imap ? 

### Output
urlKit\CurlException: (22) The requested URL returned error: 404 Not Found at [https://pecl.php.net/rest/r/imap/stable.txt:The requested URL returned error: 404 Not Found]
Trace:

    0) CurlKit\CurlDownloader->request('https://pecl.php.net/rest/r/imap/stable.txt')
    1) PhpBrew\Downloader\PhpCurlDownloader->process('https://pecl.php.net/rest/r/imap/stable.txt', '/tmp/phpbrew_Th3nea')
    2) PhpBrew\Downloader\BaseDownloader->download('https://pecl.php.net/rest/r/imap/stable.txt')
    3) PhpBrew\Downloader\BaseDownloader->request('https://pecl.php.net/rest/r/imap/stable.txt')
    4) PhpBrew\Extension\Provider\PeclProvider->getPackageXml('imap', 'stable')
    5) PhpBrew\Extension\Provider\PeclProvider->buildPackageDownloadUrl('stable')
    6) PhpBrew\Extension\ExtensionDownloader->download(PhpBrew\Extension\Provider\PeclProvider, 'stable')
    7) PhpBrew\Command\ExtensionCommand\InstallCommand->execute('imap')
    8) call_user_func_array([PhpBrew\Command\ExtensionCommand\InstallCommand, 'execute'], ['imap'])
    9) CLIFramework\CommandBase->executeWrapper(['imap'])
    10) CLIFramework\Application->run(['/usr/local/bin/phpbrew', 'ext', 'install', 'imap'])
    11) PhpBrew\Console->runWithTry(['/usr/local/bin/phpbrew', 'ext', 'install', 'imap'])
    12) require('phar:///usr/local/bin/phpbrew/scripts/phpbrew-emb.php')

```
### Command

    phpbrew ext install imap 

### Platform

 Ubuntu 16.04

Running PHP: 
7.1.12     
7.0

**Comment by morozov** [comment]
@andrzejpakula most likely, you have removed your PHP build directory which is `~/.phpbrew/build/php-x.y.z`. In this case, PHPBrew cannot find the extension directory and thinks that it's a PECL extension, however, it's not.

The only working solution I can offer at the moment is reinstalling the PHP for which you're trying to install the extension.

Please see #924 for the reference.

**Comment by umbri** [comment]
```phpbrew ext install imap -- --with-kerberos --with-imap-ssl```

**Comment by morozov** [comment]
@umbri it's a different issue, unrelated here.

**Comment by peter279k** [comment]
The `imap` extension should be compiled during `phpbrew install` command running.

It cannot use the `phpbrew ext install imap` to install the extension after building and compiling the current PHP version.
