### ISSUE TITLE
php 5.3.10 installed successfully but when i tried to load zend guard loader it gives me error

### ISSUE THREAD

**Issue by deepakthakur07** [phpbrew/phpbrew#944]
when i run phpbrew use 5.3.10
### Output

```
Failed loading /home/deepak/Downloads/ZendGuardLoader.so:  /home/deepak/Downloads/ZendGuardLoader.so: undefined symbol: compiler_globals

```
### Platform

OS:

    Ubuntu 16.04

Running PHP: 
    5.3.10
Installing PHP:

**Comment by morozov** [comment]
@deepakthakur07, most likely, the `ZendGuardLoader.so` you're using is incompatible with the PHP you've built. What can be incompatible:

1. The PHP minor/major version.
2. Thread safety (ZTS/NTS)
3. Maybe processor architecture x86/x64.

**Comment by deepakthakur07** [comment]
php that i have built is thread safe. Does is causing the problem.

**Comment by morozov** [comment]
If your extension is NTS, then probably yes. Could you post the output of your `php -v` and the link where you download your extension? From what I can see, [this](http://www.zend.com/en/products/loader/thank-you-zend-loader?package=1518) distribution contains only one build, so most likely it's NTS, not ZTS.

**Comment by deepakthakur07** [comment]
> Failed loading /usr/lib/php/ZendGuardLoader.so:  /usr/lib/php/ZendGuardLoader.so: undefined symbol: compiler_globals
> PHP 5.3.10 (cli) (built: Jan 16 2018 21:00:40) 
> Copyright (c) 1997-2012 The PHP Group
> Zend Engine v2.3.0, Copyright (c) 1998-2012 Zend Technologies
>

**Comment by deepakthakur07** [comment]
**extension link**
http://downloads.zend.com/guard/5.5.0/ZendGuardLoader-php-5.3-linux-glibc23-x86_64.tar.gz

**Comment by morozov** [comment]
I can load this extension into an NTS build which means either it's incompatible with ZTS at all or you need to find the ZTS build:
```
↪ php -v
PHP 5.3.29 (cli) (built: Sep 29 2017 11:12:55) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2014 Zend Technologies
    with Xdebug v2.2.7, Copyright (c) 2002-2015, by Derick Rethans

↪ php -r "echo PHP_ZTS, PHP_EOL;"
0
```

**Comment by deepakthakur07** [comment]
Thanks. I have installed 5.3.28 and zend loader is working now. But i forgot to install some libs, drivers etc during php install.

> sudo phpbrew install php-5.3.28 +apxs2=/usr/bin/apxs2

Now i have build this version and now i need pdo,pgsql etc. Should i need to install php again or these things(pdo, pgsql etc) can be installed separately.

**Comment by morozov** [comment]
> Should i need to install php again or these things(pdo, pgsql etc) can be installed separately.

Most of the extensions can be installed in a shared way but some (like `mysqli`) cannot. You can try installing them one by one like `phpbrew ext install $ext` and see if it works. Otherwise, you'll have to rebuild PHP with all needed variants enabled.
