### ISSUE TITLE
phpbrew is not downloading the php archives properly (I just get empty files)

### ISSUE THREAD

**Issue by vladiibine** [phpbrew/phpbrew#946]
### Command

```
23:20]shefuto ~/.phpbrew $ tree
.
├── bashrc
├── bin
├── build
├── distfiles
├── php
│   ├── php-5.4.45
│   ├── php-5.5.35
│   ├── php-5.6.30
│   └── php-7.2.1
├── phpbrew.fish
├── php-releases.json
├── register
└── variants

10 directories, 3 files




23:20]shefuto ~/.phpbrew $ phpbrew --debug install 7.2.1
===> phpbrew will now build 7.2.1
You haven't set any variant. A default set of extensions will be installed for the minimum requirement:
[bcmath, bz2, calendar, cli, ctype, dom, fileinfo, filter, ipc, json, mbregex, mbstring, mhash, pcntl, pcre, pdo, phar, posix, readline, sockets, tokenizer, xml, curl, zip, openssl]
Please run 'phpbrew variants' for more information.

===> Loading and resolving variants...
Downloading http://www.php.net/get/php-7.2.1.tar.bz2/from/this/mirror via php stream
PHP Warning:  file_get_contents(http://www.php.net/get/php-7.2.1.tar.bz2/from/this/mirror): failed to open stream: Connection timed out in phar:///home/shefuto/phpbrew/phpbrew/src/PhpBrew/Downloader/PhpStreamDownloader.php on line 37
===> Extracting /home/shefuto/.phpbrew/distfiles/php-7.2.1.tar.bz2 to /home/shefuto/.phpbrew/build/tmp.1516310483/php-7.2.1
tar: This does not look like a tar archive

bzip2: Compressed file ends unexpectedly;
	perhaps it is corrupted?  *Possible* reason follows.
bzip2: Inappropriate ioctl for device
	Input file = (stdin), output file = (stdout)

It is possible that the compressed file(s) have become corrupted.
You can use the -tvv option to test integrity of such files.

You can use the `bzip2recover' program to attempt to recover
data from undamaged sections of corrupted files.

tar: Child returned status 2
tar: Error is not recoverable: exiting now
Error: Extract failed:




23:21]shefuto ~/.phpbrew $ tree -h
.
├── [ 15K]  bashrc
├── [4.0K]  bin
├── [4.0K]  build
│   └── [4.0K]  tmp.1516310483
├── [4.0K]  distfiles
│   └── [   0]  php-7.2.1.tar.bz2
├── [4.0K]  php
│   ├── [4.0K]  php-5.4.45
│   ├── [4.0K]  php-5.5.35
│   ├── [4.0K]  php-5.6.30
│   └── [4.0K]  php-7.2.1
├── [ 21K]  phpbrew.fish
├── [ 52K]  php-releases.json
├── [4.0K]  register
└── [4.0K]  variants

11 directories, 4 files
```
### Build Log

    gist here

### Platform

OS:

   ubuntu 16.04

Running PHP: 
PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.22-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies

Installing PHP: 7.2.1

**Comment by vladiibine** [comment]
Extra info: this happened when installing other versions of php (i randomly tried to install a few, but that didn't work)

Update: Found a workaround for the download step: I just went to the mirror listed in the output, and downloaded the file manually, and saved it to the distfiles folder. After that, running the command again seemed to proceed past the point where it had failed earlier. (It used the file I had downloaded, and started building PHP)

**Comment by morozov** [comment]
> PHP Warning:  file_get_contents(http://www.php.net/get/php-7.2.1.tar.bz2/from/this/mirror): failed to open stream: Connection timed out in phar:///home/shefuto/phpbrew/phpbrew/src/PhpBrew/Downloader/PhpStreamDownloader.php on line 37

You may also try using the `--connect-timeout` option which is available for the `install` and `ext install` commands.

You can also check the value of the [`default_socket_timeout`](http://php.net/manual/en/filesystem.configuration.php#ini.default-socket-timeout) INI variable which the timeout for the PHP Stream downloader defaults to (60 seconds by default). Does it take longer than that in your case?

**Comment by vladiibine** [comment]
With 200 seconds as the socket timeout it works.
I'll be closing the ticket then, thanks a lot :)
