### ISSUE TITLE
dyld: lazy symbol binding failed: Symbol not found: _X509_get_signature_nid

### ISSUE THREAD

**Issue by brunofunny** [phpbrew/phpbrew#947]
### Output

```
bruno@13:53:00 - ~/projects/test/backend
> composer install
dyld: lazy symbol binding failed: Symbol not found: _X509_get_signature_nid
  Referenced from: /Users/bruno/.phpbrew/php/php-7.1.12/lib/php/extensions/no-debug-non-zts-20160303/openssl.so
  Expected in: flat namespace

dyld: Symbol not found: _X509_get_signature_nid
  Referenced from: /Users/bruno/.phpbrew/php/php-7.1.12/lib/php/extensions/no-debug-non-zts-20160303/openssl.so
  Expected in: flat namespace

Abort trap: 6
```

### Expected Result

Should be

```
> composer
   ______
  / ____/___  ____ ___  ____  ____  ________  _____
 / /   / __ \/ __ `__ \/ __ \/ __ \/ ___/ _ \/ ___/
/ /___/ /_/ / / / / / / /_/ / /_/ (__  )  __/ /
\____/\____/_/ /_/ /_/ .___/\____/____/\___/_/
                    /_/
Composer version 1.6.2 2018-01-05 15:28:41

Usage:
  command [options] [arguments]
```

### Command

```
phpbrew init (yes, copied and runned the source bash)
phpbrew --debug install 7.1.12 +pdo+mysql
phpbrew ext install hash
phpbrew ext install json
phpbrew ext install iconv
phpbrew ext install filter
phpbrew ext install openssl
```

### Build Log

Here is the --debug, build logs, php-m etc... [Debug and Build](https://gist.github.com/brunofunny/ba7e1807d0235410d978efc248a30ba0)

### Platform

OS:

    OS X 10.13.2 (High Sierra)

Running PHP: (builded one producing this current issue)
```(bash)
bruno@14:01:30 - ~/projects/test/backend
> php -v
PHP 7.1.12 (cli) (built: Jan 20 2018 13:30:03) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```

Installing PHP (native Mac OS High Sierra php)
```(bash)
bruno@13:57:57 - ~/projects/test/backend
> php -v
PHP 7.1.7 (cli) (built: Jul 15 2017 18:08:09) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```

**Comment by morozov** [comment]
> checking for OpenSSL support... no

It's surprising that the `openssl` extension got compiled in this case. You may have `openssl` available as a binary in your system but it doesn't mean the build dependencies are also available. Not sure how it works in HomeBrew.

Did you attach the build log of `phpbrew ext install openssl`? The [last lines](https://gist.github.com/brunofunny/ba7e1807d0235410d978efc248a30ba0#file-phpbrew-install-7-1-12-log-L56) I see in the gist are:
```
$ phpbrew switch php-7.1.12

Enjoy!
```
…which belong to `phpbrew --debug install 7.1.12 +pdo+mysql`. Could you attach the output of `phpbrew ext install openssl` as well?

Also, to clarify, does the output of `php -m` belong to the PHP which you run PHPBrew on or the one which you build?

**Comment by brunofunny** [comment]
- Added in the gist the openssl output build
- Yes, the php -m is the one which I build not the native factory installed php

**Comment by morozov** [comment]
@brunofunny sorry, I have no idea what's wrong here. It looks like the OpenSSL version you're using to compile the extension is incompatible with it. However, the build script detects it as compatible:
```
checking for OpenSSL support... yes, shared
checking for OpenSSL version... >= 1.0.1
```
Is it possible that you're using some much newer version like 1.1.0? Not sure if it's compatible with the extension. Depending on the way you got it installed (HomeBrew?) please check the version.

**Comment by brunofunny** [comment]
@morozov That's exactly it.

It wasn't using the OpenSSL version, it was using the OS X version which uses LibreSSL.

```(bash)
>openssl version
LibreSSL 2.2.7
>/usr/local/Cellar/openssl/1.0.2n/bin/openssl version
OpenSSL 1.0.2n 7 Dec 2017
```
So I did

```(bash)
phpbrew install 7.1.12 +pdo+mysql+openssl=/usr/local/Cellar/openssl/1.0.2n/
```

and now it worked!

Thanks for pointing the right direction!
