### ISSUE TITLE
PHPBrew PHP-7.2.2 sodium not working

### ISSUE THREAD

**Issue by simonkulessa** [phpbrew/phpbrew#949]
### Output

Hi, 
I´ve compiled PHP-7.2.2 with the option "--with-sodium" but It when testing it with a php file we get:

PHP Fatal error:  Uncaught Error: Call to undefined function sodium_crypto_pwhash_str() in /tmp/test.php:3
Stack trace:
#0 {main}
  thrown in /tmp/test.php on line 3

Fatal error: Uncaught Error: Call to undefined function sodium_crypto_pwhash_str() in /tmp/test.php:3
Stack trace:
#0 {main}
  thrown in /tmp/test.php on line 3

when doing "php -m" we can see sodium enabled, "php -i | grep libsodium" gives us:

libsodium headers version => 1.0.8
libsodium library version => 1.0.8

but it simply doesn´t work. We tried the old and the new namespaces, both won´t work.

### Expected Result

libsodium working

### Command

    phpbrew ext install libsodium / or compile with "--with-libsodium"

### Platform

OS: Ubuntu 16.04

Running PHP: 7.2.2

Content of test.php:

```php
<?php

sodium_crypto_pwhash_str(
    'test',
    SODIUM_CRYPTO_PWHASH_OPSLIMIT_INTERACTIVE,
    SODIUM_CRYPTO_PWHASH_MEMLIMIT_INTERACTIVE
);
```

Anyone any ideas? It works on the mac of the developer (brew and php-7.2.2)

Thanks in advance
Simon

**Comment by morozov** [comment]
I can reproduce the issue but I it doesn't look caused by PHPBrew. I compiled PHP manually `--with-sodium` and I see the same behavior as described above (same PHP, libsodium and Ubuntu versions).

Additionally, similar functions to what you're trying to use are available:
```
↪ php --re sodium | grep sodium_crypto_pwhash_
    Function [ <internal:sodium> function sodium_crypto_pwhash_scryptsalsa208sha256 ] {
    Function [ <internal:sodium> function sodium_crypto_pwhash_scryptsalsa208sha256_str ] {
    Function [ <internal:sodium> function sodium_crypto_pwhash_scryptsalsa208sha256_str_verify ] {
```

Which makes me think that either this function requires some additional dependencies or it's been removed from the extension for some reason.

**Comment by simonkulessa** [comment]
We installed php v7.2.2 via ppa:ondrej and there it is working.

**Comment by simonkulessa** [comment]
Hi,

we managed to get it working :)

We had libsodium-dev in version 1.0.8 installed, as I read for sodium with PHP-7.2 you need to have a version greater than 1.0.8 installed. So we upgraded to 1.0.16 and it works :)

Regards
Simon

**Comment by morozov** [comment]
Cool. So there's no problem here. Thanks for letting know @simonkulessa.

**Comment by bizmate** [comment]
just FYI , on ubuntu 18, i found that when i installed libsodium-dev it got installed as sodium.so in my 

```
~/.phpbrew/php/php-7.3.9/lib/php/extensions/no-debug-non-zts-20180731
```
folder so php was not finding the extension correctly. 

I just symlinked it to make it work

`$ ln -s sodium.so libsodium.so`
