### ISSUE TITLE
Fatal error: Call to undefined function PhpBrew\json_decode()

### ISSUE THREAD

**Issue by nmohanan** [phpbrew/phpbrew#955]
### Output

phpbrew install php-5.6.0 +mysql +json +pdo +apxs2=usr/bin/apx2
# WARNING: json extension is required for parsing release info.
# WARNING: ctype extension might be required for parsing yaml file.
PHP Fatal error:  Call to undefined function PhpBrew\json_decode() in phar:///usr/bin/phpbrew/src/PhpBrew/ReleaseList.php on line 50

Fatal error: Call to undefined function PhpBrew\json_decode() in phar:///usr/bin/phpbrew/src/PhpBrew/ReleaseList.php on line 50

### Command

phpbrew --debug install php-5.6.0 +mysql +json +pdo +apxs2=usr/bin/apx2

### Platform

OS:

    Ubuntu 17.04

Running PHP: Need to install php 5.6 with mysql and apache

Installing PHP: installed php 5.6 but after trying to install apache and mysql showing this error.

**Comment by morozov** [comment]
Looks like your system PHP doesn't have the JSON extension loaded. Please try:
```
sudo apt install php7.0-json
```

**Comment by nmohanan** [comment]
sudo apt-get install php7.0-json
Reading package lists... Done
Building dependency tree       
Reading state information... Done
php7.0-json is already the newest version (7.0.22-0ubuntu0.17.04.1).
0 upgraded, 0 newly installed, 0 to remove and 2 not upgraded.

**Comment by morozov** [comment]
@nmohanan please see if the output your `php -m` contains `ctype` and `json`. Even if the packages are installed, they may be disabled in your PHP configuration.

**Comment by nmohanan** [comment]
When i do php -m i can see the ctype and json in the list, 
php -m
[PHP Modules]
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
ftp
gd
gettext
hash
iconv
intl
json
libxml
mbstring
mcrypt
mysqli
mysqlnd
openssl
pcntl
pcre
PDO
pdo_mysql
Phar
posix
readline
Reflection
session
shmop
SimpleXML
soap
sockets
SPL
standard
sysvmsg
sysvsem
sysvshm
tokenizer
wddx
xml
xmlreader
xmlwriter
xsl
Zend OPcache
zip
zlib

[Zend Modules]
Zend OPcache

**Comment by morozov** [comment]
Are you sure you're using the same PHP for running PHPBrew? According to the output, both extensions are installed and loaded but PHPBrew says they aren't. Is there a chance you have another PHP which doesn't have those extensions and you're running PHP on it?

**Comment by oscarromero** [comment]
Same problem here. 

I have installed with this:
`phpbrew install php-7.2.7 +json +ctype +mbstring +iconv +dom +mcrypt +curl +mysql +pdo +xml +xmlrpc +soap +zip +zlib +bcmath +bz2 +cli +exif +openssl +gettext +sockets +readline +gd +posix +gcov +ftp +mbregex +imap +filter +libgcc +debug +phpdbg +pcre +pgsql +phar +mhash +kerberos +intl +ipc +ipv6 +fileinfo +editline +sqlite +static 
`

But executing `phpbrew path` throws this error:

> PHP Warning:  PHP Startup: Unable to load dynamic library 'json.so' (tried: /home/vagrant/.phpbrew/php/php-7.2.7/lib/php/extensions/debug-non-zts-20170718/json.so (/home/vagrant/.phpbrew/php/php-7.2.7/lib/php/extensions/debug-non-zts-20170718/json.so: undefined symbol: __gcov_merge_add), /home/vagrant/.phpbrew/php/php-7.2.7/lib/php/extensions/debug-non-zts-20170718/json.so.so (/home/vagrant/.phpbrew/php/php-7.2.7/lib/php/extensions/debug-non-zts-20170718/json.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

**Comment by taliesinmillhouse** [comment]
`phpbrew ext install json` fixed it for me.
