### ISSUE TITLE
Not working on OSX

### ISSUE THREAD

**Issue by MatthD** [phpbrew/phpbrew#960]
I am trying to use phpbrew on osx but it does not work.. a problem with readline it seems, I installed requirement

### Output

checking for readline support... yes

checking for tgetent in -lncurses... yes

checking for readline in -lreadline... yes

checking for rl_pending_input in -lreadline... no

configure: error: invalid readline installation detected. Try --with-libedit instead.

### Expected Result

To install php 7.2.3

### Command

Paste your phpbrew install command here (be sure to install with `--debug` flag, e.g. `phpbrew --debug install`)

    phpbrew install 7.2.3

### Build Log

    gist here

### Platform

OS:

    MAC OSX 10.13.3

**Comment by MatthD** [comment]
Ok, it was about the linking of icu4c, i added "-force option".

Now i got this error when it try to build : 

`Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 4194312 bytes) in phar:///usr/local/bin/phpbrew/src/PhpBrew/Console.php on line 139`

**Comment by MatthD** [comment]
For the memory problem, I had to edit my /etc/php.ini to change " memory_size" to something greater.
Now I am facing a compilation error : 

The last 5 lines in the log file:
```
  "_X509_get_signature_nid", referenced from:

      _zif_openssl_x509_parse in openssl.o

ld: symbol(s) not found for architecture x86_64

clang: error: linker command failed with exit code 1 (use -v to see invocation)

make: *** [sapi/cli/php] Error 1
```

Why phpbrew does compilation instead of download already prebuild for system Binary like nvm does?

**Comment by MatthD** [comment]
Ok So, phpbrew does not work easily on hight Sierra (xcode9).
The easiest way is to install versions via brew (`brew install php72`...)
Then use https://github.com/wilmoore/php-version

**Comment by heitoralthmann** [comment]
Hi @MatthD,
I'm having the same issue with High Sierra in here.

Any findings on this since you closed the issue?
