### ISSUE TITLE
Build Failed with ICU 61.1

### ISSUE THREAD

**Issue by infomaniac50** [phpbrew/phpbrew#962]
The build fails on Arch Linux after upgrading libicu. The new ICU version is 61.1 and requires a flag to build PHP correctly. Arch Linux defines this flag before building their php package. 

I don't know if you have something like homebrew-php ENV.append so I entered ``export CPPFLAGS+=' -DU_USING_ICU_NAMESPACE=1'`` before phpbrew install and it fixed the build for me.

See Also:
- icu-config --version 61.1
- https://bugs.archlinux.org/task/58061
- http://source.icu-project.org/repos/icu/trunk/icu4c/readme.html#RecBuild
- https://github.com/openwrt/packages/issues/5853
- https://github.com/Homebrew/homebrew-php/issues/4831

### Output

```
===> phpbrew will now build 7.1.16
---> Parsing variants from command arguments '+default +mysql +opcache +sqlite +iconv +intl'
===> Loading and resolving variants...
Checking distribution checksum...
Checksum matched: 348e2af9c7c0f327a57a972674078777dfde189e2598acbcb8618b9645b0e7e5
===> Distribution file was successfully extracted, skipping...
Source Directory: /home/derek/.phpbrew/build/php-7.1.16
Found existing Makefile, running make clean to ensure everything will be rebuilt.
You can append --no-clean option after the install command if you don't want to rebuild.
===> Running make clean: /usr/bin/make -C '/home/derek/.phpbrew/build/php-7.1.16' --quiet 'clean'
Running Command:/usr/bin/make -C '/home/derek/.phpbrew/build/php-7.1.16' --quiet 'clean'
Writing variant info to /home/derek/.phpbrew/php/php-7.1.16/phpbrew.variants
===> Checking patches...
Checking patch for replace apache php module name with custom version name
Enabled variants: [mysql, opcache, sqlite, iconv, intl, xml, bcmath, bz2, calendar, cli, ctype, dom, fileinfo, filter, ipc, json, mbregex, mbstring, mhash, mcrypt, pcntl, pcre, pdo, pear, phar, posix, readline, sockets, tokenizer, curl, openssl, zip]
Disabled variants: []
Found existing build.log, renaming it to /home/derek/.phpbrew/build/php-7.1.16/build.log.1522796231
===> Configuring 7.1.16...


Use tail command to see what's going on:
   $ tail -F /home/derek/.phpbrew/build/php-7.1.16/build.log


./configure '--cache-file=/home/derek/.phpbrew/cache/config.cache' '--prefix=/home/derek/.phpbrew/php/php-7.1.16' '--with-config-file-path=/home/derek/.phpbrew/php/php-7.1.16/etc' '--with-config-file-scan-dir=/home/derek/.phpbrew/php/php-7.1.16/var/db' '--disable-all' '--enable-phar' '--enable-session' '--enable-short-tags' '--enable-tokenizer' '--with-pcre-regex' '--with-zlib=/usr' '--with-mysqli=mysqlnd' '--with-pdo-mysql=mysqlnd' '--enable-opcache' '--with-sqlite3' '--with-pdo-sqlite' '--with-iconv' '--enable-intl' '--enable-dom' '--enable-libxml' '--enable-simplexml' '--enable-xml' '--enable-xmlreader' '--enable-xmlwriter' '--with-xsl' '--with-libxml-dir=/usr' '--enable-bcmath' '--with-bz2=/usr' '--enable-calendar' '--enable-cli' '--enable-ctype' '--enable-dom' '--enable-fileinfo' '--enable-filter' '--enable-shmop' '--enable-sysvsem' '--enable-sysvshm' '--enable-sysvmsg' '--enable-json' '--enable-mbregex' '--enable-mbstring' '--with-mhash' '--with-mcrypt=/usr' '--enable-pcntl' '--with-pcre-regex' '--with-pcre-dir=/usr' '--enable-pdo' '--with-pear=/home/derek/.phpbrew/php/php-7.1.16/lib/php/pear' '--enable-phar' '--enable-posix' '--with-readline=/usr' '--enable-sockets' '--enable-tokenizer' '--with-curl=/usr' '--with-openssl=/usr' '--enable-zip' >> /home/derek/.phpbrew/build/php-7.1.16/build.log 2>&1
===> Checking patches...
Checking patch for php5.3.29 multi-sapi patch.
Checking patch for php5.3.x on 64bit machine when intl is enabled.
Checking patch for openssl dso linking patch
===> Building...
make >> /home/derek/.phpbrew/build/php-7.1.16/build.log 2>&1
Error: Make failed:
The last 5 lines in the log file:
                               ^~~~~~~~~

/home/derek/.phpbrew/build/php-7.1.16/ext/intl/intl_convertcpp.cpp:79:76: error: request for member ‘length’ in ‘from’, which is of non-class type ‘const int’

  u_strToUTF8WithSub(ZSTR_VAL(u8res), capacity, &actual_len, utf16buf, from.length(),

                                                                            ^~~~~~

make: *** [Makefile:910: ext/intl/intl_convertcpp.lo] Error 1

Please checkout the build log file for more details:
	 tail /home/derek/.phpbrew/build/php-7.1.16/build.log
```

### Expected Result

```
===> phpbrew will now build 7.1.16
---> Parsing variants from command arguments '+default +mysql +opcache +sqlite +iconv +intl'
===> Loading and resolving variants...
Checking distribution checksum...
Checksum matched: 348e2af9c7c0f327a57a972674078777dfde189e2598acbcb8618b9645b0e7e5
===> Distribution file was successfully extracted, skipping...
Source Directory: /home/derek/.phpbrew/build/php-7.1.16
Found existing Makefile, running make clean to ensure everything will be rebuilt.
You can append --no-clean option after the install command if you don't want to rebuild.
===> Running make clean: /usr/bin/make -C '/home/derek/.phpbrew/build/php-7.1.16' --quiet 'clean'
Running Command:/usr/bin/make -C '/home/derek/.phpbrew/build/php-7.1.16' --quiet 'clean'
Writing variant info to /home/derek/.phpbrew/php/php-7.1.16/phpbrew.variants
===> Checking patches...
Checking patch for replace apache php module name with custom version name
Enabled variants: [mysql, opcache, sqlite, iconv, intl, xml, bcmath, bz2, calendar, cli, ctype, dom, fileinfo, filter, ipc, json, mbregex, mbstring, mhash, mcrypt, pcntl, pcre, pdo, pear, phar, posix, readline, sockets, tokenizer, curl, openssl, zip]
Disabled variants: []
Found existing build.log, renaming it to /home/derek/.phpbrew/build/php-7.1.16/build.log.1522796701
===> Configuring 7.1.16...


Use tail command to see what's going on:
   $ tail -F /home/derek/.phpbrew/build/php-7.1.16/build.log


./configure '--cache-file=/home/derek/.phpbrew/cache/config.cache' '--prefix=/home/derek/.phpbrew/php/php-7.1.16' '--with-config-file-path=/home/derek/.phpbrew/php/php-7.1.16/etc' '--with-config-file-scan-dir=/home/derek/.phpbrew/php/php-7.1.16/var/db' '--disable-all' '--enable-phar' '--enable-session' '--enable-short-tags' '--enable-tokenizer' '--with-pcre-regex' '--with-zlib=/usr' '--with-mysqli=mysqlnd' '--with-pdo-mysql=mysqlnd' '--enable-opcache' '--with-sqlite3' '--with-pdo-sqlite' '--with-iconv' '--enable-intl' '--enable-dom' '--enable-libxml' '--enable-simplexml' '--enable-xml' '--enable-xmlreader' '--enable-xmlwriter' '--with-xsl' '--with-libxml-dir=/usr' '--enable-bcmath' '--with-bz2=/usr' '--enable-calendar' '--enable-cli' '--enable-ctype' '--enable-dom' '--enable-fileinfo' '--enable-filter' '--enable-shmop' '--enable-sysvsem' '--enable-sysvshm' '--enable-sysvmsg' '--enable-json' '--enable-mbregex' '--enable-mbstring' '--with-mhash' '--with-mcrypt=/usr' '--enable-pcntl' '--with-pcre-regex' '--with-pcre-dir=/usr' '--enable-pdo' '--with-pear=/home/derek/.phpbrew/php/php-7.1.16/lib/php/pear' '--enable-phar' '--enable-posix' '--with-readline=/usr' '--enable-sockets' '--enable-tokenizer' '--with-curl=/usr' '--with-openssl=/usr' '--enable-zip' >> /home/derek/.phpbrew/build/php-7.1.16/build.log 2>&1
===> Checking patches...
Checking patch for php5.3.29 multi-sapi patch.
Checking patch for php5.3.x on 64bit machine when intl is enabled.
Checking patch for openssl dso linking patch
===> Building...
make >> /home/derek/.phpbrew/build/php-7.1.16/build.log 2>&1
Build finished: 13.4 minutes.
Installing...
---> Creating php-fpm.conf
---> Creating php.ini
---> Copying /home/derek/.phpbrew/build/php-7.1.16/php.ini-development 
---> Found date.timezone is not set, patching...
Initializing pear config...
sh: pear: command not found
sh: pear: command not found
sh: pear: command not found
Enabling pear auto-discover...
sh: pear: command not found
Source directory: /home/derek/.phpbrew/build/php-7.1.16
Congratulations! Now you have PHP with 7.1.16 as php-7.1.16

* We found that you enabled 'mysql' variant, you might need to setup your
  'pdo_mysql.default_socket' or 'mysqli.default_socket' in your php.ini file.

* To configure your installed PHP further, you can edit the config file at
    /home/derek/.phpbrew/php/php-7.1.16/etc/php.ini

To use the newly built PHP, try the line(s) below:

    $ phpbrew use php-7.1.16

Or you can use switch command to switch your default php to php-7.1.16:

    $ phpbrew switch php-7.1.16

Enjoy!
```

### Command

Paste your phpbrew install command here (be sure to install with `--debug` flag, e.g. `phpbrew --debug install`)

    phpbrew --debug install php-7.1.16 +default +mysql +opcache +sqlite +iconv +intl

### Build Log

    https://gist.github.com/infomaniac50/042c33b5a18e05e1fe69aee3dc3ccdec

### Platform

OS:

    Arch Linux

Running PHP: 

Arch Linux packaged PHP 7.2.4

Installing PHP:

PHP 7.1.16

**Comment by morozov** [comment]
@infomaniac50 thank you for the detailed report. Currently, we don't have an API to declare extension-specific environment. The concept of a variant only allows declaring extension-specific command line arguments like `--with-*` or `--enable=*`.

A patch either adding the new API or fixing this particular issue is welcome.

**Comment by infomaniac50** [comment]
I'm not sure if adding ``export CPPFLAGS+=' -DU_USING_ICU_NAMESPACE=1'`` to all builds would be safe. I'm thinking of adding a new patch to check the ICU version. pkg-config can provide the version assuming you know the package name beforehand.

Arch Linux:
pkg-config --modversion icu-i18n

CloudLinux Server 6.9 (aka RedHat 6.9 + kmod-lve):
pkg-config --modversion icu

**Comment by infomaniac50** [comment]
Notes for pkg-config


Arch Linux:
pkg-config --modversion icu-i18n

CloudLinux Server 6.9 (aka RedHat 6.9 + kmod-lve):
pkg-config --modversion icu

**Comment by kilip** [comment]
this should be fixed by using `CPPFLAGS+=' -DU_USING_ICU_NAMESPACE=1'` I have found that in arch php configure can't find openssl library, so I need to add phpbrew command with `-- --with-openssl`. Here's my complete command in arch:

```shell

CPPFLAGS+=' -DU_USING_ICU_NAMESPACE=1' phpbrew install 7.2.4 as 7.2 +doyolabs -- --with-openssl

```

And my complete `~/.phpbrew/config.yaml` file:
```yaml
variants:
    doyolabs:
        fpm:
        opcache:
        bz2:
        calendar:
        ipc:
        pcntl:
        pcre:
        phar:
        posix:
        readline:
        sockets:
        tokenizer:
        curl:
        zip:
        mysql:
        pgsql:
        pdo:
        intl:
        bcmath:
        bz2:
        calendar:
        cli:
        ctype:
        dom:
        fileinfo:
        filter:
        ipc:
        json:
        mbregex:
        mbstring:
        mhash:
        mcrypt:
        sqlite:
        iconv:
        gd:
          - --with-libdir=lib/x86_64-linux-gnu
          - --with-gd=/usr
          - --with-jpeg-dir=/usr
          - --enable-gd-natf
          - --with-jpeg-dir=/usr
          - --with-png-dir=/usr
          - --enable-gd-native-ttf
          - --with-xpm-dir=/usr
          - --with-freetype-dir=/usr/include/freetype2/
```

**Comment by infomaniac50** [comment]
https://github.com/infomaniac50/phpbrew-testing A repo for testing phpbrew builds on various OSes. Moved to Vagrant from Docker to remove kernel dependencies. Arch Linux kernels break CentOS 6 userspace.

**Comment by desyncr** [comment]
Can confirm @kilip's flags works. In my case Mac OSX High Sierra. I was getting ` error: unknown type name 'UnicodeString'` and similar errors and warnings trying to build `intl`.

# Build log:
```
/usr/local/Cellar/icu4c/61.1/include/unicode/unistr.h:286:20: note: 'icu_61::UnicodeString' declared here
class U_COMMON_API UnicodeString : public Replaceable
                   ^
/Users/mini/.phpbrew/build/php-7.1.15/ext/intl/intl_convertcpp.cpp:28:25: error: unknown type name 'UnicodeString'
int intl_stringFromChar(UnicodeString &ret, char *str, size_t str_len, UErrorCode *status)
                        ^
/Users/mini/.phpbrew/build/php-7.1.15/ext/intl/intl_convertcpp.cpp:59:40: error: unknown type name 'UnicodeString'; did you mean 'icu_61::UnicodeString'?
zend_string* intl_charFromString(const UnicodeString &from, UErrorCode *status)
                                       ^~~~~~~~~~~~~
                                       icu_61::UnicodeString
/usr/local/Cellar/icu4c/61.1/include/unicode/unistr.h:286:20: note: 'icu_61::UnicodeString' declared here
class U_COMMON_API UnicodeString : public Replaceable
                   ^
12 warnings and 7 errors generated.
```

I was using the following configs:

```
$ icu-config  --version
61.1
$ phpbrew --version
phpbrew - 1.23.1
cliframework core: 2.5.4
```

# Build command:

```
$ CXXFLAGS='-std=c++11 -stdlib=libc++' phpbrew --debug install php-7.1 \
	+default +pdo +mysql -intl +icu +xml +sqlite \
    +fpm -- --with-openssl
```

# Extension intl
```
CPPFLAGS+=' -DU_USING_ICU_NAMESPACE=1'  CXXFLAGS='-std=c++11 -stdlib=libc++'  phpbrew ext install intl
```

Hope it helps.

**Comment by infomaniac50** [comment]
It looks like this issue only affects php-7.1.16 on Arch Linux.

libicu is still on version 61.1

```bash
$ pkg-config --modversion icu-i18n
61.1
```

**Comment by wweaver** [comment]
I know this thread is about getting intl package installed on linux, but I found it when trying to get it to work with my Mac so I figured I'd post in case it's helpful for this thread and for anybody trying to get it to work for Mac.

I was able to get intl package installed via phpbrew by running:

`phpbrew extension install intl -- --with-icu-dir=$(brew --prefix icu4c)`

I found this reference that lead me to try it and it worked.

https://github.com/docker-library/php/issues/307#issuecomment-262491765

**Comment by peter279k** [comment]
Sometimes the PHP needs to compile the old icu library version.

For Ubuntu 18.04+, it's fine to install the `libicu-dev` package and follow the [troubleshooting solution](https://github.com/phpbrew/phpbrew/wiki/Troubleshooting#configure-error-unable-to-detect-icu-prefix-or-no-failed-please-verify-icu-install-prefix-and-make-sure-icu-config-works) to build PHP version with `libicu`.

**Comment by RAHUKNAAZ9900** [comment]
===> phpbrew will now build 7.1.16
---> Parsing variants from command arguments '+default +mysql +opcache +sqlite +iconv +intl'
===> Loading and resolving variants...
Checking distribution checksum...
Checksum matched: 348e2af9c7c0f327a57a972674078777dfde189e2598acbcb8618b9645b0e7e5
===> Distribution file was successfully extracted, skipping...
Source Directory: /home/derek/.phpbrew/build/php-7.1.16
Found existing Makefile, running make clean to ensure everything will be rebuilt.
You can append --no-clean option after the install command if you don't want to rebuild.
===> Running make clean: /usr/bin/make -C '/home/derek/.phpbrew/build/php-7.1.16' --quiet 'clean'
Running Command:/usr/bin/make -C '/home/derek/.phpbrew/build/php-7.1.16' --quiet 'clean'
Writing variant info to /home/derek/.phpbrew/php/php-7.1.16/phpbrew.variants
===> Checking patches...
Checking patch for replace apache php module name with custom version name
Enabled variants: [mysql, opcache, sqlite, iconv, intl, xml, bcmath, bz2, calendar, cli, ctype, dom, fileinfo, filter, ipc, json, mbregex, mbstring, mhash, mcrypt, pcntl, pcre, pdo, pear, phar, posix, readline, sockets, tokenizer, curl, openssl, zip]
Disabled variants: []
Found existing build.log, renaming it to /home/derek/.phpbrew/build/php-7.1.16/build.log.1522796231
===> Configuring 7.1.16...


Use tail command to see what's going on:
   $ tail -F /home/derek/.phpbrew/build/php-7.1.16/build.log


./configure '--cache-file=/home/derek/.phpbrew/cache/config.cache' '--prefix=/home/derek/.phpbrew/php/php-7.1.16' '--with-config-file-path=/home/derek/.phpbrew/php/php-7.1.16/etc' '--with-config-file-scan-dir=/home/derek/.phpbrew/php/php-7.1.16/var/db' '--disable-all' '--enable-phar' '--enable-session' '--enable-short-tags' '--enable-tokenizer' '--with-pcre-regex' '--with-zlib=/usr' '--with-mysqli=mysqlnd' '--with-pdo-mysql=mysqlnd' '--enable-opcache' '--with-sqlite3' '--with-pdo-sqlite' '--with-iconv' '--enable-intl' '--enable-dom' '--enable-libxml' '--enable-simplexml' '--enable-xml' '--enable-xmlreader' '--enable-xmlwriter' '--with-xsl' '--with-libxml-dir=/usr' '--enable-bcmath' '--with-bz2=/usr' '--enable-calendar' '--enable-cli' '--enable-ctype' '--enable-dom' '--enable-fileinfo' '--enable-filter' '--enable-shmop' '--enable-sysvsem' '--enable-sysvshm' '--enable-sysvmsg' '--enable-json' '--enable-mbregex' '--enable-mbstring' '--with-mhash' '--with-mcrypt=/usr' '--enable-pcntl' '--with-pcre-regex' '--with-pcre-dir=/usr' '--enable-pdo' '--with-pear=/home/derek/.phpbrew/php/php-7.1.16/lib/php/pear' '--enable-phar' '--enable-posix' '--with-readline=/usr' '--enable-sockets' '--enable-tokenizer' '--with-curl=/usr' '--with-openssl=/usr' '--enable-zip' >> /home/derek/.phpbrew/build/php-7.1.16/build.log 2>&1
===> Checking patches...
Checking patch for php5.3.29 multi-sapi patch.
Checking patch for php5.3.x on 64bit machine when intl is enabled.
Checking patch for openssl dso linking patch
===> Building...
make >> /home/derek/.phpbrew/build/php-7.1.16/build.log 2>&1
Error: Make failed:
The last 5 lines in the log file:
                               ^~~~~~~~~

/home/derek/.phpbrew/build/php-7.1.16/ext/intl/intl_convertcpp.cpp:79:76: error: request for member ‘length’ in ‘from’, which is of non-class type ‘const int’

  u_strToUTF8WithSub(ZSTR_VAL(u8res), capacity, &actual_len, utf16buf, from.length(),

                                                                            ^~~~~~

make: *** [Makefile:910: ext/intl/intl_convertcpp.lo] Error 1

Please checkout the build log file for more details:
	 tail /home/derek/.phpbrew/build/php-7.1.16/build.log
