### ISSUE TITLE
httpd.conf location in Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by guangrei** [phpbrew/phpbrew#973]
hi, i got the case where apache2 still use php 7 system version, here output when restarting apache2
```
/ > root@8b83d5307314 [php:7.2.7 -phpbrew]
# sudo service apache2 restart
 * Restarting Apache httpd web server apache2                                                                                               [Sat Jul 07 17:47:20.281962 2018] [so:warn] [pid 126511] AH01574: module php7_module is already loaded, skipping
                                                                                                                                     [ OK ]
```
as  `README.md`  say i must comment out or remove some settings in  `/etc/httpd/conf/httpd.conf` but the file isn't exists, i also looking in  `/etc/apache2/httpd.conf` with same result

could someone tell me where  `httpd.conf` location in Ubuntu 18.04 LTS or any step to fix this ?

thx

**Comment by hashmat11** [comment]
httpd.conf: historically the main Apache2 configuration file, named after the httpd daemon. Now the file does not exist. In older versions of Ubuntu the file might be present, but empty, as all configuration options have been moved to the [referenced](https://help.ubuntu.com/lts/serverguide/httpd.html) directories.

**Comment by guangrei** [comment]
thank you very much

**Comment by MarcoSchool** [comment]
I like this explanation 
https://askubuntu.com/questions/652095/cant-find-httpd-conf
