### ISSUE TITLE
I installed php-5.3.29 sucessfull but testing with phpinfo.php I only get a blank page

### ISSUE THREAD

**Issue by michaelyx2** [phpbrew/phpbrew#974]
Since installation of phpbrew I cannot run php-files. When I open a php-file in browser, it seems only the html-part is decoded. 
Opening phpinfo.php I only get a blank page.
Please help! 

 ###Output

===> phpbrew will now build 5.3.29
PHP 5.3 requires +intl, enabled by default.
===> Loading and resolving variants...
Checking distribution checksum...
Checksum matched: c4e1cf6972b2a9c7f2777a18497d83bf713cdbecabb65d3ff62ba441aebb0091
===> Distribution file was successfully extracted, skipping...
Found existing Makefile, running make clean to ensure everything will be rebuilt.
You can append --no-clean option after the install command if you don't want to rebuild.
===> Running make clean: /usr/bin/make -C '/home/michaelyx/.phpbrew/build/php-5.3.29' --quiet 'clean'
===> Checking patches...
Checking patch for replace apache php module name with custom version name
Found existing build.log, renaming it to /home/michaelyx/.phpbrew/build/php-5.3.29/build.log.1531239511
===> Configuring 5.3.29...

Use tail command to see what's going on:
   $ tail -F /home/michaelyx/.phpbrew/build/php-5.3.29/build.log

===> Checking patches...
Checking patch for php5.3.29 multi-sapi patch.
Checking patch for php5.3.x on 64bit machine when intl is enabled.
3 changes patched.
Checking patch for openssl dso linking patch
===> Building...
Build finished: 2.8 minutes.
Installing...
---> Creating php-fpm.conf
---> Creating php.ini
---> Copying /home/michaelyx/.phpbrew/build/php-5.3.29/php.ini-development 
Found existing /home/michaelyx/.phpbrew/php/php-5.3.29/etc/php.ini.
---> Found date.timezone is not set, patching...
---> Turn off detect_encoding for php 5.3.*
Initializing pear config...
config-set succeeded
config-set succeeded
config-set succeeded
Enabling pear auto-discover...
config-set succeeded
Congratulations! Now you have PHP with 5.3.29 as php-5.3.29
...

### Expected Result
phpbrew should provide that I can run my php files

### Command

    phpbrew install 5.3.29 +default+mysql

### Build Log

   <script src="https://gist.github.com/michaelyx2/a9fdc1753760d03e853eb91cebbed4d2.js"></script>

### Platform

OS:    Ubuntu 16.04

Running PHP: 7.0

Installing PHP: 5.3.29

**Comment by michaelyx2** [comment]
On Restart of Ubuntu I get this Error: "Folgender Fehler wurde beim Laden von /home/michaelyx/.profile gefunden: /home/michaelyx/.phpbrew/init: Zeile 2: Invalid: Befehl nicht gefunden. Das hat die Folge, dass die Sitzung nicht richtig konfiguriert sein wird. Sie sollten so bald wie möglich das Problem beheben."

Content of the File .../.phpbrew/init :
# DO NOT EDIT THIS FILE
Invalid argument php-7.2.7

Looks like phpbrew is not correctly initialized?!
What can I do?

**Comment by jasny** [comment]
Translated:
> The following error was found when loading /home/michaelyx/.profile: /home/michaelyx/.phpbrew/init: Line 2: Invalid: command not found. As a result, the session will not be configured correctly. You should fix the problem as soon as possible.

@michaelyx2 Maybe you can fix it manually. The contents of my `~/.phpbrew/init` file is;

```
# DO NOT EDIT THIS FILE
export PHPBREW_ROOT=/home/arnold/.phpbrew
export PHPBREW_HOME=/home/arnold/.phpbrew
export PHPBREW_LOOKUP_PREFIX=
export PHPBREW_PHP=php-7.1.3
export PHPBREW_PATH=/home/arnold/.phpbrew/php/php-7.1.3/bin
# Run this command to configure your shell:
# # eval "$(phpbrew env)"
```

Change **php-7.1.3** with the version you're running, like **php-5.3.29**.

Alternatively, try doing

```
phpbrew switch-off
phpbrew switch php-5.3.29
```
