### ISSUE TITLE
phpbrew fpm : neither starts nor stops the fpm processes when run as root

### ISSUE THREAD

**Issue by YvesLeBorg** [phpbrew/phpbrew#975]
I build 7.2.8 on El-Capitan, with fpm.  When using `phpbrew fpm` to start, i get this (my home account, where the .phpbrew directory is.

    DarkMax:~ yvesleborg$ phpbrew fpm start
    Starting php-fpm...
    [31-Jul-2018 22:33:46] NOTICE: [pool www] 'user' directive is ignored when FPM is not running as root
    [31-Jul-2018 22:33:46] NOTICE: [pool www] 'group' directive is ignored when FPM is not running as root
    DarkMax:~ yvesleborg$ ps -ef | grep fpm
     501 73618     1   0 10:34pm ??         0:00.00 /Users/yvesleborg/.phpbrew/php/php-7.2.8/sbin/php-fpm --php-ini /Users/yvesleborg/.phpbrew/php/php-7.2.8/etc/php.ini --fpm-config /Users/yvesleborg/.phpbrew/php/php-7.2.8/etc/php-fpm.conf --pid /Users/yvesleborg/.phpbrew/php/php-7.2.8/var/run/php-fpm.pid
     501 73619 73618   0 10:34pm ??         0:00.00 /Users/yvesleborg/.phpbrew/php/php-7.2.8/sbin/php-fpm --php-ini /Users/yvesleborg/.phpbrew/php/php-7.2.8/etc/php.ini --fpm-config /Users/yvesleborg/.phpbrew/php/php-7.2.8/etc/php-fpm.conf --pid /Users/yvesleborg/.phpbrew/php/php-7.2.8/var/run/php-fpm.pid
     501 73620 73618   0 10:34pm ??         0:00.00 /Users/yvesleborg/.phpbrew/php/php-7.2.8/sbin/php-fpm --php-ini /Users/yvesleborg/.phpbrew/php/php-7.2.8/etc/php.ini --fpm-config /Users/yvesleborg/.phpbrew/php/php-7.2.8/etc/php-fpm.conf --pid /Users/yvesleborg/.phpbrew/php/php-7.2.8/var/run/php-fpm.pid
     501 73622 65593   0 10:34pm ttys005    0:00.00 grep fpm

    DarkMax:~ yvesleborg$ phpbrew fpm stop
    Stopping php-fpm...

Thus, this works for stopping/starting, but breaks my stack. Want to run these processes as same luser as apache.

So, i su into root and attempt the same as root : 

### Output

```
sh-3.2# php -v
PHP 7.2.8 (cli) (built: Jul 31 2018 17:07:03) ( ZTS DEBUG )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.8, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans
sh-3.2# phpbrew fpm start
sh-3.2# ps -ef | grep fpm
    0 73578 73544   0 10:32pm ttys005    0:00.00 grep fpm
sh-3.2# 
```

### Expected Result

```
a list of processes running !

```

### Command

Paste your phpbrew install command here (be sure to install with `--debug` flag, e.g. `phpbrew --debug install`)

     phpbrew -d install 7.2.8 +default   +apxs2='/usr/local/opt/apache2/bin/apxs'   \
     +fpm +mysql +gd +pdo \
     +icu=/usr/local/opt/icu4c \
     +openssl='/usr/local/opt/openssl' \
     -- \
     --with-curl=/usr/local \
     --with-jpeg-dir=/usr/local/opt/jpeg --with-png-dir=/usr/local/opt/png \
     --with-fpm-user=_www --with-fpm-group=_www \
     --with-gd=shared
     
    phpbrew switch 7.2.8
    
    phpbrew ext install xdebug  
    phpbrew ext install opcache
    phpbrew ext install apcu 
    phpbrew ext install propro
    phpbrew ext install raphf
    phpbrew ext install iconv
    phpbrew ext install igbinary
    phpbrew ext install gmagick 2.0.0RC1
    phpbrew ext install memcached
    phpbrew ext install intl
    CFLAGS="-I/usr/local/opt/openssl/include" PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig" phpbrew ext install event
....

### Build Log

    gist here

### Platform

OS:

 OS X 10.11.6, El Capitan
phpbrew 1.23.1

Running PHP: 

homebrew, 5.5.38

Installing PHP:

php 7.2.8 (same issue with 5.6.37(

**Comment by peter279k** [comment]
The issue is outdated and closed now.
