### ISSUE TITLE
Failed to install GD extension

### ISSUE THREAD

**Issue by owen800q** [phpbrew/phpbrew#976]
### Output
Downloading https://pecl.php.net/rest/r/gd/stable.txt via curl extension
CurlKit\CurlException: (22) The requested URL returned error: 404 Not Found at [https://pecl.php.net/rest/r/gd/stable.txt:The requested URL returned error: 404 Not Found]
Thrown from phar:///usr/local/bin/phpbrew/vendor/corneltek/curlkit/src/CurlKit/CurlDownloader.php at line 156:

  153        $ch = $this->createCurlResource($options);
  154        $data = curl_exec($ch);
  155        if (!$data) {
> 156            throw new CurlException($ch, $url . ":" . curl_error($ch) );
  157        }
  158
  159        // We don't enable CURLOPT_FOLLOWLOCATION because
  160        // the progress bar does not work after the 1st redirect..

Trace:

    1) CurlKit\CurlDownloader->request('https://pecl.php.net/rest/r/gd/stable.txt')

    2) PhpBrew\Downloader\PhpCurlDownloader->process('https://pecl.php.net/rest/r/gd/stable.txt', '/tmp/phpbrew_SeJ52o')
        from phar:///usr/local/bin/phpbrew/src/PhpBrew/Downloader/BaseDownloader.php:49

    3) PhpBrew\Downloader\BaseDownloader->download('https://pecl.php.net/rest/r/gd/stable.txt')
        from phar:///usr/local/bin/phpbrew/src/PhpBrew/Downloader/BaseDownloader.php:69

    4) PhpBrew\Downloader\BaseDownloader->request('https://pecl.php.net/rest/r/gd/stable.txt')
        from phar:///usr/local/bin/phpbrew/src/PhpBrew/Extension/Provider/PeclProvider.php:47

    5) PhpBrew\Extension\Provider\PeclProvider->getPackageXml('gd', 'stable')
        from phar:///usr/local/bin/phpbrew/src/PhpBrew/Extension/Provider/PeclProvider.php:74

    6) PhpBrew\Extension\Provider\PeclProvider->buildPackageDownloadUrl('stable')
        from phar:///usr/local/bin/phpbrew/src/PhpBrew/Extension/ExtensionDownloader.php:35

    7) PhpBrew\Extension\ExtensionDownloader->download(PhpBrew\Extension\Provider\PeclProvider, 'stable')
        from phar:///usr/local/bin/phpbrew/src/PhpBrew/Command/ExtensionCommand/InstallCommand.php:156

    8) PhpBrew\Command\ExtensionCommand\InstallCommand->execute('gd', '--', '--with-gd=/opt/local', '--with-png-dir=/opt/local', '--with-jpeg-dir=/opt/local')
PHP Notice:  Undefined index: file in phar:///usr/local/bin/phpbrew/vendor/corneltek/cliframework/src/ExceptionPrinter/DevelopmentExceptionPrinter.php on line 112
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/phpbrew:0
PHP   2. require() /usr/local/bin/phpbrew:99
PHP   3. PhpBrew\Console->runWithTry() phar:///usr/local/bin/phpbrew/scripts/phpbrew-emb.php:2
PHP   4. CLIFramework\ExceptionPrinter\DevelopmentExceptionPrinter->dump() phar:///usr/local/bin/phpbrew/src/PhpBrew/Console.php:152
PHP   5. CLIFramework\ExceptionPrinter\DevelopmentExceptionPrinter->dumpTrace() phar:///usr/local/bin/phpbrew/vendor/corneltek/cliframework/src/ExceptionPrinter/DevelopmentExceptionPrinter.php:163

Notice: Undefined index: file in phar:///usr/local/bin/phpbrew/vendor/corneltek/cliframework/src/ExceptionPrinter/DevelopmentExceptionPrinter.php on line 112

Call Stack:
    0.0004     409760   1. {main}() /usr/local/bin/phpbrew:0
    0.0183     797264   2. require('phar:///usr/local/bin/phpbrew/scripts/phpbrew-emb.php') /usr/local/bin/phpbrew:99
    0.0230    1160792   3. PhpBrew\Console->runWithTry() phar:///usr/local/bin/phpbrew/scripts/phpbrew-emb.php:2
    1.5052    3594488   4. CLIFramework\ExceptionPrinter\DevelopmentExceptionPrinter->dump() phar:///usr/local/bin/phpbrew/src/PhpBrew/Console.php:152
    1.5056    3594488   5. CLIFramework\ExceptionPrinter\DevelopmentExceptionPrinter->dumpTrace() phar:///usr/local/bin/phpbrew/vendor/corneltek/cliframework/src/ExceptionPrinter/DevelopmentExceptionPrinter.php:163

PHP Notice:  Undefined index: line in phar:///usr/local/bin/phpbrew/vendor/corneltek/cliframework/src/ExceptionPrinter/DevelopmentExceptionPrinter.php on line 113
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/phpbrew:0
PHP   2. require() /usr/local/bin/phpbrew:99
PHP   3. PhpBrew\Console->runWithTry() phar:///usr/local/bin/phpbrew/scripts/phpbrew-emb.php:2
PHP   4. CLIFramework\ExceptionPrinter\DevelopmentExceptionPrinter->dump() phar:///usr/local/bin/phpbrew/src/PhpBrew/Console.php:152
PHP   5. CLIFramework\ExceptionPrinter\DevelopmentExceptionPrinter->dumpTrace() phar:///usr/local/bin/phpbrew/vendor/corneltek/cliframework/src/ExceptionPrinter/DevelopmentExceptionPrinter.php:163

Notice: Undefined index: line in phar:///usr/local/bin/phpbrew/vendor/corneltek/cliframework/src/ExceptionPrinter/DevelopmentExceptionPrinter.php on line 113

Call Stack:
    0.0004     409760   1. {main}() /usr/local/bin/phpbrew:0
    0.0183     797264   2. require('phar:///usr/local/bin/phpbrew/scripts/phpbrew-emb.php') /usr/local/bin/phpbrew:99
    0.0230    1160792   3. PhpBrew\Console->runWithTry() phar:///usr/local/bin/phpbrew/scripts/phpbrew-emb.php:2
    1.5052    3594488   4. CLIFramework\ExceptionPrinter\DevelopmentExceptionPrinter->dump() phar:///usr/local/bin/phpbrew/src/PhpBrew/Console.php:152
    1.5056    3594488   5. CLIFramework\ExceptionPrinter\DevelopmentExceptionPrinter->dumpTrace() phar:///usr/local/bin/phpbrew/vendor/corneltek/cliframework/src/ExceptionPrinter/DevelopmentExceptionPrinter.php:163

        from :0

    9) call_user_func_array([PhpBrew\Command\ExtensionCommand\InstallCommand, 'execute'], ['gd', '--', '--with-gd=/opt/local', '--with-png-dir=/opt/local', '--with-jpeg-dir=/opt/local'])
        from phar:///usr/local/bin/phpbrew/vendor/corneltek/cliframework/src/CommandBase.php:846

    10) CLIFramework\CommandBase->executeWrapper(['gd', '--', '--with-gd=/opt/local', '--with-png-dir=/opt/local', '--with-jpeg-dir=/opt/local'])
        from phar:///usr/local/bin/phpbrew/vendor/corneltek/cliframework/src/Application.php:398

    11) CLIFramework\Application->run(['/usr/local/bin/phpbrew', '--debug', 'ext', 'install', 'gd', '--', '--with-gd=/opt/local', '--with-png-dir=/opt/local', '--with-jpeg-dir=/opt/local'])
        from phar:///usr/local/bin/phpbrew/src/PhpBrew/Console.php:114

    12) PhpBrew\Console->runWithTry(['/usr/local/bin/phpbrew', '--debug', 'ext', 'install', 'gd', '--', '--with-gd=/opt/local', '--with-png-dir=/opt/local', '--with-jpeg-dir=/opt/local'])
        from phar:///usr/local/bin/phpbrew/scripts/phpbrew-emb.php:2

    13) require('phar:///usr/local/bin/phpbrew/scripts/phpbrew-emb.php')
        from /usr/local/bin/phpbrew:99

...
```


### Expected Result

```
...
```

### Command


    phpbrew --debug ext install gd -- --with-gd=/opt/local --with-png-dir=/opt/local --with-jpeg-dir=/opt/local-- --....

### Build Log

    No build log

### Platform

OS:

   Ubuntu 16.04

Running PHP: 
PHP 7.2.7 (cli) (built: Jul  7 2018 22:39:12) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans


Installing PHP:
PHP 7.2.7 (cli) (built: Jul  7 2018 22:39:12) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans

**Comment by jasny** [comment]
@owen800q `gd` is not a Pecl extension and can be bundled with PHP. You need to add `+gd` when installing a PHP version.

    phpbrew install php 7.2.10 +default +gd
