### ISSUE TITLE
Fix StyleCI configuration (continuous integration)

### ISSUE THREAD

**Issue by jasny** [phpbrew/phpbrew#981]
StyleCI fails due to a configuration error. This is confusing when creating a pull request.

It seems like the configution has a `linting` option, which is not longer available.

![screenshot-github styleci io-2018 09 25-14-14-55](https://user-images.githubusercontent.com/100821/46014192-bf4b9e00-c0ce-11e8-94db-19d7afba6c90.png)

**Comment by kevinnio** [comment]
@c9s @GM-Alex @jhdxr @marcioAlmada @shinnya 

Could one of you guys take a look at this? Should be quick to fix and it's making GitHub mark all recent PRs as failing.

**Comment by shinnya** [comment]
Thank you for reporting! I removed `linting` option from the StyleCI setting of this repo.

**Comment by c9s** [comment]
I think we should remove the style CI. It's really bothering.

**Comment by c9s** [comment]
I removed the webhook.
