### ISSUE TITLE
TravisCI tests fail due to Github API rate limits (continuous integration)

### ISSUE THREAD

**Issue by jasny** [phpbrew/phpbrew#982]
Running tests on Travis CI randomly fail, due to Github API rate limits. This results in a 403 response.

> For unauthenticated requests, the rate limit allows for up to 60 requests per hour. Unauthenticated requests are associated with the originating IP address, and not the user making requests.

To fix the issue, use authenticated requests instead.

> For API requests using Basic Authentication or OAuth, you can make up to 5000 requests per hour. 

In the Travis configuration you can use an encrypted environment variable for your secret key.  [See documentation](https://docs.travis-ci.com/user/environment-variables/#defining-encrypted-variables-in-travisyml)

_I recommend creating a new (`phpbrew-robot`) Github user for this, that doesn't have any write privileges to these repositories._

![screenshot-travis-ci org-2018 09 25-14-28-55](https://user-images.githubusercontent.com/100821/46014541-f3738e80-c0cf-11e8-8800-15f507d6c6d6.png)

**Comment by jhdxr** [comment]
Thank you for your advice. I have followed your suggestions, and it's now under testing. Hopefully the CI will finally go back to green after a very loooooooong time.

@c9s I've created account @phpbrew-bot for this purpose. However, this account is bind with my personal email address. so if you have any better choice, e.g. a phpbrew-related domain, I really appreciate it if you can provide a email account for this shared account. btw, could you drop me an email so I can send the password of that account to you?
