### ISSUE TITLE
Project status

### ISSUE THREAD

**Issue by theofidry** [phpbrew/phpbrew#988]
Hello there. 

I find that project very helpful and love to use it. However, its maintenance seems a bit sporadic. I wonder if anything else could be done to help with that? From what I see there seem to be a few problematic points:

- @c9s availability: maybe more contributors could shim in as maintainers to help out and avoid c9s to be too pressured and be the contribution bottleneck.
- The insane old dependencies: PHPBrew is compatible with _PHP 5.3_. In itself, it's perfectly fine as it allows to broaden the range of users like Composer does. However although quite popular, PHPBrew is not nearly as used, popular and well maintained as Composer and its codebase and range of features is also significantly bigger. This begs the question: should the minimal requirements be updated? I think a better solution would be to upgrade to PHP 7+ to help out with the codebase. If PHP 5.x support is still necessary, maybe solutions to transpile new PHP code to older versions such as [7to5](https://github.com/spatie/7to5) should be considered. For example, this could take the form of a [Box compactor](https://github.com/humbug/box/blob/master/doc/configuration.md#compactors-compactors) so that the shipped PHPBrew PHAR remains PHP5.3 compatible whilst the codebase can happily benefit from newer PHP features.
- The lack of visibility in the work left to do. There is a bunch of issues all over the place but overall I think maybe phpbrew should cut down some features such as the App Store in favor eventually of a [phive](https://github.com/phar-io/phive) integration. In other words, we are missing a kind of roadmap to really help out with the project as contributors.

Thoughts?

/cc @c9s

**Comment by jasny** [comment]
Second that. I'm more than happy to spend some time on the project. However, I'm a bit reluctant to do so if PRs just stay open. The project has become too successful and important as a single person side project. Adding maintainers seem like a must to keep the project thriving.

**Comment by theofidry** [comment]
cc @jhdxr which apparently has writing access to the repo as well :)

**Comment by jhdxr** [comment]
As for the second point, I agree we increase the minimum requirements to 7+ when php 5.6 reach its EOL. and of course we should also increase the major version of phpbrew for this minimum requirements update. we may also consider to maintain the old branch for a period of time, but at some point we may finally drop it.
Reason behind this decision: The latest OS may not be able to compile the old PHP (travis-ci drops php 5.3 on Ubuntu Trusty), and old OS may not be able to compile the latest PHP as well. So one day, we may be in a dilemma that although phpbrew supported all versions, php itself wouldn't be able to be compiled.

**Comment by jhdxr** [comment]
btw, I want to make PHPBrew can be installed via Composer (although it may become the chicken or the egg). However, I realize that some of the dependencies are required by branch instead of tag, and I don't think it's a good idea to ask users to change their Composer settings.

**Comment by jhdxr** [comment]
I'm working on http to https. and I found the PHPUnit we used are also out of support. currently we use phpunit 4.8 for PHP 5.x, and 5.7 for PHP 7.x. But according to [PHPUnit offical site](https://phpunit.de/supported-versions.html). 5.7 is supposed to support till PHP 7.1. so it's risky to use it for 7.2+.
PHPUnit has changed its code structure since 6.x (using namespace) so the "magic" I used now cannot be applied to higer version.

**Comment by theofidry** [comment]
>I want to make PHPBrew can be installed via Composer 

I think it's entirely fair. I'm a big fan of providing the choice of the installation process to the users. Fox example for [Box](https://github.com/humbug/box/blob/master/doc/installation.md#installation) I provide 4 ways:

- homebrew
- PHAR
- phive
- Composer

If you wish to limit the potential Composer dependencies conflicts, I would recommend to provide a shim. Typically you can [scope](https://github.com/humbug/php-scoper) the application to remove any potential conflict (this however may not be a trivial process, scoping will always be flimsy) and published the scoped code in a shim library like [PHPStan does](https://github.com/phpstan/phpstan-shim). Note that this process is eased by using [Box](https://github.com/humbug/box)

> As for the second point, I agree we increase the minimum requirements to 7+ when php 5.6 reach its EOL.

To move the codebase forward, I would be bold and aim at PHP 7.3 directly. Realistically the codebase is gonna take time to revamp, by the time it is done PHP7.3 won't look as a bleeding edge anymore. It's certainly gonna remove a potential user base, but for a project of the size of phpbrew I think a better alternative is to look for ways to transpile code to older versions: it's the easiest way to provide support for legacy applications IMO.

But anyway, that's just my personal opinion after all :P The main goal of this issue in the end is more to try to be able to make the project move forward and active again 😄

**Comment by theofidry** [comment]
>targeting php 7.3 means once you switch to old version you won't be able to switch back.

I think it is fine: the old phpbrew versions will still be there. Plus as I mentioned before, I think it's more efficient to invest in supporting 7.3+ _and_ a PHP 7 to 5.3 transpiller rather than supporting 5.3.

**Comment by jhdxr** [comment]
I don't think a converter is possible. there is some library, e.g. [symfony-polyfill](https://github.com/symfony/polyfill), trying to do this job. but IMO this is only useful for new functions/classes/constants. New syntax, including type declarations, generators are not easy to simulate. 

I would support this idea (targeting a high version) only if phpbrew has its own interpreter, which means it wouldn't be affected by changing of system-wide php. Actually we discussed this idea before (but I cannot find that issue now), then it become how are we able to get this done (another the chicken and the egg).

**Comment by theofidry** [comment]
>I don't think a converter is possible

There is such transpilers, e.g. [7to5](https://github.com/spatie/7to5). I'm sure there is more work required to make it good enough for a project like phpbrew but it's a good start. That said I would imagine it to be only for the PHAR.

**Comment by morozov** [comment]
@theofidry I'm currently working on #872 (70% done) that will allow using a fixed PHP runtime for PHPBrew and dropping old PHP versions.

**Comment by theofidry** [comment]
Oh cool! How does that work?

**Comment by morozov** [comment]
Look at https://github.com/morozov/phpbrew/compare/phpbrew:master...morozov:issues/872 (currently is only implemented for Fish but I'll port it to Bash as well at the end).

The idea is to introduce the `phpbrew system [<path>|<build>]` subcommand. It can be used as following:
- `phpbrew system 7.4.0`, or…
- `phpbrew system /usr/bin/php` 

Once the system PHP binary is set, it will be used internally by PHPBrew regardless of which PHP version is currently used:
```
$ phpbrew system
/home/morozov/.phpbrew/php/php-7.4.0/bin/php

$ php -v
PHP 7.4.0 (cli) (built: Nov 27 2019 18:44:06) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.0, Copyright (c), by Zend Technologies
    with Xdebug v2.8.0, Copyright (c) 2002-2019, by Derick Rethans

$ phpbrew use 5.6.40

$ php -v
PHP 5.6.40 (cli) (built: Nov 28 2019 08:26:13) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.5.5, Copyright (c) 2002-2017, by Derick Rethans

$ phpbrew list
  php-7.4.0
  php-7.3.12
  php-7.1.33
* php-5.6.40
```
As you can see from the patch, my current build requires PHP 7.2 or newer but PHPBrew keeps working even if PHP 5.6 is currently used.

**Comment by theofidry** [comment]
So you're providing a way for phpbrew to still works although the user might have asked to use an older PHP version via phpbrew; that's cool and a good step forward! 

It won't solve the problem if one user try to install phpbrew on a system which doesn't have any recent version of PHP. But I guess this could be mitigated by providing a cask recipe or docker image...

**Comment by morozov** [comment]
@theofidry I commented on your above concern in https://github.com/phpbrew/phpbrew/issues/872#issuecomment-559984764. Let's move this part of the discussion there.

**Comment by morozov** [comment]
@theofidry I currently have all the needed permissions to maintain the repository.

> I think maybe phpbrew should cut down some features such as the App Store in favor eventually of a [phive](https://github.com/phar-io/phive) integration.

I'm all for it. It's a source of additional maintenance and is barely as feature-rich as Phive. You're welcome to file a deprecation ticket and we can drop it in a subsequent release.

> In other words, we are missing a kind of roadmap to really help out with the project as contributors.

Given the lack of manpower, I don't think we should be building any long-going plans. The first thing I want to do is to bump the PHP requirement w/o losing the ability to build older PHP versions, then get rid of the unmaintained dependencies (ideally, all of them), and then we can talk about implementing new features.

Besides that, if you have other suggestions, please file a more actionable issue.

**Comment by theofidry** [comment]
Since @morozov has taken over and has been quite active & reactive lately, I think this issue's answer has been given :)
