### ISSUE TITLE
error: pcntl: fork() not supported by this platform

### ISSUE THREAD

**Issue by dubis** [phpbrew/phpbrew#993]
### Output
Error: Configure failed:
The last 5 lines in the log file:
checking for Adabas support... cp: cannot stat '/usr/local/lib/x86_64-linux-gnu/odbclib.a': No such file or directory

yes

checking whether to enable pcntl support... yes

checking for fork... no

configure: error: pcntl: fork() not supported by this platform

Please checkout the build log file for more details:
         tail /opt/phpbrew/build/php-5.4.45/build.log

### Expected Result

PHP installation OK 

### Command

phpbrew install 5.4.45 +all +curl=/opt/curl-7.26.0 +openssl=/usr/local/openssl/ +kerberos=/usr +imap=/usr/local/openssl/ -- --enable-pcntl --with-unixODBC=shared,/usr/nekoware --with-pdo-odbc=unixODBC,/usr/nekoware

### Build Log

checking PHP version... 5.4.45, ok
checking size of long int... 8
checking checking if we're on a 64-bit platform... yes
checking Oracle ORACLE_HOME install directory... /usr/lib/oracle/11.2/client64
checking ORACLE_HOME library validity... lib
checking Oracle library version compatibility... 11.1
checking for Adabas support... cp: cannot stat '/usr/local/lib/x86_64-linux-gnu/odbclib.a': No such file or directory
yes
checking whether to enable pcntl support... yes
checking for fork... no
configure: error: pcntl: fork() not supported by this platform
debian9:/opt/phpbrew$

### Platform

OS:

  DEBIAN 9.6

Running PHP: 
 ps -aef |grep php
root       345     1  2 11:25 ?        00:00:01 php-fpm: master process (/etc/php/7.0/fpm/php-fpm.conf)
www-data   362   345  0 11:25 ?        00:00:00 php-fpm: pool www
www-data   363   345  0 11:25 ?        00:00:00 php-fpm: pool www
system     399   384  0 11:26 pts/0    00:00:00 grep php

Installing PHP:
 php -version
PHP 7.0.33-0+deb9u1 (cli) (built: Dec  7 2018 11:36:49) ( NTS )

**Comment by c9s** [comment]
could you attach your /opt/phpbrew/build/php-5.4.45/build.log ? thanks

**Comment by dubis** [comment]
Hi,
The commande `phpbrew install 5.4.45 +default+openssl=/opt/OpenSSL/openssl-1.0.1u`
solve my problem. I've got php version 5.4.45  with many php-cgi compiled and installed
Thanks for your support
