### ISSUE TITLE
Is a PHP instance installed with phpbrew affected by tainted go-pear.phar security breach?

### ISSUE THREAD

**Issue by Sweetchuck** [phpbrew/phpbrew#994]
Is a PHP instance installed with phpbrew affected by the tainted go-pear.phar security breach?

http://blog.pear.php.net/

> PEAR server is down
>
> A security breach has been found on the http://pear.php.net webserver, with a tainted go-pear.phar discovered. The PEAR website itself has been disabled until a known clean site can be rebuilt. A more detailed announcement will be on the PEAR Blog once it's back online.
>
> If you have downloaded this go-pear.phar in the past six months, you should get a new copy of the same release version from GitHub (pear/pearweb_phars) and compare file hashes. If different, you may have the infected file.

**Comment by morozov** [comment]
Closing this as stale and probably no longer relevant. If you're concerned about the breach, you should have taken the corresponding measures by now. Otherwise, please use the source code to answer this question.
