### ISSUE TITLE
Got so many errors while fresh install on ubuntu 18.04

### ISSUE THREAD

**Issue by arifikhsan** [phpbrew/phpbrew#996]
### Output

```
errors occured because many of packages/libraries on ubuntu have not been installed
```

### Expected Result

```
successful install without error
```

### Command

    phpbrew --debug install --stdout 7.3 as 7.3-dev +default +intl --

### Platform

OS: Ubuntu 18.04

Running PHP: 7.3

Installing PHP: 7.3

After a lot of searching, this is the list of installation that i have to do

```
sudo apt install libssl-dev
sudo apt install libxml2-dev
sudo apt install libbz2-dev
sudo apt install libmcrypt-dev
sudo apt install libxslt-dev
sudo apt install libcurl4-openssl-dev
sudo apt install libcurl4-gnutls-dev
sudo apt install libreadline-dev
sudo apt install libzip-dev
```

**Comment by arifikhsan** [comment]
sorry, i just read the requirement recently

but i still found that i have to install `lcov`, which is not available in requirement yet

next, i have no error

**Comment by morozov** [comment]
The extension dependencies are listed on the [Requirements](https://github.com/phpbrew/phpbrew/wiki/Requirement) page on wiki. Please feel free to add missing extension or dependencies.
